### ISSUE TITLE
Fragment 中跳转到其他页面需要onActivityResult 

### ISSUE THREAD

**Issue by gongxm0412** [alibaba/ARouter#100]
Fragment中跳转到其他Activity ，需要有返回值  onActivityResult

常用的方法是
Intent mintent = new Intent(getActivity(), AddDoingActivity.class);
startActivityForResult(mintent, ReqCodeAdd);
页面能正常接收返回值

但是ARouter里面
 ARouter.getInstance().build("/app/doing/add").navigation(getActivity(), ReqCodeAdd);
这样没有办法接收到返回值

是不是我用法有问题？

**Comment by zhi1ong** [comment]
已知问题，因为Fragment中没有传递当前实例到sdk中，建议直接在Activity中调用Fragment的onActivityResult即可。

**Comment by qq549631030** [comment]
这种情况就不用Arouter直接跳了，只用来找类名就行了  
Postcard postcard = ARouter.getInstance().build("/app/doing/add"); LogisticsCenter.completion(postcard);
Class tarActivity = postcard.getDestination();
