### ISSUE TITLE
There is no route match the path

### ISSUE THREAD

**Issue by githuvn** [alibaba/ARouter#1001]
我觉得很不好用,每次有新module时就是There is no route match the path，还找不到问题，后面又自己好了，为什么又13k的star呢？

**Comment by StarAndRainbow** [comment]
+1

**Comment by zhi1ong** [comment]
文档里说的很清楚了，这种情况是因为开发过程中因为没有版本号修改所以不会重新生成路由表，要么 clean & build 要么 openDebug();

if (isDebug()) {           // These two lines must be written before init, otherwise these configurations will be invalid in the init process
    ARouter.openLog();     // Print log
    ARouter.openDebug();   // Turn on debugging mode (If you are running in InstantRun mode, you must turn on debug mode! Online version needs to be closed, otherwise there is a security risk)
}
