### ISSUE TITLE
ARouter init logistics center exception

### ISSUE THREAD

**Issue by xiang23** [alibaba/ARouter#1018]
调用 ARouter.init
在AGP7.0.2的时候正常，升级到7.2.1的时候出现这个问题，因为我没使用自动注册插件，追了下代码，问题似乎出在编译生成的文件上
正常情况的routermap
![image](https://user-images.githubusercontent.com/14964761/182319729-7a60b150-33db-4fb8-aa36-1f259925f000.png)
异常情况的routermap
![image](https://user-images.githubusercontent.com/14964761/182319769-ba99f8c1-dabb-4e8a-bc6b-c2b66fe231cb.png)

多生成了ExternalSynthetic$Condy0这个东西，然后通过反射时创建的就报错了
<img width="453" alt="image" src="https://user-images.githubusercontent.com/14964761/182320170-469c04cd-c951-4eb4-9f3a-89f5b7c93ba4.png">

**Comment by xiang23** [comment]
似乎是与jacoco冲突导致，关闭了就好了

**Comment by blundell** [comment]
Not sure "turning off Jacoco" is a solution 😆 

This issue still persists and we see it with:

Arouter 1.3.0
AGP 8.4.1

We also use the 

[arouter-jailbird-plugin](https://github.com/JailedBird/ArouterGradlePlugin/issues) 1.0.2

The workaround was to use this plugin during the code coverage debug build as well. Like this in the config:

`disableTransformWhenDebugBuild = false`

<img width="910" alt="image" src="https://github.com/user-attachments/assets/2844779b-8d9a-4853-b5d3-6e6df43a4c9b">

That means we go into the path on 150, and avoid the path on 158 which causes the crash

**Comment by Mr414Zheng** [comment]
```gradle
android {
    // ... 其他配置
    

    buildTypes {
        debug {
            // 关闭代码覆盖率收集
            testCoverageEnabled false
            // ... 其他debug配置
        }
        
        release {
            // 通常release版本默认就是false，也可以显式设置
            testCoverageEnabled false
            // ... 其他release配置
        }
    }
}
```

**Comment by blackhorse6** [comment]
解决了吗
