### ISSUE TITLE
分组问题,麻烦了

### ISSUE THREAD

**Issue by player1992** [alibaba/ARouter#104]
我项目结构是sample，baselibrary和testlibrary,在sample下的路由规则是"/test/xxx",然后我的testlibrary下的路由规则也定义成为“/test/xxx”的时候会出现testlibrary的页面跳转成功，但是sample下的页面跳转就会失败的情况（no route matched!），把testlibrary的路由规则改为“jump/xxx”，和sample的路由分组不一致的话，sample和testlibrary才能都跳转成功。

**Comment by zhi1ong** [comment]
是这样，文档中应该有说，不同的模块下不能使用相同分组，同一个模块下可以有多个分组
