### ISSUE TITLE
基于 KSP 和 AGP 8 的重构版本

### ISSUE THREAD

**Issue by aleyn97** [alibaba/ARouter#1052]
https://github.com/aleyn97/router

**Comment by blundell** [comment]
hero (but there is also https://github.com/jadepeakpoet/ARouter)

**Comment by dartrui** [comment]
英雄们。希望你们能坚持下去，被阿里恶心到了

**Comment by kymjs** [comment]
用TheRouter吧
https://therouter.cn/docs/2022/11/23/01
