### ISSUE TITLE
java1.8支持？

### ISSUE THREAD

**Issue by eyre** [alibaba/ARouter#106]
在java1.8中使用，出现如下告警：
注: ARouter::Compiler >>> AutowiredProcessor init. <<<
警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.AutowiredProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'

**Comment by zhi1ong** [comment]
仅仅是提示，支持的

**Comment by passos** [comment]
既然是支持的，那为什么要提示警告呢
