### ISSUE TITLE
webview设置webviewclient后，跳转失败

### ISSUE THREAD

**Issue by zhengjs2003** [alibaba/ARouter#107]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhengjs2003** [comment]
添加webview.setWebViewClient(new WebViewClient());后，点击h5页面中的连接，提示找不到网页。
删除了webview.setWebViewClient(new WebViewClient());则能正常跳转

**Comment by zhi1ong** [comment]
和你自己使用的webviewclient有关系，看看你自己的webviewclient的实现，原生的是没问题的

**Comment by zhengjs2003** [comment]
使用ARouter项目，在TestWebview里加上 webview.setWebViewClient(new WebViewClient()); 就不行了。

**Comment by zhi1ong** [comment]
webview.setWebViewClient(new WebViewClient());  你既然set了一个webviewclinet，那你就要自己在shouldOverrideUrl里面去处理自定义Schame，你直接就写了一行new WebviewClient 肯定不行啊，上面不是说么，你既然要自己实现WebviewClient，那就要去 “实现” 它啊
