### ISSUE TITLE
 Gradle Build Tools 版本过高引起 There is no route match the path [/xxx/xxx], in group [xxx][ ]

### ISSUE THREAD

**Issue by stansen** [alibaba/ARouter#109]
当使用
 classpath 'com.android.tools.build:gradle:2.2.3'
没有出现问题

当使用 classpath 'com.android.tools.build:gradle:2.3.1'
则出现There is no route match the path [/xxx/xxx], in group [xxx][ ]问题

折腾了一下午...

**Comment by zhi1ong** [comment]
和gradle版本没太大关系，```There is no route match the path [/xxx/xxx], in group [xxx]``` 只是表象，要排查一下具体原因，猜测是你是开启了InstantRun，但是没有在init之前 调用 openDebug，因为gradle插件不用最新的，不会开启InstantRun，所以你降下去之后就能用了

**Comment by ikkyu0319** [comment]
同样遇到这种问题~

**Comment by gzbbxu** [comment]
同问
