### ISSUE TITLE
这个库不能跟这个注解库androidannotations一起使用，有没有办法？

### ISSUE THREAD

**Issue by richfuns** [alibaba/ARouter#110]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

这个注解库实在太方便了，http://androidannotations.org， 有没有办法同时使用啊？

**Comment by zhi1ong** [comment]
他把activity都拷贝了一份，已经不能跳转到原本的activity了，自然不行

**Comment by jiuwu0905** [comment]
我在想。
其实如果能让 androidAnnotations 的  processor 先执行，再把 arouter 的里 路由指向  复制的activity 就应该 可以了。
但我找不到一个可以控制执行顺序的方法。

**Comment by zhi1ong** [comment]
可以直接clone androidAnnotation 的源码，把 ARouter的 处理器加进去，就能通过代码逻辑控制顺序了。
