### ISSUE TITLE
kotlin支持

### ISSUE THREAD

**Issue by xiaozhilaoliu** [alibaba/ARouter#111]
使用kotlin时候，
apply plugin: 'kotlin-kapt'

kapt {
    generateStubs = true
    arguments {
        arg("moduleName", moduleName:project.getName())
    }
}

会抛出异常：

: error: ARouter::Compiler An exception is encountered, [These no module name, at 'build.gradle', like :
e: 

e:   apt {
e:       arguments {
e:           moduleName project.getName();
e:       }
e:   }
e:   ]

**Comment by zhi1ong** [comment]
我回头测试一下，报错应该是 kapt没有把参数穿进去

**Comment by chanchangxing** [comment]
请问关于这个问题解决了吗？

**Comment by xiaozhilaoliu** [comment]
问题解决了，是我自己写错了！
arg("moduleName", moduleName:project.getName())
用应该为：
arg("moduleName", project.getName())

**Comment by chanchangxing** [comment]
成功了！感谢！

**Comment by dukezhao** [comment]
我也这么写了，为什么不行？

**Comment by zhi1ong** [comment]
@dukezhao  新版本参数 key 不叫 moduleName 看文档
