### ISSUE TITLE
SingleTask模式的Activity通过scheme协议被调起时，onNewIntent中收不到数据

### ISSUE THREAD

**Issue by jason0539** [alibaba/ARouter#115]
如何复现：
1、把Demo中的Test1Activity启动模式改为singleTask
2、在外部应用使用scheme协议多次钓起Test1Activity

现象
Test1Activity的onNewIntent()中收到的intent的mExtras中的数据丢失了

**Comment by zhi1ong** [comment]
通过schame拉起页面的时候，ARouter判断没有Flag，会重新setFlag

**Comment by jason0539** [comment]
没理解，那应该怎么解决这个问题？

**Comment by jason0539** [comment]
debug到_ARouter的_navigation方法里面，ActivityCompat.startActivity的时候，intent中mExtras还不为空，但是到了Test1Activity中的onNewIntent收到的intent就没有数据了

**Comment by zhi1ong** [comment]
我验证一下

**Comment by xiaolongyuan** [comment]
+1 newIntent intent 拿不到数据

**Comment by zhi1ong** [comment]
指的是不能自动注入么？自动注入是直接拿的 getIntent, onNewIntent中要把 intent 赋值进去，setIntent(intent) ， 然后再 ARouter.getInstant().inject(this)

**Comment by jason0539** [comment]
不是注入的问题，可以再看下我的描述，是intent中的数据丢失了

**Comment by zhi1ong** [comment]
activity 中的 intent 没数据，数据在 onNewIntent() 的参数中传进来的

**Comment by xiaolongyuan** [comment]
问题是没有传进来啊  两个intent都没有数据 setIntent之后也还是没数据

**Comment by zhi1ong** [comment]
可以在源码中断点调试一下，我测试没有这个问题

**Comment by xiaolongyuan** [comment]
@zhi1ong 调过  你是用什么拿数据的？
1
```
 intent.getExtras().getString("page");
        intent.getStringArrayExtra("page");
```
2
```
 setIntent(intent);
getIntent().getData()
getIntent().getExtras()
getIntent().getStringExtra("page")
```
都取不到

![image](https://user-images.githubusercontent.com/3142363/28149953-007e31d6-67c4-11e7-838c-8826d6340d77.png)

**Comment by zhi1ong** [comment]
你页面里面有 page 字段和 Autowired 注解么？

**Comment by xiaolongyuan** [comment]
@zhi1ong 我没用这种方式取值 必须要 以 “ page 字段和 Autowired 注解” 方式取值？

**Comment by zhi1ong** [comment]
你可以不用自动注入，但是必须用 Autowired 标识，你想想，要是你不标识，我怎么知道以什么类型放入 intent 中呢，也不知道该提取uri中的哪些字段。

**Comment by xiaolongyuan** [comment]
好的 虽然很别扭 但好像如你所说 并没有太好的方式  把查询参数单独截取出来放进一个参数里 似乎方便一些

**Comment by zhi1ong** [comment]
这部分我更新到文档中，因为我是提供有让你获取原始URL的方法了，如果不希望写 注解，可以自己提取原始的URL自行提取参数。这部分标记一下比较合理，对于新页面来说
