### ISSUE TITLE
用最新版本，混淆打包出错

### ISSUE THREAD

**Issue by richfuns** [alibaba/ARouter#116]
已按照教程添加了Proguard混淆规则，但是还是报如下错误：
Warning:com.alibaba.android.arouter.facade.model.RouteMeta: can't find referenced class javax.lang.model.element.Element
Warning:there were 10 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.

请大家指教，谢谢

**Comment by zhi1ong** [comment]
不用主动依赖 annotation包，

**Comment by richfuns** [comment]
你好，不太明白，不需要依赖这个包吗？compile 'com.alibaba:arouter-annotation:1.0.3'

**Comment by zhi1ong** [comment]
不用主动依赖，有传递依赖的

**Comment by yubaokang** [comment]
遇到同样的问题。没有主动依赖怎么解决

**Comment by zhi1ong** [comment]
warning 直接忽略就行， 自行Google一下 proguard 如何 忽略warning

**Comment by taixiang** [comment]
@richfuns  遇到同样的问题，请问你解决没？
