### ISSUE TITLE
withFlags

### ISSUE THREAD

**Issue by JDDJJ** [alibaba/ARouter#119]
带flag跳转报错
![2734075c-0711-4fb2-887c-797c998aa028](https://cloud.githubusercontent.com/assets/16041527/26725225/1a0bec74-47d0-11e7-8e42-62661971e385.png)
![29e44886-6663-4961-8f0a-241b5ac6e0c6](https://cloud.githubusercontent.com/assets/16041527/26725227/1b953b90-47d0-11e7-809a-af46e3b07b76.png)

**Comment by JDDJJ** [comment]
ARouter.getInstance().build(Page.MainActivity).withFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP).navigation(this);
要加this

**Comment by hprostudy** [comment]
高版本的Android不传this也不报错了

**Comment by zhi1ong** [comment]
应该是年代久远的bug了
