### ISSUE TITLE
找不到任何包含com.alibaba.android.arouter.routes包名的类

### ISSUE THREAD

**Issue by AllynYonge** [alibaba/ARouter#12]
用你的Sample运行时，init后，加载了/data/apk/com.alibaba.xx.xx.xx/base.apk，找不到任何包含com.alibaba.android.arouter.routes包名的类，导致跳转时找不到模块

**Comment by zhi1ong** [comment]
因为有可能是MultiDex的情况，不止一种加载路径的，找不到这个包的话，可以看一下
1. 是不是混淆规则的问题，没有Keep之类的，Demo的话，直接Debug运行
2. 如果是开启了InstantRun的话，要reBuild一次，重新安装，新增注解之后，会生成新的映射文件，可能不会被Instant Run发现

**Comment by AllynYonge** [comment]
@zhi1ong 关掉InstantRun就好了
