### ISSUE TITLE
混淆后service的实现找不到

### ISSUE THREAD

**Issue by achenglike** [alibaba/ARouter#121]
按照稳定加入混淆代码，启用混淆后，无论是自动注入还是依赖查找方式都无法找到service的实现

**Comment by achenglike** [comment]
我现在暂时的处理方式是，混淆加入：
-keep public class com.alibaba.android.arouter.routes.**{*;}
-keep class * implements com.alibaba.android.arouter.facade.template.ISyringe{*;}
-keep class * implements com.alibaba.android.arouter.facade.template.IProvider{*;}

service用使用依赖查找，未使用自动注入

**Comment by zhi1ong** [comment]
自己反编译看看，混淆不耽误service
