### ISSUE TITLE
kotlin 中无法使用Autowired注解

### ISSUE THREAD

**Issue by qq8803128** [alibaba/ARouter#122]
在kotlin中的Activity中定义了一个
    @Autowired(name = "id")
    public var id: String?= null

编译时报错
ARouter::Compiler An exception is encountered, [The autowired fields CAN NOT BE 'private'!!! please check field [type] in class [com.xinkuai.mobile.ui.web.Web]]

**Comment by thisdk** [comment]
我也遇到这个问题.题主解决了吗

**Comment by zhi1ong** [comment]
@JvmField

**Comment by thisdk** [comment]
@Autowired
    lateinit var avatarUrl: String
