### ISSUE TITLE
com.alibaba.android.arouter.exception.HandlerException: Init provider failed! <init> []

### ISSUE THREAD

**Issue by duantao561** [alibaba/ARouter#126]
在MyApplication中初始化 就报这个错误：com.alibaba.android.arouter.exception.HandlerException: Init provider failed! <init> []。如果把ARouter.openLog(); ARouter.openDebug();这两句注释掉，就不报错了，但是ARouter跳转功能也不能用了！此时会显示Filter 0 classes by packageName <com.alibaba.android.arouter.routes>
求大神们指点！！

**Comment by whoislxy** [comment]
同上！

**Comment by zhi1ong** [comment]
init provider failed, 初始化某一个 Service的提供者的时候失败了，断点调试一下，看看具体哪个报错了

**Comment by duantao561** [comment]
和成功的项目 逐一对比 发现把minifyEnabled 改为false  就好了！好坑啊~

**Comment by zhi1ong** [comment]
minifyEnabled=false 是不混淆的意思

**Comment by FebMaple** [comment]
我的把混淆关掉还是没用

**Comment by duantao561** [comment]
buildTypes {
        debug {
            minifyEnabled false //使用arouter  debug模式下必须置为false
            // Uses new built-in shrinker http://tools.android.com/tech-docs/new-build-system/built-in-shrinker
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            testProguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguardTest-rules.pro'
        }

        release {
            minifyEnabled true
            useProguard true
            signingConfig signingConfigs.app
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            testProguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguardTest-rules.pro'
        }
    }

我只是把debug下minifyEnabled改为false,就能用了，release不用改也没问题。也可能是其他原因导致的，但具体我也不知道是为什么？

**Comment by weiweiiapps** [comment]
n my case Setting > Build, Execution, Deployment > Instant run

Uncheck "Enable Instant Run to hot swap code/resource changes on deploy"

Worked Fine.

**Comment by whoislxy** [comment]
ths

weiweiiapps <notifications@github.com> 于2019年1月22日周二 下午5:14写道：
