### ISSUE TITLE
混淆报错

### ISSUE THREAD

**Issue by huaminghui** [alibaba/ARouter#127]
混淆报出警告，没法打包请问如何解决
Warning: com.alibaba.android.arouter.facade.model.RouteMeta: can't find referenced class javax.lang.model.element.Element
Warning: com.alibaba.android.arouter.facade.model.RouteMeta: can't find referenced class javax.lang.model.element.Element
Warning: com.alibaba.android.arouter.facade.model.RouteMeta: can't find referenced class javax.lang.model.element.Element
Warning: com.alibaba.android.arouter.facade.model.RouteMeta: can't find referenced class javax.lang.model.element.Element
Warning: com.alibaba.android.arouter.facade.model.RouteMeta: can't find referenced class javax.lang.model.element.Element
Warning: com.alibaba.android.arouter.facade.model.RouteMeta: can't find referenced class javax.lang.model.element.Element

**Comment by zhi1ong** [comment]
-dontwarn

**Comment by taixiang** [comment]
@huaminghui  遇到同样的问题，请问你解决没？

**Comment by taixiang** [comment]
@zhi1ong  请问-dontwarn 怎么配置的， 加的-dontwarn com.alibaba.android.arouter.facade.model.RouteMeta  没有用的

**Comment by ohowen** [comment]
@taixiang 
-dontwarn javax.lang.model.element.**
