### ISSUE TITLE
从Library不能跳转app的路由

### ISSUE THREAD

**Issue by conanchen** [alibaba/ARouter#128]
创建的项目结构如下：
1. app 主项目
- 定义了路由："/app/main/MainActivity" 、 “/feature/question/QuestionEditActivity"
2. message Library module
- 定义了路由："/question/QuestionChatActivity"
3. login   Library module
- 定义了路由："/feature/login/LoginActivity"

发现从library不能跳转到app的路由，看到app的路由已经创建
- 注: ARouter::Compiler >>> AutowiredProcessor init. <<<
警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.AutowiredProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> InterceptorProcessor init. <<<
警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.InterceptorProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> RouteProcessor init. <<<
警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.RouteProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler >>> Found routes, start... <<<
注: ARouter::Compiler >>> Found routes, size is 2 <<<
注: ARouter::Compiler >>> Found activity route: org.ditto.hiask.asknanswer.QuestionEditActivity <<<
注: ARouter::Compiler >>> Start categories, group = feature, path = /feature/question/QuestionEditActivity <<<
注: ARouter::Compiler >>> Found activity route: org.ditto.hiask.MainActivity <<<
注: ARouter::Compiler >>> Start categories, group = app, path = /app/main/MainActivity <<<
注: ARouter::Compiler >>> Generated group: app<<<
注: ARouter::Compiler >>> Generated group: feature<<<
注: ARouter::Compiler >>> Generated provider map, name is ARouter$$Providers$$app <<<
注: ARouter::Compiler >>> Generated root, name is ARouter$$Root$$app <<<

下面代码，前三个分支都起作用：
```
        if (position % 5 == 0) {
            ARouter.getInstance().build("/feature/login/LoginActivity").navigation();
        } else if (position % 5 == 1) {
            ARouter.getInstance().build("/feature/login/Login2Activity").navigation();
        } else if (position % 5 == 2) {
            ARouter.getInstance().build("/question/QuestionChatActivity").navigation();
        } else if (position % 5 == 3) {
            ARouter.getInstance().build("/feature/question/QuestionEditActivity").navigation();
        }else {
            ARouter.getInstance().build("/app/main/MainActivity").navigation();
        }

```

**Comment by zhi1ong** [comment]
不能跳转的话，和你的页面在哪个lib关系不大，要去看看是不是配置正确了，看看和demo有什么区别，还是lib中没有配置 annotationProcessor

**Comment by conanchen** [comment]
仔细查看，原来不同library定义的路由前缀必须不同。
ARouter.getInstance().build("/feature/login/LoginActivity").navigation(); 这个路由在login-library里面
ARouter.getInstance().build("/feature/question/QuestionEditActivity").navigation(); 这个路由在app里面定义

定义路由时要仔细查看，前缀作为group，不同library里使用同样前缀时不行的、不行的、不行的？
看看Arouter能不能改进一下？

**Comment by zhi1ong** [comment]
这个文档qa中应该有写的，不同lib中使用相同的分组会导致映射文件冲突
