### ISSUE TITLE
initInterceptors 不考虑线程不安全吗

### ISSUE THREAD

**Issue by mjjde** [alibaba/ARouter#13]
我在看代码的时候看到下面这段

     public static void initInterceptors() {
        executor.execute(new Runnable() {
            @Override
            public void run() {
                if (null != interceptorsIndex && interceptorsIndex.size() > 0) {
                    for (Map.Entry<Integer, Class<? extends IInterceptor>> entry :   interceptorsIndex.entrySet()) {
                        Class<? extends IInterceptor> interceptorClass = entry.getValue();
                        try {
                            IInterceptor iInterceptor = interceptorClass.getConstructor().newInstance();
                            iInterceptor.init(mContext);
                            interceptors.add(iInterceptor);
                        } catch (Exception ex) {
                            throw new HandlerException(TAG + "ARouter init interceptor error! name = [" + interceptorClass.getName() + "], reason = [" + ex.getMessage() + "]");
                        }
                    }

                    interceptorHasInit = true;

                    logger.info(TAG, "ARouter interceptors init over.");

                    synchronized (interceptorInitLock) {
                        interceptorInitLock.notifyAll();
                    }
                }
            }
        });
    }

发现好像不是线程安全的？

**Comment by zhi1ong** [comment]
initInterceptor只会调用一次，这个是由整个SDK的初始化流程控制的，SDK的初始化是有锁的。

**Comment by mjjde** [comment]
这段代码里面是由线程池执行的,对里面的TreeMap的读取和对ArrayList的写入不会造成问题吗？

**Comment by zhi1ong** [comment]
逻辑上不会，拦截器的初始化确实是在线程池中异步的，但是第一次路由调用的时候，如果拦截器没有初始化完的话，路由请求会等待拦截器初始化结束， checkInterceptorsInitStatus() ，不会同时读写的。

**Comment by mjjde** [comment]
我的意思是

    // Cache interceptor
    private static Map<Integer, Class<? extends IInterceptor>> interceptorsIndex = new TreeMap<>();
    private static List<IInterceptor> interceptors = new ArrayList<>();

是否需要换成线程安全的Map和List

异步里面如果一个线程在初始化最后一个拦截器 而另一个线程不进入for循序就去执行下面的
interceptorHasInit = true;

这样的话checkInterceptorsInitStatus()是否就失效了呢

**Comment by zhi1ong** [comment]
```
initInterceptor只会调用一次，这个是由整个SDK的初始化流程控制的，SDK的初始化是有锁的。
```
如果**不考虑上下文的话，单看这段代码是有线程安全风险的**，但是首先这个方法不会被调用多次，他**只会被调用一次**，是通过ARouter.init()里面的锁来控制的，这就保证了interceptorHasInit不会被多次修改，其次这个List的读取是一定在写入完成之后，是由interceptorHasInit这个标志位来控制的，以上，这里应该是没有问题的。

**Comment by mjjde** [comment]
恩 好的  谢谢你的解答 ~
