### ISSUE TITLE
多个模块，不能引用相同的ARouter么？

### ISSUE THREAD

**Issue by chond** [alibaba/ARouter#131]
Error:Execution failed for task ':app:transformClassesWithJarMergingForInternalDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/alibaba/android/arouter/routes/ARouter$$Group$$module$1.class

**Comment by zhi1ong** [comment]
多个模块中不能使用相同的分组名，就是 /1/*
