### ISSUE TITLE
传递参数问题

### ISSUE THREAD

**Issue by liaoshengrui** [alibaba/ARouter#132]
再次打开启动模式为 singleTask 和 singleInstance 的Activity 接受不到传递的参数
injection()在onStart()时注入

**Comment by CNyezi** [comment]
同样的，我在onCreate中调用了下面函数
````
        ARouter.getInstance().inject(this);
````
但是问题不在这里，我使用的是JAVA 8， 在编译过程中提示我注释解释器版本1.8大于AROUTER的1.7
请问这样的问题该如何去解决？

**Comment by zhi1ong** [comment]
java向下兼容的，编译警告可以忽略

**Comment by vqinlin** [comment]
这个问题解决了？  我使用的最新版本，还是有这个问题呀。。。。

**Comment by EnzoXRay** [comment]
我也遇到了这个问题，怎么解决？

**Comment by EnzoXRay** [comment]
解决了，这种情况可以在 onNewIntent() 生命周期方法中通过 intent.getExtras().getXXX() 拿到传递的参数。

**Comment by CNyezi** [comment]
> 解决了，这种情况可以在 onNewIntent() 生命周期方法中通过 intent.getExtras().getXXX() 拿到传递的参数。

你是真能挖坟啊兄弟。。。卧槽
