### ISSUE TITLE
No route matched

### ISSUE THREAD

**Issue by rexydimen** [alibaba/ARouter#133]
编译也通过了，route path检查过了没问题。可是一直报错“no route matched”。目前疑惑的是build.gradle配置问题。
我的配置如下（参照git库说明写的）：
android {
    defaultConfig {
	...
	javaCompileOptions {
	    annotationProcessorOptions {
		arguments = [ moduleName : project.getName() ]
	    }
	}
    }
}

dependencies {
    // 替换成最新版本, 需要注意的是api
    // 要与compiler匹配使用，均使用最新版可以保证兼容
    compile 'com.alibaba:arouter-api:1.2.1.1'
    annotationProcessor 'com.alibaba:arouter-compiler:1.1.2.1'
    ...
}

我看ARouter Demo本地配置如下：
    annotationProcessor project(':arouter-compiler')
    compile project(':arouter-api')
    compile project(':arouter-annotation')
唯独少了个arouter-annotation的远程依赖。
这个是必须的吗？

**Comment by haofei91** [comment]
arouter-annotation 已经包含在compile 'com.alibaba:arouter-api中了

**Comment by zhi1ong** [comment]
基础问题，自行参照Q&A排查，或者加交流群管理员给你解答
