### ISSUE TITLE
和butterknife冲突

### ISSUE THREAD

**Issue by DJYSmall** [alibaba/ARouter#134]
Error:Execution failed for task ':app:compileDebugAndroidTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by zhangluya** [comment]
@DJYSmall hi，我也遇到这个问题了，请问你是怎么解决的？

**Comment by DJYSmall** [comment]
@zhangluya 你看看你用的是不是apt，改成 annotationProcessor 试试有没有用

**Comment by DJYSmall** [comment]
你看看你用的是不是apt，改成 annotationProcessor 试试有没有用



在 2017-06-26 17:30:27，"zhangluya" <notifications@github.com> 写道：


@DJYSmall hi，我也遇到这个问题了，请问你是怎么解决的？

**Comment by yanxinmiao** [comment]
同样遇到， 项目总有个module ，加入了ARouter支持Kotlin的配置后，butterknife 就有问题了，生成不了模板代码，bindview 得到的控件都是null 。

把如下代码注释后， butterknife 使用正常
`
apply plugin: 'kotlin-kapt'
kapt {
    arguments {
        arg("moduleName", project.getName())
    }
}
kapt 'com.alibaba:arouter-compiler:1.0.3'
`
这问题怎么解决呢 ?? @zhi1ong

**Comment by YummyLau** [comment]
@yanxinmiao 你的gradle版本是？

**Comment by yanxinmiao** [comment]
```
 classpath 'com.android.tools.build:gradle:3.0.0'
```

**Comment by yanxinmiao** [comment]
```
 kapt 'com.jakewharton:butterknife-compiler:8.8.1'
```
butterknife 依赖时annotationProcessor 改成 kapt问题就解决了， 具体原因不知道 。
