### ISSUE TITLE
传递对象参数时出现空指针异常

### ISSUE THREAD

**Issue by dingchao823** [alibaba/ARouter#135]
`
HomeBody homeBody = new HomeBody("mm");

ARouter.getInstance().build("/app/appActivity")
                        .withString("mm", "1")
                        .withString("ff", "1")
                        .withObject("object", homeBody)
                        .navigation();
`
* mm, ff 两个参数是可以传递的，@AutoWire 工作正常。

* withObject（） 报错 java.lang.NullPointerException，后来添加了 fastJson 依赖，问题依旧。请问这个问题应该从哪方面着手。

**Comment by dingchao823** [comment]
是因为没有实现 SerializationService 接口导致不能传递对象，接收的对象可以不用实现该接口。

**Comment by clstudy** [comment]
我实现SerializationService 接口，还是会有空指针
