### ISSUE TITLE
关于序列化对象的传递

### ISSUE THREAD

**Issue by yihuajia** [alibaba/ARouter#139]
请问目前不能通过withSerializable来传递一个序列化过后的对象，而只能是通过实现SerializationService这个接口来传递吗？

**Comment by zhi1ong** [comment]
嗯，Serializable 这种不好做 url 中取值的兼容，就直接放弃了

**Comment by zhi1ong** [comment]
只是不能注入，不是不能传递

**Comment by yihuajia** [comment]
谢谢，通过bundle传递了

**Comment by zhi1ong** [comment]
withSerializable 是可以继续用的，只不过在目标页面自动注入。

**Comment by taosimple** [comment]
最好在注释或文档上写一下，发现传的值是null，还以为哪里用错了，搜索才找到这里来
