### ISSUE TITLE
apt切换到annotationProcessor后找不到编译项目

### ISSUE THREAD

**Issue by lfp1991lfp** [alibaba/ARouter#14]
java.lang.RuntimeException: Arouter::Compiler >>> No module name

**Comment by zhi1ong** [comment]
apt传参也要用新写法

**Comment by lfp1991lfp** [comment]
有类似的传参写法吗

**Comment by zhi1ong** [comment]
看一下文档 '其他#4'

**Comment by gmfbilu** [comment]
我也遇到类似的问题
请问你最后是怎么解决的啊，我的gradle版本是3.0.1
