### ISSUE TITLE
 Fragment 中使用 @Autowired ，按官方 proguard 配置混淆后于无法正确获取 argment 中的值

### ISSUE THREAD

**Issue by lasttimes** [alibaba/ARouter#140]
正常来说 Fragment 是无需混淆的，估计测试的程序默认把所有 Fragment 混淆了？

解决办法：
于 proguard 文件中添加以下两行，不混淆有使用了 @Autowired 的类及对应成员
-keep class com.alibaba.android.arouter.facade.annotation.Autowired
-keepclasseswithmembers class * {
    @com.alibaba.android.arouter.facade.annotation.Autowired <fields>;
}

**Comment by zhi1ong** [comment]
正常四大组件和 Fragment 一般都是不混淆的，这个我没有标注，回头把这个整理到文档中
