### ISSUE TITLE
不同Moudle之间的跳转有时候可以有时候不可以

### ISSUE THREAD

**Issue by leon2017** [alibaba/ARouter#142]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhi1ong** [comment]
请提供更多细节，多 module 调用和跳转经测试没有问题

**Comment by SuXiGithub** [comment]
请确保在使用到Router的module的gradle中加入如下两个代码块
javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ moduleName : project.getName() ]
            }
        }

 annotationProcessor 'com.alibaba:arouter-compiler:1.0.3'
