### ISSUE TITLE
Interceptor不支持继承的问题

### ISSUE THREAD

**Issue by maplebilly** [alibaba/ARouter#143]
## Look at here

在InterceptorProcessor中看到如下验证的方法，在这里应该限制了拦截器必须是直接实现Interceptor接口才能被正确处理，如果是父类实现了接口是无法被正确处理的。
想问一下这方面是怎么考虑的？
因为考虑过做一个baseInterceptor去做一些统计，虽然后来发现没什么必要，但是发现了这个问题，想了解一下当时是如何考虑的。
谢谢~
private boolean verify(Element element) {
        Interceptor interceptor = element.getAnnotation(Interceptor.class);
        // It must be implement the interface IInterceptor and marked with annotation Interceptor.
        return null != interceptor && ((TypeElement) element).getInterfaces().contains(iInterceptor);
    }

**Comment by zhi1ong** [comment]
拦截器本身是没必要继承的， 所有的拦截器都要过一遍的，拦截器这种面向切面的思路就是 你放进来就生效，移出去就失效的东西，互相继承，就不符合单一原则了
