### ISSUE TITLE
拦截器问题。

### ISSUE THREAD

**Issue by chenyang1900** [alibaba/ARouter#147]
在想怎么实现界面替换 ，如 要搞一个活动，原生界面不满足需要 ，如何把这个界面改成web页而又不影响其他原生界面，然后活动结束又替换回来 。又或者一个界面发生崩溃或存在问题 ，把他替换成web页 。 基于ARouter 怎么能够快速的实现这个。怎么基于跳转拦截器实现这个问题

**Comment by zhi1ong** [comment]
这个分成两个问题：
第一个用拦截器，可以通过接口下发一部分路径列表，如果符合的跳转到活动页
第二个要用全局降级，ARouter会在跳转失败之后调用全局降级，如果你配置了的话，可以弄一个公共错误页，来集中处理这些异常情况

>> issues 只接收 bug和建议，交流提问请去 交流群。

**Comment by dukezhao** [comment]
全局降级咋用？
