### ISSUE TITLE
Fragment如何跳转呢

### ISSUE THREAD

**Issue by xiaolongyuan** [alibaba/ARouter#149]
示例Demo只有简单的
```
  Fragment fragment = (Fragment) ARouter.getInstance().build("/test/fragment").navigation();
  Toast.makeText(this, "找到Fragment:" + fragment.toString(), Toast.LENGTH_SHORT).show();
```

如果是从webview中直接导航到Fragment 而Fragment又需要Activity包裹 有什么好的处理方式么？

我想到的是使用拦截器

**Comment by zhi1ong** [comment]
没有什么太好的处理方式，ARouter只能提供获取Fragment实例，你这种还是要跳转到 Activitity，在Activity中通过参数决定使用的Fragment，交流不要用 issues，去交流群

**Comment by sanxieryu** [comment]
可以定义一个Activity ，先navigation()到activity 并携带参数withString("target","/test/fragment"),在activity中取参数并navigation() 得到Fragment， 在用activity显示fragment

**Comment by zhi1ong** [comment]
嗯，其实能拿到 Fragment 实例，就可以自行发挥了，Fragment 这种还做不到那么通用，一般也是专用于部分页面的，拿到实例自己处理比较合适

**Comment by yangyiRunning** [comment]
@sanxieryu   

接着你上面的论述说，那如果是activity要像自己孵化出的fragment传参呢？  是不是ARouter就帮不上什么忙了？   只能用传统的newInstance的方式从宿主activity向fragment传想要的参数？

**Comment by yangyiRunning** [comment]
@sanxieryu

接着你上面的论述说，那如果是activity要向自己孵化出的fragment传参呢？ 是不是ARouter就帮不上什么忙了？ 只能用传统的newInstance的方式从宿主activity向fragment传想要的参数？

**Comment by devshawn-github** [comment]
i find  this case ,  withX method have benn used to jump to frgament but  does not work as expcted. Finally, Fragment.setArguments works

**Comment by GitChenM** [comment]
传参：ARouter.getInstance().build(RouterMap.Floor.tangFragment).withBundle("eventBundle", bundle).navigation() as Fragment
获取 ：  val bundle = arguments?.getBundle("eventBundle")

**Comment by shawndegit** [comment]
Thanks
