### ISSUE TITLE
和Dagger冲突，导致无法使用

### ISSUE THREAD

**Issue by wensonli** [alibaba/ARouter#151]
使用 开启 Dagger2 后apply plugin: 'com.neenbedankt.android-apt'，ARouter无法跳转，
gradle去掉dagger2后正常。

请问ARouter是否可以支持Dagger2 ?

**Comment by zhi1ong** [comment]
和 Dagger2 没关系，要么都用 'com.neenbedankt.android-apt' ，要么都用 annotationProcessor ,不能混用
