### ISSUE TITLE
从Library 1不能跳转Library 2

### ISSUE THREAD

**Issue by BeEagle** [alibaba/ARouter#152]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

package com.troy.module1;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import com.alibaba.android.arouter.facade.annotation.Route;
import com.alibaba.android.arouter.launcher.ARouter;

@Route(path = Constant.Module1Path.OrderActivity)
public class OrderActivity extends AppCompatActivity {

    Button module1_tv;
    Button module1_tv2;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_order);

        module1_tv = (Button)findViewById(R.id.module1_tv);
        module1_tv2 = (Button)findViewById(R.id.module1_tv2);

        module1_tv.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ARouter.getInstance()
                        .build("/order/order1activity")
                        .navigation();
            }
        });

        module1_tv2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ARouter.getInstance()
                        .build("/module2/orderactivity")
                        .navigation();
            }
        });

    }
}

package com.troy.module2;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import com.alibaba.android.arouter.facade.annotation.Route;
@Route(path = "/module2/orderactivity")
public class OrderActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_order);
    }
}

**Comment by zhi1ong** [comment]
module之间相互依赖了么
