### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by JavenCoder** [alibaba/ARouter#153]
## Look at here

i: 注: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule]
i: 

i: 注: ARouter::Compiler >>> AutowiredProcessor init. <<<
i: 

w: 警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.AutowiredProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
w: 

i: 注: ARouter::Compiler >>> Found autowired field, start... <<<
i: 

i: 注: ARouter::Compiler categories finished.
i: 

i: 注: ARouter::Compiler >>> Start process 1 field in StoryListFragment ... <<<
i: 

i: 注: ARouter::Compiler >>> StoryListFragment has been processed, StoryListFragment$$ARouter$$Autowired has been generated. <<<
i: 

i: 注: ARouter::Compiler >>> Autowired processor stop. <<<
i: 

i: 注: ARouter::Compiler The user has configuration the module name, it was [app]
i: 

i: 注: ARouter::Compiler >>> InterceptorProcessor init. <<<
i: 

w: 警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.InterceptorProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
w: 

i: 注: ARouter::Compiler The user has configuration the module name, it was [app]
i: 

i: 注: ARouter::Compiler >>> RouteProcessor init. <<<
i: 

w: 警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.RouteProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
w: 

i: 注: ARouter::Compiler >>> Found routes, start... <<<
i: 

i: 注: ARouter::Compiler >>> Found routes, size is 1 <<<
i: 

e: 错误: ARouter::Compiler An exception is encountered, [null]
e: 

e:       at com.alibaba.android.arouter.compiler.processor.RouteProcessor.routeVerify(RouteProcessor.java:407)
e:       at com.alibaba.android.arouter.compiler.processor.RouteProcessor.categories(RouteProcessor.java:376)
e:       at com.alibaba.android.arouter.compiler.processor.RouteProcessor.parseRoutes(RouteProcessor.java:245)
e:       at com.alibaba.android.arouter.compiler.processor.RouteProcessor.process(RouteProcessor.java:146)
e:       at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
e:       at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
e:       at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
e:       at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
e:       at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
e:       at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
e:       at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
e:       at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:73)
e:       at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:42)
e:       at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:205)
e:       at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:166)
e:       at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:82)
e:       at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:89)
e:       at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:99)
e:       at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:76)
e:       at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.analyze(KotlinToJVMBytecodeCompiler.kt:365)
e:       at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:105)
e:       at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:354)
e:       at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:139)
e:       at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
e:       at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
e:       at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:182)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl.execCompiler(CompileServiceImpl.kt:397)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execCompiler(CompileServiceImpl.kt:99)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:365)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:99)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2$$special$$inlined$withValidClientOrSessionProxy$lambda$1.invoke(CompileServiceImpl.kt:798)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2$$special$$inlined$withValidClientOrSessionProxy$lambda$1.invoke(CompileServiceImpl.kt:99)
e:       at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:825)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$checkedCompile(CompileServiceImpl.kt:99)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2.invoke(CompileServiceImpl.kt:797)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2.invoke(CompileServiceImpl.kt:99)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive(CompileServiceImpl.kt:1004)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive$default(CompileServiceImpl.kt:865)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:791)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$doCompile(CompileServiceImpl.kt:99)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1.invoke(CompileServiceImpl.kt:364)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1.invoke(CompileServiceImpl.kt:99)
e:       at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:336)
e:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
e:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
e:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
e:       at java.lang.reflect.Method.invoke(Method.java:498)
e:       at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
e:       at sun.rmi.transport.Transport$1.run(Transport.java:200)
e:       at sun.rmi.transport.Transport$1.run(Transport.java:197)
e:       at java.security.AccessController.doPrivileged(Native Method)
e:       at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
e:       at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
e:       at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
e:       at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
e:       at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
e:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
e:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
e:       at java.lang.Thread.run(Thread.java:745)

**Comment by JavenCoder** [comment]
r如果是Demo中的Activity没有问题如果是一个普通 的Koltin类就不行了~~  然后就要报错e: 错误: ARouter::Compiler An exception is encountered, [null]
e: 

e:       at com.alibaba.android.arouter.compiler.processor.RouteProcessor.routeVerify(RouteProcessor.java:407)
e:       at com.alibaba.android.arouter.compiler.processor.RouteProcessor.categories(RouteProcessor.java:376)
e:       at com.alibaba.android.arouter.compiler.processor.RouteProcessor.parseRoutes(RouteProcessor.java:245)
e:       at com.alibaba.android.arouter.compiler.processor.RouteProcessor.process(RouteProcessor.java:146)

**Comment by JavenCoder** [comment]
`
/**
 * 故事仓库
 * Created by coder on 2017/7/18.
 */
@Route(path = "/kotlin/aa")
class StoryRepo{


    /**
     * 获取所有的分类
     */
    fun listStoryCategory(): List<Category> {
        val arrayList = ArrayList<Category>()
        return (0 until 10).mapTo(arrayList) { Category("$it", "Item:$it") }
    }
`

**Comment by JavenCoder** [comment]
类似这样的类~~

**Comment by bestreview** [comment]
你解决了吗 我也遇到了同样的问题了

**Comment by zhi1ong** [comment]
要用 Kapt

**Comment by yatou252303** [comment]
呃，这个问题我这边也遇到，通过异常看不出来任何有用的信息。在Fragment上@Route（path=‘’），报的这个错。最后发现，自己写的BaseFragment 竟然没有继承Fragment，导致Arouter 无法读取注解信息，我类个擦。手残浪费了一大天

**Comment by starktonys** [comment]
> 呃，这个问题我这边也遇到，通过异常看不出来任何有用的信息。在Fragment上@route（path=‘’），报的这个错。最后发现，自己写的BaseFragment 竟然没有继承Fragment，导致Arouter 无法读取注解信息，我类个擦。手残浪费了一大天

大佬你怎么解决的
