### ISSUE TITLE
多模块引用会报错，望解决

### ISSUE THREAD

**Issue by vdiskmobile** [alibaba/ARouter#155]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

多Module引用com.alibaba:arouter-api:1.2.1.1
会报错：
com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Group$$module;

我更希望的姿势是，每个Module可以进行单独的app发布，多个Module可添加到主App中，作为一个大App发布，单个Module引用没问题，同时添加到主App中会报Multiple dex files define的错误，试了无法进行exclude

**Comment by zhi1ong** [comment]
这是因为你在多个module中定义了相同的group 的 path

**Comment by zhi1ong** [comment]
多个模块的 library name 不要相同，别都叫 module

**Comment by zhangjilei106787** [comment]
我的项目里面主工程引用了 一个szlirbary, szlirbary引用了另一个基础lirbary         现在  szlirbary和主app项目都引用了ARouter框架    主app工程和类库szlirbary都配置了  javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
            }
        } 
在主app里面初始化了    现在主app里面跳转szlirbary 里面一个activity 无法跳转  路径也对
报了 Cannot find local variable 'getChildCount'
求解答  不知道怎么回事
