### ISSUE TITLE
关于init时反射问题

### ISSUE THREAD

**Issue by YZHIWEN** [alibaba/ARouter#156]
- 在ARouter调用init的时候，我看到用到很多反射调用apt生成代码，看到官方介绍文档时也提出反射消耗性能，不理解目前通过apt再去反射带来的好处，这种方式不是需要更多的反射反射操作吗？

**Comment by zhi1ong** [comment]
这种方案是尽可能少的反射，跳转的时候没有反射，反射是用来加载路由表，做不到完全没有反射。

**Comment by YZHIWEN** [comment]
尽可能少的反射？你怎么衡量

**Comment by zhi1ong** [comment]
可以阅读以下源码，这里反射只是加载每个模块的根路由表，这个表中保存了其他的group，可以简单的认为没多一个模块，多1~3次反射，通常一个app少有100个或以上数量的模块(可以认为是尽可能少)，如果每个页面都反射，平均一个模块有数十个页面，反射的数量至少是10倍以上

**Comment by YZHIWEN** [comment]
其实我只是觉得这里还有优化空间，只是性价比问题。

目前是通过apt -> 生成代码 -> 反射，我觉得直接通过反射一个模块的规范的初始化代码，也许会更简单。通过apt只是增加编译工作量，其实还是用到反射，反射工作量应该可以更好避免

**Comment by YZHIWEN** [comment]
自己的见解想法

**Comment by zhi1ong** [comment]
apt 是为了把需要反射的信息收集起来，方便init的时候进行处理，如果不用apt来收集，不同的模块怎么知道去反射哪些文件呢
