### ISSUE TITLE
使用Autowired解析List类型的参数

### ISSUE THREAD

**Issue by wuzhendev** [alibaba/ARouter#157]
在使用 @Autowired 解析List<String>类型的参数时生成的代码：
`substitute.getIntent().getStringExtra("extra"), ArrayList<String>.class`

请问如何使用Autowired解析List类型传递的参数

**Comment by zhi1ong** [comment]
目前没支持，场景有限，可以考虑支持一下

**Comment by liujing906qd** [comment]
有些时候需要前端页面给到一些复杂列表数据，比如带有属性的图片列表。fastjson 有通过List<范型>获取class的支持，这边有可能的话，可以考虑一下支持。
