### ISSUE TITLE
ARouter  withObject 传对象就报错

### ISSUE THREAD

**Issue by Onionsss** [alibaba/ARouter#160]
` Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.object2Json(java.lang.Object)' on a null object reference`

看一下 分析下是什么原因

**Comment by zhi1ong** [comment]
不用分析，是因为你没实现 SerializationService，仔细看看文档

**Comment by Onionsss** [comment]
好的 解决了

**Comment by wpq2014** [comment]
我实现了，但还是报错了，不过只出现了一次
@Route(path = "/service/json")
public class JsonServiceImpl implements SerializationService {

    @Override
    public void init(Context context) {

    }

    @Override
    public <T> T json2Object(String text, Class<T> clazz) {
        return new Gson().fromJson(text, clazz);
    }

    @Override
    public String object2Json(Object instance) {
        return new Gson().toJson(instance);
    }

    @Override
    public <T> T parseObject(String input, Type clazz) {
        return new Gson().fromJson(input, clazz);
    }

}

日志：
java.lang.NullPointerException

Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.a(java.lang.Object)' on a null object reference

com.alibaba.android.arouter.facade.Postcard.com.alibaba.android.arouter.facade.Postcard withObject(java.lang.String,java.lang.Object)(Postcard.java:244)

机型：三星 SM G950F    
版本：Android 8.0.0,level 26    
ROM：samsung/dreamltexx
CPU：armeabi

**Comment by thwchao** [comment]
实体类必须要有空构造

**Comment by parcool** [comment]
这些问题官方文档只字不提， 全靠别人采坑。果断unstar

**Comment by tangshxiao** [comment]
难用的要死

**Comment by qweenhool** [comment]
> 这些问题官方文档只字不提， 全靠别人采坑。果断unstar

说的一点也不错，我被坑好几回了，这就是所谓的国内大厂出品的么？
