### ISSUE TITLE
IInterceptor 拦截器没有被初始化！

### ISSUE THREAD

**Issue by crazy1235** [alibaba/ARouter#161]
拦截器没有被初始化，init()函数没有被回调！

`@Interceptor(priority = 1, name = BaseContract.NAME_LOGIN_INTERCEPTOR)
public class LoginInterceptor implements IInterceptor {
    @Override
    public void process(Postcard postcard, InterceptorCallback callback) {

        Log.d("LoginInterceptor", "process");

        int extra = postcard.getExtra();

        Log.d("LoginInterceptor", "extra:" + extra);
       }

    @Override
    public void init(Context context) {
        Log.d("LoginInterceptor", context.toString());
    }
}
`

请问这是怎么回事？

**Comment by zhi1ong** [comment]
问题请去交流群咨询，这里仅接受bug

你这个问题多半是因为你这个拦截器并没有被识别到，所在的module没有配置 AnnotationProcessor
