### ISSUE TITLE
Build出错

### ISSUE THREAD

**Issue by songzhw** [alibaba/ARouter#17]
我的build.gradle是：
```groovy
compile 'com.alibaba:arouter-api:1.0.3'
annotationProcessor 'com.alibaba:arouter-compiler:1.0.3'
```

出错：

```
Error:Failed to resolve: annotationProcessor
```
==================================================
备注： 
我把build.gradle中的1.0.3改成1.0.2仍失败， 同样的错误
但改为1.0.1就build成功了

请问是不是高版本的没有上传到仓库里？

**Comment by zhi1ong** [comment]
以jcenter为准

看错误可能不是找不到sdk，而是gradle-plugin版本小于2.2，不支持annotationProcessor

**Comment by songzhw** [comment]
我用的是2.2，应该是支持annotationProcessor
