### ISSUE TITLE
跨进程路由

### ISSUE THREAD

**Issue by starchen84** [alibaba/ARouter#170]
请问支持跨进程路由吗？

**Comment by zhi1ong** [comment]
暂不支持，场景不够丰富，支持影响性能

**Comment by daliyan** [comment]
> 暂不支持，场景不够丰富，支持影响性能

这话感觉不能同意。跨进程还是存在需求的，而且如果能够在调用的时候很好的区分本地还是跨进程是不会影响性能的。
