### ISSUE TITLE
主工程无法跳转module

### ISSUE THREAD

**Issue by ChasonChen** [alibaba/ARouter#171]
基本情况，主app依赖base模块，依赖在添加在base模块中，在主app和base模块的build.gradle文件对应位置都有添加javaCompileOptions代码段，在Application中有添加ARouter.openDebug()。开启instantRun后，无法跳转，关闭后就能成功跳转。

**Comment by ChasonChen** [comment]
补充，工程中没有使用apt，全部为annotationProcessor。

**Comment by zhi1ong** [comment]
首先肯定可以跳转到 子模块的，这里只接收bug反馈，问题请去交流群，可以检查一下子模块是不是配置了 annotationProcessor

**Comment by ChasonChen** [comment]
这个是我写的一个Demo，有详细描述过程，有空你看看吧。https://github.com/ChasonChen/ARouterDemo
