### ISSUE TITLE
加固后部分机型获取不到

### ISSUE THREAD

**Issue by heqiwen** [alibaba/ARouter#173]
## Look at here
部分机型 魅族m1 系统版本：Flyme os 4.2.1.3Y
360加固后 和 乐固加固后  ARouter.getInstance().build() 获取不到 报 java.lang.NullPointerException: java.lang.NullPointerException

**Comment by jack-github** [comment]
360加固不正常，腾讯乐固、不加固正常！

**Comment by zhi1ong** [comment]
这个需要 360 的开发同学支持一下，请直接联系他们的客服

**Comment by jack-github** [comment]
已经360客服沟通过了，他们已经定位到问题了，后面会发版修复！

**Comment by wpq2014** [comment]
这个问题解决了吗？
