### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.object2Json(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by wangweiqi23** [alibaba/ARouter#175]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.object2Json(java.lang.Object)' on a null object reference

跳转代码如下：
ARouter.getInstance().build("/home/activity/tween")
                        .withLong("key1", 666L)
                        .withString("key3", "888")
                        .withObject("key4", new MyOjbect("Jack", 1))
                        .navigation();

工程中已经实现了这个解析类：

    @Route(path = "/service/json")
    public class JsonServiceImpl implements SerializationService {
    @Override
    public void init(Context context) {

    }

    @Override
    public <T> T json2Object(String text, Class<T> clazz) {
        return JSON.parseObject(text, clazz);
    }
    @Override
    public String object2Json(Object instance) {
        return JSON.toJSONString(instance);
    }
    }

不知道哪里问题了？？

**Comment by zhi1ong** [comment]
你可以尝试着单独获取这个service试试，这个错误是ARouter没拿到这个service

**Comment by BingoHe** [comment]
我也遇到这个问题了，都不解释一下吗？直接close了？

**Comment by zhi1ong** [comment]
明显是版本太老了 `SerializationService` 里面是有 3 个方法的，虽然废弃了一个
