### ISSUE TITLE
jdk版本过低

### ISSUE THREAD

**Issue by Vicenttree** [alibaba/ARouter#179]
Error:注: ARouter::Compiler >>> AutowiredProcessor init. <<<
警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.AutowiredProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler >>> Found autowired field, start... <<<

**Comment by zhi1ong** [comment]
这个只是一个 警告，没有影响

**Comment by liuxuesong001** [comment]
我也出现了，但是无法运行，有影响
