### ISSUE TITLE
请教每个module都要配置annotationProcessorOptions吗？有没有统一的设置

### ISSUE THREAD

**Issue by petersom** [alibaba/ARouter#180]
注: ARouter::Compiler >>> AutowiredProcessor init. <<<
错误: ARouter::Compiler An exception is encountered, [These no module name, at 'build.gradle', like :
  apt {
      arguments {
          moduleName project.getName();
      }
  }
  ]

 FAILED

请教有很多moudle时，每个module都要配置annotationProcessorOptions吗？有没有统一的设置

**Comment by zhi1ong** [comment]
是每个module都要配置的，为了应对单个module 分别编译的场景

**Comment by moonljt521** [comment]
项目里有很多module，没有用到arouter的module 也要配置么，目前不配置报错了
