### ISSUE TITLE
在AndroidManifest.xml里设置android:launchMode无效

### ISSUE THREAD

**Issue by wannoo1990** [alibaba/ARouter#182]
有几个Activity设置了android:launchMode="singleTask"和android:launchMode="singleInstance"，使用startActivity跳转界面，设置能生效，但使用 ARouter.getInstance().build(path).navigation()设置却无法生效。还是一直创建新界面，getTaskId()也一直是新的。

**Comment by wannoo1990** [comment]
请问ARouter.getInstance().build(path).navigation()时有办法可以设置目标的Flag嘛，比如这样：
        intent.setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);
        startActivity(intent);

**Comment by YuMengShuaii** [comment]
因为你只能通过ARouter的withFlag来设置LaunchMode   ARouter在跳转Activity的时候处理Flag了  代码如下
                int flags = postcard.getFlags();
                if (-1 != flags) {
                    intent.setFlags(flags);
                } else if (!(currentContext instanceof Activity)) {    // Non activity, need less one flag.
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                }

**Comment by wuhaiyang** [comment]
@YuMengShuaii @zhi1ong 能否给这个地方设置一个优先级呢？manifest 优先级高于withFlag

**Comment by YuMengShuaii** [comment]
@wuhaiyang   从我贴的代码段可以看出  如果你在跳转activity的时候传入当前activity对象，他就不会为intent设置Flag，因为arouter跳转startActivity的时候不传activity对象的话，默认使用的ApplicationContext，使用ApplictaionContext跳转必须加上Intent.FLAG_ACTIVITY_NEW_TASK这个flag，所以可以写成这样.navigation(activity);

**Comment by zhi1ong** [comment]
@YuMengShuaii  正解 ！
