### ISSUE TITLE
用 Robolectric 跑测试时，无法 init，在初始化 Activity 之前拿不到 application，请问有办法解决吗

### ISSUE THREAD

**Issue by fujian26** [alibaba/ARouter#184]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhi1ong** [comment]
没有 Application 无法完成初始化，需要逻辑上想办法解决
