### ISSUE TITLE
使用服务的混淆配置

### ISSUE THREAD

**Issue by GypsyLife** [alibaba/ARouter#188]
- → 使用服务、拦截器时需要增加如下混淆配置，
-keep class * implements com.alibaba.android.arouter.facade.template.IProvider{*;}
-keep class * implements com.alibaba.android.arouter.facade.template.IInterceptor{*;}
相关混淆配置的文档请更新。

**Comment by zhi1ong** [comment]
不需要keep这两个，IProvider 和 IInterceptor 会被 keep 掉

**Comment by fifa0329** [comment]
经验证 确实需要
加上
-keep class * implements com.alibaba.android.arouter.facade.template.IProvider{;}
-keep class * implements com.alibaba.android.arouter.facade.template.IInterceptor{;}
