### ISSUE TITLE
多fragment单activity拦截器不管用

### ISSUE THREAD

**Issue by yihuajia** [alibaba/ARouter#189]
在单activity多fragment的结构下，自定义的拦截器好像并没有起到作用，拦截器初始化成功了的。难道只能用于拦截activity的跳转？那如果是要实现登录拦截的话，那不是只能在PathReplaceService中进行了？

**Comment by yihuajia** [comment]
看才看了下源码，postcard.greenChannel(); 为什么要这样做呢？谢谢

**Comment by zhi1ong** [comment]
Fragment 目前只能提供获取实例，不能提供跳转，so 不会进行拦截，否则会导致主线程阻塞
