### ISSUE TITLE
跨模块拦截器不起作用

### ISSUE THREAD

**Issue by TealerProg** [alibaba/ARouter#191]
## Look at here
操作步骤，比如：
从主工程进入A模块，A模块设置登录拦截器，从A模块跳转到B模块的B1界面，B1界面要检查用户是否登录，但是拦截器不起作用

**Comment by zhi1ong** [comment]
建议自行断点调试一下，确认拦截器是否生效，要保证A模块打包进最终产物

**Comment by TealerProg** [comment]
好的，已经解决问题，可以拦截了

**Comment by moonljt521** [comment]
怎么解决的。。。
