### ISSUE TITLE
关于ARouter的依赖注入

### ISSUE THREAD

**Issue by EthanCo** [alibaba/ARouter#192]
想用ARouter的IProvider来进行依赖注入Model层和Presenter层，但发现一个问题。
查看源码发现所有初始化后的provider是放在Warehouse.providers 这个Map中的，那么所有Model层和Persenter层只要初始化过后，就一直强引用着，这样子会造成内存泄漏吧。  

     Class<? extends IProvider> providerMeta = (Class<? extends IProvider>) routeMeta.getDestination();
     IProvider instance = Warehouse.providers.get(providerMeta);
     if (null == instance) { // There's no instance of this provider
           IProvider provider;
           try {
                  provider = providerMeta.getConstructor().newInstance();
                  provider.init(mContext);
                  Warehouse.providers.put(providerMeta, provider);
                  instance = provider;
           } catch (Exception e) {
                   throw new HandlerException("Init provider failed! " + e.getMessage());
            }
      }
     postcard.setProvider(instance);

**Comment by zhi1ong** [comment]
设计上的考虑是一个 app 虽然提供大量的功能，但是不会所有的功能都是频繁使用的，Service 只有用过之后才会被缓存，只初始化一次，Service 是不应该依赖页面的，不会有内存泄漏

**Comment by EthanCo** [comment]
还是有些不理解
我对内存泄漏的理解是 指某些内存由于某种原因无法被释放，只是View的内存泄漏更为显著吧。
我希望的是Activity销毁的时候，相应的Model和Presenter也能够被销毁，GC的时候能够被回收。  
IProvider这个好像不符合我的需求。
IProvider似乎更适用于跨组件之间的解耦或提供一些单例的实例，没理解错的话，应该是这样子吧。

**Comment by zhi1ong** [comment]
IProvider 主要是用于组件间通信的，可以互相调用，作为一个单例的Service，肯定要一直持有，不然就失去意义了，每次都重新初始化，Model Presenter 的场景就是你自己的发挥了

**Comment by EthanCo** [comment]
好的，谢谢 !
