### ISSUE TITLE
关于Arouter中Fragment的@Autowired获取不到参数值的问题

### ISSUE THREAD

**Issue by liangruiyuwanba** [alibaba/ARouter#193]
代码如下：

BlankFragment fragment = (BlankFragment) ARouter.getInstance().build(Uri.parse("arouter://m.aliyun.com/test/fragment?name=liangsanbo")).navigation();
                FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
                transaction.add(fragment, "ChoiceSecondGameDialogFragment");
                transaction.commitAllowingStateLoss();

Fragment：
@Route(path = "/test/fragment")
public class BlankFragment extends DialogFragment {

    @Autowired
    String name;

    public BlankFragment() {
        // Required empty public constructor
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ARouter.getInstance().inject(this);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        Log.d("TEST","name:"+name);
        View view = View.inflate(this.getActivity(),R.layout.fragment_test,null);
        return view;
    }

}

为什么name的值是null呢？请问哪里写的不正确吗？

**Comment by zhi1ong** [comment]
请自行断点调试

**Comment by liangruiyuwanba** [comment]
我调试了啊，paramtype为空，导致没有注入，只能使用withLong这种形式才能注入程序，url这种形式不可以，估计是你们的程序有问题吧？

**Comment by liangruiyuwanba** [comment]
这个问题只有在fragmeng注入的时候有问题，但是activity是正常的

**Comment by zhi1ong** [comment]
你在他的 Activity 容器中能拿到 Extra 中的内容么？ Fragment的注入就是通过 getArguments() 实现的，要是父容器里面都没有 Intent 的话，肯定不是不能注入的

**Comment by jiahongfei** [comment]
你在他的 Activity 容器中能拿到 Extra 中的内容么？ Fragment的注入就是通过 getArguments() 实现的，要是父容器里面都没有 Intent 的话，肯定不是不能注入的

我不太理解这个意思，我目前也碰到这种情况了额

**Comment by Billxxxx** [comment]
> 这个问题只有在fragmeng注入的时候有问题，但是activity是正常的

RouteProcessor 第242 只有activity的时候才会根据Autowired注解写入paramsType这个变量，fragment的时候是没有的，paramsType这个变量关系到url是否支持转换为属性。

**Comment by SwiftyWang** [comment]
> RouteProcessor 第242 只有activity的时候才会根据Autowired注解写入paramsType这个变量，fragment的时候是没有的，paramsType这个变量关系到url是否支持转换为属性。
发现了，现在有fix这个问题吗？
