### ISSUE TITLE
反射方法getAnnotation找不到Route注解

### ISSUE THREAD

**Issue by huwentao** [alibaba/ARouter#195]
`

  @Layout(R.layout.activity_login)
  @Route(path = "/enter/loginActivity")
  @TranslucentStatusBar
  class LoginActivity : BaseActivity(), LoginContract.LoginView {}

`

`

  abstract class BaseActivity : AppCompatActivity() {
    fun callMe(targetClass: Class<out BaseActivity>) {
          val route = targetClass.getAnnotation(Route::class.java)
         //得到route为null
          if (route != null && route.path.isNotEmpty()) {
              ARouter.getInstance().build(route.path).navigation()
          }
      }
  }

`

**以上可以查询到Layout跟TranslucentStatusBar注解，但是查不到Route，麻烦告知是什么原因**

**Comment by zhi1ong** [comment]
想要在运行的时候获取注解？@Route 不是 Runtime注解，运行期拿不到
