### ISSUE TITLE
跳转Activity的时候能否不强制使用post(Runnable)方式

### ISSUE THREAD

**Issue by qq549631030** [alibaba/ARouter#197]
跳转Activity的时候现在是强制使用post(Runnable)方式，能不能先判断现在是不是在主线程，是的话直接执行跳转，不是的时候再用post(Runnable)
现在这种实现调navigation后立即调finish()关掉当前Activity会出现白屏

**Comment by zhi1ong** [comment]
不能直接 finish ,可以在跳转的 onArrival 回调中 finish
