### ISSUE TITLE
在Fragment里面 跳转问题。

### ISSUE THREAD

**Issue by caijia** [alibaba/ARouter#198]
fragment 跳activity 原生跳转： startActivityForResult(intent,requestCode);  由于是用fragment的实例调用。所有可以在fragmet的 onActivityResult(int requestCode, int resultCode, Intent data) 的方法收到回调。

aRouter跳转：ARouter.getInstance().build("xx/xx").navigation(getActivity(), 200);  不能在fragment里面的
onActivityResult 收到回调。

**Comment by shitb** [comment]
同问. 一样的问题

**Comment by yangyiRunning** [comment]
@caijia   

README文件里面作者的说法：↓

` // 构建标准的路由请求，startActivityForResult
// navigation的第一个参数必须是Activity，第二个参数则是RequestCode
ARouter.getInstance().build("/home/main", "ap").navigation(this, 5); `

文档内容中说第一个参数必须是Activity，点击进入去跟navigation方法的源码，最后定位在了ARouter类的_navigation方法下，里面有一句ActivityCompat.startActivityForResult...，说明这个startActivityForResult的动作是actvitiy启动起来的，而只有fragment.startActivityForResult...启动起来时fragment才能收到result回调。

**Comment by zhi1ong** [comment]
这是个老问题了，onActivityResult **推荐在 Activity 容器中进行转发**，暂时不会支持传递 Fragment，Fragment 本身不是 Context 子类，会影响 API 定义的复杂性

**Comment by wangrunxiang** [comment]
@zhi1ong API定义的复杂性？无法不就是增加一个Fragment的重载的问题？
