### ISSUE TITLE
ARouter初始化耗时太长

### ISSUE THREAD

**Issue by laomengzhu** [alibaba/ARouter#200]
整个App有8个跳转，ARouter初始化要消耗300MS，能否优化下初始化

**Comment by zhi1ong** [comment]
1. Debug 会耗时长，因为要支持 Instant Run
2. Release 的情况下耗时不会长，并且只有首次安装之后会加载路由表，以后打开都会读取缓存

**Comment by laomengzhu** [comment]
的确，Release版本耗时很短，第一次30ms，后面启动都是6ms以内，感谢！！！

**Comment by hongxialiu** [comment]
你好，是冷启动方式吗？release版本，杀掉app进程，然后启动，测冷启动速度会相比引入arouter之前多200ms

**Comment by Andylove1314** [comment]
我测的怎么每次初始化都得1000ms以上？

**Comment by s7655120** [comment]
我这边目前也发现每次初始化都需要1500ms左右

**Comment by zhpanvip** [comment]
> 我测的怎么每次初始化都得1000ms以上？

跟手机性能有关系，在天猫精灵上启动得7-8s的时间呢。

**Comment by zhi1ong** [comment]
涉及到 dex 扫描首装确实会比较耗时，要是app体量比较大的话，最好还是用 register 插件
