### ISSUE TITLE
@Autowired注解支持问题

### ISSUE THREAD

**Issue by liangruiyuwanba** [alibaba/ARouter#202]
@Autowired目前只支持在activity和fragment中使用，为什么不考虑扩展到普通类中，这样ARouter就可以和Spring框架相媲美了，因为本来咱们这个框架也参考了很多Spring框架的架构和思想

**Comment by zhi1ong** [comment]
框架的功能要聚焦，这些功能都是为了 组件化 服务的，不能做成工具箱。

**Comment by liangruiyuwanba** [comment]
这个也不是工具箱吧，这个只是解耦的一部分，就是为组件化服务的

**Comment by zhi1ong** [comment]
在 Context 中的注入是依赖 intent.get 的，如果在 普通类中做注入，就需要考虑是 get 还是反射了，用户使用的时候会遇到很多问题
