### ISSUE TITLE
x86的机型初始化crash

### ISSUE THREAD

**Issue by kobewylb** [alibaba/ARouter#203]
GI-I9500_TMMARS
系统版本

Android 5.1,level 22
ROM

Samsung/unia_x86
CPU架构
x86

java.lang.ExceptionInInitializerError:
--
2 com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:39)
3 ......
4 Caused by:
5 java.lang.IllegalArgumentException:
6 java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1277)
7 java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1200)
8 com.alibaba.android.arouter.thread.DefaultPoolExecutor.<init>(DefaultPoolExecutor.java:50)
9 com.alibaba.android.arouter.thread.DefaultPoolExecutor.getInstance(DefaultPoolExecutor.java:36)
10 com.alibaba.android.arouter.launcher._ARouter.<clinit>(_ARouter.java:51)
11 com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:39)
12 com.leoao.coach.app.CoachApplication.onCreate(CoachApplication.java:183)
13 com.stub.StubApp.onCreate(StubApplication.java:84)
14 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
15 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4562)
16 android.app.ActivityThread.access$1500(ActivityThread.java:151)
17 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
18 android.os.Handler.dispatchMessage(Handler.java:102)
19 android.os.Looper.loop(Looper.java:135)
20 android.app.ActivityThread.main(ActivityThread.java:5263)
21 java.lang.reflect.Method.invoke(Native Method)
22 java.lang.reflect.Method.invoke(Method.java:372)
23 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
24 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by kobewylb** [comment]
必挂

**Comment by kobewylb** [comment]
为什么没人回复呢

**Comment by zhi1ong** [comment]
任何 x86 都不行么

**Comment by kobewylb** [comment]
发现很多，arm64-v8a架构的手机也不行，VIVO X7PLUS、OPPO R9、VIVO X7、VIVO X6A、VIVO X7

**Comment by seulfish** [comment]
我也遇到了，求解

**Comment by zhi1ong** [comment]
初始化失败，不一定是 ARouter 自己的 Crash，ARouter 会初始化用户自己提供的拦截器，请检查一下 拦截器 init 方法中是否有问题

**Comment by zhi1ong** [comment]
@kobewylb  最近拿demo验证了一圈，发现这几台机器不会有问题，建议你优先用 ARouter 的 demo 上传测试一下。

**Comment by doublechoose** [comment]
没有用到拦截器，只是简单的使用ARouter，但是也碰到了初始化异常，机型：VIVO X7，XPlay5A
