### ISSUE TITLE
混淆后自动注入无效，只能手动查找service

### ISSUE THREAD

**Issue by hardrubic** [alibaba/ARouter#208]
@Autowired
TaskService taskService;

测试过，官方的混淆方案自动注入无效，只能使用ARouter.getInstance().navigation(TaskService.class);代码才能跑得通。

而且，混淆条件需要加入
-keep class * implements com.alibaba.android.arouter.facade.template.IProvider{*;}

**Comment by zhi1ong** [comment]
1. 自动注入有效
2. 混淆条件我会确认一下，近期有很多人提出该疑问

**Comment by jamin0107** [comment]
同样遇到这个问题.

**Comment by jamin0107** [comment]
同样遇到这个问题.我是在Application里定义了Service,初始化,ARouter之后.马上inject.初始化失败,没有proguard的情况下就是OK的.

**Comment by fifa0329** [comment]
经验证 确实需要
加上
-keep class * implements com.alibaba.android.arouter.facade.template.IProvider{;}
-keep class * implements com.alibaba.android.arouter.facade.template.IInterceptor{;}
