### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by ytjojo** [alibaba/ARouter#209]
混淆还要加一行
-keep class * implements com.alibaba.android.arouter.facade.template.IProvider{*;}
不然找不到

**Comment by zhi1ong** [comment]
理论上不用

**Comment by fifa0329** [comment]
经验证 确实需要
加上
-keep class * implements com.alibaba.android.arouter.facade.template.IProvider{*;}
-keep class * implements com.alibaba.android.arouter.facade.template.IInterceptor{*;}
