### ISSUE TITLE
Arouter报ANR

### ISSUE THREAD

**Issue by plmmanwu** [alibaba/ARouter#211]
Q：
ANR keyDispatchingTimedOut
com.alibaba.android.arouter.utils.ClassUtils.getFileNameByPackageName(ClassUtils.java:103)

android版本：
android4.1-4.3，4.3出现次数最多

**Comment by zhi1ong** [comment]
debug 有可能，扫描的量很大，release 不会，而且只有第一次会扫描

**Comment by naturs** [comment]
三星 GT-I9300
系统：4.1.2
release模式下，ARouter.init()首次耗时7s左右，以后每次耗时200ms ~ 500ms左右，手机本身确实也很卡，不知道可不可以不扫描全部类，改成其他方式？

**Comment by zhi1ong** [comment]
首次启动肯定要扫描全部类，9300 都5年前的机器了，卡点正常

**Comment by naturs** [comment]
初始化时间应该主要消耗在`LogisticsCenter.init()`方法中的`List<String> classFileNames = ClassUtils.getFileNameByPackageName(mContext, ROUTE_ROOT_PAKCAGE);`这一行中，按我的理解，这一行就是查找所有有相同包名和类名前缀的类，这些类的后缀就是模块名，对于一个项目来说，模块总是有限的，所以建议这里增加一种不是很友好的方式：让开发者在初始化的时候手动传入模块名列表，这样应该会大大减少初始化时间，虽然使用和维护复杂了，但也算多了一个选择。

在实际项目中，application初始化本身就比较耗时（一般大量初始化都放这里），所以如果ARouter初始化时间能少一些会更好。

我现在遇到的问题就是application本身已经比较耗时了，加上ARouter，在一些低端机型上很容易在初始化时ANR，新机型上确实没这个问题。

**Comment by zhi1ong** [comment]
嗯，前几个版本有一个优化点，就是只有首次更新或者安装的时候，会更新一次路由表，以后启动就不会重新扫描了

让用户自己传入的话，就增加了维护成本了，不太合适。

**Comment by xing634325131** [comment]
这个问题依旧存在。。4.4.4的设备（小米2A）上还是有ANR

**Comment by zhi1ong** [comment]
@xing634325131 用 arouter-register 插件
