### ISSUE TITLE
Android Studio 3.0 debug模式经常注入失败

### ISSUE THREAD

**Issue by imliujun** [alibaba/ARouter#215]
在Android Studio 3.0 bate 7 上使用kotlin和Java混合开发
debug模式调用了以下代码：
```java
if (BuildConfig.DEBUG) {
            ARouter.openLog()
            ARouter.openDebug()
            ARouter.printStackTrace()
        }
```

代码改动比较大的时候，要么dex文件合并失败不能运行，要么运行起来依赖注入失效。
需要手动clean才可以

**Comment by zhi1ong** [comment]
1. openDebug() 要在 init 之前
2. 我在用 AS2.3 ，推荐使用 稳定版开发

**Comment by imliujun** [comment]
openDebug是在init之前调用的
AS3.0估计快出稳定版了，也该进行一些适配了吧
