### ISSUE TITLE
 AndroidManifest.xml 缺少组件权限 (Request a CVE ID)

### ISSUE THREAD

**Issue by akast** [alibaba/ARouter#216]
在 AndroidManifest.xml 的第 10 行，程序未用导出标记或权限对此公共组件进行保护。
        <activity android:name=".SchemeFilterActivity">
任何应用程序都能访问在显式定义中未明确分配访问权限的公共组件。 

Android 应用程序中活动、接收者和服务组件的 exported 属性的默认值取决于 intent-filter 是否存在。如果存在 intent-filter，说明该组件可供外部使用。因此应将 exported 属性设为 true。这样该组件就能被 Android 平台上的其他任何应用程序访问。 以下是一个存在 intent-filter 且未设置明确访问权限的 Android 活动示例。

 <activity android:name=".AndroidActivity"/> 
   <intent-filter android:label="activityName"/> 
    <action android:name=".someFunAction"/> 
   </intent-filter> 
    ... 
 </activity> 

该活动可能被恶意应用程序利用。

没有明确的访问权限的组件应该为异常。除非该组件确实需要被所有应用程序访问，否则开发人员应该通过在显式文件中明确定义访问权限来保护组件，以免其被恶意应用程序滥用。下面是使用明确分配的访问权限重写的上文中活动组件的声明。

 <activity android:name=".AndroidActivity" android:permission="FriendsOnly"/> 
   <intent-filter android:label="activityName"/> 
    <action android:name=".someFunAction"/> 
   </intent-filter> 
   ... 
 </activity> 

http://cve.mitre.org/cve/request_id.html#cna_coverage 这里看到你们可以发CVE编号，不知道这小问题能否请求一个CVE编号。

**Comment by zhi1ong** [comment]
arouter 不需要任何权限，你看的权限配置可能是demo中
