### ISSUE TITLE
Android数据不安全存储(Request a CVE ID) 

### ISSUE THREAD

**Issue by akast** [alibaba/ARouter#217]
程序在 AndroidManifest.xml 的第 7 行请求将数据写入 Android 外部存储的权限。
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

写入外部存储的文件可被任意程序与用户读写。程序不可将个人可识别信息等敏感信息写入外部存储中。通过 USB 将 Android 设备连接到电脑或其他设备时，就会启用 USB 海量存储模式。在此模式下，可以读取和修改写入外部存储的任意文件。此外，即使卸载了写入文件的应用程序，这些文件仍会保留在外部存储中，因而提高了敏感信息被盗用的风险。 

例 1：AndroidManifest.xml 的 <uses-permission .../%gt; 元素包含危险属性。

 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> 

请勿将以后要使用的受信敏感信息或数据写入外部存储中。而应将其写入程序特定的位置，例如 SQLite 数据库（由 Android 平台提供）。程序内的任意类都可以按名称访问您所创建的任意数据库，而程序外的类则不能。

例 2.通过创建 SQLiteOpenHelper 的子类和替代 OnCreate() 方法来创建一个新的 SQLite 数据库。

    public class MyDbOpenHelper extends SQLiteOpenHelper {

    private static final int DATABASE_VERSION = 2;
    private static final String DICTIONARY_TABLE_NAME = "dictionary";
    private static final String DICTIONARY_TABLE_CREATE =
                "CREATE TABLE " + DICTIONARY_TABLE_NAME + " (" +
                KEY_WORD + " TEXT, " +
                KEY_DEFINITION + " TEXT);";

    DictionaryOpenHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(DICTIONARY_TABLE_CREATE);
    }
}

另一种选择则是写入该设备的内部存储中。默认情况下，保存到内部存储中的文件为该程序专用的，其他程序和用户无法直接访问。用户卸载程序时，保存在内部存储中的文件也会随之删除，保证不会留下任何重要的信息。

例 3：以下代码创建了一个专用文件并将其写入设备的内部存储中。此 Context.MODE_PRIVATE 声明会创建一个文件（或是替换同名文件），并将其设定为当前程序的专用文件。

String FILENAME = "hello_file";
String string = "hello world!";

FileOutputStream fos = openFileOutput(FILENAME, Context.MODE_PRIVATE);
fos.write(string.getBytes());
fos.close();

**Comment by zhi1ong** [comment]
arouter 不需要任何权限，你看的权限配置可能是demo中
