### ISSUE TITLE
获取不到fragment实例...

### ISSUE THREAD

**Issue by yangyiRunning** [alibaba/ARouter#218]
- 场景：在嵌套Fragment中通过ARouter调用跨模块的Fragment作为ViewPagerAdapter中的实例返回，返回的实例为null。

- 注：
1. 确定集成已经成功。
2. 别的场景下可以获取实例。

- 通过断点debug显示走了navigationCallBack当中的onLost方法，具体的debug打印的value如下： ↓

` Postcard{uri=null, tag=null, mBundle=Bundle[{name=新闻}], flags=-1, timeout=300, provider=null, greenChannel=false, optionsCompat=null, enterAnim=0, exitAnim=0}
RouteMeta{type=null, rawType=null, destination=null, path='/news/NewsFragment', group='news', priority=-1, extra=0} `

希望得到解惑，谢谢。

**Comment by zhi1ong** [comment]
理论上任何场景下，都不耽误获取的，走到了 onLost，还是没有找到，排查下是不是 Instant run的问题

**Comment by harry235day** [comment]
@yangyiRunning 请问这个问题最后怎么解决的

**Comment by AnyLifeZLB** [comment]
大佬们最后的解决方法是？
