### ISSUE TITLE
崩溃Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. com.alibaba.android.arouter.launcher._ARouter$2.run(_ARouter.java:359)

### ISSUE THREAD

**Issue by plmmanwu** [alibaba/ARouter#219]
android.util.AndroidRuntimeException

Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
com.alibaba.android.arouter.launcher._ARouter$2.run(_ARouter.java:359)

android.app.ContextImpl.startActivity(ContextImpl.java:1249)
--
2 android.content.ContextWrapper.startActivity(ContextWrapper.java:322)
3 android.support.v4.content.ContextCompatJellybean.startActivity(ContextCompatJellybean.java:34)
4 android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:151)
5 com.alibaba.android.arouter.launcher._ARouter$2.run(_ARouter.java:359)
6 android.os.Handler.handleCallback(Handler.java:808)
7 android.os.Handler.dispatchMessage(Handler.java:103)
8 android.os.Looper.loop(Looper.java:229)
9 android.app.ActivityThread.main(ActivityThread.java:5493)
10 java.lang.reflect.Method.invokeNative(Native Method)
11 java.lang.reflect.Method.invoke(Method.java:515)
12 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
13 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
14 dalvik.system.NativeStart.main(Native Method)

这是什么原因

**Comment by zhi1ong** [comment]
看起来是很久很久的一个老版本bug，请升级到最新版本体验。

**Comment by plmmanwu** [comment]
已经升级到最新了  还是会报

**Comment by zhi1ong** [comment]
自己看下 _ARouter.java L345，优先判断用户是否传了 Flag，然后判断如果没有传入 Activity，会加上 FLAG_ACTIVITY_NEW_TASK，这块你应该主动设置了 Flag，还没传 Activity

**Comment by plmmanwu** [comment]
意思是主动传入flag的时候要在navigation的参数里面传入activity是吗

**Comment by zhi1ong** [comment]
@plmmanwu  是的，因为你如果主动设置了 Flag，我是不会去检查里面有没有 NEW_TASK 的

**Comment by nuisanceless** [comment]
1 android.app.ContextImpl.startActivity(ContextImpl.java:707)
2 android.content.ContextWrapper.startActivity(ContextWrapper.java:364)
3 android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:248)
4 com.alibaba.android.arouter.launcher._ARouter.startActivity(_ARouter.java:429)
5 com.alibaba.android.arouter.launcher._ARouter.access$200(_ARouter.java:44)
6 com.alibaba.android.arouter.launcher._ARouter$3.run(_ARouter.java:372)
7 android.os.Handler.handleCallback(Handler.java:739)
8 android.os.Handler.dispatchMessage(Handler.java:95)
9 android.os.Looper.loop(Looper.java:179)
10 android.app.ActivityThread.main(ActivityThread.java:5769)
11 java.lang.reflect.Method.invoke(Native Method)
12 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
13 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by nuisanceless** [comment]
最新的版本  还是出现了这个问题
