### ISSUE TITLE
请提供拦截器抽象多实例的接口

### ISSUE THREAD

**Issue by Tamicer** [alibaba/ARouter#221]
#stions**
例如我不同模块走拦截器  我只能通过path进行判断

但我的需求是:

不是所有的跳转都走一个拦截器
能否给拦截器给抽象的Type

 强烈要求作者更新

**Comment by zhi1ong** [comment]
这块不建议用 path 判断是否命中某个拦截器，推荐使用 Route 中的参数 extra 来判断，是一个 int，通过位运算可以配置 32 个开关，直接用位运算决定是否命中拦截器
