### ISSUE TITLE
跨模块获取fragment为null

### ISSUE THREAD

**Issue by gindoc** [alibaba/ARouter#223]
在Module App中调用

`Fragment fragment = (Fragment) ARouter.getInstance().build("/test/user").navigation();`，

其中“/test/user”是另一个Module中的fragment，这样获取的fragment是null。同模块获取fragment则没有问题，请问是什么原因呢？是不支持跨模块获取fragment吗？

**Comment by zhi1ong** [comment]
没有这样的限制，怀疑是配置问题

**Comment by runhwguo** [comment]
核对了注解的字符串和build()一样的，但就是为null，同样遇到这个问题，请问有解决么？

**Comment by liuyangqiao** [comment]
@zhi1ong @gindoc @runhwguo 我用的kotlin也遇到了这种情况，配置没有问题，就是获取fragment是null

**Comment by gindoc** [comment]
我后来是用IProvider来提供的，类似这样
```
@Route(path = "/service/xxx")
public class xxxProvider implements IProvider {
    @Override
    public Fragment providerFragment(Object... args) {
        return new xxxFragment();
    }

    @Override
    public void init(Context context) {
    }
}
```
@runhwguo @liuyangqiao

**Comment by ZNbaoding** [comment]
我遇到了同样的问题，Clean Project然后卸载app重新安装解决了。

**Comment by AndroidBirdBoom** [comment]
> 我遇到了同样的问题，Clean Project然后卸载app重新安装解决了。

我也是这样解决的。。。

**Comment by AttITuder** [comment]
这算是一个bug吧

> > 我遇到了同样的问题，Clean Project然后卸载app重新安装解决了。
> 
> 我也是这样解决的。。。

这是一个bug吧，到现在还是同样问题

**Comment by chendroidc** [comment]
> 我遇到了同样的问题，Clean Project然后卸载app重新安装解决了。

我特么的。。。。牛批了

**Comment by AlceZhang** [comment]
真特么神奇 Clean Project然后卸载app重新安装 就O了

**Comment by TsaiYongChuan** [comment]
是的，傻逼ARouter在实现fragment的时候需要一个空构造函数
