### ISSUE TITLE
三星i9500一直初始化报错

### ISSUE THREAD

**Issue by qq2519157** [alibaba/ARouter#228]
其他手机运行都正常,系统版本: Android 5.1,level 22  ,   CPU架构 : x86 ;
下面附上bugly的日志
1 java.lang.ExceptionInInitializerError:
--
2 com.alibaba.android.arouter.e.a.a(TbsSdkJava:39)
3 ......
4 Caused by:
5 java.lang.IllegalArgumentException:
6 java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1277)
7 java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1200)
8 com.alibaba.android.arouter.f.b.<init>(TbsSdkJava:50)
9 com.alibaba.android.arouter.f.b.a(TbsSdkJava:36)
10 com.alibaba.android.arouter.e.b.<clinit>(TbsSdkJava:51)
11 com.alibaba.android.arouter.e.a.a(TbsSdkJava:39)
12 com.cn.pppcar.MyApplication.a(TbsSdkJava:118)
13 com.cn.pppcar.MyApplication.onCreate(TbsSdkJava:72)
14 com.stub.StubApp.onCreate(StubApplication.java:86)
15 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
16 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4562)
17 android.app.ActivityThread.access$1500(ActivityThread.java:151)
18 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
19 android.os.Handler.dispatchMessage(Handler.java:102)
20 android.os.Looper.loop(Looper.java:135)
21 android.app.ActivityThread.main(ActivityThread.java:5263)
22 java.lang.reflect.Method.invoke(Native Method)
23 java.lang.reflect.Method.invoke(Method.java:372)
24 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
25 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by zhi1ong** [comment]
8 com.alibaba.android.arouter.f.b.(TbsSdkJava:50)
9 com.alibaba.android.arouter.f.b.a(TbsSdkJava:36)
10 com.alibaba.android.arouter.e.b.(TbsSdkJava:51)
11 com.alibaba.android.arouter.e.a.a(TbsSdkJava:39)
12 com.cn.pppcar.MyApplication.a(TbsSdkJava:118)

类名都不对，不知道是不是被你魔改了，看不到具体错误

**Comment by qq2519157** [comment]
并不是我魔改了,这个是腾讯bugly上报的日志,我这边是后台看到的i9500这款手机一直初始化失败
12 com.cn.pppcar.MyApplication.a(TbsSdkJava:118) 这一行的代码就是ARouter.init(this);

**Comment by zhi1ong** [comment]
@qq2519157  是否使用了某些安全加固功能，建议和厂商沟通一下
