### ISSUE TITLE
ARouter::There is no route match the path [/main/home2], in group [main][ ] 

### ISSUE THREAD

**Issue by fbinba3955** [alibaba/ARouter#229]
gradle文件：
javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ moduleName : project.getName() ]
            }
        }

    compile rootProject.ext.dependencies["arouter-api"]
    annotationProcessor rootProject.ext.dependencies["arouter-compiler"]

同一个module里面无法跳转
报ARouter::There is no route match the path [/main/home2], in group [main][ ] 

使用startActivity可以正常跳转。

1.检查目标页面的注解是否配置正确，正确的注解形式应该是 (@Route(path="/test/test"), 如没有特殊需求，请勿指定group字段，废弃功能)
2.检查目标页面所在的模块的gradle脚本中是否依赖了 arouter-compiler sdk (需要注意的是，要使用apt依赖，而不是compile关键字依赖)
3.检查编译打包日志，是否出现了形如 ARouter::�Compiler >>> xxxxx 的日志，日志中会打印出发现的路由目标
4.启动App的时候，开启debug、log(openDebug/openLog), 查看映射表是否已经被扫描出来，形如 D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[4]，GroupIndex > 0

124条目都查看没有异常，3没有发现文中的日志。

**Comment by zhi1ong** [comment]
没有3 就是插件没生效，annotationProcessor 没执行，是 Gradle 的编译日志，可以命令行执行看

基本的跳转问题，可以去讨论群
