### ISSUE TITLE
使用360加固后，android4.4报No mapping files were found, check your configuration please

### ISSUE THREAD

**Issue by wei120698598** [alibaba/ARouter#230]
使用360加固后，android4.4报
` ARouter openLog[ ] 
11-03 14:20:58.608 16649-16649/com.lianzi.lian I/ARouter::: ARouter openDebug[ ] 
11-03 14:20:58.610 16649-16649/com.lianzi.lian I/ARouter::: ARouter printStackTrace[ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=printStackTrace & LineNumber=-1 ] 
11-03 14:20:58.727 16649-16649/com.lianzi.lian I/ARouter::: ARouter init start.[ThreadId=1 & ThreadName=main & FileName=ARouter.java & ClassName=com.alibaba.android.arouter.launcher.ARouter & MethodName=init & LineNumber=-1 ] 
11-03 14:20:58.734 16649-16649/com.lianzi.lian I/ARouter::: Run with debug mode or new install, rebuild router map.[ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=init & LineNumber=-1 ] 
11-03 14:20:58.739 16649-16649/com.lianzi.lian I/ARouter::: VM with name 'Android' does not have multidex support
11-03 14:20:58.740 16649-16649/com.lianzi.lian E/ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths
11-03 14:20:58.741 16649-16649/com.lianzi.lian I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.1][ThreadId=1 & ThreadName=main & FileName=DefaultThreadFactory.java & ClassName=com.alibaba.android.arouter.thread.DefaultThreadFactory & MethodName=newThread & LineNumber=-1 ] 
11-03 14:20:58.769 16649-16649/com.lianzi.lian D/ARouter::: Filter 0 classes by packageName <com.alibaba.android.arouter.routes>
11-03 14:20:58.770 16649-16649/com.lianzi.lian I/ARouter::: Find router map finished, map size = 0, cost 36 ms.[ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=init & LineNumber=-1 ] 
11-03 14:20:58.771 16649-16649/com.lianzi.lian I/ARouter::: Load root element finished, cost 0 ms.[ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=init & LineNumber=-1 ] 
11-03 14:20:58.772 16649-16649/com.lianzi.lian E/ARouter::: No mapping files were found, check your configuration please![ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=init & LineNumber=-1 ] 
11-03 14:20:58.773 16649-16649/com.lianzi.lian D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[0], InterceptorIndex[0], ProviderIndex[0][ThreadId=1 & ThreadName=main & FileName=LogisticsCenter.java & ClassName=com.alibaba.android.arouter.core.LogisticsCenter & MethodName=init & LineNumber=-1 ] 
11-03 14:20:58.774 16649-16649/com.lianzi.lian I/ARouter::: ARouter init success![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=init & LineNumber=-1 ] 
11-03 14:20:58.775 16649-16649/com.lianzi.lian W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=-1 ] 
11-03 14:20:58.776 16649-16649/com.lianzi.lian W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=-1 ] 
11-03 14:20:58.793 16649-16649/com.lianzi.lian W/ARouter::: ARouter::There is no route match the path [/arouter/service/interceptor], in group [arouter][ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=-1 ] 
11-03 14:20:58.824 16649-16649/com.lianzi.lian W/ARouter::: ARouter::No postcard![ThreadId=1 & ThreadName=main & FileName=_ARouter.java & ClassName=com.alibaba.android.arouter.launcher._ARouter & MethodName=navigation & LineNumber=-1 ] `

不加固或者加固后android4.4以上的版本都正常

**Comment by zhi1ong** [comment]
请 联系 @360加固

**Comment by liuchao0206** [comment]
@wei120698598 360帮你解决了么
