### ISSUE TITLE
1.2.2版本后新增页面不能生效问题

### ISSUE THREAD

**Issue by Dwan-xie** [alibaba/ARouter#234]
关于新增页面之后，无法跳转？
使用版本1.2.2，手机OPPO A33 系统：5.1.1
[long_text_2017-11-07.txt](https://github.com/alibaba/ARouter/files/1449934/long_text_2017-11-07.txt)

1.在读取dex中所有文件时，有可能失败。但是在第一步的判断里就更新了version，这样就会出现routemap是空的情况。理论上应保证这个操作的原子性，map读取成功才更新version。
` List<String> classFileNames = ClassUtils.getFileNameByPackageName(mContext, ROUTE_ROOT_PAKCAGE);`

2.多进程的情况下，synchronized不能有效的控制多个进程间的执行顺序。又由于sp的数据共享，就会看到同时打出
`"Run with debug mode or new install, rebuild router map."` 和 `"Load router map from cache."`的Log

旧版切后台进行覆盖安装会出现此问题，完全杀死则不会。

**Comment by zhi1ong** [comment]
1. 这里确实存在问题，不过如果要是 dex 加载不成功，就算没更新版本下次也不会成功，要看一下是不是加固引起的加载失败，这个会改掉

2. 目前还没有支持多进程，初始化的时候，要判断一下，只在主进程初始化
