### ISSUE TITLE
跳转动画问题

### ISSUE THREAD

**Issue by N-Richard** [alibaba/ARouter#236]
## Look at here
APP设置全局跳转动画style后，跳转调用当前页面finish，则全局动画失效。如果通过Arouter设置了跳转动画则没有问题

**Comment by zjw592824304** [comment]
可以试试继承基类的方法来设置跳转动画

**Comment by daleiyinsi** [comment]
我也有这个问题

**Comment by zhi1ong** [comment]
通过 ARouter 跳转的话，要设置一下动画，不然就按 manifest 中的配置走
