### ISSUE TITLE
fragment 添加跳转但是在onActivityResult无法收到数据

### ISSUE THREAD

**Issue by xujie198705292135** [alibaba/ARouter#239]
fragment跳转的代码
ARouter.getInstance().build("/wzy/selectBankActivity").navigation(context,100);

 intent=new Intent();
 intent.putExtra("carkname",s.bankCardName);
 intent.putExtra("carkId",s.id);
 intent.putExtra("bankCardNo",s.bankCardNo);
 intent.putExtra("bankCode",s.bankCode);
 intent.putExtra("bankType",s.bankType);
 ((Activity)mContext).setResult(Activity.RESULT_OK,intent);
 ((Activity) mContext).finish();

**Comment by zhi1ong** [comment]
是有这个问题，请自己在 Activity 中转发 onActivityResult 事件，接口不方便兼容 Fragment
