### ISSUE TITLE
使用SerializationService，混淆后出错

### ISSUE THREAD

**Issue by ClownQiang** [alibaba/ARouter#240]
这边我在项目中使用了SerializationService来进行withObject传递参数，在打Release包混淆之后出现了crash。通过debug找到了原因，应该是混淆导致Postcard中withObject中serializationService找不到对应实现的SerializationService，而出现了空指针的问题。

希望在文档中的混淆规则添加一下，对于SerializationService以及实现SerializationService的class进行keep处理 : )

**Comment by zhi1ong** [comment]
文档已更新
