### ISSUE TITLE
Activity注解内容无法使用指定常量字符串

### ISSUE THREAD

**Issue by TheStar4Fate** [alibaba/ARouter#241]
我使用Kotlin编写代码，在注解中使用常量提示“Only 'const val' can be used in constant expressions”。希望能改进下这个问题。
![_20171114162853](https://user-images.githubusercontent.com/7358871/32770343-3d93cb06-c95a-11e7-8d60-488f993c263a.png)

**Comment by zhi1ong** [comment]
和 ARouter 没什么关系，请自行排查，注解中不能引用变量
