### ISSUE TITLE
Kotlin Autowired数值编译不成功

### ISSUE THREAD

**Issue by VictorChow** [alibaba/ARouter#243]
在kotlin的Activity里如下写：
```kotlin
@Autowired
lateinit var s: String
@Autowired
var i = 0
@Autowired
var d = 0.0
```
只要存在数值类型的均编译不成功

Log:
`Error:error: ARouter::Compiler An exception is encountered, [The inject fields CAN NOT BE 'private'!!! please check field [i] in class [com.test.TestActivity]]`

我测试了一下用Java的类修改Kotlin Activity的属性，类似TestActivity$$ARouter$$Autowired
```java
private void t() {
    activity.s = ""; // String类型可以直接赋值
    activity.i = 1; //报错，应该用activity.setI(1);
    activity.d = 1.0 //报错，应该用activity.setD(0.0);
}
```

**Comment by VictorChow** [comment]
加上@JvmField是可以编译的 属性如果多的话每个都需要加有点繁琐😅

**Comment by SGA-Biao-Zhang** [comment]
> 加上@JvmField是可以编译的 属性如果多的话每个都需要加有点繁琐😅
解决啦，初用     咋内多坑。。。。
