### ISSUE TITLE
通过 URL 跳转问题

### ISSUE THREAD

**Issue by yibaimishenlan** [alibaba/ARouter#248]
如果 WebView 设置了 WebViewClient， 发现 路由功能 不起作用了。 当然， 之所以设置WebViewClient，是为了 直接在APP 中的WebView 打开网页，换言之，就是不启动浏览器。
然而 有些H5 需要打开原生界面，这该如何处理呢？

**Comment by zhi1ong** [comment]
自己提供 webviewClient，要自己处理 schame 跳转，拼装 intent
