### ISSUE TITLE
 # ARouter task pool No.1, thread No.1(3428)  SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by q960757274** [alibaba/ARouter#256]
bugly上报的错误，影响用户很多，最终跟踪在Arouter初始化的时候，出错线程日志：

#00 pc 527cf81a <unknown>
--
2 #01 pc 527a0763 <unknown>
3 java:
4 com.stub.StubApp.interface12(Native Method)
5 com.alibaba.android.arouter.utils.ClassUtils$1.void run()(ClassUtils.java)
6 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
7 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
8 java.lang.Thread.run(Thread.java:838)

求大神解答，谢谢！！！

**Comment by zhi1ong** [comment]
看起来是加固导致的，请联系相关厂商
