### ISSUE TITLE
#11765 com.alibaba.android.arouter.exception.HandlerException

### ISSUE THREAD

**Issue by fangbingran** [alibaba/ARouter#257]
java.lang.RuntimeException:Unable to create application s.h.e.l.l.S: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [unable to open DEX file]
--
2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4443)
3 ......
4 com.alibaba.android.arouter.exception.HandlerException:ARouter::ARouter init logistics center exception! [unable to open DEX file]
5 com.alibaba.android.arouter.core.LogisticsCenter.void init(android.content.Context,java.util.concurrent.ThreadPoolExecutor)(SourceFile:85)
6 com.alibaba.android.arouter.launcher._ARouter.boolean init(android.app.Application)(SourceFile:61)
7 com.alibaba.android.arouter.launcher.ARouter.void init(android.app.Application)(SourceFile:41)
8 com.junte.base.MyApplication.void onCreate()(SourceFile:108)
9 s.h.e.l.l.S.onCreate(Unknown Source)
10 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
11 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4440)
12 android.app.ActivityThread.access$1500(ActivityThread.java:141)
13 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
14 android.os.Handler.dispatchMessage(Handler.java:102)
15 android.os.Looper.loop(Looper.java:136)
16 android.app.ActivityThread.main(ActivityThread.java:5113)
17 java.lang.reflect.Method.invokeNative(Native Method)
18 java.lang.reflect.Method.invoke(Method.java:515)
19 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
20 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
21 dalvik.system.NativeStart.main(Native Method)

**Comment by zhi1ong** [comment]
加固导致的，请联系加固厂商，让他们支持
