### ISSUE TITLE
关于服务管理的建议

### ISSUE THREAD

**Issue by achenglike** [alibaba/ARouter#259]
是否以动态代理的方式来为未找到服务的接口返回一个打印错误日志的实现防止空指针会比较好。

**Comment by zhi1ong** [comment]
挺好的建议，可以提交一个 PR

**Comment by achenglike** [comment]
😭，好像我太天真了，试了下，对于需要返回值的接口声明代理返回数据是有问题的。如果代理了，就需要返回伪造的数据，有可能导致使用者进一步使用伪造的错误数据而产生其它错误。
