### ISSUE TITLE
如何使用PendingIntent

### ISSUE THREAD

**Issue by tangoox** [alibaba/ARouter#261]
如果要跳转的页面在其他模块 如果构建这个PendingIntent；

 PendingIntent pIntent = PendingIntent.getActivity(context, 0, ？, 0);

**Comment by tangoox** [comment]
..哈哈，我的锅，直接用class就行。
Intent intent = new Intent(context, SettingActivity.class);
SettingActivity是其他模块的界面

**Comment by oahgnez** [comment]
其他模块的界面直接引用了那就和统一模块没区别了吧，如果真的是不同模块无法直接引用类应该怎么办

**Comment by gindoc** [comment]
@oahgnez 隐式intent

**Comment by oahgnez** [comment]
@gindoc  感谢回复，时间有点久，想不起来当时为什么提问了。。。
推测一下，当时应该是在做组件化重构，想的应该不是activity，应该是想问接口类等的引用吧。。。然后自己可能是把接口下沉了吧。。
