### ISSUE TITLE
常规动画失效

### ISSUE THREAD

**Issue by moonljt521** [alibaba/ARouter#262]
手机系统7.0.1 ，全局style是默认的，
ARouter.getInstance().build("/routerb/RouterBActivity")
                        .withTransition(R.anim.slide_in_bottom,R.anim.slide_out_bottom)
                        .navigation();
这个配置没有改变默认的动画样式，就是R.anim.slide_in_bottom,R.anim.slide_out_bottom 都不生效；

 Intent intent = new Intent(this, Router_B_Activity.class);
               startActivity(intent);
                overridePendingTransition(R.anim.slide_in_bottom,R.anim.slide_out_bottom);
这个显示的动画是自己配置的，生效了。

ActivityOptionsCompat形式的动画也生效。
求教是怎么回事

**Comment by wpq2014** [comment]
我也是这个问题，有的生效有的不生效，splash到guide和main没有设置动画正常Intent没出现动画，用了ARouter就会出现缩放动画。。

**Comment by LinXiaoTao** [comment]
``` java
if ((0 != postcard.getEnterAnim() || 0 != postcard.getExitAnim()) && currentContext instanceof Activity) {    // Old version.
                            ((Activity) currentContext).overridePendingTransition(postcard.getEnterAnim(), postcard.getExitAnim());
}
```
试试使用 `Activity` 参数的 `navigation(Activity mContext, int requestCode)`

**Comment by liuleshuai** [comment]
currentContext instanceof Activity也就是说上下文必须是Activity才可以实现动画，
```
public Object navigation() {
    return navigation(null);
}
public Object navigation(Context context) {
    return navigation(context, null);
}
```
所以，想要实现自定义的动画跳转必须使用.navigation(activity)这种形式。
