### ISSUE TITLE
在子module中初始化，在app module中使用，路由时找不到目标页面

### ISSUE THREAD

**Issue by swnnn** [alibaba/ARouter#264]
baserouter build.gradle 中配置
defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ moduleName : project.getName() ]
            }
}
dependencies {
    compile project(':arouter-api')
    annotationProcessor project(':arouter-compiler')
}

在 app module build.gradle中配置
defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ moduleName : project.getName() ]
            }
}
dependencies {
    compile project(':arouter-api')
    annotationProcessor project(':arouter-compiler')
    compile project(path: ':baserouter')
}

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER. */
public class ARouter$$Group$$other implements IRouteGroup {
  @Override
  public void loadInto(Map<String, RouteMeta> atlas) {
    atlas.put("/other/nn", RouteMeta.build(RouteType.ACTIVITY, DetailActivity.class, "/other/nn", "other", null, -1, -2147483648));
  }
}
这个类已经生成了

在app module 中一些Activity中使用@Route定义path，但路由时报route no match exception
请问该怎么解呢？

**Comment by swnnn** [comment]
配置有错，已解决~~

**Comment by androiddeveloper007** [comment]
请问怎么解决的？
