### ISSUE TITLE
狂点测试跳转失效

### ISSUE THREAD

**Issue by wpq2014** [alibaba/ARouter#266]
测试狂点，刚开始可以跳转，后来就都不行了，主要log如下：
E/ARouter::: Task rejected, too many task![ThreadId=1 & ThreadName=main & FileName=DefaultPoolExecutor.java & ClassName=com.alibaba.android.arouter.thread.DefaultPoolExecutor$1 & MethodName=rejectedExecution & LineNumber=54 ]

**Comment by hailongren** [comment]
遇到了同样的问题，请问如何解决的？

**Comment by hailongren** [comment]
https://github.com/alibaba/ARouter/issues/384 已解决
