### ISSUE TITLE
找不到注入的Object

### ISSUE THREAD

**Issue by xiehuiyun** [alibaba/ARouter#267]
//Router.class
  public static void getLoansSecurityActivity(ApplyStep applyStep) {
        sRouter.build(APPLY_LOANS_SECURITY).withObject(SECURITY_TAG, applyStep).navigation();
    }

//activity.class
 @Autowired
    ApplyStep applyStep;

    @Override
    protected void initialize() {               //onCreate()中的方法
        super.initialize();
        Router.inject(this);
    }
   
    我引用到applyStep时显示空指针异常，该Activity中只有一个ApplyStep

**Comment by zhi1ong** [comment]
SECURITY_TAG = “ applyStep”  ？
