### ISSUE TITLE
Autowired 导致默认的Boolean赋值无效

### ISSUE THREAD

**Issue by fifa0329** [alibaba/ARouter#268]
@Autowired
    public boolean realTimeLog=true;

	/**
	 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER. */
	public class H5Activity$$ARouter$$Autowired implements ISyringe {
	  private SerializationService serializationService;

	  @Override
	  public void inject(Object target) {
	    serializationService = ARouter.getInstance().navigation(SerializationService.class);;
	    H5Activity substitute = (H5Activity)target;
	    substitute.mUrl = substitute.getIntent().getStringExtra("page_url");
	    substitute.mPageTitle = substitute.getIntent().getStringExtra("page_title");
	    substitute.mCanDoRefresh = substitute.getIntent().getBooleanExtra("canRefresh", false);
	    substitute.mShowClose = substitute.getIntent().getBooleanExtra("showClose", false);
	    substitute.canShare = substitute.getIntent().getBooleanExtra("canShare", false);
	    substitute.realTimeLog = substitute.getIntent().getBooleanExtra("realTimeLog", false);
	  }
	}

忽略了我原先的赋值
public boolean realTimeLog=true;

能否改成
`    substitute.realTimeLog = substitute.getIntent().getBooleanExtra("realTimeLog", substitute.realTimeLog);`

**Comment by fifa0329** [comment]
刚刚看了下 1.2.4 开始，已经修正为正确逻辑了

我用的是1.2.1.1

可以匿了

**Comment by YuanKJ-** [comment]
嗯？我看compiler的版本还是1.2.2，api版本1.5.0，设置默认值无效，仍然会被覆盖，请教一下？
