### ISSUE TITLE
提示警告没什么影响吧？

### ISSUE THREAD

**Issue by Jack1995** [alibaba/ARouter#271]
Warning:警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.AutowiredProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'

Warning:警告: 以下选项未被任何处理程序识别: '[moduleName, kapt.kotlin.generated]'

**Comment by siyehua** [comment]
我也是这个,没什么影响
