### ISSUE TITLE
模块之间的跳转报错   There is no route match the path [/xxx/xxx], in group [xxx][ ]"

### ISSUE THREAD

**Issue by yy941002** [alibaba/ARouter#277]
已经按要求配置了，求解

**Comment by EdisonLiao** [comment]
我也遇到了这个问题哎

**Comment by zhangyc** [comment]
同样遇到了。

**Comment by a158684** [comment]
我也遇到了~

**Comment by a158684** [comment]
用的gradle:3.0.1

**Comment by liujia95** [comment]
@zhi1ong 请问是什么原因，希望能解答一下

**Comment by liujia95** [comment]
我的已经解决了，是因为没有在跳转的那个路由页面中的build.gradle下配置注解解析器造成的。

**Comment by zhangyc** [comment]
如果大家是因为组件化产生的问题的话，记得在moduleA和moduleB之间都要加入Arouter相关的配置

**Comment by EdisonLiao** [comment]
@zhangyc 小弟再补充一下，每个module的build.gradle中在android{ }里面加上：
javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
            }
        }

**Comment by yubaokang** [comment]
gradle3.0.1 也遇到这个问题，求解

**Comment by gzbbxu** [comment]
我也遇到了

**Comment by orangegithub1** [comment]
除了以上所说的，app主模块需要把所有要跳转的模块引入进去，我是通过这种方法解决的

**Comment by zhangyc** [comment]
@orangegithub1 是的，不然也会报这个错

**Comment by mmdsyl** [comment]
我也遇到了这个问题, 最后发现是和Butter Knife的注解处理器 不兼容.

**Comment by leon2017** [comment]
①、你需要把要路由跳转的模块组件依赖到app模块里面去
②、你需要路由的模块都要依赖Arouter

**Comment by dahezi** [comment]
我发现重启手机可以解决。。。。

**Comment by MrShuHong** [comment]
04-02 23:18:39.620 22071-22071/com.demo.myarouter I/ARouter::: ARouter openLog[ ] 
04-02 23:18:39.621 22071-22071/com.demo.myarouter I/ARouter::: ARouter openDebug[ ] 
04-02 23:18:39.621 22071-22071/com.demo.myarouter I/ARouter::: ARouter init start.[ ] 
04-02 23:18:39.625 22071-22071/com.demo.myarouter I/ARouter::: Run with debug mode or new install, rebuild router map.[ ] 
04-02 23:18:39.631 22071-22071/com.demo.myarouter I/ARouter::: VM with name 'Android' has multidex support
04-02 23:18:39.631 22071-22071/com.demo.myarouter D/ARouter::: Found InstantRun support
04-02 23:18:39.633 22071-22071/com.demo.myarouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.1][ ] 
04-02 23:18:39.635 22071-22071/com.demo.myarouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.2][ ] 
04-02 23:18:39.636 22071-22071/com.demo.myarouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.3][ ] 
04-02 23:18:39.637 22071-22071/com.demo.myarouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.4][ ] 
04-02 23:18:39.638 22071-22071/com.demo.myarouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.5][ ] 
04-02 23:18:39.640 22071-22071/com.demo.myarouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.6][ ] 
04-02 23:18:39.642 22071-22071/com.demo.myarouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.7][ ] 
04-02 23:18:39.645 22071-22071/com.demo.myarouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.8][ ] 
04-02 23:18:39.647 22071-22071/com.demo.myarouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.9][ ] 
04-02 23:18:39.801 22071-22071/com.demo.myarouter D/ARouter::: Filter 7 classes by packageName <com.alibaba.android.arouter.routes>
04-02 23:18:39.810 22071-22071/com.demo.myarouter I/ARouter::: Find router map finished, map size = 7, cost 185 ms.[ ] 
04-02 23:18:39.829 22071-22071/com.demo.myarouter I/ARouter::: Load root element finished, cost 18 ms.[ ] 
04-02 23:18:39.830 22071-22071/com.demo.myarouter D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[2], InterceptorIndex[0], ProviderIndex[2][ ] 
04-02 23:18:39.831 22071-22071/com.demo.myarouter I/ARouter::: ARouter init success![ ] 
04-02 23:18:39.832 22071-22071/com.demo.myarouter W/ARouter::: ARouter::No postcard![ ] 
04-02 23:18:39.833 22071-22071/com.demo.myarouter W/ARouter::: ARouter::No postcard![ ] 
04-02 23:18:39.836 22071-22071/com.demo.myarouter D/ARouter::: The group [arouter] starts loading, trigger by [/arouter/service/interceptor][ ] 
04-02 23:18:39.838 22071-22071/com.demo.myarouter D/ARouter::: The group [arouter] has already been loaded, trigger by [/arouter/service/interceptor][ ] 
04-02 23:18:39.841 22071-22071/com.demo.myarouter I/ARouter::: ARouter init over.[ ]

**Comment by MrShuHong** [comment]
欲哭无泪啊 ， 按照配置依然出现问题。

**Comment by MrShuHong** [comment]
@zhangyc 如果在每个用route的module里都配置* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Group$$com;

* Tr

**Comment by MrShuHong** [comment]
@zhangyc 如果在每个用route的module里都配置annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.

com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Group$$com;

**Comment by MrShuHong** [comment]
@zhangyc  这样造成里重复依赖的问题如何解决

**Comment by pdog18** [comment]
@MrShuHong 不会有重复依赖的问题的

**Comment by pdog18** [comment]
遇到这个问题的同学请仔细检查是否在每个`build.gradle`文件中都正确设置了以下代码
```groovy
kapt {
    arguments {
        arg("moduleName", project.getName())
    }
}


dependencies {
//...
    kapt 'com.alibaba:arouter-compiler:1.1.4'
}
```

⚠️注意！`arouter-compiler` 这个依赖必须在`build.gradle`中声明，只在`base_module`中声明然后引用`base_module`中引用是无效的！

**Comment by MrShuHong** [comment]
@pdog18 问题我已经解决了 谢谢， 确实是我配置的问题 ， 每一个module 都需要添加配置

**Comment by benjaminGzq** [comment]
关闭instantRun

**Comment by wangdd1201** [comment]
请问楼主，我配置了以后，APP这个model内的activity跳转都报There's no router match,但是APP model跳转其他的model内的activity，或者其他model内activity跳转都正常，配置都是一样的，请问是什么问题

**Comment by Novice9527** [comment]
@wangdd1201 我也是这个问题啊，你有没有解决啊？求指点

**Comment by wangdd1201** [comment]
@Novice9527 没有解决，你要是解决了告诉我一声，我解决了也告诉你你一下

**Comment by Novice9527** [comment]
@wangdd1201  我的好像突然好了  就把根目录中的register 版本改成最新的

**Comment by wangdd1201** [comment]
@Novice9527 你现在修改后register的版本是多少?

**Comment by wangdd1201** [comment]
@Novice9527 
compile 'com.alibaba:arouter-api:x.x.x'
    annotationProcessor 'com.alibaba:arouter-compiler:x.x.x'

register?????你说的这个在哪修改？

**Comment by Novice9527** [comment]
@wangdd1201 
![tim 20180525095045](https://user-images.githubusercontent.com/35387382/40522007-379f3166-6001-11e8-8395-fdf02f0f3e00.png)

**Comment by docwei2050** [comment]
终于解决了，，，比如A 和 Bmodule 要相互跳转，那么两个都要设置 javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }   

然后依赖要加上annotationProcessor 'com.alibaba:arouter-compiler:1.2.2'

不会出现重复依赖哈，，，

当然你的基础库依赖里面也要有：
    api('com.alibaba:arouter-api:1.4.1')
    annotationProcessor 'com.alibaba:arouter-compiler:1.2.2'

**Comment by ManLiShiChao9** [comment]
我想问下,为什么跳转,会跳转不到自己想要页面,他会跳转到一个不知道哪来的页面,有谁遇到过这个错误吗

**Comment by zhangyc** [comment]
应该是写错了。。




发自网易邮箱大师
在2019年06月11日 11:45，ManLiShiChao9 写道：

我想问下,为什么跳转,会跳转不到自己想要页面,他会跳转到一个不知道哪来的页面,有谁遇到过这个错误吗

**Comment by QianJiah** [comment]
组件化下进行组件单独调试时，也会出现这个错误，在build.gradle下添加对应需要跳转的组件模块依赖，就没这个错误了

**Comment by Android-xiaole** [comment]
> 
> 
> 我也遇到了这个问题, 最后发现是和Butter Knife的注解处理器 不兼容.

我测试的时候发现就算去掉模块化的依赖，只是在app内之间的跳转都会出现这个问题（别的非模块化的Demo没问题），后来注释掉butterknife相关依赖就好了...然后再依赖回来也没问题，真的奇葩

**Comment by zacdaryl** [comment]
我遇到的情况是kotlin项目中配置的不对，如果module是kotlin项目，应在build.gradle中如下配置：
`// 可以参考 module-kotlin 模块中的写法
apply plugin: 'kotlin-kapt'

kapt {
    arguments {
        arg("AROUTER_MODULE_NAME", project.getName())
    }
}

dependencies {
    compile 'com.alibaba:arouter-api:x.x.x'
    kapt 'com.alibaba:arouter-compiler:x.x.x'
    ...
}`

**Comment by squareBQ** [comment]
充分说明了认真看文档的重要性 :no_mouth:

**Comment by yanchengdeng** [comment]
> 
> 
> 遇到这个问题的同学请仔细检查是否在每个`build.gradle`文件中都正确设置了以下代码（kotlin项目，java项目参考修改）
> 
> ```groovy
> kapt {
>     arguments {
>         arg("moduleName", project.getName())
>     }
> }
> 
> 
> dependencies {
> //...
>     kapt 'com.alibaba:arouter-compiler:1.1.4'
> }
> ```
> 
> ⚠️注意！`arouter-compiler` 这个依赖必须在`build.gradle`中声明，只在`base_module`中声明然后引用`base_module`中引用是无效的！

最后这句话解决了我的问题：
⚠️注意！`arouter-compiler` 这个依赖必须在`build.gradle`中声明，只在`base_module`中声明然后引用`base_module`中引用是无效的！
调试半天不知道问题出现在，谢谢！

**Comment by jeffrylgh** [comment]
> 除了以上所说的，app主模块需要把所有要跳转的模块引入进去，我是通过这种方法解决的

app中引入了其他module，为啥不直接用startActivity跳转...干嘛还用ARouter，多此一举嘛
