### ISSUE TITLE
使用studio 3.0 导入老项目，报错Could not find method android() for arguments这是什么原因呢？

### ISSUE THREAD

**Issue by junfenggithub** [alibaba/ARouter#280]
## Look at here

apt {
    arguments {
        moduleName project.getName();
    }
}
这个位置报错

**Comment by lgengsy** [comment]
gradle 升级到新版本吧，issue估计都没有人看。感觉没有人维护issue的样子啊 。都去QQ群讨论了？加群也加不上啊 ，“真感动".
