### ISSUE TITLE
工程配置Java 8 编译的时候会有警告

### ISSUE THREAD

**Issue by lgengsy** [alibaba/ARouter#282]
使用Java7编译正常，使用Java8编译会提示以下警告，这些警告要不要处理？可以忽略么？会在什么情况下产生影响？
Warning:Supported source version 'RELEASE_7' from annotation processor 'com.alibaba.android.arouter.compiler.processor.AutowiredProcessor' less than -source '1.8'

Warning:Supported source version 'RELEASE_7' from annotation processor 'com.alibaba.android.arouter.compiler.processor.InterceptorProcessor' less than -source '1.8'

Warning:Supported source version 'RELEASE_7' from annotation processor 'com.alibaba.android.arouter.compiler.processor.RouteProcessor' less than -source '1.8'

**Comment by woaigmz** [comment]
同样问题，编译不过，好像不支持 java8 ，项目用的 lamda 表达式
注: ARouter::Compiler >>> AutowiredProcessor init. <<<
警告: 来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.AutowiredProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
错误: ARouter::Compiler An exception is encountered, [These no module name, at 'build.gradle', like :
  apt {
      arguments {
          moduleName project.getName();
      }
  }
  ]

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: ARouter::Compiler >>> No module name, for more information, look at gradle log.

**Comment by protectedMan** [comment]
这个问题应当如何处理@zhi1ong

**Comment by passos** [comment]
所以，你看，咱们的开源项目就是这样的。。。

**Comment by protectedMan** [comment]
> 所以，你看，咱们的开源项目就是这样的。。。

官僚风气

**Comment by JeckChou** [comment]
> > 所以，你看，咱们的开源项目就是这样的。。。
> 
> 官僚风气

我一直watch butterKnife，glide，这些开源项目，人家维护的很标准，对于这个项目，我早就恶心了，后面打算自己写一个

**Comment by zhi1ong** [comment]
写法的问题，之前是 @SupportedSourceVersion(SourceVersion.RELEASE_7)，现在已经改掉了，3 月份之后的版本就没这个 warning 了

**Comment by passos** [comment]
3 月份之后的版本就没有这个警告了吗？我花了 5 分钟做了一个测试项目，https://github.com/passos/ARouterTest

编译结果

```
./gradlew asDebug
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :app:compileDebugJavaWithJavac
Gradle may disable incremental compilation as the following annotation processors are not incremental: jetified-arouter-compiler-1.2.2.jar (com.alibaba:arouter-compiler:1.2.2), auto-service-1.0-rc2.jar (com.google.auto.service:auto-service:1.0-rc2).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
注: ARouter::Compiler >>> AutowiredProcessor init. <<<
警告: 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> InterceptorProcessor init. <<<
警告: 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> RouteProcessor init. <<<
initial commit
警告: 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler >>> Found routes, start... <<<
注: ARouter::Compiler >>> Found routes, size is 1 <<<
注: ARouter::Compiler >>> Found activity route: com.example.aroutertest.TestActivity <<<
注: ARouter::Compiler >>> Start categories, group = test, path = /test/activity <<<
注: ARouter::Compiler >>> Generated group: test<<<
注: ARouter::Compiler >>> Generated provider map, name is ARouter$$Providers$$app <<<
注: ARouter::Compiler >>> Generated root, name is ARouter$$Root$$app <<<
3 个警告

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 22s
26 actionable tasks: 21 executed, 5 up-to-date
```

**Comment by zeuscode** [comment]
我也遇到,真坑

**Comment by zhi1ong** [comment]
> 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
> 注: ARouter::Compiler The user has configuration the module name, it was [app]

来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler The user has configuration the module name, it was [app]

这个包名是 org.gradle.api , 和 ARouter 没有关系

**Comment by zhi1ong** [comment]
这只是一个 warning，忽略即可，编译不过另有其他原因，2L 的报错都已经很明显了 

 No module name, for more information, look at gradle log.

没有配置模块名

**Comment by moten07** [comment]
> 这只是一个 warning，忽略即可，编译不过另有其他原因，2L 的报错都已经很明显了
> 
> No module name, for more information, look at gradle log.
> 
> 没有配置模块名

正解，但不继续维护确实不太好，其实大多数公司现在还是秉承能用就行
