### ISSUE TITLE
为什么没有 setData() 的接口

### ISSUE THREAD

**Issue by flyer88** [alibaba/ARouter#285]
我从 A Activity 跳转到 B Activity 时，发现 调用 getIntent().getData() 是空的
所以想问下，有没有类似 setData 的接口，可以用来设置
以及后续会不会给出接口，让我们自己设置 intent 里面的其他参数

**Comment by zhangyc** [comment]
使用with()向下一个页面传递

**Comment by flyer88** [comment]
with 只能传到 bundle 中，获取时只能通过 getExtras 不能通过 getData 进行获取

**Comment by flyer88** [comment]
getData 获取到的对象是 uri，现在只能获取到 bundle 对象了，导致一些老业务需要全量修改，所以想问会提供类似 withData() 之类的接口嘛？

**Comment by zhangyc** [comment]
with可以传递自定义对象，在第二个页面@Autowired直接使用就好。这个也不满足你的场景？

**Comment by flyer88** [comment]
满足，但是老的业务需要全量修改

**Comment by zhangyc** [comment]
心疼你一分钟
