### ISSUE TITLE
使用arouter-api：1.3.1，arouter-compiler:1.1.4无法进行跨模块跳转，但本模块跳转是可以的

### ISSUE THREAD

**Issue by fomin-zhu** [alibaba/ARouter#286]
## Look at here
01-24 09:41:15.860 17007-17007/com.fomin.arouter I/ARouter::: ARouter openLog[ ] 
01-24 09:41:15.861 17007-17007/com.fomin.arouter I/ARouter::: ARouter openDebug[ ] 
01-24 09:41:15.861 17007-17007/com.fomin.arouter I/ARouter::: ARouter init start.[ ] 
01-24 09:41:15.862 17007-17007/com.fomin.arouter I/ARouter::: Run with debug mode or new install, rebuild router map.[ ] 
01-24 09:41:15.868 17007-17007/com.fomin.arouter I/ARouter::: VM with name 'Android' has multidex support
01-24 09:41:15.870 17007-17007/com.fomin.arouter E/ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths
01-24 09:41:15.871 17007-17007/com.fomin.arouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.1][ ] 
01-24 09:41:15.893 17007-17007/com.fomin.arouter D/ARouter::: Filter 9 classes by packageName <com.alibaba.android.arouter.routes>
01-24 09:41:15.896 17007-17007/com.fomin.arouter I/ARouter::: Find router map finished, map size = 9, cost 35 ms.[ ] 
01-24 09:41:15.907 17007-17007/com.fomin.arouter I/ARouter::: Load root element finished, cost 10 ms.[ ] 
01-24 09:41:15.907 17007-17007/com.fomin.arouter D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[3], InterceptorIndex[0], ProviderIndex[2][ ] 
01-24 09:41:15.909 17007-17007/com.fomin.arouter I/ARouter::: ARouter init success![ ] 
01-24 09:41:15.910 17007-17007/com.fomin.arouter W/ARouter::: ARouter::No postcard![ ] 
01-24 09:41:15.911 17007-17007/com.fomin.arouter W/ARouter::: ARouter::No postcard![ ] 
01-24 09:41:15.913 17007-17007/com.fomin.arouter D/ARouter::: The group [arouter] starts loading, trigger by [/arouter/service/interceptor][ ] 
01-24 09:41:15.915 17007-17007/com.fomin.arouter D/ARouter::: The group [arouter] has already been loaded, trigger by [/arouter/service/interceptor][ ] 
01-24 09:41:15.919 17007-17007/com.fomin.arouter I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.2][ ] 
01-24 09:41:15.922 17007-17007/com.fomin.arouter I/ARouter::: ARouter init over.[ ] 
01-24 09:41:16.085 17007-17007/com.fomin.arouter W/ARouter::: ARouter::No postcard![ ] 
01-24 09:41:16.085 17007-17007/com.fomin.arouter W/ARouter::: ARouter::No postcard![ ] 
01-24 09:41:16.086 17007-17007/com.fomin.arouter D/ARouter::: The group [module1] starts loading, trigger by [/module1/main][ ] 
01-24 09:41:16.087 17007-17007/com.fomin.arouter D/ARouter::: The group [module1] has already been loaded, trigger by [/module1/main][ ]

**Comment by KitTak** [comment]
怎么解决的？现在是主模块调用没有，但是子模块调主模块就报错
