### ISSUE TITLE
支持路由表动态配置

### ISSUE THREAD

**Issue by liangruiyuwanba** [alibaba/ARouter#293]
为什么不支持动态路由表配置，这样可以直接在服务端下发路由表，目前来看是不是咱们的整体架构不支持动态路由表配置，这种需求应该挺多的，最好提供支持动态路由表配置

**Comment by zhi1ong** [comment]
可以支持，实现 PathReplaceService

**Comment by liangruiyuwanba** [comment]
有demo吗？具体不知道怎么通过PathReplaceService 来实现

**Comment by alen252** [comment]
好像回答者没有理解这个issue的意思

**Comment by zhi1ong** [comment]
1.5.2 会提供动态注册路由信息的接口，在 dev 分支已提交
