### ISSUE TITLE
Route 注解可见性

### ISSUE THREAD

**Issue by LinXiaoTao** [alibaba/ARouter#294]
你好。我现在有个需求，需要在运行时获取 Activity 对应的 path。但我发现 `@Route` 是 `@Retention(RetentionPolicy.CLASS)`，是否能改成 `RUNTIME`。

**Comment by yanzhenjie** [comment]
本着编译时注解的原则是不建议这样做的。  
我们可以在本地实现一个`Processor`，大概如下：
```
@AutoService(Processor.class)
@SupportedOptions("moduleName")
@SupportedSourceVersion(SourceVersion.RELEASE_7)
@SupportedAnnotationTypes("com.alibaba.android.arouter.facade.annotation.Route")
public class RecordPathProcessor extends AbstractProcessor {
        ....;
}
```

这里可以生成一个类来记录项目中所有的`path`，这样也可以满足动态改变`path`的需求，在需要的时候反射生成的类获取相应的`path`即可。

**Comment by LinXiaoTao** [comment]
@yanzhenjie 谢谢，我试试。

**Comment by BigBigDeBoy** [comment]
@LinXiaoTao 这个解决了吗

**Comment by zhi1ong** [comment]
目前提供生成路由文档了，可以在 json 格式中解析出 path
