### ISSUE TITLE
问下 这个 支持 Fragment的路由跳转嘛

### ISSUE THREAD

**Issue by ggchxx** [alibaba/ARouter#3]
问下 这个 支持 Fragment的路由跳转嘛

**Comment by zhi1ong** [comment]
目前不支持，本来是有这个考虑的，因为支持Fragment的话，一方面要搞一个通用的Activity在外面包一下，**UI的效果很难和App保持统一**，另一方面，**通常Fragment都是一个Activity中包好几个**，比较典型的就是各种app的首页，这种情况下还是**推荐用Router跳转到这个Activity，然后带一个参数进去，比方说tab=2，然后自己在onCreate里面自行切换**

**Comment by ggchxx** [comment]
收到，谢谢

**Comment by xiaobailong24** [comment]
@zhi1ong 您好，我是使用的您的建议：**
推荐用Router跳转到这个Activity，然后带一个参数进去，比方说tab=2，然后自己在onCreate里面自行切换**，来控制Fragment的切换，但是这样有一个问题，就是**每次跳转Activity都会重建**，不知道您遇到这个问题没？请问怎么解决？谢谢！

**Comment by zhi1ong** [comment]
activity 设置成singleTask的

**Comment by xiaobailong24** [comment]
@zhi1ong 收到。感谢

**Comment by xiaolongyuan** [comment]
activity 设置成singleTask 之后会走onNewIntent  但在这里 取不到值啊
