### ISSUE TITLE
ARouter::Compiler

### ISSUE THREAD

**Issue by yubaokang** [alibaba/ARouter#303]
注: ARouter::Compiler >>> AutowiredProcessor init. <<<
注: ARouter::Compiler The user has configuration the module name, it was [b_router_module]
注: ARouter::Compiler >>> InterceptorProcessor init. <<<
注: ARouter::Compiler The user has configuration the module name, it was [b_router_module]
注: ARouter::Compiler >>> RouteProcessor init. <<<
警告: 以下选项未被任何处理程序识别: '[moduleName]'

**Comment by sxfhblf123** [comment]
请问问题解决了吗，什么原因

**Comment by kan137g** [comment]
同样出现了这个问题导致无法通过编译，但是其他项目又没这个问题。好像是跟eventbus冲突了

**Comment by kan137g** [comment]
刚刚解决，因为和eventbus的注解冲突了。但是通过编译后还是有   “警告: 以下选项未被任何处理程序识别: '[moduleName]'”。

**Comment by wangsanshi** [comment]
> 刚刚解决，因为和eventbus的注解冲突了。但是通过编译后还是有 “警告: 以下选项未被任何处理程序识别: '[moduleName]'”。

你好，请问下是怎么解决的呢？
