### ISSUE TITLE
@Route(path = "/test/TestBaseActivity", priority = 100)设置优先级无效果

### ISSUE THREAD

**Issue by jianesrq0724** [alibaba/ARouter#304]
有两个页面，继承关系
@Route(path = "/test/TestBaseActivity", priority = 100)
public class TestBaseActivity extends AppCompatActivity 

@Route(path = "/test/TestBaseActivity", priority = 10)
public class TestActivity extends TestBaseActivity 

设置优先级无效果

**Comment by zhi1ong** [comment]
这个 priority 为保留配置，未用于优先级判断
