### ISSUE TITLE
ARouter 采用腾讯乐加固后不执行

### ISSUE THREAD

**Issue by xoptimal** [alibaba/ARouter#305]
如题,  最新版本~

**Comment by shaDowZwy** [comment]
我也遇到这种问题 好像不仅仅是腾讯乐固 用其他加固方式也会报错

**Comment by xoptimal** [comment]
乐固问题, 已联系技术人员进行修复~

**Comment by shaDowZwy** [comment]
@xoptimal 老铁 你现在用的是乐固哪个版本啊，我用的还是不行啊

**Comment by xoptimal** [comment]
@shaDowZwy  乐固正式修复这个问题, 说大概一个星期这样 , 到时候会通知到调试下, 没问题再发一个版本~  现在还没发呢

**Comment by GGjin** [comment]
就是还没发是吧。。我也刚刚遇到这个问题。。

**Comment by s7655120** [comment]
同样遇到此问题 不知道怎么解决 ARouter版本
com.alibaba:arouter-api:1.3.1， com.alibaba:arouter-compiler:1.1.4

**Comment by xoptimal** [comment]
处理了一个星期+ , 还没好 0.0  好了我再通知你们  0.0
