### ISSUE TITLE
ARouter的安全原理/机制

### ISSUE THREAD

**Issue by JimmieWong** [alibaba/ARouter#308]
在给团队推介布道ARouter的时候，如何回答这个问题？
或者说ARouter采取了什么机制策略来保证安全性？特别是银行金融业务场景。

**Comment by zhi1ong** [comment]
ARouter 本身只负责转发，没有安全性相关的指标

跳转到特定的页面确实有安全性的需求的话，可以通过参数加签的方式来解决

**Comment by zhi1ong** [comment]
ARouter 本身只负责转发，没有安全性相关的指标

跳转到特定的页面确实有安全性的需求的话，可以通过参数加签的方式来解决
