### ISSUE TITLE
希望可以支持动态参数和多url

### ISSUE THREAD

**Issue by s949492225** [alibaba/ARouter#309]
1.是否能够支持在url里声明参数,例如taobao://goodsDetail/{id},这个id就可以作为一个参数,类似retrofit和vue那种路由的写法
2.有时页面需要多个url,类如一个通用页面,但是具体的业务是不同的,这样更利于理解上和分类,至少使用schema的层面上可以有语义化

**Comment by Cazaea** [comment]
同求
