### ISSUE TITLE
仔细对比了wiki下面的路由跳转问题和issue里面的问题 发现 InstantRun support error, com.android.tools.fd.runtime.Paths 跟其他日志不太一致

### ISSUE THREAD

**Issue by awpss** [alibaba/ARouter#310]
## Look at here

03-01 17:21:52.825 9117-9117/com.yijiupi.dealerdevelop I/ARouter::: ARouter openLog[ ] 
03-01 17:21:52.982 9149-9149/? I/ARouter::: VM with name 'Android' has multidex support
03-01 17:21:52.983 9149-9149/? E/ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths
03-01 17:21:53.040 9149-9149/? I/ARouter::: ARouter openLog[ ] 
03-01 17:22:10.344 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:10.344 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:10.346 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:10.346 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:10.460 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:10.460 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:11.626 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:11.627 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:11.627 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::There is no route match the path [/distribution/DistributionMainActivity], in group [distribution][ ] 
03-01 17:22:11.675 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:12.537 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ] 
03-01 17:22:12.537 9117-9117/com.yijiupi.dealerdevelop W/ARouter::: ARouter::No postcard![ ]

**Comment by mayanhu** [comment]
InstantRun support error, com.android.tools.fd.runtime.Paths 这个错误是怎么解决的呢
