### ISSUE TITLE
配置都没问题，但是路由加载失败，麻烦看一下啊，谢谢

### ISSUE THREAD

**Issue by richfuns** [alibaba/ARouter#319]
所有版本都是最新的
  compile 'com.alibaba:arouter-api:1.3.1'
  compile 'com.alibaba:arouter-annotation:1.0.4'
  annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'

提示下面的错误： 
![image 1](https://user-images.githubusercontent.com/1400999/37320499-ed6b5984-26ae-11e8-84a3-28f8db7b08a5.png)

**Comment by richfuns** [comment]
W/ARouter::: ARouter::No postcard![ ] 
W/ARouter::: ARouter::No postcard![ ] 
W/ARouter::: ARouter::There is no route match the path [/main/index], in group [main][ ] 
W/ARouter::: ARouter::No postcard![ ] 

上面的日志没有贴完

**Comment by richfuns** [comment]
找到问题了，我只在BaseLibrary Module引入的Router，并没有在最外层的App壳引入，就有这个问题，好奇怪啊，我的App壳已经依赖了BaseLibrary Module了啊，求指教，谢谢

**Comment by javalong** [comment]
我也是一样问题，想把arouter统一引用到lib.base模块 
然后 app模块引入lib.base模块
报同样的错误

**Comment by richfuns** [comment]
现在看来，需要路由的模块都要compile这个库才行

**Comment by hexl1231** [comment]
组件化,引入ARouter,把代码贴出来看啊 谢谢
