### ISSUE TITLE
ARouter::ARouter init logistics center exception

### ISSUE THREAD

**Issue by gmfbilu** [alibaba/ARouter#320]
ARouter::ARouter init logistics center exception! [Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference]
我只要打包出来的apk安装就出现这种问题，已经关闭instant run了，而且没有加固

**Comment by Novice9527** [comment]
我也有这个问题，你解决了吗

**Comment by zhi1ong** [comment]
没配置 versionName
