### ISSUE TITLE
直接下载Demo，初始化后点击“简单的应用内跳转”，跳转失败。

### ISSUE THREAD

**Issue by leizhiliang** [alibaba/ARouter#321]
03-13 06:48:42.618 21586-21586/com.alibaba.android.arouter.demo I/ARouter::: ARouter openLog[ ] 
03-13 06:48:46.698 21586-21586/com.alibaba.android.arouter.demo I/ARouter::: ARouter openDebug[ ] 
03-13 06:48:46.698 21586-21586/com.alibaba.android.arouter.demo I/ARouter::: ARouter init start.[ ] 
03-13 06:48:46.708 21586-21586/com.alibaba.android.arouter.demo I/ARouter::: Load router map by arouter-auto-register plugin.[ ] 
03-13 06:48:46.708 21586-21586/com.alibaba.android.arouter.demo I/ARouter::: Load root element finished, cost 8 ms.[ ] 
03-13 06:48:46.708 21586-21586/com.alibaba.android.arouter.demo D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[4], InterceptorIndex[1], ProviderIndex[2][ ] 
03-13 06:48:46.708 21586-21586/com.alibaba.android.arouter.demo I/ARouter::: ARouter init success![ ] 
03-13 06:48:46.709 21586-21586/com.alibaba.android.arouter.demo W/ARouter::: ARouter::No postcard![ ] 
03-13 06:48:46.709 21586-21586/com.alibaba.android.arouter.demo W/ARouter::: ARouter::No postcard![ ] 
03-13 06:48:46.715 21586-21586/com.alibaba.android.arouter.demo D/ARouter::: The group [arouter] starts loading, trigger by [/arouter/service/interceptor][ ] 
03-13 06:48:46.715 21586-21586/com.alibaba.android.arouter.demo D/ARouter::: The group [arouter] has already been loaded, trigger by [/arouter/service/interceptor][ ] 
03-13 06:48:46.717 21586-21586/com.alibaba.android.arouter.demo I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.1][ ] 
03-13 06:48:46.718 21586-21586/com.alibaba.android.arouter.demo I/ARouter::: ARouter init over.[ ] 
03-13 06:48:46.719 21586-21649/com.alibaba.android.arouter.demo E/test: 位于moudle1中的拦截器初始化了
03-13 06:48:46.719 21586-21649/com.alibaba.android.arouter.demo I/ARouter::: ARouter interceptors init over.[ ] 
03-13 06:48:53.515 21586-21586/com.alibaba.android.arouter.demo W/ARouter::: ARouter::No postcard![ ] 
03-13 06:48:53.515 21586-21586/com.alibaba.android.arouter.demo W/ARouter::: ARouter::No postcard![ ] 
03-13 06:48:53.515 21586-21586/com.alibaba.android.arouter.demo W/ARouter::: ARouter::There is no route match the path [/test/activity2], in group [test][ ] 
03-13 06:48:53.533 21586-21586/com.alibaba.android.arouter.demo W/ARouter::: ARouter::No postcard![ ]

**Comment by qaz349293703** [comment]
+1，demo下载了。instant run关闭了运行也没有，build生成apk文件导入手机安装demo，也是一样没用，点击下面的什么应用内跳转，什么跳转FORRESULT等都是提示There is no route matched

**Comment by FanGo2** [comment]
我把arouter-register的gradle版本改成和主工程一样的就可以了
dependencies {
    compile 'com.android.tools.build:gradle:2.3.0'
}

**Comment by FanGo2** [comment]
register改成1.0.2版本就可以了，classpath 'com.alibaba:arouter-register:1.0.2'

**Comment by kongnanlive** [comment]
太不靠谱了！！
