### ISSUE TITLE
简化

### ISSUE THREAD

**Issue by Cazaea** [alibaba/ARouter#322]
@Route(path = "/xxx/xxx") // 必须标明注解  一定要这样？ 
        不能简单点？
        例如：@Route("xxx")
        在ShameFilterActivity声明时，给定sheme为activity
        通过ARouter.getInstance().build("activity://xxx").navigation();
        进行跳转可以吗？

**Comment by zhi1ong** [comment]
1. 是为了和拦截器等共用一个注解，简写要求使用 value 字段
2. 查看 build(Uri uri)
