### ISSUE TITLE
README.md中 五、更多功能      4. 重写跳转URL return语句应该时uri而不是url。

### ISSUE THREAD

**Issue by JamonJou** [alibaba/ARouter#324]
/**
    * For uri type.
    *
    * @param uri raw uri
    */
   Uri forUri(Uri uri) {
	return url;    // 按照一定的规则处理之后返回处理后的结果
   }

**Comment by zhi1ong** [comment]
可以提交 PR

**Comment by JamonJou** [comment]
好的。
