### ISSUE TITLE
startActivity 中 context 应该为 activity 吧

### ISSUE THREAD

**Issue by xie123** [alibaba/ARouter#328]
![image](https://user-images.githubusercontent.com/7463283/37563495-ec26d906-2abc-11e8-8870-fd2e185b3ff9.png)
1.这里的currentContext 应该也要转成activity ，要不然 activity 的 启动模式有问题呀

**Comment by zhi1ong** [comment]
和你上层的 api 传递的有关系，不是说强转之后它就是 Activity

**Comment by xie123** [comment]
在你的navigation() 里 ，Context 为空的话，这个currentContext 始终为Application ， 会影响到 activity的启动模式（就比如activity默认的启动模式）。我测试--->加上requestCode ，结果activity 的启动正常。我的标题写错了，表达意思错了

**Comment by xie123** [comment]
更深层次的Context 的 理解就GG...大概就是这个意思。

**Comment by zhi1ong** [comment]
这个是不强制你放 Activity 的

**Comment by NazcaLines** [comment]
我也遇到了同样的问题。

**Comment by NazcaLines** [comment]
这个问题和v4版本有关。在低版本的v4上，ActivityCompat.startActivity的入参是Activity，在高版本的v4上，入参是Context
