### ISSUE TITLE
Demo跑在Android7.0的三星S7Edge上找不到路径

### ISSUE THREAD

**Issue by prpr894** [alibaba/ARouter#330]
Demo跑在Android7.0的三星S7Edge上找不到路径，华为的7.0的系统没问题，但是三星的不行，原生8.0也遇到过相同的问题，找不到路径。但是情况仅发生在自动打的debug包或者配置好的自动签名的release包，手动打包签名后的apk安装上不会出现这种情况。

**Comment by zhi1ong** [comment]
新版本 instant run 的问题，需要使用 arouter-register 插件，或关闭 instant-run
