### ISSUE TITLE
Kotlin和Java的混编项目怎么配置？？？

### ISSUE THREAD

**Issue by cheetah747** [alibaba/ARouter#331]
我按照常见问题里的kotlin配置了gradle之后，报错了，编译不通过
`Error:(43, 0) Could not find method kapt() for arguments [com.alibaba:arouter-compiler:1.1.3] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`
原来的配置跳转kotlin页面跳转不了。

**Comment by cheetah747** [comment]
もういい。。。

**Comment by thebitmin** [comment]
你的 gradle 配置的有问题吧，你帖全 gradle 看看

有没有漏了
```
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
```
