### ISSUE TITLE
Android Studio 3.0 使用implementation和compile有什么区别吗？implementation无法加载ARoute，而 compile可以

### ISSUE THREAD

**Issue by FY6** [alibaba/ARouter#333]
## Look at here

compile project(':module_base')

implementation project(':module_base')

**Comment by Lillls** [comment]
使用implementation只有在本模块内能用到

**Comment by YuJunKui1995** [comment]
compile==api
implementation是为了加快多模块依赖的编译速度  
楼上所述没毛病  implementation仅本模块可用

**Comment by magiclonw** [comment]
U must replace implementation to api
