### ISSUE TITLE
多个拦截器顺序问题

### ISSUE THREAD

**Issue by qaz349293703** [alibaba/ARouter#334]
// 比较经典的应用就是在跳转过程中处理登陆事件，这样就不需要在目标页重复做登陆检查
// 拦截器会在跳转之间执行，多个拦截器会按优先级顺序依次执行
@Interceptor(priority = 8, name = "测试用拦截器")
public class TestInterceptor implements IInterceptor {。。。。}

readme.mk上如上述所示写的，但是我写了二个拦截器，二个的priority大小更换，执行顺序都是不变的。我看issue关闭里面又写着priority是预留的，还没有功能，那么当前如何让拦截器按顺序执行？？？

**Comment by zhi1ong** [comment]
priority 是有效的，你可能没有重新 build
