### ISSUE TITLE
    compile "com.android.support:support-v4:${SUPPORT_LIB_VERSION}"

### ISSUE THREAD

**Issue by yubaokang** [alibaba/ARouter#335]
## Look at here
 对support的依赖不能用 provided  吗？
- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by seelikes** [comment]
support版本的compile依赖导致使用ARouter但不使用25.2.0support版本的编译都会在gradle里提示错误

既然我们只用到了support中的类，而不使用资源，为什么不去provide编译呢

不过估计得升级gradle版本，因为只有implementation可以隐藏aar依赖
