### ISSUE TITLE
Android studio 3.0 中使用更高的gradle版本出的问题。

### ISSUE THREAD

**Issue by VVZ1991** [alibaba/ARouter#337]
原来的项目没问题，现在新的项目用到的kotlin混编，并提升了gradle的两个版本。 
所有在build.gradle中两种方式都配置了。会不是kapt和annotationProcessor不能共存的问题啊

那几个检查项，也都校对了好久。求助

gradle-wrapper.properties中
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
工程build.gradle
classpath 'com.android.tools.build:gradle:3.0.1'
发现怎么编译都不能通过

更详细的配置如下

检查gradle console的截图如下
![image](https://user-images.githubusercontent.com/8370996/37814290-2f6fce9e-2ea4-11e8-8df2-67edee477a47.png)
这个被编译的路由也调不同。

------------------------------------------------------------------------------------------
主工程的build.gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.2.0'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

------------------------------------------------------------------------------------------
app的 build.gradle

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

kapt {
    arguments {
        arg("moduleName", project.getName())
    }
}

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.tude.android.test"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    repositories {
        flatDir {
            dirs '../goods/libs', 'libs', '../edit2d/libs'
        }
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile project(':goods')
    implementation 'com.github.bumptech.glide:glide:4.3.1'
    implementation 'com.google.code.gson:gson:2.4'
    compile project(':lib')
    kapt 'com.alibaba:arouter-compiler:1.1.4'
    annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'
    compile 'com.alibaba:arouter-api:1.2.4'
}

------------------------------------------------------------------------------------------
goods.lib工程  build.gradle
if (isDebug.toBoolean()) {
    apply plugin: 'com.android.application'
} else {
    apply plugin: 'com.android.library'
}
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

kapt {
    arguments {
        arg("moduleName", project.getName())
    }
}

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    useLibrary 'org.apache.http.legacy'
    sourceSets {
        main {
            if (isDebug.toBoolean()) {
                manifest.srcFile 'src/debug/AndroidManifest.xml'
//                res.srcDirs = ['src/main/debug/res']
            } else {
                manifest.srcFile 'src/release/AndroidManifest.xml'
                java {
                    //排除java/debug文件夹下的所有文件
                    exclude 'debug/**'
                }
            }
        }
    }

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
            }
        }

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    repositories {
        flatDir {
            dirs '../goods/libs', 'libs', '../edit2d/libs'
        }
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile project(':lib')
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support:design:27.1.0'
    implementation 'com.android.support:support-v4:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'
    compile 'com.alibaba:arouter-api:1.2.4'
    kapt 'com.alibaba:arouter-compiler:1.1.4'
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    ..........
}

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'me.tatarka:gradle-retrolambda:3.2.4'
    }

}
repositories {
    jcenter()
}

apply plugin: 'me.tatarka.retrolambda'
------------------------------------------------------------------------------------------

**Comment by VVZ1991** [comment]
经过尝试，已经把ARouter里面kapt全部丢弃，仅使用AnnotaionProcesser项目可运行。

**Comment by SephirothLT** [comment]
请问 是直接去掉kapt  保留annotationProcesser么？ 那 `   javaCompileOptions {
        annotationProcessorOptions {
            arguments = [moduleName: project.getName()]
        }
    }`需要去掉么？
