### ISSUE TITLE
用了这个路由后，第一次打开App启动很慢，有没有什么办法通过配置加快

### ISSUE THREAD

**Issue by lvshtwl** [alibaba/ARouter#338]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhi1ong** [comment]
使用 自动注册 插件，文档中有

**Comment by lvshtwl** [comment]
加了，没什么用，还是很慢




| |
吕少强
邮箱：18813069256@163.com
|

签名由 网易邮箱大师 定制

在2018年05月04日 10:44，刘志龙 写道：

Closed #338.

**Comment by lvshtwl** [comment]
加了 自动注册 插件，第一次启动的时候。debug状态还是很慢
