### ISSUE TITLE
ARouter.init()黑屏问题

### ISSUE THREAD

**Issue by LuckSiege** [alibaba/ARouter#341]
在Android 4.4.2的OPPO手机调用ARouter.init()方法会有1，2秒的黑屏时间，而且在有路由的页面 跳转在部分手机会出现跳转卡顿问题。

**Comment by zhi1ong** [comment]
可能是手机问题，ARouter 初始化的时候如果未使用 arouter-register 的话，会扫描 dex，性能差的手机可能卡顿，可以使用 arouter-register 插件
