### ISSUE TITLE
studio 升级到3.1.0后，组件化方案使用出错

### ISSUE THREAD

**Issue by jingzhanwu** [alibaba/ARouter#343]
sutdio是最新的3.1.0版本，ARouter是1.3.1 和1.1.4，我的开发模式是组件化，按照文档配置后，第一次可以成功从一个module到另一个module跳转。没有修改代码重新编译了一次就编译失败 sudio右下角一直就提示
Unsupported Modules Detected: Compilation is not supported for following modules:错误，导致项目无法运行。去掉ARouter的配置后项目可以正常运行。查询网上资料 重启sudio，删除.idea,.gradle等方式都无法解决。

**Comment by fengshenyanyi** [comment]
我也遇到了这个问题,请问你们解决了吗??

**Comment by jingzhanwu** [comment]
没有

**Comment by cloud1105** [comment]
我也是

**Comment by jingzhanwu** [comment]
@Autowired 注解的变量不能申明成 private 的

**Comment by imliujun** [comment]
我也遇到这个问题了，因为Android Sutdio 3.1.0版本修改了 Build 的日志输入样式，kapt编译失败看不出来具体错误信息，所以搞半天不知道什么原因，其实就是在一个kotlin类中@Autowired注解的一个属性没有添加@JvmField注解，如果是Java代码应该会报具体错误信息吧

**Comment by junge89221** [comment]
@imliujun  请问你具体是怎么修改的呢？我也遇到了这个问题···

**Comment by imliujun** [comment]
@junge89221  我的问题是 ``@Autowired``注解的字段不是 public 的，所以自动生成依赖注入失败
