### ISSUE TITLE
跟databinding发生冲突

### ISSUE THREAD

**Issue by liubo123** [alibaba/ARouter#344]
使用 SureUseCarBinding sureUseCarBinding;
    private SureUseCarModel sureUseCarModel;
    @Autowired(name = MainContanst.CAR_BEAN)
    int carBean;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        sureUseCarBinding = DataBindingUtil.setContentView(this, R.layout.sure_use_car);
        sureUseCarModel = ViewModelProviders.of(this).get(SureUseCarModel.class);
        ARouter.getInstance().inject(this);
        LLog.i("carBean = " + carBean);
        //sureUseCarBinding.setCarBean(carBean);
        initTitle();
    }
时，databinding编译不过。

**Comment by achenglike** [comment]
兄弟，需要提供错误日志。另外我也用了arouter和databinding编译正常

**Comment by zhi1ong** [comment]
都用 apt，或者都用 annotationProcessor

**Comment by shenbengit** [comment]
@Autowired这个注解好像和Databinding冲突，会提示databinding不存在。

**Comment by freeyob** [comment]
> annotationProcessor

用的都是annotationProcessor

**Comment by freeyob** [comment]
> @Autowired这个注解好像和Databinding冲突，会提示databinding不存在。

**Comment by shuwenyouxi** [comment]
> > @Autowired这个注解好像和Databinding冲突，会提示databinding不存在。

我才你是因为kt用@Autowire没加@JvmField
