### ISSUE TITLE
跳转新页面，并且finish()当前页面，出现短暂黑屏

### ISSUE THREAD

**Issue by huaxiaolin** [alibaba/ARouter#347]
### 问题描述：
假设有两个页面（A，B），当从A页面跳转到B页面的时候，执行了如下代码
ARouter.getInstance().build("/app/" + code).withBundle("bundle", bundle).navigation(mContext);
this.finish();
这样过会出现短暂的黑屏，原因是代码中**真正执行跳转的方法会在this.finish()之后执行**，查看源码可知
![](http://7xqweu.com1.z0.glb.clouddn.com/TI%20.png)  
从代码中可知，执行跳转的代码会被放入looper,所以就不可能立即执行。
### 建议：
可在此处进行线程判断，在非主线程时再放入looper。

**Comment by 345509960** [comment]
建议你写个NavCallback 当跳转完成后才 finish

**Comment by zhi1ong** [comment]
@huaxiaolin  按照 @345509960  的办法即可解决
