### ISSUE TITLE
不同的module使用同一个group，导致找不到RouteMeta

### ISSUE THREAD

**Issue by yihuaqi** [alibaba/ARouter#348]
当在不同的module定义相同的group的时候，会因为生成的IRouteGroup的路径和class名一致，导致只能加载某一个module的RouteMeta。

com.alibaba.android.arouter.routes.ARouter$$Group$${group name}这样。
有什么办法避免class路径不冲突吗？

**Comment by zhi1ong** [comment]
不同 module 不能共用一个 group，这个技术上可以解决，但是容易导致实际开发中非常混乱
