### ISSUE TITLE
aroute 怎么实现非页面跳转的埋点，例如点击事件，并没有触发页面间的跳转

### ISSUE THREAD

**Issue by nichousha1935** [alibaba/ARouter#357]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhi1ong** [comment]
ARouter 主要是为了解决组件化之后的跳转和通信的，不能解决点击事件的埋点
