### ISSUE TITLE
关于@Autowired参数传递方案不统一的问题

### ISSUE THREAD

**Issue by whataa** [alibaba/ARouter#360]
在Postcard中，提供了诸如`withByteArray`等方法传递相关对象参数，与`withObject`直接序列化为String不同的是，上述方法是直接调用Bundle的对应方法`mBundle.putByteArray(key, value);`

但是在目标页面通过`@Autowired`注解的byte[]、char[]等参数在编译期间生成的代码却是被转为了形如以下形式：
```
parseObject(substitute.getIntent().getStringExtra("xxx"),  TypeWrapper<xx>);
```
通过查阅源码，在[AutowiredProcessor](https://github.com/alibaba/ARouter/blob/master/arouter-compiler/src/main/java/com/alibaba/android/arouter/compiler/processor/AutowiredProcessor.java#L226)中，处理生成的模板方案和`Postcard`类提供的参数传递方案并没有一一对应。

**Comment by zhi1ong** [comment]
除了基础的 with，剩下的其他类型建议直接用 withObject , 走序列化

**Comment by whataa** [comment]
既然走序列化，那就建议把其它无效的传参方法移除掉，否则很容易误导，还希望重视下，谢谢！

**Comment by zhi1ong** [comment]
@Autowired 是附加的功能，正常的 withXxxxx 可以 getXxxx 拿到，这里只是这些非基本类型，不支持自动注入

**Comment by whataa** [comment]
OK，可能是我对`@Autowired`的使用理解有误吧
