### ISSUE TITLE
你们测试一下VIVO s6A吧，除了Kotlin页面能跳转过去以外，都崩溃了

### ISSUE THREAD

**Issue by xwc520** [alibaba/ARouter#361]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by Code6666** [comment]
三星 galaxy s6 edge 除了Kotlin页面能跳转过去以外，都崩溃了

**Comment by Code6666** [comment]
是 使用姿势不对吗？ 求指教

**Comment by 371280835** [comment]
我问题更奇怪，windows电脑编译出来的apk不能跳转到主模块声明的Activity，但是用mac机编译可以跳转。gradle版本是一样的。

**Comment by spynokia** [comment]
@371280835 我跟你一样情况，解决了吗？

**Comment by xwc520** [comment]
我解决了，如果是kotlin项目要用kotlin的配置，java的话使用java的配置
