### ISSUE TITLE
在拦截器内使用callback.onContinue(postcard); 无效

### ISSUE THREAD

**Issue by liangjingkanji** [alibaba/ARouter#364]
![image](https://user-images.githubusercontent.com/21078112/39562576-01e52612-4edf-11e8-8af8-f980aa63d54b.png)

日志打印出来了, 但是没有跳转页面

**Comment by liangjingkanji** [comment]
原因是使用了
setTag

解决办法是
`setTag(null)`

希望官方修复下

**Comment by zhi1ong** [comment]
你占用了 tag 么，拦截器里面会把是否成功记在 tag 里面

**Comment by liangjingkanji** [comment]
我在Tag里面放Activity用来打开对话框.... \
我仿造Sample里面的静态Activity的形式拿到的Activity为空
我建议开放Tag功能来使用, 方便我弹对话框

**Comment by adonis-lsh** [comment]
> 你占用了 tag 么，拦截器里面会把是否成功记在 tag 里面

这个真是误导人啊
