### ISSUE TITLE
界面跳转问题

### ISSUE THREAD

**Issue by huangruqi88** [alibaba/ARouter#365]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.uchon"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        //方法64
        multiDexEnabled true

        //阿里路由框架
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ moduleName : project.getName() ]
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'

    //    /** BaseRecyclerViewHelper **/
    //    // https://github.com/CymChad/BaseRecyclerViewAdapterHelper
    //    implementation "com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.22"

    /** 工具类*/
    //https://github.com/Blankj/AndroidUtilCode
    implementation 'com.blankj:utilcode:1.14.1'

    //https://github.com/tbruyelle/RxPermissions
    implementation 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.5@aar'

    // RXJava + Retriofit
    implementation 'io.reactivex.rxjava2:rxjava:2.1.12'
    implementation 'com.squareup.okio:okio:1.14.0'
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'
    implementation 'com.google.code.gson:gson:2.8.1'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'

    /** Glide图片加载*/

    //https://github.com/bumptech/glide
    implementation 'com.github.bumptech.glide:glide:4.7.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'

    /** GreenDao数据库*/
    //https://github.com/greenrobot/greenDAO
    implementation 'org.greenrobot:greendao:3.2.2'

    /** ButterKnife */
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'

    /** EventBus */
    //https://github.com/greenrobot/EventBus
    implementation 'org.greenrobot:eventbus:3.1.1'

    /** Leafcanry */

    //https://github.com/square/leakcanary
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.5.4'
    releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'

    /** 方法64 */
    implementation 'com.android.support:multidex:1.0.3'

    /** ImmersionBar 4.4以上沉浸式实现 **/
    // https://github.com/gyf-dev/ImmersionBar
    implementation 'com.gyf.barlibrary:barlibrary:2.3.0'

    /** 阿里路由 */
    //https://github.com/alibaba/ARouter
    implementation 'com.alibaba:arouter-api:1.3.1'
    annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'

    /** 百分比布局*/
    implementation 'com.zhy:percent-support-extends:1.0.1'
    implementation project(':refresh-layout')

    /** Fragment懒加载 */
    //https://github.com/YoKeyword/Fragmentation
    implementation 'me.yokeyword:fragmentation:1.3.3'
    implementation 'me.yokeyword:fragmentation-swipeback:1.3.3'
}

这是我的app下的build.gradle,

**// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
//        classpath "com.alibaba:arouter-register:1.0.0"
//        classpath 'com.novoda:bintray-release:0.5.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
    tasks.withType(Javadoc) {
        options {
            encoding "UTF-8"
            charSet 'UTF-8'
            links "http://docs.oracle.com/javase/7/docs/api"
        }
    }
}

//ext {
//    minSdkVersion = 16
//    targetSdkVersion = 25
//    compileSdkVersion = 25
//    buildToolsVersion = '25.0.3'
//}

task clean(type: Delete) {
    delete rootProject.buildDir
}

** 
这个是project下的build.gradle   gradle是4.4的 我写的demo里面可以正常跳转，但是在项目中不能跳转
ARouter::There is no route match the path [/test/TestActivity], in group [test]这个是log

**Comment by vucre** [comment]
apply plugin: 'com.alibaba.arouter'

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath "com.alibaba:arouter-register:1.0.2"
    }
}

这些加进去了吗

**Comment by wangdd1201** [comment]
我也遇到这些问题，你的说的配置我都配置了，并且有的能跳转有的不能跳转不知道为什么，我在不同的model中都配置了

**Comment by wangdd1201** [comment]
请问楼主，我配置了以后，APP这个model内的activity跳转都报There's no router match,但是APP model跳转其他的model内的activity，或者其他model内activity跳转都正常，配置都是一样的，请问是什么问题?

**Comment by pj1993** [comment]
我也遇到了相同的问题，请问解决了吗？其他模块可以相互跳转，但是其他模块跳转到app model就会报错There's no router match
