### ISSUE TITLE
arouter跨模块调用方法，我打包后运行可以生效，但是直接debug运行，不生效

### ISSUE THREAD

**Issue by wangfengzxz** [alibaba/ARouter#367]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by wangfengzxz** [comment]
public static String getUserName(String userId) {
        IChatModuleService chatModuleService = ARouter.getInstance().navigation(IChatModuleService.class);
        if (chatModuleService != null) {
            return chatModuleService.getUserName(userId);
        }
        return "";
    }
debug运行，chatModuleService一直未null,不过release打包后，就正常了。

**Comment by wangfengzxz** [comment]
哦哦，是的，你的回答解决了问题。

**Comment by runhwguo** [comment]
good idea.
if (BuildConfig.DEBUG) {
                ARouter.openLog();     // 打印日志
                ARouter.openDebug();
            }
