### ISSUE TITLE
请问为什么Provider should skip all of interceptors ?

### ISSUE THREAD

**Issue by longforus** [alibaba/ARouter#370]
我定义了一个Provider, 我也想他在不符合条件的时候也会被拦截,但是发现无效,看源码发现:
PROVIDER 和 FRAGMENT 被调用了greenChannel(),貌似也没有方法修改,请问有什么方法可以实现拦截么?

不知道这样设置的目的是什么? 给用户一个选择的机会会不会好一些呢?

**Comment by zhi1ong** [comment]
这个需求可以后面加一个开关
