### ISSUE TITLE
在已开启PictureInPicture模式时，ARouter跳转的新页面会在PictureInPicture窗口中打开

### ISSUE THREAD

**Issue by BBBOND** [alibaba/ARouter#372]
## 问题如下：
![image](https://user-images.githubusercontent.com/9862759/39964526-1942a0a0-56b9-11e8-8449-0d19cf14bfd2.png)
## 图一为已开启PIP窗口，
![image](https://user-images.githubusercontent.com/9862759/39964540-3b77b64c-56b9-11e8-9c29-031424b4c78d.png)
## 图二为打开一个新Activity，正常不应该在PIP窗口中打开，但是ARouter这么做了

**Comment by GalenLeo** [comment]
请问怎么解决？

**Comment by conghuahuadan** [comment]
同样存在问题，请问怎么解决？
