### ISSUE TITLE
这个怎么在Android Studio中使用

### ISSUE THREAD

**Issue by QingYWu** [alibaba/ARouter#374]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by QingYWu** [comment]
将项目下载好了之后，表示不会再AndroidStudio中使用，是将ARoute项目直接导入到自己的项目中吗？

**Comment by rainyandsunny** [comment]
你是要运行里面的demo还是将ARouter运用于自己的项目？
