### ISSUE TITLE
TextUtils.splitQueryParameters

### ISSUE THREAD

**Issue by yihuaqi** [alibaba/ARouter#377]
TextUtils.splitQueryParameters里应该调用String query = rawUri.getQuery()而不是String query = rawUri.getEncodedQuery()

当一个uri含有encode过的字符时，会导致参数无法被解析

**Comment by zhi1ong** [comment]
对 URL 进行一次解码是标准套路

**Comment by yihuaqi** [comment]
getEncodedQuery是解码？看一眼Uri的源码吧。getQuery才是拿到解码字串

**Comment by zhi1ong** [comment]
@yihuaqi 你说的对，我没注意看问题，这个之前是有过考虑的，所以特意用的 getEncodedQuery ，不对 url 中的内容做任何处理
