### ISSUE TITLE
在    .withObject("registerListBean",bean) 的时候 一直报错

### ISSUE THREAD

**Issue by wuao** [alibaba/ARouter#380]
Application uncaught exception in thread "main" java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.object2Json(java.lang.Object)' on a null object reference
bean实现 了无参构造函数

debug 之后发现 在Postcard
![image](https://user-images.githubusercontent.com/12946169/40354174-d8144a0a-5de5-11e8-95b4-1ee4b212213c.png)
ARouter.getInstance().navigation(SerializationService.class)=null 
SerializationService这个没拿到

**Comment by zhi1ong** [comment]
需要自行实现 SerializationService
