### ISSUE TITLE
能否支持下根据path路径去获取对应的Activity Class

### ISSUE THREAD

**Issue by xudjx** [alibaba/ARouter#381]
这类需求在多模块开发的时候遇到的比较多，因为不仅仅是页面的单向跳转，比如通知栏跳转页面，或者通过context.startActivities同时开启多个页面时

**Comment by sunkeding** [comment]
对对对，这个通知栏跳转的需求非常需要啊，大佬们尽快开放出来呗

**Comment by zhi1ong** [comment]
暂时不会，和主线需求不太一致

**Comment by yangchong211** [comment]
大佬，通知栏跳转页面，先跳转首页，然后跳转到某个页面，这个如何用路由来实现！
@zhi1ong @zhuzhaoyuan

**Comment by Android500** [comment]
可以通过Service方式调用其他组件获取Intent，然后再用原来的startActivities启动，绕了一个大弯
