### ISSUE TITLE
@Autowired不支持ArrayList<String>传递

### ISSUE THREAD

**Issue by hongwei5261** [alibaba/ARouter#382]
@Autowired(name = BUNDLE_KEY_CONVERSATION_TYPE)
ArrayList<String> mConversationTypes;
此类型传递出错，默认识别为String

**Comment by xuexiangjys** [comment]
@Autowired只能支持Intent支持的类型，其他的object需要使用序列化服务才行

**Comment by zhi1ong** [comment]
withObject
