### ISSUE TITLE
关于Arouter 跳转问题

### ISSUE THREAD

**Issue by yujunhua93** [alibaba/ARouter#393]
你好，我在使用库的时候，在6.0的测试机上可以正常跳转页面，但是在8.0的手机上面run app后却无法进行页面的跳转

**Comment by LouisShark** [comment]
@yujunhua93 你解决了吗 我也碰到了类似问题

**Comment by LouisShark** [comment]
已解决，原来是Arouter版本更新之后需要自己添加objToJson这种序列化的方法，以前的版本好像是自带的
