### ISSUE TITLE
Fragment中不支持startActivityForResult

### ISSUE THREAD

**Issue by hongwei5261** [alibaba/ARouter#397]
Arouter在Fragment中不支持startActivityForResult,默认result会到Activity中

**Comment by 4332weizi** [comment]
没办法，官方表示太丑了不支持。我现在这么做的：
```
Postcard postcard = ARouter.getInstance()
                .build("/xxx/xxx")
                .withInt("xxx", 1)
                .withString("xxxx", "string");
LogisticsCenter.completion(postcard);
Intent intent = new Intent(fragment.getActivity(), postcard.getDestination());
intent.putExtras(postcard.getExtras());
fragment.startActivityForResult(intent, requestCode);
```

**Comment by aloe20** [comment]
强烈建议让Fragment也支持startActivityForResult。这样就不用每次在Activity中写onActivityResult了

**Comment by ccj659** [comment]
需要修改源码,在 _navigation 方法中 修改

`        // Navigation in main looper.
                new Handler(Looper.getMainLooper()).post(new Runnable() {
                    @Override
                    public void run() {
                        if (requestCode > 0) {  // Need start for result

                            if (routeCard.getV4Fragment()!=null){
                                Intent intent = new Intent(context, routeCard.getDestination());
                                intent.putExtras(routeCard.getExtras());
                                routeCard.getV4Fragment().startActivityForResult(intent, requestCode);
                            }else {
                                ActivityCompat.startActivityForResult((Activity) currentContext, intent, requestCode, routeCard.getOptionsBundle());

                            }
`

**Comment by hongwei5261** [comment]
@ccj659 fragment的内容在case activity下修改是否合适？

**Comment by ccj659** [comment]
case activity 这里的意思是 目的地是 activity, 并不是出发地是activity, 所以思路上是没有问题的. 出发地(activity, Fragment, 其他)跳转到activity
