### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by zxp0505** [alibaba/ARouter#4]
Error:Unknown host 'mirrors.taobao.net'. You may need to adjust the proxy settings in Gradle. 
项目编译出现这个问题 请问如何解决

**Comment by Sum41forever** [comment]
镜像连不上，
1.尝试挂个代理试试。
2.换镜像

**Comment by zxp0505** [comment]
能提供个镜像服务器吗 我试了上海的这个 但是还是不行
sdk.gdgshanghai.com 端口：8000

![Uploading image.png…]()

**Comment by zhi1ong** [comment]
是我的问题，warpper中的镜像路径没有替换掉，是我们内网的镜像，我改一下

**Comment by Sum41forever** [comment]
我不知道啊淘宝的镜像是啥。我一般都是挂的代理服务器。
我用的Shadowsocks 
![sss](https://cloud.githubusercontent.com/assets/18468976/21832792/a269c116-d7e8-11e6-9009-6788778b77eb.png)

**Comment by zhi1ong** [comment]
可以暂时不用warpper，直接用本地的gradle即可 💯

**Comment by zhi1ong** [comment]
已经改好了 👍 ,重新pull下

**Comment by zxp0505** [comment]
好了   多谢 :+1:

**Comment by lihua45678910** [comment]
你们都解决了吗？心态爆炸
