### ISSUE TITLE
初始化后还是会出抛出ARouter::Init::Invoke init(context) first!"异常

### ISSUE THREAD

**Issue by tanghongbin** [alibaba/ARouter#40]
我接入了最新版的Arouter-sdk，然后也接入了freeline，我的android-sdk是23，gradle是2.2.3，我发现如果用android studio原生的run运行的话100%会抛出上面异常，用freeline就不会，不知道是谁的问题。。。

**Comment by zhi1ong** [comment]
建议您先单独使用ARouter试试。

**Comment by 529523346** [comment]
我也遇到了这种情况，在服务器错误日志上报里看到的，影响用户比较少，但确实出现了，不知道怎么回事

**Comment by carl1990** [comment]
+1

**Comment by BananaHuo** [comment]
同样，在 mate 30 5G版 TAS-AN00 这个型号的线上机型也出现了这个问题，有人知道怎么解决吗？？
