### ISSUE TITLE
ARouter在kotlin跨模块调用问题

### ISSUE THREAD

**Issue by liucanrui8018** [alibaba/ARouter#400]
ARouter在kotlin跨模块启动activity的时候,跳转成功,但intent参数获取失败,总是显示默认值,请问如何解决？

**Comment by zhi1ong** [comment]
源码调试一下

**Comment by fy5220** [comment]
@liucanrui8018 你解决了么?我也总是获取不到值...自己用intent获取就可以获取到..
@zhi1ong 一般出现场景好像是传递多个值..比如a页面传递a b俩值到c页面.然后b页面传递b c值到c页面.然后c页面有时候就接收不到值.
