### ISSUE TITLE
Fragment跨module跳转，获取实例为null

### ISSUE THREAD

**Issue by liuyangqiao** [alibaba/ARouter#404]
## Look at here

我用的是模拟器(android 7.1)和红米note3(android 6.0)  
模拟器直接是获取实例是null,红米没报错，直接crash

配置没有问题：
我的配置如下：
发起页面(在ModuleA)：
if (isModule.toBoolean()) {
    apply plugin: 'com.android.application'
} else {
    apply plugin: 'com.android.library'

}
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
**apply plugin: 'kotlin-kapt'
kapt {
    arguments {
        arg("moduleName", project.getName())
    }
}**

kapt 'com.alibaba:arouter-compiler:1.1.1'
  api rootProject.ext.dependencies.arouter_api(这个是抽取在公用库中)

被调起fragment（在muduleB）：
配置和上面一样

**Comment by zhi1ong** [comment]
每个模块都要依赖 annotationProcessor 的

**Comment by AttITuder** [comment]
同一个模块可以获得对象，跨模块获得Fragment对象为null？每个模块都是相同的依赖

**Comment by tangnuo** [comment]
请问最后如何解决的？我的kotlin-android-extensions插件，获取的View实例也是null；
