### ISSUE TITLE
拦截器中怎么获取Activity,实现转场动画

### ISSUE THREAD

**Issue by wanghao25877** [alibaba/ARouter#406]
withTransition 在 .navigation(activity); 
 未传acvitiy时失效，拦截器中怎么获取 activity

**Comment by zhi1ong** [comment]
可以提交一个 PR，在 Postcard 里面加一个 context

**Comment by lujun525** [comment]
> 可以提交一个 PR，在 Postcard 里面加一个 context

大神，问下啥是PR，我现在有个需求就是在拦截器里做跳转，但是我拿不到activity（我跳转的这个页面不方便用拦截器），不知道该怎么解决

**Comment by lujun525** [comment]
> 可以提交一个 PR，在 Postcard 里面加一个 context

我现在有个需求就是在拦截器里做跳转，但是我拿不到activity（得用context做跳转，比较特殊），看最新版本Postcard里还没context

**Comment by chengfan2017** [comment]
ActivityUtils.getTopActivity()
