### ISSUE TITLE
不同module间跳转问题

### ISSUE THREAD

**Issue by clouse** [alibaba/ARouter#41]
能简单概述下不同module间原理吗？跟了很久源码没看懂，后期能添加实现原理的文档吗？
顺便问下 _ARouter的类的_navigation方法中的intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);这个标记位有什么作用？实际好像没有新建任务栈

**Comment by zhi1ong** [comment]
提问去交流群，这里用来放bug的。
