### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Ysrfengnull** [alibaba/ARouter#419]
ext.arouter_api_version = '1.3.1'
ext.arouter_compiler_version = '1.1.4'

Cause: duplicate entry: com/alibaba/android/arouter/routes/ARouter$$Group$$messageToCenter.class

**Comment by zhi1ong** [comment]
不同模块中不能用相同的 group 名

**Comment by li-xiaojun** [comment]
@zhi1ong 
我也是在模块中出现了这个问题，你说的*不同模块中不能用相同的 group 名*是指什么group，我并没有指定过什么group

**Comment by aolphn** [comment]
> 不同模块中不能用相同的 group 名

good job
