### ISSUE TITLE
和ActivityRouter比起来，真的太难用了，关键是跳转路径必须以/开头，否则直接崩溃

### ISSUE THREAD

**Issue by 985557461** [alibaba/ARouter#42]
## Look at here

- → Did you add apt plugin
- → Did you add annotation above target activity
- → Did you read the source code carefully

**Comment by zhi1ong** [comment]
1. 首先请你**认真的看完整个文档**，再告诉我是不是难用
2. 这是一个解耦开发**框架**，不是单纯用来跳转的，不要拿去和跳转用的sdk做比较
3. 路径用一个“/”开头，是为了**规范**
4. 有更好的建议请提交PR
5. issues 是提交bug的地方
