### ISSUE TITLE
postCard.setExtra() 中的int值无法在拦截器中拿到? 

### ISSUE THREAD

**Issue by liangjingkanji** [alibaba/ARouter#421]
那只能在注解Router中才能设置extra???

**Comment by liangjingkanji** [comment]
那我一个页面对应多种状态岂不是不能用extra了

**Comment by zhi1ong** [comment]
可以用 getExtra 拿到，不是 getExtras

**Comment by liangjingkanji** [comment]
我就是用的getExtra ,  拿不到, 我现在用withflag 替代了......

**Comment by zhiwei1990** [comment]
问题场景：
一个WebActivity可以加载登录/非登录的页面。希望在ARouter的navigation时候，动态区分哪些需要拦截，哪些不需要拦截。按照官方文档，需要WebActivity配置extra字段注解。登录拦截器的判断就出现了不便，倘若不需要登录的来用greenChannel标记，那么会引起其他拦截器都会放行的问题。
在ARouter.build()之后生成的postcard对象，setExtra并不能生效，debug到源码，发现依旧会被注解的extra值覆盖掉。似乎setExtra并没有存到对应的route的map中。如此这个postcard的setExtra函数便是无用了。
建议：希望可以让postcard的setExtra函数可以优先级高于注解extra，使之动态代码控制。

**Comment by zhiwei1990** [comment]
> 可以用 getExtra 拿到，不是 getExtras

大佬，就不开新的issue了，有空时候，烦请看一下，这个建议是否有必要。

问题场景：
一个WebActivity可以加载登录/非登录的页面。希望在ARouter的navigation时候，动态区分哪些需要拦截，哪些不需要拦截。按照官方文档，需要WebActivity配置extra字段注解。登录拦截器的判断就出现了不便，倘若不需要登录的来用greenChannel标记，那么会引起其他拦截器都会放行的问题。
在ARouter.build()之后生成的postcard对象，setExtra并不能生效，debug到源码，发现依旧会被注解的extra值覆盖掉。似乎setExtra并没有存到对应的route的map中。如此这个postcard的setExtra函数便是无用了。
建议：希望可以让postcard的setExtra函数可以优先级高于注解extra，使之动态代码控制。
