### ISSUE TITLE
无法跳转ARouter::There is no route match the path [/common/touch], in group [common][ ] 

### ISSUE THREAD

**Issue by LiuDongCai** [alibaba/ARouter#423]
配置正常
07-02 15:29:09.432 32138-32138/? I/ARouter::: ARouter init start.[ ] 
    Run with debug mode or new install, rebuild router map.[ ] 
07-02 15:29:09.433 32138-32138/? I/ARouter::: VM with name 'Android' has multidex support
07-02 15:29:09.434 32138-32138/? E/ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths
07-02 15:29:09.434 32138-32138/? I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.1][ ] 
07-02 15:29:09.759 32064-32064/com.addcn.android.house591 D/ARouter::: Filter 3 classes by packageName <com.alibaba.android.arouter.routes>
07-02 15:29:09.760 32064-32064/com.addcn.android.house591 I/ARouter::: Find router map finished, map size = 3, cost 618 ms.[ ] 
07-02 15:29:09.761 32064-32064/com.addcn.android.house591 I/ARouter::: Load root element finished, cost 1 ms.[ ] 
07-02 15:29:09.762 32064-32064/com.addcn.android.house591 D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[1], InterceptorIndex[0], ProviderIndex[2][ ] 
07-02 15:29:09.762 32064-32064/com.addcn.android.house591 I/ARouter::: ARouter init success![ ] 
07-02 15:29:09.763 32064-32064/com.addcn.android.house591 W/ARouter::: ARouter::No postcard![ ] 
    ARouter::No postcard![ ] 
07-02 15:29:09.763 32064-32064/com.addcn.android.house591 D/ARouter::: The group [arouter] starts loading, trigger by [/arouter/service/interceptor][ ] 
07-02 15:29:09.764 32064-32064/com.addcn.android.house591 D/ARouter::: The group [arouter] has already been loaded, trigger by [/arouter/service/interceptor][ ] 
07-02 15:29:09.764 32064-32064/com.addcn.android.house591 I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.2][ ] 
07-02 15:29:09.765 32064-32064/com.addcn.android.house591 I/ARouter::: ARouter init over.[ ] 
07-02 15:29:10.018 32138-32138/? D/ARouter::: Filter 3 classes by packageName <com.alibaba.android.arouter.routes>
07-02 15:29:10.020 32138-32138/? I/ARouter::: Find router map finished, map size = 3, cost 588 ms.[ ] 
07-02 15:29:10.021 32138-32138/? I/ARouter::: Load root element finished, cost 1 ms.[ ] 
07-02 15:29:10.022 32138-32138/? D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[1], InterceptorIndex[0], ProviderIndex[2][ ] 
07-02 15:29:10.022 32138-32138/? I/ARouter::: ARouter init success![ ] 
07-02 15:29:10.023 32138-32138/? W/ARouter::: ARouter::No postcard![ ] 
    ARouter::No postcard![ ] 
07-02 15:29:10.023 32138-32138/? D/ARouter::: The group [arouter] starts loading, trigger by [/arouter/service/interceptor][ ] 
07-02 15:29:10.024 32138-32138/? D/ARouter::: The group [arouter] has already been loaded, trigger by [/arouter/service/interceptor][ ] 
07-02 15:29:10.024 32138-32138/? I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.2][ ] 
07-02 15:29:10.025 32138-32138/? I/ARouter::: ARouter init over.[ ] 
07-02 15:29:10.051 32159-32159/? D/ARouter::: Filter 3 classes by packageName <com.alibaba.android.arouter.routes>
07-02 15:29:10.054 32159-32159/? I/ARouter::: Find router map finished, map size = 3, cost 651 ms.[ ] 
07-02 15:29:10.055 32159-32159/? I/ARouter::: Load root element finished, cost 1 ms.[ ] 
07-02 15:29:10.056 32159-32159/? D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[1], InterceptorIndex[0], ProviderIndex[2][ ] 
07-02 15:29:10.056 32159-32159/? I/ARouter::: ARouter init success![ ] 
07-02 15:29:10.058 32159-32159/? W/ARouter::: ARouter::No postcard![ ]

**Comment by LiuDongCai** [comment]
无论是debug还是签名打包版本都是如此

**Comment by LiuDongCai** [comment]
implementation 'com.alibaba:arouter-api:1.3.1'
 annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'

**Comment by LiuDongCai** [comment]
在demo里可以跳转，但是在项目里就不行……

**Comment by eenie** [comment]
我从win切换到mac环境也出现这个问题了。
