### ISSUE TITLE
Autowired注解问题

### ISSUE THREAD

**Issue by canhuah** [alibaba/ARouter#424]
比如下面这个name,必须和ARouter.getInstance().build("/test/activity1").withString("name",xxx)..中withString("这个key",xxx)保持一致,实际上是不是有些不好,因为多个界面都使用的话我还需要挨个去保持一致,有可能发生错误,我可能想要下面这样的该如何支持呢,这样我就可以把这个@Autowired(key="name")中的"name"保存在某个常量类里面,避免上面的错误..当然这个只是个人的想法,也不知道是否合理
  // 现在的                               
   @Autowired                         
    String name;                   

  //可能想要的
@Autowired(key="name")
     String mName;

ARouter.getInstance().build("/test/activity1")
              .withString("name", null)   //看这里
              .withInt("age", 18)
               .withBoolean("boy", true)
               .withLong("high", 180)
                .withString("url", "https://a.b.c")
                .withParcelable("pac", testParcelable)
                .withObject("obj", testObj)
                 .navigation();

**Comment by zhi1ong** [comment]
本来就支持， @Autowired(name="name")
