### ISSUE TITLE
ARouter compile message output type

### ISSUE THREAD

**Issue by JeckChou** [alibaba/ARouter#425]
when I release my project which with library Arouter, my output console  will print message like '

注: ARouter::Compiler The user has configuration the module name, it was [XXX] |  
-- | --

'

it is worried me and bad for Warning Free. can you change output type from warning to info or others but warning , error etc

**Comment by zhi1ong** [comment]
我用的是 `Diagnostic.Kind.NOTE`，没有 info 这个日志级别
