### ISSUE TITLE
 Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Group$$service;

### ISSUE THREAD

**Issue by xie123** [alibaba/ARouter#43]
1.配置一切正常。
2.我目前用了ARouter 暴露服务的功能
3.我的项目进行分包。modelA 依赖于lib.framework.在lib.framework中有服务暴露了，就是继承了IProvider,然后在modelA中我也新建了服务(继承了IProvider)
.然后在编译的时候提示:
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Group$$service;
Error:com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Group$$service;
Error:com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Group$$service;
Error:java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Group$$service;
Error:com.android.dex.DexException: Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Group$$service;

**Comment by zhi1ong** [comment]
不同模块中使用了相同的分组，分组冲突了

**Comment by liuxuesong001** [comment]
我也出现了这个问题，我写了2个public class JsonServiceImpl implements SerializationService，报的这个错。
