### ISSUE TITLE
您好，我使用最1.3.1的时候，带返回值启动，但是没有回调onActivityResult这个方法呢

### ISSUE THREAD

**Issue by xingfu0809** [alibaba/ARouter#432]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by fanturbo** [comment]
说下我遇到的情况哈。_ARouter的这个方法中_navigation(final Context context, final Postcard postcard, final int requestCode, final NavigationCallback callback)，对requestCode做了判断，只有当requestCode大于0时才会调用startActivityForResult方法。
