### ISSUE TITLE
annotationProcessor生成文件命名改进建议

### ISSUE THREAD

**Issue by water54** [alibaba/ARouter#435]
## Look at here

 现在生成的格式为ARouter$$Group$$groupName，但是不同模块可能会有属于同一分组的provider。比如基础服务在app模块会有，在其它模块同样可能存在（我承认目前我们项目结构还不合理）  
 建议生成文件命名以ARouter$$Group$$moduleName$$groupName?

**Comment by zhi1ong** [comment]
这块约定上就要求不同模块中不能用相同的分组，不然很容易会导致路由趋向混乱了
