### ISSUE TITLE
arouter支持非原生fragment吗？比如华为，小米，oppo, vivo等厂商都会有自己的support包

### ISSUE THREAD

**Issue by hongxialiu** [alibaba/ARouter#447]
麻烦问下，arouter支持非原生fragment吗？比如华为，小米，oppo, vivo等厂商都会有自己的support包，里面fragment不是android.app.fragment.我按照arouter源码层有使用到fragment的地方，增加厂商自己support包的fragment,编译arouter_api报错如下：

错误: 服务配置文件不正确, 或构造处理程序对象javax.annotation.processing.Processor: Provider com.alibaba.android.arouter.compiler.processor.AutowiredProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/squareup/javapoet/TypeName时抛出异常错误

**Comment by jokermonn** [comment]
只找到了 oppo 的官方 sdk 链接，其他厂商的链接放一下？

**Comment by hongxialiu** [comment]
可以通过iprovider来曲线救国
