### ISSUE TITLE
Arouter打开属性为SingleTask的Activity 多次

### ISSUE THREAD

**Issue by ClarkZhangdi** [alibaba/ARouter#448]
### 跳转btn 多次点击之后
**//                跳转到购买详情页面
                ARouter.getInstance().build("/order/components/OrderShoppingCommitActivity")
                        .withObject("beanList", idAvBottomView.getBeanList())
                        .withObject("beanCount", idAvBottomView.getBeanCount())
                        .withObject("ShootingOrderDetailResp", resp)
                        .withInt("placeId", placeId)
                        .navigation(this, 100);**

### 打开指定Activity多次
        **<activity
            android:name=".modules.order.components.OrderShoppingCommitActivity"
            android:launchMode="singleTask"
            android:screenOrientation="portrait" />**

**Comment by bauer-bao** [comment]
这个问题为什么关闭？怎么解决？

**Comment by bauer-bao** [comment]
.withFlags(Intent.FLAG_ACTIVITY_NEW_TASK)加这一行就好了。

**Comment by DreamZXCreator** [comment]
因为arouter跳转startActivity的时候不传activity对象的话，默认使用的ApplicationContext，使用ApplictaionContext跳转必须加上Intent.FLAG_ACTIVITY_NEW_TASK这个flag，从而导致了你说的问题。如果你想实现预期效果，要么使用navigation(activity），要么在build时候，手动setFlags()。
