### ISSUE TITLE
release 下ARouter::There is no route match the path [/arouter/service/interceptor]  debug正常

### ISSUE THREAD

**Issue by xiangtian134** [alibaba/ARouter#449]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

- 
ARouter::There is no route match the path [/arouter/service/interceptor]

配置按照文档配置debug下正常运行，release打包apk  打开ARouter调试  init ARouter  提示ARouter::There is no route match the path [/arouter/service/interceptor]，求教大佬这是什么原因

**Comment by taseal** [comment]
试试在proguard添加：
-keep class dalvik.system.DexFile{*;}

**Comment by zhi1ong** [comment]
按照文档配置混淆
