### ISSUE TITLE
"没有应用可执行此操作" -- 请选择一个应用

### ISSUE THREAD

**Issue by lovingning** [alibaba/ARouter#450]
在华为手机上进行页面跳转时,有些界面无法跳转.

查看日志发现没有任何产出

只是会系统弹窗提醒"选择一个应用"

"没有应用可执行此操作"

按说只有隐式intent请求启动其他组件时才可能出现这种情况,但很明显的,我应用里面并没有哪个活动是隐式的.

这个问题之前倒是没发现,debug和release包都有这个问题

**Comment by zhi1ong** [comment]
看看 SchemeFilter 里面怎么注册的，应该是域名没匹配
