### ISSUE TITLE
Program type already present: com.alibaba.android.arouter.routes.ARouter$$Providers$$*

### ISSUE THREAD

**Issue by vjHuang** [alibaba/ARouter#455]
### **问题：**
在模块化开发实践中，多项目（注意不是多模块）需要打包成aar包之后，再拿到一个一体化项目引用，在编译时会报错：
Program type already present: com.alibaba.android.arouter.routes.ARouter$$Providers$$app

### **原因：**
因为那些项目自己也可以作为独立的app运行，所以module名是默认的app，所以他们生成的ARouter类，都是叫com.alibaba.android.arouter.routes.ARouter$$Providers$$app，这就导致aar里的类名跟最后一体化那个项目自己的类重名冲突了。

### **解决办法：**
修改每个项目默认的模块名（app）为单独的，如app_a，app_b之类的，避免生成的ARouter类名字一样即可。修改方法网上有，自己找找。

**Comment by banshake** [comment]
hi
在使用WMRouter的时候也经常有Program type already present: ***
不过后面的重复类，每次都不一样，可能是org.intellij.lang.annotations.JdkConstants$ListSelectionMode
Error: Program type already present: com.ms.square.android.expandabletextview.ExpandableTextView$ExpandCollapseAnimation

**Comment by Knight-ZXW** [comment]
> hi
> 在使用WMRouter的时候也经常有Program type already present: ***
> 不过后面的重复类，每次都不一样，可能是org.intellij.lang.annotations.JdkConstants$ListSelectionMode
> Error: Program type already present: com.ms.square.android.expandabletextview.ExpandableTextView$ExpandCollapseAnimation

Me too ，我们用WMRouter ,也遇到了这个问题，虽然clean一下项目就好了，但是 出现的概率太高了

**Comment by banshake** [comment]
> > hi
> > 在使用WMRouter的时候也经常有Program type already present: ***
> > 不过后面的重复类，每次都不一样，可能是org.intellij.lang.annotations.JdkConstants$ListSelectionMode
> > Error: Program type already present: com.ms.square.android.expandabletextview.ExpandableTextView$ExpandCollapseAnimation
> 
> Me too ，我们用WMRouter ,也遇到了这个问题，虽然clean一下项目就好了，但是 出现的概率太高了

每次都clean，构建一次要10多分钟，太痛苦了

**Comment by scsfwgy** [comment]
测试发现，不要在不同module中用同一个group,不然会出现这个问题。因为：ARouter$$Group$$xxx xxx就是组名，不同module会生成不同的ARouter$$Group$$xxx，会导致重复。

**Comment by 123yangu** [comment]
> 测试发现，不要在不同module中用同一个group,不然会出现这个问题。因为：ARouter$$Group$$xxx xxx就是组名，不同module会生成不同的ARouter$$Group$$xxx，会导致重复。
这个有办法解决吗？这个难道每个工厂的报名都要加tag来创建包吗？感觉不太合理哟

**Comment by zhi1ong** [comment]
这个是在文档里特意说明的，技术上可以避免，不过为了防止后续难以维护，故意这么处理的。
同一个 group 不要出现在多个 module 里，不然维护起来会非常困难
