### ISSUE TITLE
ARouter.getInstance().build(Uri).withString("","")在目标界面无法获取with过去的参数

### ISSUE THREAD

**Issue by luleijun** [alibaba/ARouter#456]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhi1ong** [comment]
当然可以获取到 with 的参数，如果 uri 中有同名参数，会以 uri 中的参数为准

**Comment by zhi1ong** [comment]
你可能用了老版本的 SDK，旧版本曾经有该问题，请使用最新版本
