### ISSUE TITLE
点击不会跳转，在同一个module

### ISSUE THREAD

**Issue by xie123** [alibaba/ARouter#46]
当我点击跳的时候会有下面的log

 W/ARouter::: ARouter::No postcard![ ] 
W/ARouter::: ARouter::No postcard![ ] 
D/ARouter::: The group [login] starts loading, trigger by [/login/LoginIndexActivity][ ] 
D/ARouter::: The group [login] has already been loaded, trigger by [/login/LoginIndexActivity][ ] 
I/: 这里是ARouter的跳转回调---onFound
I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.2][ ]<-----------这个是啥

**Comment by xie123** [comment]
点击编译后ARouter$$Group$$login已经生成了

**Comment by fanturbo** [comment]
问下这个问题是怎么解决的？是由是什么导致的呢
