### ISSUE TITLE
develop分支 TypeKind缺少SERIALIZABLE 无法运行

### ISSUE THREAD

**Issue by hloong** [alibaba/ARouter#461]
## Look at here
Developer分支报错，是漏写了SERIALIZABLE 么？

![image](https://user-images.githubusercontent.com/3353954/43514437-c6e816bc-95b2-11e8-82e2-126d3265f903.png)

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhi1ong** [comment]
更新最新的代码试试
