### ISSUE TITLE
连续点击8次无法跳转的bug

### ISSUE THREAD

**Issue by po1arbear** [alibaba/ARouter#463]
protected Object navigation(final Context context, final Postcard postcard, final int requestCode, final NavigationCallback callback) {
        try {
            LogisticsCenter.completion(postcard);
        } catch (NoRouteFoundException ex) {
            logger.warning(Consts.TAG, ex.getMessage());

            if (debuggable()) { // Show friendly tips for user.
                Toast.makeText(mContext, "There's no route matched!\n" +
                        " Path = [" + postcard.getPath() + "]\n" +
                        " Group = [" + postcard.getGroup() + "]", Toast.LENGTH_LONG).show();
            }

            if (null != callback) {
                callback.onLost(postcard);
            } else {    // No callback for this invoke, then we use the global degrade service.
                DegradeService degradeService = ARouter.getInstance().navigation(DegradeService.class);
                if (null != degradeService) {
                    degradeService.onLost(context, postcard);
                }
            }

            return null;
        }

        if (null != callback) {
            callback.onFound(postcard);
        }

        if (!postcard.isGreenChannel()) {   // It must be run in async thread, maybe interceptor cost too mush time made ANR.
            interceptorService.doInterceptions(postcard, new InterceptorCallback() {
                /**
                 * Continue process
                 *
                 * @param postcard route meta
                 */
                @Override
                public void onContinue(Postcard postcard) {
                    _navigation(context, postcard, requestCode, callback);
                }

                /**
                 * Interrupt process, pipeline will be destory when this method called.
                 *
                 * @param exception Reson of interrupt.
                 */
                @Override
                public void onInterrupt(Throwable exception) {
                    if (null != callback) {
                        callback.onInterrupt(postcard);
                    }

                    logger.info(Consts.TAG, "Navigation failed, termination by interceptor : " + exception.getMessage());
                }
            });
        } else {
            return _navigation(context, postcard, requestCode, callback);
        }

        return null;
    }
拦截器连续拦截八次后，_ARouter类中的navigation方法里的回调不执行（也出现延迟2分钟左右收到回调），导致点击无任何响应

**Comment by adonis-lsh** [comment]
我也发现了同样的问题

**Comment by CK875430315** [comment]
怎么解决的

**Comment by szn0212** [comment]
同样遇到该问题，该怎么解决？

**Comment by adonis-lsh** [comment]
> 同样遇到该问题，该怎么解决？

连续点击的时候,你要把原来跳转的事件给消费掉才行,不然的话连续点击事件就会进入到队列进行排队,然后会触发超时时间,具体的逻辑忘了,你每次点击确保跳转事件被消耗就没事
