### ISSUE TITLE
Autowired 没有数据

### ISSUE THREAD

**Issue by tututututututu** [alibaba/ARouter#47]
@Autowired
   String id;
   @Autowired
  String openId;

ARouter.getInstance().build("/mdressstyle/DressStyleDetailActivity")
                        .withString("id", dressStyleInfoList.getRows().get(position).getId())
                        .withString("openId", AppData.USER_INFO.getStaff().getOpenId())
                        .navigation();

but id and openId 没有数据

**Comment by fnastyCalvin** [comment]
请先确定添加了对应的库
```
compile 'arouter'
annotationProcessor 'arouter-compiler'
compile 'arouter-annotation'
```
因为是编译时注解，`@Autowired`会生成对应的class文件

**Comment by zhi1ong** [comment]
可能是没有调用 ARouter.getInstance().inject(this); 这个最佳实践是放在Activity基类中

**Comment by GJson** [comment]
onCreate 方法开始要先执行 ARouter.getInstance().inject(this);
