### ISSUE TITLE
重复跳转问题

### ISSUE THREAD

**Issue by mny459** [alibaba/ARouter#471]
请教一个问题：我有两个Module，Module A声明了两个路径：Route(path = "/moduleA/a")和Route(path = "/moduleA/b")，ModuleB有Route(path = "/moduleB/c")。
我一开始进入 Route(path = "/moduleB/c") 然后进入 Route(path = "/moduleA/b") ，接着进入Route(path = "/moduleA/a") ，以上都可以正常跳转，然而从Route(path = "/moduleA/a") 调治 Route(path = "/moduleB/c") 却怎么也跳转不过去了。这种该怎么处理呢？

**Comment by zhi1ong** [comment]
看起来你是从 B -> A 可以，从 A -> B 不行，那就是 B 没有依赖 compiler sdk 呗

**Comment by mny459** [comment]
可能是我没有描述清楚，并不是这样的。我重新说一下：
- a、b属于A，
- c属于B。
- a可以到b和c，b也可以到a和c，c也可以到a和b。
- 但是，如果我从一个d(d是程序入口，类似于Splash)到c，然后c到a，a到b，这个时候b不能到c。
