### ISSUE TITLE
Could not find com.alibaba:arouter-compiler:1.4.0.

### ISSUE THREAD

**Issue by flyou** [alibaba/ARouter#472]
https://repo.jfrog.org/artifactory/libs-release-bintray/com/alibaba/arouter-compiler/1.4.0/arouter-compiler-1.4.0.jar?referrer

{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}

**Comment by zhi1ong** [comment]
compiler 最新版本 1.2.0，README 里面有最新版本说明

**Comment by captain-miao** [comment]
-，- 没找到，先这样配置吧：
```
dependencies {
    // 替换成最新版本, 需要注意的是api
    // 要与compiler匹配使用，均使用最新版可以保证兼容
    compile 'com.alibaba:arouter-api:1.4.0'
    annotationProcessor 'com.alibaba:arouter-compiler:1.2.0'
    ...
}
```
