### ISSUE TITLE
升级 compiler sdk 导致 [No module name, for more information, look at gradle log.]

### ISSUE THREAD

**Issue by lujianyun06** [alibaba/ARouter#475]
项目分多个模块，每个模块都写了
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
            }
        }
在每个模块的dependencies中加了 annotationProcessor "com.alibaba:arouter-compiler:+"
在baselib的dependencies中为：  api "com.alibaba:arouter-api:+"，

也试了把依赖中的“+”换成版本号，仍无法解决问题，奇怪的是前几天一直是可以运行的，今天突然无法运行，报如下错：

ARouter::Compiler >>> No module name, for more information, look at gradle log.

注: ARouter::Compiler >>> AutowiredProcessor init. <<<
注: ARouter::Compiler >>> Found autowired field, start... <<<
注: ARouter::Compiler categories finished.
注: ARouter::Compiler >>> Start process 1 field in SearchProductDelegate ... <<<
注: ARouter::Compiler >>> SearchProductDelegate has been processed, SearchProductDelegate$$ARouter$$Autowired has been generated. <<<
注: ARouter::Compiler >>> Autowired processor stop. <<<
错误: ARouter::Compiler An exception is encountered, [These no module name, at 'build.gradle', like :
  apt {
      arguments {
          moduleName project.getName();
      }
  }
  ]
:indexlibrary:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':indexlibrary:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: ARouter::Compiler >>> No module name, for more information, look at gradle log.

**Comment by lujianyun06** [comment]
解决了。。把annotationProcessorOptions中的moduleName换成AROUTER_MODULE_NAME就行了。。但是为什么呢？

**Comment by lujianyun06** [comment]
原来是这样，多谢

**Comment by gabyallen** [comment]
参数改变后有用
