### ISSUE TITLE
ARouter::Compiler >>> No module name, for more information, look at gradle log.

### ISSUE THREAD

**Issue by huangchaoqingcheng** [alibaba/ARouter#479]
之前好好的  
后来想尝试用eventbus的索引 按文档集成eventbus后报了这个错，
  javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
           //是不是这里写的不对？
                arguments = [eventBusIndex: 'com.knight.common.MyEventBusIndex']
            }
        }

**Comment by Handy045** [comment]
虽然不清楚为什么，但是吧evenBusIndex移动到上面一行就可以了 例如：
javaCompileOptions {
annotationProcessorOptions {
arguments = [eventBusIndex: 'com.knight.common.MyEventBusIndex']
arguments = [moduleName: project.getName()]
}
}
ps.最新版不叫moduleName
