### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.object2Json(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by huanyuan** [alibaba/ARouter#481]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhi1ong** [comment]
传递自定义对象，需要实现 SerializationService，看文档
