### ISSUE TITLE
组件化Release包中，Fragment无法自动注入，但是getArguments中有数据，Activity可以自动注入。

### ISSUE THREAD

**Issue by cx324** [alibaba/ARouter#483]
目前猜测是混淆导致的，因为关闭混淆或者设置debuggable,fragment就可以自动注入了，混淆中仅保留ARouter的混淆也是一样，并且必须加上-ignorewarnings，因为总是会有 这个警告 导致编译中断：Warning: com.alibaba.android.arouter.facade.model.RouteMeta: can't find referenced class javax.lang.model.element.Element
   专门写了没有逻辑的demo测试发现好像也是这样

**Comment by cx324** [comment]
找到解决办法了，自动注入的Fragment需要keep，但是不知道为什么，难道是这个fragment被混淆了导致无法注入的吗？可是跳转能够跳转过来，证明ARouter还是能找到这个Fragment的吧。activity不keep好像也能注入。

**Comment by zhongxiong00** [comment]
遇到同样的问题，求解答、

**Comment by cx324** [comment]
@zhongxiong00 在混淆里面keep一下你自动注入的fragment

**Comment by zhongxiong00** [comment]
> @zhongxiong00 在混淆里面keep一下你自动注入的fragment

不应该啊，我是通过这种方式获取的
    @Autowired(name = PageRouteConstants.PageParam.BOOLEAN_PARAM)
    public boolean mNeedBack;

**Comment by cx324** [comment]
> > @ zhongxiong00在混淆里面保持一下你自动注入的片段
> 
> 不应该啊，我是通过这种方式获取的
> @Autowired（name = PageRouteConstants.PageParam.BOOLEAN_PARAM）
> public boolean mNeedBack;

和你怎么获取没关系吧, 不要混淆你这个fragment就行了

**Comment by zhongxiong00** [comment]
> > > @ zhongxiong00在混淆里面保持一下你自动注入的片段
> > 
> > 
> > 不应该啊，我是通过这种方式获取的
> > @Autowired（name = PageRouteConstants.PageParam.BOOLEAN_PARAM）
> > public boolean mNeedBack;
> 
> 和你怎么获取没关系吧, 不要混淆你这个fragment就行了

这样处理不太好吧？

**Comment by cx324** [comment]
不放心的话在加固一下吧 @zhongxiong00

**Comment by zhongxiong00** [comment]
> 不放心的话在加固一下吧 @zhongxiong00

我的意思肯定是哪里没配置，等作者解答吧。  @zhi1ong
