### ISSUE TITLE
下载你们的demo运行，各种问题

### ISSUE THREAD

**Issue by shisp** [alibaba/ARouter#485]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

InstantRun我没开，该初始化的初始化了，该打开的打开了，但是还是1.There's no route matched Path = [/test/activity2] Group = [test]；2.  .withObject("obj", testObj) 报错Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.alibaba.android.arouter.facade.service.SerializationService.object2Json

**Comment by shisp** [comment]
直接运行你们所谓的“官方”demo，代码一个字没去改动，出问题了，提isuee，没说明缘由，直接关闭？？？？？

**Comment by zhi1ong** [comment]
1. 直接下载 Demo，可以理解成下载 demo.apk 么？这个 apk 没问题
2. 各种问题是什么问题？要具体描述问题，多个问题提交多个 issue

**Comment by shisp** [comment]
download zip，解压，用as打开，编译运行，就出现开头我我提的错误，as版本3.0.1，gradle-4.1-all，classpath 'com.android.tools.build:gradle:3.0.1'

**Comment by candyguy242** [comment]
一样，升级了一下apt版本：
COMPILE_SDK_VERSION=28
BUILDTOOLS_VERSION=28.0.2
SUPPORT_LIB_VERSION=27.1.1
MIN_SDK_VERSION=21
TARGET_SDK_VERSION=25

跑了跑模拟器，各种找不到路由和崩溃

**Comment by candyguy242** [comment]
@shisp 改了一下几个module的build文件配置，好了

原来工程中的配置比较乱，按配置说明，修改编译配置，再把那几个相关moudle的中router与api的工程依赖注释掉，改为远程依赖，再clean工程，重新运行即可。
android {
    defaultConfig {
        ...
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }
    }
}

dependencies {
    // 替换成最新版本, 需要注意的是api
    // 要与compiler匹配使用，均使用最新版可以保证兼容
    compile 'com.alibaba:arouter-api:x.x.x'
    annotationProcessor 'com.alibaba:arouter-compiler:x.x.x'
    ...
}
    compile 'com.alibaba:arouter-api:1.4.0'
    annotationProcessor 'com.alibaba:arouter-compiler:1.2.0'

好奇怪为什么官方的这几个工程里为啥不改改，直接与文档一致就好了啊，还要再费事的自己找问题。
