### ISSUE TITLE
关于生成doc文档的建议

### ISSUE THREAD

**Issue by candyguy242** [alibaba/ARouter#488]
目前生成的doc文档是json格式的，不太方便浏览，有两个建议：
1、增加一个字段desc,用注解或读取源代码的注释来赋值，用来在生成的文档中简要描述这个类的作用；
2、提供一个html工具，可以在网页上加载并以表格的形式展示内容，或者可以生成网页；

**Comment by zhi1ong** [comment]
1. 有相同功能的字段 `name` 
2. json 格式是为了方便用户自行解析成其他可读的格式，这块我可以做个小工具，读取输入的文档进行展示

**Comment by KeqingLI** [comment]
生成的doc文档 只有当前模块的 可以把依赖的所有模块汇总么
