### ISSUE TITLE
关于在fragment 使用 navigation(Activity mContext, int requestCode) 中的问题

### ISSUE THREAD

**Issue by bai123456** [alibaba/ARouter#489]
使用版本：
arouter-api：1.4.0
arouter-compiler: 1.2.1

问题： 
 ARouter.getInstance().build(“”).navigation(Activity mContext, int requestCode) 仅接受 Activity 对象.
在 fragment 内使用不能回调 onActivityResult。只能通过 fragment 依附的 activity 接收

**Comment by OnlyMyRailgun** [comment]
我也有同样的问题，于是我从activity里往下面分发

**Comment by dvlp-org** [comment]
不支持跳转fragment, api只有获取fragment吧。兄弟

**Comment by bai123456** [comment]
@xybean 是的  ，我目前的解决方案是在 activity 中手动调用 fragment 的onActivityResult

**Comment by LateNightMoon** [comment]
在Fragment中调用startActivityForResult会同时走Activity和Fragment的onActivityResult,而用Activity调用startActivityForResult只会调用Activity的onActivityResult。

**Comment by OnlyMyRailgun** [comment]
@xybean 
```
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        List<Fragment> allFragments = getSupportFragmentManager().getFragments();
        if (allFragments != null) {
            for (Fragment fragment : allFragments) {
                fragment.onActivityResult(requestCode, resultCode, data);
            }
        }
    }
```

**Comment by xybean** [comment]
@OnlyMyRailgun 谢谢你的代码，因为在Activity中处理这个逻辑对我们的项目来说过于繁琐笨，不过我已经采用了扩展ARouter跳转的功能，使它支持Fragment的onActivityResult()。

**Comment by ivarxiong** [comment]
目前 我是这么写 基本能解决 fragment work 的跳转问题
  
public static void startActivityForResult(FragmentX fragment, String fragmentName, Bundle args, int request_code){
        int seq = fragment.getSequenceNumber();
        if(fragment.getActivity() instanceof AppCompatActivityX) {
            ((AppCompatActivityX)fragment.getActivity()).setSeqNum(seq);
        }
        ARouter.getInstance().build(ActivityXHelp.CONTAINER_ACTIVITY)
                .withString(EXTRA_FRAGMENT_ROUTE_NAME, fragmentName)
                .withBundle(EXTRA_FRAGMENT_ARGS, args)
                .navigation(fragment.getActivity(), ((seq) << 8) + (request_code & 0xffff));
    }

然后 重写  AppCompatActivity 中的

 @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) { 
        reqSeqNum = _requestFromRouteSequenceNumber;
        _requestFromRouteSequenceNumber = 0;
        if (reqSeqNum != 0){
            if(reqSeqNum == (requestCode >> 8)) {
                Fragment frag = findActiveFragment(getSupportFragmentManager().getFragments(), reqSeqNum);
                if (frag != null) {
                    frag.onActivityResult(requestCode & 0xff, resultCode, data);
                    return;
                }
            }
        }
        super.onActivityResult(requestCode, resultCode, data);
    }

这是 在不改框架的情况下的方案

**Comment by RunCross** [comment]
@xybean 请问扩展的写法是怎么样的

**Comment by xybean** [comment]
@RunCross  see https://github.com/xybean/FragmentARouter
