### ISSUE TITLE
暴露的服务注入为空

### ISSUE THREAD

**Issue by SuOtk** [alibaba/ARouter#49]
项目里有2个module,一个app,一个common.
我把app module里的Application 当作一个服务接口的实现类来提供给common module注入
但是注入的一直为空.我也调用了Arouter的init.  在需要注入的地方也调用了 ARouter.getInstance().inject(this);
注解也检查了很多遍都没有问题.
不知道为何一直注入不了?是不是这种方式使用不支持?

**Comment by zhi1ong** [comment]
服务要由ARouter来实例化和初始化，Application这种不适合用作服务

子模块要拿到Application有太多办法，用ARouter的话，服务的init方法中的参数Context就是Application

**Comment by SuOtk** [comment]
我发现我common模块没有依赖app模块的时候,通过Arouter是获取不到app模块中的服务的.
我是想不通过模块间直接依赖的方式,而是通过Arouter获取服务来解决common和app之间依赖关系混乱的问题.
如果common不依赖app,能否通过Arouter获取到app中的服务?

**Comment by SuOtk** [comment]
我找到了为什么一直注解的是null.
我在BaseActivity中需要注入一个服务,
但是编译后apt只生成了一个叫做BaseActivity$$ARouter$$Autowired的类.
其他的Activity继承了BaseActivity后,调用了BaseActivity中的ARouter.getInstance().inject(this);
最后执行到AutowiredServiceImpl的autowire方法的时候,这个方法中className是子Activity的类名.找不到对应的Activity$$ARouter$$Autowired,所以没有注入.
为何自动生成的类没有子Activity的Autowired,还是说autowire方法查找的类名不对?

**Comment by zhi1ong** [comment]
1. 跨模块调用的话，需要抽象出一个接口包，来约束api
2. 基类中不能使用自动注入，基类中的服务直接采用依赖查找即可
