### ISSUE TITLE
There's no route matched

### ISSUE THREAD

**Issue by bandit001** [alibaba/ARouter#492]
按照文档在每一个module中添加了如下配置
javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName(), AROUTER_GENERATE_DOC: "enable"]
            }
        }

    compile 'com.alibaba:arouter-api:1.4.0'
    annotationProcessor 'com.alibaba:arouter-compiler:1.2.1'

所有的跳转activity都有相应的route注解
app主工程中build相应子目录下创建了apt目录，生成了相应的route文件，其他library工程没有，结果就是app内跳转正常，app跳转module工程提示There's no route matched!

求答疑？

**Comment by bandit001** [comment]
单独make module之后相应的route路由文件也生成了，但是app跳转module还是提示找不到路由

**Comment by bandit001** [comment]
问题已经解决：
1、不是所有模块需要引入arouter配置，只需要跳转的模块配置即可
2、app主模块需要把所有要跳转的模块compile进去（希望此条注意事项能写入文档，坑了一天了）

**Comment by ShawnRacine** [comment]
@zhi1ong 请写入文档。
