### ISSUE TITLE
onNewIntent autowired 不生效

### ISSUE THREAD

**Issue by JinpengLiu** [alibaba/ARouter#497]
当Activity 的launchMode 设置为 singleTask，在activity再次被启动时，autowired 不会生效，
intent里可以取到数据，希望可以在onNewIntent的时候也能自动处理一下intent的数据

**Comment by zhi1ong** [comment]
onCreate 里面也要你自己调用 ARouter.inject(this) 的，同理 onNewIntent 里面你也要自己调用一下这个
