### ISSUE TITLE
fragment与映射关系

### ISSUE THREAD

**Issue by treycc** [alibaba/ARouter#50]
1.会添加fragment支持吗
2.api能否获取到映射列表，方便团队使用

**Comment by zhi1ong** [comment]
1. 短期内不会支持，因为加载Fragment需要一个Activity容器，这个容器由框架提供不太合适，UI很难和app统一

2. 目前没有，后续会支持，生成映射文档

**Comment by treycc** [comment]
直接返回fragment就好，加载交给调用者去做就可以了

**Comment by zhi1ong** [comment]
这样就很难统一了，调用方需要预先之后目标是Fragment还是Activity

**Comment by yangyiRunning** [comment]
@zhi1ong 

`  短期内不会支持，因为加载Fragment需要一个Activity容器，这个容器由框架提供不太合适，UI很难和app统一  `

如果只提供一个空的Activity呢？比如contentView中的布局仅仅是一个相对布局或者是帧布局的布局容器，无任何的UI风格效果，这样也不会有“UI很难与app统一的问题”。
