### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by hansionit** [alibaba/ARouter#500]
编译时报这个错误是ARouter引起的吗？
AGPBI: {"kind":"error","text":"Program type already present: a.API","sources":[{}],"tool":"D8"}

**Comment by hansionit** [comment]
来自注释处理程序 'com.alibaba.android.arouter.compiler.processor.AutowiredProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'

**Comment by hansionit** [comment]
解决了 不是Arouter的问题

**Comment by kun1988** [comment]
> 解决了 不是Arouter的问题

请问怎么解决的？我也出现了这个问题

**Comment by liuxuesong001** [comment]
请问，您是如何解决的？

**Comment by scsfwgy** [comment]
`AGPBI: {"kind":"error","text":"Program type already present: com.alibaba.android.arouter.routes.ARouter$$Group$$home1","sources":[{}],"tool":"D8"}`


more:
`AGPBI: {"kind":"error","text":"Program type already present: com.alibaba.android.arouter.routes.ARouter$$Group$$home1","sources":[{}],"tool":"D8"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.alibaba.android.arouter.routes.ARouter$$Group$$home1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
114 actionable tasks: 3 executed, 111 up-to-date
11:34:51: Task execution finished 'build'.`
