### ISSUE TITLE
通过withObject传自定义对象，目标页面获取到的值为null

### ISSUE THREAD

**Issue by yihuajia** [alibaba/ARouter#501]
arouter api 1.4.0
arouter compiler 1.2.1
目前做的是平板项目
1、A是rootFragment包含B(左侧)、C(右侧)两个fragment，A、B页面均可以收到通过withObject传过来的值，但是C拿到的却是null。在升级这个版本之前，从其它页面进入A页面时是没有出现过这情况的，但是通过复杂点的操作这个情况也是必现。但是升级该版本之后，从其它页面进入A页面，C页面都获取不到了传过来的值，必现。   然而bundle中是有值的，SerializationService中也有日志，唯独C页面中获取不到
2、如今通过withObject传参到DialogFragment也是获取到的值为null，也是必现

**Comment by zhi1ong** [comment]
断点调试一下，看看是哪一步拿不到值

**Comment by yihuajia** [comment]
再断点就是跟arouter的源码了，反正bundle里面有值，但是通过注解过来就是null
