### ISSUE TITLE
  net::ERR_UNKNOWN_URL_SCHEME,请问这种如何解决？

### ISSUE THREAD

**Issue by xxyandroid** [alibaba/ARouter#51]
三星真机：跑demo

url跳转跳转失败，依旧停留在webview界面。
 界面显示    找不到网页！！！net::ERR_UNKNOWN_URL_SCHEME
日志：
03-15 16:14:46.314 1968-1968/com.alibaba.android.arouter.demo W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 1968
03-15 16:14:46.334 1968-1968/com.alibaba.android.arouter.demo W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 1968
03-15 16:14:46.344 1968-1968/com.alibaba.android.arouter.demo I/chromium: [INFO:CONSOLE(0)] "Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png", source: data:text/html,chromewebdata (0)

**Comment by xxyandroid** [comment]
不胜感激！

**Comment by zhi1ong** [comment]
这个可能和框架关系不大，应该是浏览器禁用了打开外部链接，请先跑一下demo试试。

**Comment by BigXiangxy** [comment]
下载的apk也是这样的，应该就是浏览器禁用打开外部链接的问题。有没有方式友好的提示下呢。浏览器禁用打开外部链接ARouter收到通知。这个不好解决...  谢谢。期望有好的解决方案。

**Comment by zhi1ong** [comment]
这种没有什么好办法，只能在前端的js上着手想办法。

**Comment by BigXiangxy** [comment]
好的.   多谢 #
