### ISSUE TITLE
singleTop无效

### ISSUE THREAD

**Issue by xncHung** [alibaba/ARouter#511]
当在短时间内发请多个路由时，页面的singleTop会失效，已经传递了Activity,断点调试确认框架并没有为路由加FLAG_ACTIVITY_NEW_TASK。

**Comment by zhi1ong** [comment]
框架默认不会加，如果传入了 Activitity 的话

**Comment by tangkunttkk** [comment]
我也碰到了同样的问题,请问是怎么解决的呢,上面提到的“框架默认不会加，如果传入了 Activitity 的话”是什么意思啊?
