### ISSUE TITLE
建议减少第三方库的使用 

### ISSUE THREAD

**Issue by wanggq654321** [alibaba/ARouter#515]
compile 'org.apache.commons:commons-lang3:3.4'
    compile 'org.apache.commons:commons-collections4:4.1'

这两个可以去掉吗？ 
用java 自带的

**Comment by wanggq654321** [comment]
compile 'com.alibaba:fastjson:1.2.48'   这个推荐使用 gson

**Comment by jokermonn** [comment]
阿里的库都是用 fastjson 的，不过看 arouter 用 json 的地方并不是很多，确实可以删除 fastjson 的使用或者封装一层让开发者自行提供 json 解析库

**Comment by wanggq654321** [comment]
compile 'org.apache.commons:commons-lang3:3.4'
compile 'org.apache.commons:commons-collections4:4.1'

这两个可以去掉吗？
用java 自带的

**Comment by jokermonn** [comment]
都得等作者来回答了 😂

**Comment by zhi1ong** [comment]
fastjson 本来就不依赖呀，序列化方法是要你自己提供的

**Comment by wanggq654321** [comment]
> @wanggq654321 你说这些都没依赖啊，api 里面 Treemap 都是自己写的

compile 'org.apache.commons:commons-lang3:3.4'
compile 'org.apache.commons:commons-collections4:4.1'   在这个 arouter-compiler  模块里面

**Comment by jokermonn** [comment]
注解处理器的代码不会打入 apk

**Comment by wanggq654321** [comment]
另外我发现一个问题：
 Fragment fragment = (Fragment) ARouter.getInstance()
                .build("/test/fragment")
                .withString("name", "nimeide ")
                .withString("key", "33334444 ")
                .navigation();


在Fragment Autowired注解 接收不到值，用getArguments().getString("key") 就可以，不知道作者试过吗？：
@Route(path = "/test/fragment")
public class BlankFragment extends Fragment {

    @Autowired
    String name;
}

**Comment by wanggq654321** [comment]
> 注解处理器的代码不会打入 apk

明白，谢谢回复

**Comment by wanggq654321** [comment]
ARouter.getInstance().inject(this);  是的，感谢作者
