### ISSUE TITLE
关于在MVP中依赖注入问题

### ISSUE THREAD

**Issue by weiaiCmeng** [alibaba/ARouter#519]
能在V层直接注入到P层V层的接口吗?
@Route(path = RouteUtil.Map.Map_baidu_presenter, name = "nihao")
public class BaiduActyPresenter implements BaiduActyContract.Presenter {

    private BaiduActyContract.View mView ;

    @Override
    public void init(Context context) {
        BaiduActivity activity = (BaiduActivity) context;

    }

    public BaiduActyPresenter(BaiduActyContract.View mView) {
        this.mView = mView;
    }

init方法中有context可以强转成当前activity,有没有向Dagger2.0那样直接使用activity继承的接口BaiduActyContract.View那种形式,在P层不引用content的

**Comment by zhi1ong** [comment]
不能
