### ISSUE TITLE
希望加入序列化参数和对fragment的支持

### ISSUE THREAD

**Issue by s949492225** [alibaba/ARouter#52]
1.序列化可以采用json序列化的形式,这样就能解决基本类型传输的问题.
2.至于fragment支持是因为为了复用有些fragment需要单独的去展示,Router这里指定一个容器activity,bundle原生不动的传递给fragment是可以的,参数自动注入这个功能非常好.

**Comment by zhi1ong** [comment]
1. 序列化参数支持是有计划的
2. Fragment的顾虑是不知道应该由谁来指定这个Activity容器

**Comment by yangyiRunning** [comment]
@zhi1ong  如何给fragment传递参数？ 用提供的withXXX的API指定参数之后，在目的地对应的Fragment如何接收？

**Comment by yangyiRunning** [comment]
@zhi1ong  作者你好，请问如何给fragment传递参数？ 用提供的withXXX的API指定参数之后，在目的地对应的Fragment如何接收？

**Comment by zhi1ong** [comment]
@yangyiRunning  正常 getArguments 或者 使用 @Autowired 注入

**Comment by MartinDong** [comment]
大哥别开枪，自己人，下面是Kotlin写法， 

```kotlin
//获取指定的Fragment实例
val roomList = ARouter.getInstance()
                .build(ARouterPath.FRG_HOTEL_DETAIL_ROOM)
                //这里跟Activity传值一样，传输的Parcelable必须完整的重写那几个方法
                .withParcelable("mHouseInfo", mHouseInfo)
                .navigation() as Fragment

//然后再目标Fragment 中

@Route(path = ARouterPath.FRG_HOTEL_DETAIL_ROOM)
class RoomListFragment : BaseFragment {
    //@JvmField必须声明，否则编译不过去
    @JvmField
    @Autowired
    internal var mHouseInfo: HouseInfo? = null

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        ARouter.getInstance().inject(this)
        return super.onCreateView(inflater, container, savedInstanceState)
    }

}


```

**Comment by junge89221** [comment]
@MartinDong  段友，你好
@Route(path = "/mine/fragment")
class MineMainFragment : MVPBaseFragment<MineMainContract.IView, MineMainPresenter>(), MineMainContract.IView {

    private val userInfo = UserInfo()
    private val myOrder = MyOrder()
    private val myHealthy = MyHealthy()
    private val myFamilies = MyFamilies()
    private val mySmartHome = MySmartHome()
    private val myUptown = MyUptown()

    private lateinit var messageNumView: TextView
    private lateinit var refreshView: SwipeRefreshLayout
    private lateinit var headerBackground: ImageView

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val rootView = inflater.inflate(R.layout.fragment_mine_main, container, false)
        EventBus.getDefault().register(this)
        initPartner(rootView)
        return rootView
    }

然后我再：Fragment a = （Fragment）ARouter.getInstance().build("/mine/fragment").navigation()；获取到的是个null。求解
