### ISSUE TITLE
关于module模块配置的解决方案

### ISSUE THREAD

**Issue by wanggq654321** [alibaba/ARouter#520]
源码都扒了一遍，大致原理都明白了，module解耦还是有点疑问 ？

主项目App的build.gradle加入moduleA 依赖后App需要对moduleA 初始化和配置moduleA参数
同理：主项目App的build.gradle加入moduleB 依赖后App需要对moduleB 初始化和配置moduleB 参数

当我主项目App的build.gradle去掉moduleA 依赖后如何保持代码不动？

**Comment by wanggq654321** [comment]
突然发现 https://github.com/alibaba/ARouter/issues/520  结尾是520

**Comment by wanggq654321** [comment]
作者可以参考： CC  DDComponent  这个嘛 ， 主要都是为了 module的解耦

**Comment by wanggq654321** [comment]
4、方法调用
利用ServiceLoader可以实现方法调用。

WMRouter的method包中提供了通用的Function接口Func0 ~ Func9、FuncN，分别表示参数为0~9或可变参数的方法。声明方法时应该实现Function接口，示例如下。对于调用次数较多的方法，建议声明为singleton，避免每次调用时重复创建。

@RouterService(interfaces = Func2.class, key = "/add", singleton = true)
public class AddMethod implements Func2<Integer, Integer, Integer> {
    @Override
    public Integer call(Integer a, Integer b) {
        return a + b;
    }
}
方法的调用示例如下：

Func2<Integer, Integer, Integer> addMethod = Router.getService(Func2.class, "/add");
Integer result = addMethod.call(1, 2);
也可以直接通过callMethod调用，根据参数个数匹配对应的Function接口。

Integer result = Router.callMethod("/add", 1, 2);

**Comment by wanggq654321** [comment]
看了下   美团的方案，这个是解耦方法

**Comment by zhi1ong** [comment]
没明白你的需求是什么，模块就是模块，模块提供的服务，就在模块的服务的 init 方法中初始化，按需初始化，第一次用到的时候就会初始化
