### ISSUE TITLE
 java.lang.ClassCastException

### ISSUE THREAD

**Issue by bandit001** [alibaba/ARouter#527]
_ARouter.java==============line 408

ActivityCompat.startActivityForResult((Activity) currentContext, intent, requestCode, postcard.getOptionsBundle());

currentContext为空的时候，使用的application context

**Comment by zhi1ong** [comment]
By design

**Comment by zhi1ong** [comment]
设置 RequestCode 的情况下，必须用 Activity

**Comment by bandit001** [comment]
1 com.alibaba.android.arouter.launcher._ARouter.a(_ARouter.java:408)
--
2 com.alibaba.android.arouter.launcher._ARouter.a(_ARouter.java:44)
3 com.alibaba.android.arouter.launcher._ARouter$2.run(_ARouter.java:371)
4 android.os.Handler.handleCallback(Handler.java:739)
5 android.os.Handler.dispatchMessage(Handler.java:95)
6 android.os.Looper.loop(Looper.java:179)
7 android.app.ActivityThread.main(ActivityThread.java:5769)
8 java.lang.reflect.Method.invoke(Native Method)
9 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
10 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)

_ARouter 344 line======应该是当前activity为null的场景下，你们默认选择使用了application context，代码上需要处理这个classCast异常，目前的处理不健壮

**Comment by bandit001** [comment]
@zhi1ong
