### ISSUE TITLE
Module中的Autowired不起作用

### ISSUE THREAD

**Issue by liunana1993** [alibaba/ARouter#53]
clone了Arouter的源码，编辑了demo中的代码， 在app的activity中添加Autowired标记的字段有效，但是在module的activity中添加Autowired标记的字段不起作用，也不会自动生成xxxActivity$$Arouter$$Autowired文件

**Comment by liunana1993** [comment]
找到原因了：
是test-module-1的build.gradle中arouter-compiler的版本不对导致的
annotationProcessor 'com.alibaba:arouter-compiler:1.0.1'
应该使用最新版本，或者
annotationProcessor project(':arouter-compiler')

**Comment by zhi1ong** [comment]
是这个意思，看的很仔细。
