### ISSUE TITLE
好像不支持addFlags+withFlags两个flags值，导致FLAG_ACTIVITY_CLEAR_TOP跳转的activity没法实现保留原状态

### ISSUE THREAD

**Issue by Li-Zepeng** [alibaba/ARouter#530]
好像不支持addFlags+withFlags两个flags值，导致FLAG_ACTIVITY_CLEAR_TOP跳转的activity没法实现保留原状态。
    想实现用intent实现的以下功能（B上的数据依然保留）：
如果已经启动了四个Activity：A，B，C和D， 在D Activity里，想再启动一个Activity B，但不变成A,B,C,D,B，而是希望是A,B，而且B上的数据依然保留
Intent intent = new Intent();  
intent.setClass(TableActivity.this, FrameActivity.class);  
intent.addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);//设置不要刷新将要跳到的界面  
intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);//它可以关掉所要到的界面中间的activity  
startActivity(intent);

**Comment by zhi1ong** [comment]
可以直接 withFlags(Flag1 || Flag2), 会有 warning，这块已经改掉了，新增了 addFlags
