### ISSUE TITLE
1.4.1版本无法使用Autowired直接接收long[]

### ISSUE THREAD

**Issue by a483210** [alibaba/ARouter#535]
arouter api 1.4.1
arouter compiler 1.2.1

在实现SerializationService的情况下接收long[]参数，不会生成serializationService.parseObject(substitute.getIntent().getStringExtra(""), new com.alibaba.android.arouter.facade.model.TypeWrapper<long[]>(){}.getType());

如果是正常对象的情况下会生成，这里是修改了规则了吗？还是需要做某些特殊设置？

**Comment by demongel** [comment]
感觉碰到了相似的问题，使用readme例子里的withLong("key1", 666L),测试Autowired，结果一直是null，如果这个long类型放在第一个，会后续的数据也获取不到。

**Comment by guosanjun** [comment]
注入的时候用long，不用Long

**Comment by parcool** [comment]
感觉这种基本问题官方都不给个说法，全靠别人踩。。。
