### ISSUE TITLE
解决There is no route match the path的问题

### ISSUE THREAD

**Issue by baolw** [alibaba/ARouter#536]
上一个项目使用Arouter一直没有问题，这个项目使用常常出现标题显示的问题。研究了很久，终于解决。其实主要是因为使用了组件化开发分模块的问题。Arouter默认会用你申明的path的第一个/后面的字符用作group，如果你在声明路径的时候偷懒，使用了复制。

举个例子：
项目中有两个模块，一个模块是app。
app模块中有一个Activity注解如下：
@Route(path = “/app/activity1”)

一个模块是test。
test模块中有一个Activity注解如下：
@Route(path = “/test/activity2”)

上面这样注解是没问题的。

但是有人要是像我这样粗心，因为上面的字符串大家可能是放在某个interface中直接使用。这个时候可能就会选择直接复制，只改了后面的activity名字，而忘记改前面的。

那么就会出现：
app模块中有一个Activity注解如下：
@Route(path = “/app/activity1”)

一个模块是test。
test模块中有一个Activity注解如下：
@Route(path = “/**app**/activity2”)

注意上面test模块中的路径。
以上这样，这2个activity是2个不同模块的。但是他们的group用了同一个字符串app，那么在有逻辑跳转到这2个activity的时候就会报**There is no route match the path**。。。

遇到帮助遇到同样问题的朋友，却找不到解决办法的朋友。gradle的配置按官方提供的就可以。主要错误就是出现在这个大家声明path的地方。

**Comment by baolw** [comment]
似乎issue里某个问题提出了这个，不能在多个module中使用相同的group。我这里通俗化一点，帮助遇到问题的人。

**Comment by joele123** [comment]
请问下 不同插件之间跳转报There is no route match the path 的问题 怎么办？

**Comment by voodoo-jie** [comment]
我现在遇到的问题是，配置了一个全局变量，把全局变量这个路径放到变量里面去了，现在跳转的时候还是报这个错，但是那里面那几个路径是一目了然 /app/xxx ,/login/xxxx ,/share/xxxx，而且在各个module的Activity中配置的路径也没写错，检查了好几遍，但是在跳转的时候还是谈这个提示

**Comment by yanchengdeng** [comment]
> 
> 
> > 遇到这个问题的同学请仔细检查是否在每个`build.gradle`文件中都正确设置了以下代码（kotlin项目，java项目参考修改）
> > ```groovy
> > kapt {
> >     arguments {
> >         arg("moduleName", project.getName())
> >     }
> > }
> > 
> > 
> > dependencies {
> > //...
> >     kapt 'com.alibaba:arouter-compiler:1.1.4'
> > }
> > ```
> > 
> > 
> > ⚠️注意！`arouter-compiler` 这个依赖必须在`build.gradle`中声明，只在`base_module`中声明然后引用`base_module`中引用是无效的！
> 
> 最后这句话解决了我的问题：
> ⚠️注意！`arouter-compiler` 这个依赖必须在`build.gradle`中声明，只在`base_module`中声明然后引用`base_module`中引用是无效的！
> 调试半天不知道问题出现在，谢谢！
