### ISSUE TITLE
请问实现SerializationService时 @Route(path = "xxx")里的path值什么作用？

### ISSUE THREAD

**Issue by CCY0122** [alibaba/ARouter#537]
不好意思没找到哪里写了答疑群。。
你好，请问实现SerializationService时 @Route(path = "xxx")里的path值什么作用？文档里说的“方便用户自行选择序列化方式”没理解。。

**Comment by zhi1ong** [comment]
1. 你可以自己来实现这个 SerializationService，提供序列化对象的方式
2. 标上注解，才能被 ARouter 发现
