### ISSUE TITLE
多业务共用一个Activity 如何实现跳转

### ISSUE THREAD

**Issue by Oliverxyj123** [alibaba/ARouter#540]

**Comment by Oliverxyj123** [comment]
举个场景，例如webView 我们会封装一个webActivity，这样所有的webView的加载都放在这个activity,如果我有不同的业务，我的@Router注解应该怎么注解。

**Comment by JeckChou** [comment]
你将你的web url当作参数传入不就可以了吗？

**Comment by Oliverxyj123** [comment]
> 你将你的web url当作参数传入不就可以了吗？

除了这种办法还有其他的方式吗？我就是觉得这种办法比较麻烦才没用的

**Comment by JeckChou** [comment]
> > 你将你的web url当作参数传入不就可以了吗？
> 
> 除了这种办法还有其他的方式吗？我就是觉得这种办法比较麻烦才没用的

为什么麻烦？如果你想通过link用arouter跳转不是每个跳转也要准备不同link？这样你就觉得不麻烦？没看出来会简单到哪里呢

**Comment by QiYan925** [comment]
这个问题跟ARouter无关，你如果不用ARouter你会如何实现？建议不要在这里提问
