### ISSUE TITLE
找不到相关Fragment

### ISSUE THREAD

**Issue by zwonb** [alibaba/ARouter#542]
![image](https://user-images.githubusercontent.com/22101549/47984228-eacf9880-e110-11e8-9302-f58fefe9caf6.png)

新增了这两个上面第一个就找不到了
![image](https://user-images.githubusercontent.com/22101549/47984249-063aa380-e111-11e8-99de-313ef2dde10a.png)

这是一个Fragment，已经添加注解了
![image](https://user-images.githubusercontent.com/22101549/47984274-1ce0fa80-e111-11e8-8dae-e1636542001b.png)

arouter-api:1.4.0
arouter-compiler:1.2.1

**Comment by zwonb** [comment]
不同module导致的问题

**Comment by yangceng** [comment]
怎么解决呢？

**Comment by 751496032** [comment]
我也这样的问题，请问怎么解决

**Comment by WangChangQin** [comment]
+1,我用的是kotlin

**Comment by zwonb** [comment]
@WangChangQin @751496032 @yangceng 看 [#536](https://github.com/alibaba/ARouter/issues/536)

**Comment by WangChangQin** [comment]
@zwonb 我这边没重复啊
