### ISSUE TITLE
请问ARouter和Dagger2是否存在冲突？

### ISSUE THREAD

**Issue by ShshyDevooo** [alibaba/ARouter#550]
目前使用的ARouter版本
com.alibaba:arouter-api:1.4.1
com.alibaba:arouter-compiler:1.2.2
com.alibaba:arouter-register:1.0.2

在集成ARouter后dagger会出现找不到component问题？但是在生成的代码中能看到该component存在

**Comment by acaixuediananao** [comment]
同问~遇到这个问题了。怎么解决

**Comment by acaixuediananao** [comment]
> 目前使用的ARouter版本
> com.alibaba:arouter-api:1.4.1
> com.alibaba:arouter-compiler:1.2.2
> com.alibaba:arouter-register:1.0.2
> 
> 在集成ARouter后dagger会出现找不到component问题？但是在生成的代码中能看到该component存在

我的已经解决了，我的问题是因为module中的gradle中的配置写错了、、、AROUTER_MODULE_NAME这个写错了。。希望能帮到你
 //Arouter路由配置
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }
