### ISSUE TITLE
SerializationService空指针异常

### ISSUE THREAD

**Issue by Ryokooo** [alibaba/ARouter#551]
Caused by:
--
java.lang.NullPointerException:Attempt  to invoke interface method 'java.lang.String  com.alibaba.android.arouter.facade.service.SerializationService.object2Json(java.lang.Object)'  on a null object reference
com.alibaba.android.arouter.facade.Postcard.withObject(Postcard.java:244)

大部分机型都没有问题, oppo和一加会有这种错误.

**Comment by nEdAy** [comment]
mark

**Comment by tzwangbiao** [comment]
解决了吗？华为手机也报空
