### ISSUE TITLE
android9.0 arouter无效

### ISSUE THREAD

**Issue by flyer1b** [alibaba/ARouter#553]
如题 用华为magic2 9.0的系统 不能跳转了

**Comment by zhi1ong** [comment]
底层的跳转用的就是原生的 startActivity，和安卓版本无关，具体原因可以排查一下

**Comment by hiphonezhu** [comment]
Service byType 9.0手机，返回null

**Comment by Li-Zepeng** [comment]
我这儿也是，no router，9.0不行

**Comment by Li-Zepeng** [comment]
Warehouse.routes 在9.0的模拟器上size只有两个，在9.0以下就正常

**Comment by nEdAy** [comment]
Piexl 2 XL 9.0 正常
