### ISSUE TITLE
多界面跳转，拦截器问题

### ISSUE THREAD

**Issue by hongy-Li** [alibaba/ARouter#554]
A B C 三个页面，，
原始流程： 在A 中通过 startactivityforsult  到C ，然后c 可以通过  setResult  返回给A   数据。
现在需求：利用拦截器。
A 要跳转到C ，，但是经过拦截器拦截后，先跳转到B，在B中处理一下逻辑之后，B 再直接跳转到C且B自己finish .到C 之后， C处理完逻辑，同样要返回到A ，这个过程能实现吗？

**Comment by zhi1ong** [comment]
不是这么用的，A -> C ，拦截之后去 B, B 结束之后 finish 自己，然后回到拦截器，放行，而不是从 B -> C

**Comment by lujun525** [comment]
你好，我也是这么用的，这个B结束之后finish自己，咋回到拦截器啊

**Comment by zhi1ong** [comment]
@lujun525 广播之类的，通知回来即可。在拦截器中 onCoutinue
