### ISSUE TITLE
拦截器 第二次无效问题

### ISSUE THREAD

**Issue by LiChangXing** [alibaba/ARouter#555]
implementation 'com.alibaba:arouter-api:1.4.1'
    annotationProcessor 'com.alibaba:arouter-compiler:1.2.2' 
 主moudle导进去的，第一次拦截成功，第二次拦截 失败
跳转执行了   进login 的时候那句话也执行了，就是死活界面不出来

@Interceptor(name = "login", priority = 6)
public class LoginIInterceptor implements IInterceptor {
    private Context mContext;

    @Override
    public void process(Postcard postcard, InterceptorCallback callback) {
        String path = postcard.getPath();
        boolean isLogin = LoginSharedPreferences.getIsLogin(mContext);
        if (isLogin) {
            callback.onContinue(postcard);

        } else {
            switch (path) {
                //跳转login的 正常放行
                case RouterUrlUtil.ROUTHER_CHILD_LOGIN:
                    callback.onContinue(postcard);
                    break;
                default:
                    // 需要登录的直接拦截下来
                    callback.onInterrupt(null);
                    Bundle bundle = postcard.getExtras().getBundle(Constants.SP_KEY_BUNDLE);
                    if (postcard.getPath() != null) {
                        if (bundle == null)
                            bundle = new Bundle();
                        bundle.putString(Constants.SP_KEY_EXTRAS, postcard.getPath());
                    }
                    ARouter.getInstance().build(RouterUrlUtil.ROUTHER_CHILD_LOGIN).navigation();
                    break;
            }

        }
    }

    @Override
    public void init(Context context) {
        // 拦截器的初始化，会在sdk初始化的时候调用该方法，仅会调用一次
        mContext = context;
    }

 Navigation failed, termination by interceptor : com.alibaba.android.arouter.exception.HandlerException: No message.[ ]

**Comment by zhi1ong** [comment]
看看是不是循环拦截了，你在拦截器里面跳转的页面还会被拦截，要用 greenChannel 跳过拦截，或者通过条件判断

**Comment by SuXiGithub** [comment]
表示现在碰到同样问题，改如何解决？
