### ISSUE TITLE
onNewIntent无法获取传递数据

### ISSUE THREAD

**Issue by zhongxiong00** [alibaba/ARouter#560]
@Autowired(name = PageRouteConstants.PageParam.JSON_PARAM)
    public RouteParam mParam;

@Override
    protected void onNewIntent(Intent intent) {
        ARouter.getInstance().inject(this);
        LogUtils.e("" + (mParam == null));  //打印true
        if (mVpContent != null && mParam != null) {
            LogUtils.e("" + mParam.paramInt1);
            mVpContent.setCurrentItem(mParam.paramInt1);
        }
        super.onNewIntent(intent);
    }

**Comment by zhi1ong** [comment]
断点调试一下，获取没走 onNewIntent

**Comment by zhongxiong00** [comment]
> 断点调试一下，获取没走 onNewIntent

找到问题了，是没调  setIntent(intent); 
发现一个新问题，app后台很久之后，重新唤起，会出现找不到路由的情况。

**Comment by ColorDesert** [comment]
@zhongxiong00 请问你是怎么解决的，我这边也遇到了这个问题，Activity A是singleTask模式，第二次启动Activity A onNewIntent（Intent intent）方法调用了，被@Autowired注解的字段没有更新为新值

**Comment by zhongxiong00** [comment]
> @zhongxiong00 请问你是怎么解决的，我这边也遇到了这个问题，Activity A是singleTask模式，第二次启动Activity A onNewIntent（Intent intent）方法调用了，被@Autowired注解的字段没有更新为新值

    setIntent(intent);
     ARouter.getInstance().inject(this);
