### ISSUE TITLE
 "Gradle 插件实现路由表的自动加载"怎么理解

### ISSUE THREAD

**Issue by cyigo** [alibaba/ARouter#561]
想请问一下怎么自动加载的？
我对比了一下使用了下面Gradle 插件实现路由表的自动加载，跟没有使用下面代码好像没什么区别，LogisticsCenter里并没有插入代码，这是为什么？ 我理解错了吗？

使用 Gradle 插件实现路由表的自动加载
apply plugin: 'com.alibaba.arouter'

buildscript {
repositories {
jcenter()
}

dependencies {
    classpath "com.alibaba:arouter-register:?"
}
}

**Comment by cyigo** [comment]
想请问一下怎么自动加载的？
我对比了一下使用了下面Gradle 插件实现路由表的自动加载，跟没有使用下面代码好像没什么区别，LogisticsCenter里并没有插入代码，这是为什么？ 我理解错了吗？

使用 Gradle 插件实现路由表的自动加载
apply plugin: 'com.alibaba.arouter'

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath "com.alibaba:arouter-register:?"
    }
}

**Comment by zhi1ong** [comment]
没插入代码说明是插件加载失败了呗，产物中看看

**Comment by cyigo** [comment]
> 没插入代码说明是插件加载失败了呗，产物中看看

编译过程中也没有看到register的相关日志，最后apk里也没用自动生成register的相关代码，是不是有什么特殊的设置或者代码文档没有提到？
