### ISSUE TITLE
addFlags()无效

### ISSUE THREAD

**Issue by nazhr** [alibaba/ARouter#565]
## Look at here

public Postcard addFlags(int flags) {
        this.flags |= flags;
        return this;
    }

this.flags |= flags;
this.flags还是-1；
在addFlags()前，flags是默认值-1，在add后，值还是-1，在初始化后，值正常。

`ARouter.getInstance().build("/test/testActivity")
                   .withFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)
                   .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                   .navigation(this);`

这样使用才可以。

**Comment by zwonb** [comment]
**ARouter.getInstance().build(RoutePath.MAIN_UIA)
                            .addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)
                            .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                            .navigation()**
我这样使用也是无效，并不能关闭之前的Activity

**Comment by zhi1ong** [comment]
withFlags 是直接赋值，addFlags 是 |=

**Comment by YuanKJ-** [comment]
我也是一脸懵逼，居然addFlags无效
