### ISSUE TITLE
androidx 适配问题

### ISSUE THREAD

**Issue by ypus1987** [alibaba/ARouter#568]
**环境**
OS：Windows 10 1703
IDE：Android Studio 3.21
Java：Java 1.8

**过程**
使用最新的Android Studio新建工程，
gradle.properties配置
android.useAndroidX=true
android.enableJetifier=true
使用AndroidX替换支持包
**报错**
arouter 内使用支持包类或引用其他配置  项目不能运行

**Comment by daleiyinsi** [comment]
我也遇到这个问题了,希望早日解决

**Comment by linjian99666** [comment]
问题同上，希望能兼容 androidx

**Comment by SOMING2017** [comment]
+1，希望兼容androidX

**Comment by SOMING2017** [comment]
关于AndroidX适配问题详解：
一个载入了AndroidX的项目实测可以使用ARouter；
一开始使用一个kotlin+androidX+组件化的项目(A项目)运行ARouter，多方尝试均失败。
后来单独建立kotlin项目(B项目)尝试，发现只要使用kotlin的配置方式，即可运行。
我误以为ARouter没有androidX兼容，发表了上楼评论。
但当我将B项目转为androidX时，发现该项目亦可使用ARouter。
得出：androidX项目可使用ARouter。
/***********************以下为组件化项目使用ARouter的要点说明**************************/
但B项目的配置放到A项目时，使用失败。
经过一番尝试得出：确保ARouter正常运作需要项目产生了"ARouter$$Group$$XXX.java"注解引用文件，XXX为一级目录名，全局搜索查看。
总结以下注意点： 
1.不同module间@Route的一级目录不能一样；
2.使用到ARouter或@Route的module需在对应build.gradle添加配置；
2.“Clean Project”一定会清理ARouter注解引用文件，使用后必须"Rebuild Project"；
ps:使用java的配置方式的androidX项目能否使用ARouter未知，没测试。

**Comment by xiaojinzi123** [comment]
建议使用 [Component](https://github.com/xiaojinzi123/Component),配套的插件支持 kotlin, 库本身非常优秀.
并且支持 `Androidx`
