### ISSUE TITLE
关于DegradeService的建议

### ISSUE THREAD

**Issue by LinXiaoTao** [alibaba/ARouter#57]
你好。
DegradeService字面意思不是太明白，我是理解为类似**全局`onLost`捕获**。
我想能不能给DegradeService做单独处理，类似Interceptor一样，现在我这样去定义一个DegradeService
``` java
@Route(path = "/xxx/123")
public class GlobalDegradeService implements DegradeService {

    @Override
    public void init(Context context) {
        System.out.println("全局降级处理初始化");
    }

    @Override
    public void onLost(Context context, Postcard postcard) {
        System.out.println("全局降级处理");
    }

    public void customCall() {
        System.out.println("我是自定义调用");
    }
}
```
如果我跳转的path和GlobalDegradeService中定义的path，如果刚好一样的话，它就变成去获取一个Service，我想这样可能会让人感到困惑。如果它的定义是**全局`onLost`捕获**，那我觉得单独处理会合理点。

**Comment by zhi1ong** [comment]
这个DegradeService 就是全局降级服务啊，我还是没明白你的困惑，是因为这个服务和其他的服务一样，觉得比较奇怪么？但是这也是ARouter扩展性的表现，ARouter提供服务管理，ARouter内部实现也在使用服务管理。

**Comment by LinXiaoTao** [comment]
我的意思是，既然它是类似Interceptor一样的特殊服务，为什么不单独处理？

**Comment by zhi1ong** [comment]
ARouter里面正是不希望出现诸如 registerDegradleService、registerXXService 这种形式，才不做特殊处理的，所有的服务一视同仁，这样后续api接口不需要变动，有新功能加入的话，直接通过服务的方式与用户进行交互，保证api稳定。

**Comment by LinXiaoTao** [comment]
好的。谢谢
