### ISSUE TITLE
初始化的时候报了IncompatibleClassChangeError

### ISSUE THREAD

**Issue by GongZiZhang** [alibaba/ARouter#571]
报错log如下，主要集中在华为机型

java.lang.IncompatibleClassChangeError

Class 'android.content.ContextWrapper' does not implement interface 'java.util.Map' in call to 'java.lang.Object java.util.Map.get(java.lang.Object)' (declaration of 'com.alibaba.android.arouter.core.LogisticsCenter' appears in /data/user/0/com.junte/tinker/patch-90890cf4/dex/changed_classes.dex.jar)

**Comment by zhi1ong** [comment]
具体机型提供一下

**Comment by GongZiZhang** [comment]
![image](https://user-images.githubusercontent.com/17826038/49920017-9ffd2980-fee3-11e8-8ff2-d417ec5175a4.png)

**Comment by zhi1ong** [comment]
目前不会兼容，ARouter 查找 dex 的位置都是 Android 标准的，不会兼容非标准的修改

**Comment by zhi1ong** [comment]
你用了 register 插件了吧，build 补丁包的时候导致 LogisticsCenter 类有变化，被 tinker diff 出来了

**Comment by hehaodong** [comment]
@zhi1ong 那如果只把这个register插件剔除掉，arouter还能正常使用吗
