### ISSUE TITLE
setExtra无效

### ISSUE THREAD

**Issue by xncHung** [alibaba/ARouter#572]
在_Arouter的navigation方法中会调用LogisticsCenter的completion方法，这里会用路由表中的extra替换掉事先设置的extra，导致setExtra无效，这会导致动态切面无法实现。

**Comment by zhi1ong** [comment]
setExtra 不是直接调用的，是用来保存注解中标注的 extra 的

**Comment by gopple** [comment]
不能直接调用，那方法的修饰权限请改为私有。extras变量注释也说明了，可以拆解成31位来标记31种不同情况，但setExtra不管任何情况下都会被覆盖，不知道各位登陆拦截是如何做的，难道extra如果拿来标记登陆拦截操作，其他的拦截就无法使用extra标记了吗
