### ISSUE TITLE
A页面跳转到B页面，如何约束调用者要传递的参数？

### ISSUE THREAD

**Issue by binIoter** [alibaba/ARouter#586]
比如：A Module的A页面跳转到B Module的B页面，B页面接收2个参数，但是调用者不小心传了3个或者1个参数，这显然是B页面不希望的，如果能以某种方式在编译期预处理，调用的时候有编译器提示就好了，请问作者对这方面有什么好的实现思路吗？

**Comment by holleQiang** [comment]
你可以封装成提供服务的方式去跳页面，工具都给你了，看自己怎么用了
