### ISSUE TITLE
ARouter init logistics center 

### ISSUE THREAD

**Issue by hongxialiu** [alibaba/ARouter#588]
我把相关的issues都看了。没有具体解决的办法。看源码抛出的异常信息是这个com.alibaba.android.arouter.routes.ARouter$$Providers$$module_main但是不清楚怎么解决。请教一下。如果我直接捕获异常。感觉不太好

Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Providers$$module_main] at com.alibaba.android.arouter.core.LogisticsCenter.a(LogisticsCenter.java:208) 
at com.alibaba.android.arouter.launcher._ARouter.b(_ARouter.java:61) 
at com.alibaba.android.arouter.launcher.ARouter.a(ARouter.java:41)

**Comment by hongxialiu** [comment]
Arouter版本1.3.1   发现是LogisticsCenter里面的这个地方有问题。但是不清楚这里为什么会有问题

 ((IProviderGroup) (Class.forName(className).getConstructor().newInstance())).loadInto(Warehouse.providersIndex);

**Comment by hongxialiu** [comment]
不过有点奇怪。我们报错的这个版本。早已经把library name由module_main改成了比如test_name

**Comment by hongxialiu** [comment]
android 4.2版本必现。debug模式下，先在settting.gradle引用。安装运行正常。然后在settting.gradle里面去除该模块引用，覆盖安装点击运行。必蹦

**Comment by ashqal** [comment]
最近也碰到了问题，看了代码逻辑
在相同app versioncode下，ARouter会使用sp中缓存的值去初始化，

如果相同版本下你的module发生了改变，比如module_main改成了main，
之前的缓存的module_main就找不到了，就crash了

**Comment by woshitangebupasui** [comment]
> 最近也碰到了问题，看了代码逻辑
> 在相同app versioncode下，ARouter会使用sp中缓存的值去初始化，
> 如果相同版本下你的module发生了改变，比如module_main改成了main，
> 之前的缓存的module_main就找不到了，就crash了

可是我这边的应用更新好几个版本了还是有这个问题 @ashqal

**Comment by Dwan-xie** [comment]
同样遇到这个问题，更新版本后有部分用户会出现这个崩溃。

**Comment by cwwei2005** [comment]
我试了几个Arouter版本，都是有这个问题，在init时就抛出：
Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [No original dex files found for dex location /data/app/com.example

使用的是kotlin，androidX，API：28

**Comment by cwwei2005** [comment]
我使用kotlin、androidx，原来也报这个错误。后来看这个配置好了。https://www.jianshu.com/p/1dddb971c522

**Comment by JeckChou** [comment]
kapt {
    arguments {
        arg("moduleName", project.getName())
    }
}

**Comment by hongxialiu** [comment]
> 同样遇到这个问题，更新版本后有部分用户会出现这个崩溃。

兄弟，后面解决了吗？

**Comment by hongxialiu** [comment]
> ```
> // You can refer to the wording in the "module-kotlin" module
> apply plugin: 'kotlin-kapt'
> 
> kapt {
>     arguments {
>         arg("AROUTER_MODULE_NAME", project.getName())
>     }
> }
> 
> dependencies {
>     compile 'com.alibaba:arouter-api:x.x.x'
>     kapt 'com.alibaba:arouter-compiler:x.x.x'
>     ...
> }
> ```

module都配置了，还是有这个异常。

**Comment by keluokeda** [comment]
升级下版本号可以解决这个问题

**Comment by OldMan5119** [comment]
卸载重装app就好了
