### ISSUE TITLE
关于withObject传自定义对象，自定义类实现的SerializationService不走parseObject方法

### ISSUE THREAD

**Issue by sinkkin** [alibaba/ARouter#589]
测试了一下：
1、普通的自定义实体类实现Serializable，有空参的构造函数，可以正常传值；
2、实体类内部包含了静态内部类，如果实体类实现了Serializable，有空参的构造函数，传值时自定义实现的SerializationService的类只走了object2Json，不走parseObject方法（及json2Object方法），造成接受的为null；
3、实体类内部包含了静态内部类，如果实体类未实现Serializable，有空参的构造函数，可以正常传值；
那么第二种情况算是bug吗，求大佬告诉一下--

**Comment by xiaolei123** [comment]
解决了，详情看

https://my.oschina.net/xiaolei123/blog/3000339

**Comment by zhi1ong** [comment]
是这个问题，传递的自定义对象如过实现了 Serializable , 取出来的时候会按照 getSerializable，这块我看看兼容一下

**Comment by GongZiZhang** [comment]
这个问题在kotlin的data实体类中还是没有解决

**Comment by huayicheng2015** [comment]
> 测试了一下： 1、普通的自定义实体类实现Serializable，有空参的构造函数，可以正常传值； 2、实体类内部包含了静态内部类，如果实体类实现了Serializable，有空参的构造函数，传值时自定义实现的SerializationService的类只走了object2Json，不走parseObject方法（及json2Object方法），造成接受的为null； 3、实体类内部包含了静态内部类，如果实体类未实现Serializable，有空参的构造函数，可以正常传值； 那么第二种情况算是bug吗，求大佬告诉一下--

第3种情况不成立。

**Comment by huayicheng2015** [comment]
> 解决了，详情看
> 
> https://my.oschina.net/xiaolei123/blog/3000339

我看过你的文章，我的实体类既不是Serializable的子类，也不是Parcelable的子类，仍然没用。
