### ISSUE TITLE
可以在navigation之前判断path是否存在吗？

### ISSUE THREAD

**Issue by XiaoSeee** [alibaba/ARouter#590]
我找了一下api和源码，没发现这种方法。只能navigation之后看回调好像。
可以在navigation之前就知道吗？

我有这么个需求，好两个app，如果依赖了or没有依赖某个组件，界面上有点区别，直接不显示跳转的按钮。
我目前是靠提前在每个app module的xml里面定义好是否加载。
但是我想如果在代码里面自动判断，不用配置可以更智能点~

**Comment by zhi1ong** [comment]
completion

**Comment by yushilong** [comment]
> completion

你好，这是什么东东呢？？

**Comment by zhi1ong** [comment]
@yushilong 调用 completion 方法，补全失败则说明没这个 path

**Comment by yushilong** [comment]
> @yushilong 调用 completion 方法，补全失败则说明没这个 path

你好，需要补全哪些参数呢？RouteMeta这个需要补全吗？

**Comment by XiaoSeee** [comment]
我写了个方法你参考下：

```java
    public boolean checkPath(String path) {
        String group = path.substring(1, path.indexOf("/", 1));
        try {
            LogisticsCenter.completion(new Postcard(path, group));
        } catch (NoRouteFoundException e) {
            return false;
        }
        return true;
    }
```

**Comment by yushilong** [comment]
> 我写了个方法你参考下：
> 
> ```java
>     public boolean checkPath(String path) {
>         try {
>             String group = path.substring(1, path.indexOf("/", 1));
>             LogisticsCenter.completion(new Postcard(path, group));
>         } catch (Exception e) {
>             return false;
>         }
>         return true;
>     }
> ```

我这样试了不行呢，我是直接写死的path和group

**Comment by yushilong** [comment]
> 我写了个方法你参考下：
> 
> ```java
>     public boolean checkPath(String path) {
>         try {
>             String group = path.substring(1, path.indexOf("/", 1));
>             LogisticsCenter.completion(new Postcard(path, group));
>         } catch (Exception e) {
>             return false;
>         }
>         return true;
>     }
> ```

OK了，是我参数设置错了，应该设置path，我设置成了uri了
