### ISSUE TITLE
组件化开发过程中，每个组件可以作为一个app运行在手机上，ARouter的service不能做到多个组件（apk）间的通讯呀？？？

### ISSUE THREAD

**Issue by nianzixin** [alibaba/ARouter#591]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by hanshengjian** [comment]
我也考虑过这个问题，Arouter没有多进程通信的功能。多进程的通讯，主要是主app和子app之间共享数据，那么采用aidl或者contentprovider

**Comment by hanshengjian** [comment]
> 现在我应用内都不行，真搞不懂这个IProvider，就跳转Activity可以

看下你的定义和使用IProvider的代码

**Comment by Android500** [comment]
> > 现在我应用内都不行，真搞不懂这个IProvider，就跳转Activity可以
> 
> 看下你的定义和使用IProvider的代码

原因就是Autowired在Activity不能用

**Comment by zhi1ong** [comment]
@Android500  Autowired 会找生成的注入辅助类，当前类名+xxxxx，baseActivity 不行，这种场景应该不多，跳转到每个页面都会传的参数
