### ISSUE TITLE
无法获取到有构造参数的Fragment

### ISSUE THREAD

**Issue by SpringSmell** [alibaba/ARouter#592]
`@SuppressLint("ValidFragment")
@Route(path = "/child2/TestFragment")
class TestFragment(var arg: String) : Fragment() {

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return super.onCreateView(inflater, container, savedInstanceState)
    }
}`
此Fragment需要传递一个参数，不知道有没有提供这种方法。

现在目前只有将Fragment添加一个默认参数
`var arg: String=“”`

**Comment by autofocus** [comment]
一般框架都是调用Fragment的无参构造方法来实例化对象的。坦白来说，通过构造方法为Fragment传递参数很不优雅，在Fragment restore的时候就会丢失参数。一般推荐通过将参数设置到Bundle里面，然后调用fragment.setArguments方法传递参数，这样可以保证系统恢复Fragment是还能拿到传入的参数。
