### ISSUE TITLE
demo运行报错 Gradle sync failed: Could not get unknown property 'intellijPublishUsername' for task ':arouter-idea-plugin:publishPlugin' of type org.jetbrains.intellij.tasks.PublishTask.

### ISSUE THREAD

**Issue by wenlai521** [alibaba/ARouter#595]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by zhi1ong** [comment]
这是上传 as 插件的 gradle task，不要执行这个 task

**Comment by lianchengtong** [comment]
how do you resolve the issue, i have meet the same problem .

**Comment by REBOOTERS** [comment]
`

include ':app'
include ':arouter-api'
include ':arouter-compiler'
include ':arouter-annotation'
include ':module-java'
include ':module-kotlin'
include ':arouter-gradle-plugin'
//include ':arouter-idea-plugin'

`

just comment arouter-idea-plugin in settings.gradle
