### ISSUE TITLE
Can't recieve param automatically in Test3Activity~

### ISSUE THREAD

**Issue by wenzhihao123** [alibaba/ARouter#597]
## Test3Activity can't recieve param automatically，which opened by h5~
Test3Activity's OnCreate method don't have this code 'ARouter.getInstance().inject(this); '，it can't recieve the param from h5，when i add 'ARouter.getInstance().inject(this); ' in code , it worked , but it it's not automatical inject?

**Comment by zhi1ong** [comment]
嗯，修复了，demo 落下了那行 inject
