### ISSUE TITLE
Navigation to the route with a requestCode失效

### ISSUE THREAD

**Issue by wenjiahui** [alibaba/ARouter#6]
使用navigation(Activity mContext, int requestCode)，如果不设置flag，还没显示目标UI就回调onActivityResult()，目标UI 调用setResult(RESULT_OK, data)也不起作用。

**Comment by zhi1ong** [comment]
存在逻辑问题，没有设置Flag的话，默认会设置成"FLAG_ACTIVITY_NEW_TASK", 所以forResult会立刻返回，这块本来是为了防止不传入Activity context的，我改一下

**Comment by zhi1ong** [comment]
@wenjiahui  请更新 api 1.0.3
