### ISSUE TITLE
是不是不支持在android studio2.3下使用InstantRun。ARouter 使用的是最新的。

### ISSUE THREAD

**Issue by xie123** [alibaba/ARouter#60]
如题，关闭了InstantRun程序能正常启动，开启了InstantRun就启动不了.
但是我看你们的介绍说是能使用InstantRun。
我用的是模拟器7.1的。

**Comment by songzhw** [comment]
我是在Android2.3下， 开启不开启InstanceRun都启动不了。 （我用的手机，不是模拟器）
后来改annotationProcessor为apt， 这才启动成功。 希望这对你有帮助

**Comment by xie123** [comment]
改annotationProcessor为apt？那意思是gradle的版本使用的是<2.2吗？我使用的是2.3的版本

**Comment by songzhw** [comment]
我用的是AS 2.3, 但使用annotationProcessor仍不能跳转， 出toast说 no such router。 改为apt后就好了

**Comment by zhi1ong** [comment]
1. Instant Run是支持的，需要注意的是，如果开启了InstantRun，要在调用init**之前**调用openDebug，这么做是为了保证线上安全

2. annotationProcessor 最好不要和apt混用，如果有其他的sdk用了apt，要都用apt，要么都改成annotationProcessor,区别就是一个是三方开发者写的，一个是google写的，功能类似。

**Comment by xie123** [comment]
确实，我在把openDebug在初始化之前调用就可以了。谢谢了。不过这点在文档中确实没有明确写道。

**Comment by zhi1ong** [comment]
三.3 中明确提到了这部分的哦
