### ISSUE TITLE
@Autowired(required = true)

### ISSUE THREAD

**Issue by protectedMan** [alibaba/ARouter#602]
required的true orfalse到底有什么区别，我尝试设置@Autowired(required = true)
根据注释，null的时候是会触发crash的
![image](https://user-images.githubusercontent.com/17565737/51420315-07d21e80-1bcc-11e9-9227-82225e162fa6.png)
但为null时正常运行，我也尝试了required=false，没有发现有什么区别
![image](https://user-images.githubusercontent.com/17565737/51420384-9050bf00-1bcc-11e9-8b2a-ba123f0c1ef9.png)

**Comment by zhi1ong** [comment]
这块需要确认一下，可能这部分逻辑去掉了 or 被后面加功能 catch 住了
