### ISSUE TITLE
过滤指定的拦截器

### ISSUE THREAD

**Issue by yinzhengwei** [alibaba/ARouter#603]
目前ARouter中有greenChannel()方法过滤掉全部的拦截器，如果遇到在一些界面和场景需要过滤掉制定的某几个拦截器的需求时，现有的做法是在指定的那几个拦截器里挨个判断，似乎有些不太方便，望大佬们能将这个需求完善一下。

**Comment by zhi1ong** [comment]
在注解上加 extras，在拦截器中按照一定规则排除
