### ISSUE TITLE
能否增加一个ParseService？

### ISSUE THREAD

**Issue by liulinjie1990823** [alibaba/ARouter#604]
有这样一个需求，app中有很多页面是通过接口中的内页规则配置的，如app://shop/detail?a=11&b=111,解析的时候把里面所有的字段都解析成string类型通过Bundle传递到activity;但activity都是定义的不同类型的来接收，比如int,long;能不能提供一个自定义的ParseService,回调activity中定义的类型参数，然后在ParseService中通过类型判断，将string转成对应类型的值（可以在@Autowired中加入一个字段判断是否需要强转）？现在的SerializationService相当于类似的功能，但只是判断了Object的类型。

**Comment by zhi1ong** [comment]
基本类型也有判断
