### ISSUE TITLE
Autowired 注入服务能在BaseActivity使用嘛？

### ISSUE THREAD

**Issue by Android500** [alibaba/ARouter#605]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by Android500** [comment]
亲测不能，害我玩了两天，坑

**Comment by Android500** [comment]
已重伤，作者难道没用Dagger？人家怎么做的，干嘛不借鉴一下

**Comment by zhi1ong** [comment]
没看明白问题是什么，是说 inject(this) 写在 baseactivity 的 onCreate 中么

**Comment by chris-jason1224** [comment]
> 亲测不能，害我玩了两天，坑

是可以在基类中注入的，如果Autowired注入和主动查找都找不到服务，就不是inject的问题了
