### ISSUE TITLE
组件单独编译时，其他组件的Service注入问题

### ISSUE THREAD

**Issue by Android500** [alibaba/ARouter#606]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by holleQiang** [comment]
为空的时候，你抛一个异常不就好看了
![image](https://user-images.githubusercontent.com/7207975/51784510-a0484000-2184-11e9-889b-d9da18e40576.png)
