### ISSUE TITLE
kotlin和java代码混合使用的时候，build.gradle文件里面arouter-complier该使用anntationProcessor还是kapt, 

### ISSUE THREAD

**Issue by 562218352** [alibaba/ARouter#609]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by Android500** [comment]
只要存在一个kotlin文件就得按照kotlin的gradle配置来，
