### ISSUE TITLE
Arouter如何构建PendingIntent

### ISSUE THREAD

**Issue by zhaoshuiruoli** [alibaba/ARouter#611]
PendingIntent中需要传入一个Intent，如果是处于两个模块的页面，如何传递呢？写类名.class的话两个模块又耦合了吧？

**Comment by Android500** [comment]
不行，我是用Service调用组件创建Intent

**Comment by zhaoshuiruoli** [comment]
> 不行，我是用Service调用组件创建Intent

在Service中创建Intent的时候，Intent也是要传入类名的，这时候不还是耦合吗？

**Comment by LinXueyuanStdio** [comment]
我用中转Activity曲线救国，构建中转Activity的PendingIntent，传路径给中转Activity，打开中转Activity后它再根据路径跳转到想要的路径
