### ISSUE TITLE
ARouter.init耗时过长

### ISSUE THREAD

**Issue by Android500** [alibaba/ARouter#612]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

这个效率让我情以何堪？？？？？？？
![image](https://user-images.githubusercontent.com/15179354/52042094-3f9b7780-2577-11e9-8284-3e3ddc1bb592.png)
![image](https://user-images.githubusercontent.com/15179354/52042107-47f3b280-2577-11e9-8478-bf3b6504ba88.png)

**Comment by Android500** [comment]
这里不打算优化嘛

**Comment by Android500** [comment]
加了arouter-register完全没区别的好么，一样的耗时

**Comment by Android500** [comment]
机型MI 4LTE，Android系统6.0，这个机子不算老也不算太差吧

**Comment by zhi1ong** [comment]
1. 加了 arouter-register 不可能没区别，除非你只是依赖了，没声明使用插件
2. 首次安装 App 或者升级 App 后首次启动会有一定的耗时，但不会太久
3. 默认的 dex 扫描会缓存扫描结果，这里面有很多优化逻辑

**Comment by yangpeiyong** [comment]
怎么声明使用插件？
> 1. 加了 arouter-register 不可能没区别，除非你只是依赖了，没声明使用插件
> 2. 首次安装 App 或者升级 App 后首次启动会有一定的耗时，但不会太久
> 3. 默认的 dex 扫描会缓存扫描结果，这里面有很多优化逻辑

**Comment by yangpeiyong** [comment]
怎么声明使用插件？官方文档只写了加了一个claspath
`classpath "com.alibaba:arouter-register:1.0.2"`
这样就可以了吗？
 
> > 1. 加了 arouter-register 不可能没区别，除非你只是依赖了，没声明使用插件
> > 2. 首次安装 App 或者升级 App 后首次启动会有一定的耗时，但不会太久
> > 3. 默认的 dex 扫描会缓存扫描结果，这里面有很多优化逻辑
