### ISSUE TITLE
release Fragment 参数

### ISSUE THREAD

**Issue by zhongxiong00** [alibaba/ARouter#617]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by njhuangzf** [comment]
添加混淆规则
-keepclasseswithmembers class * {
    @com.alibaba.android.arouter.facade.annotation.Autowired <fields>;
}

解决release Fragment 参数取不到值

**Comment by zhongxiong00** [comment]
> 添加混淆规则
> -keepclasseswithmembers class * {
> @com.alibaba.android.arouter.facade.annotation.Autowired ;
> }
> 
> 解决release Fragment 参数取不到值

我在@Autowired 注解里面写了name=""  应该不是这个原因

**Comment by campusboy** [comment]
> 添加混淆规则
> -keepclasseswithmembers class * {
> @com.alibaba.android.arouter.facade.annotation.Autowired ;
> }
> 
> 解决release Fragment 参数取不到值

#### 写法需要纠正一下

-keepclasseswithmembers class * {
    @com.alibaba.android.arouter.facade.annotation.Autowired <fields>;
}

**Comment by campusboy** [comment]
> -keepclasseswithmembers class * {
    @com.alibaba.android.arouter.facade.annotation.Autowired <fields>;
}

**Comment by campusboy** [comment]
-keepclasseswithmembers class * {
    *** @com.alibaba.android.arouter.facade.annotation.Autowired <fields>; ***
}

**Comment by campusboy** [comment]
> 添加混淆规则
> -keepclasseswithmembers class * {
> @com.alibaba.android.arouter.facade.annotation.Autowired ;
> }
> 
> 解决release Fragment 参数取不到值

#### 补充

中间一行 Autowired和后面的分号中间还有一个  **<fields>**，评论中应该是写了，但没有显示出来。

**Comment by campusboy** [comment]
> > 添加混淆规则
> > -keepclasseswithmembers class * {
> > @com.alibaba.android.arouter.facade.annotation.Autowired ;
> > }
> > 解决release Fragment 参数取不到值
> 
> 我在@Autowired 注解里面写了name="" 应该不是这个原因

#### 补充一下写法：评论应该是写了的，但是markdown语法不对，没显示出来。

-keepclasseswithmembers class * {
    @com.alibaba.android.arouter.facade.annotation.Autowired &lt;fields&gt;;
}

**Comment by campusboy** [comment]
> 添加混淆规则
> -keepclasseswithmembers class * {
> @com.alibaba.android.arouter.facade.annotation.Autowired ;
> }
> 
> 解决release Fragment 参数取不到值

补充一下写法：评论应该是写了的，但是markdown语法不对，没显示出来。
-keepclasseswithmembers class * {
@com.alibaba.android.arouter.facade.annotation.Autowired &lt;fields&gt;;
}
