### ISSUE TITLE
ARouter::ARouter init logistics center exception导致初始化失败

### ISSUE THREAD

**Issue by Dwan-xie** [alibaba/ARouter#618]
初始化时单进程加载，没有在其他进程调用路由，并且次问题也不是必现，部分用户会出现crash。
线上用户覆盖安装会出现以下log：
java.lang.ClassNotFoundException: com.alibaba.android.arouter.routes.ARouter$$Root$$meitun_lib
java.lang.Class.classForName(Native Method)
java.lang.Class.forName(Class.java:309)
java.lang.Class.forName(Class.java:273)
com.alibaba.android.arouter.core.LogisticsCenter.init(LogisticsCenter.java:94) com.alibaba.android.arouter.launcher._ARouter.init(_ARouter.java:61)
com.alibaba.android.arouter.launcher.ARouter.init(ARouter.java:41) com.xxx.xxx.xxx.xxxxxApplication.onCreate(xxxxxApplication.java:125)
s.h.e.l.l.S.onCreate(Unknown Source)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017) android.app.ActivityThread.handleBindApplication(ActivityThread.java:5084)
android.app.ActivityThread.access$1700(ActivityThread.java:197)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
android.os.Handler.dispatchMessage(Handler.java:111)
android.os.Looper.loop(Looper.java:224)
android.app.ActivityThread.main(ActivityThread.java:5958)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113) com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alibaba.android.arouter.routes.ARouter$$Root$$meitun_lib" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.xxx.xxx.xxx-2/base.apk", dex file "null", dex file "null", dex file "null", dex file "null", dex file "null", dex file "null", dex file "null", dex file "null"],nativeLibraryDirectories=[/data/app/com.xxx.xxx.xxx-2/lib/arm, /vendor/lib, /system/lib]]
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass(ClassLoader.java:511)
java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 19 more
Suppressed: java.lang.ClassNotFoundException: com.alibaba.android.arouter.routes.ARouter$$Root$$meitun_lib
java.lang.Class.classForName(Native Method)
java.lang.BootClassLoader.findClass(ClassLoader.java:781)
java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 20 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by fantasybei** [comment]
也有类似的问题： RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.alibaba.android.arouter.routes.ARouter$$Providers$$debug

**Comment by zhi1ong** [comment]
看起来是缓存了这个文件名，但是实际上这个路由表已经不存在了，正常升级版本的时候，会清除缓存，怀疑是你调试的时候没有升级版本号，覆盖安装导致缓存没有清空

**Comment by zhi1ong** [comment]
@fantasybei 用了类似于动态部署一样的方案吧，不能不改版本号的前提的下，就删除某个路由表

**Comment by fantasybei** [comment]
> @fantasybei 用了类似于动态部署一样的方案吧，不能不改版本号的前提的下，就删除某个路由表

是的，用了Replugin，调试后发现是宿主里也用了这个，ARouter$$Providers$$debug应该是宿主生成的。后来用com.alibaba:arouter-register就好了，但是不知道为啥。

**Comment by Dwan-xie** [comment]
log就是正常用户升级新版本后出现的，并不是同版本覆盖安装导致的。并且没有使用动态部署方案。

**Comment by Dwan-xie** [comment]
@zhi1ong

**Comment by forJrking** [comment]
@zhi1ong  问题有解决嘛同样的问题。根据代码看这样可以刷新映射表 但是比较耗时。
```
try {
            if (sDebug) {
                ARouter.openLog();
                ARouter.openDebug();
                ARouter.printStackTrace();
            }
            ARouter.init(app);
        } catch (Exception e) {
            e.printStackTrace();
            //异常后建议清除映射表官方文档说 开发模式会清除
            ARouter.openDebug();
            ARouter.init(app);
        }
```
