### ISSUE TITLE
使用了ARouter的商用app大佬可以进来打个卡么

### ISSUE THREAD

**Issue by newbeginningxzm** [alibaba/ARouter#621]
使用了ARouter的商用app大佬可以打个卡么？

**Comment by liangxiwei** [comment]
我们最近在用，里面代码我都很熟了，有问题我随时可以改

**Comment by rhshen** [comment]
我们在做选型，想找一个使用ARouter的App做参考。大佬的应用有名称吗？

**Comment by rhshen** [comment]
> 我们最近在用，里面代码我都很熟了，有问题我随时可以改

我们在做选型，想找一个使用ARouter的App做参考。大佬的应用有名称吗？

**Comment by macarthor** [comment]
你们选型的具体考虑是什么呢，参考其它app什么呢？又不能分享代码，界面上也看不出arouter的使用来。。。

**Comment by rhshen** [comment]
> 你们选型的具体考虑是什么呢，参考其它app什么呢？又不能分享代码，界面上也看不出arouter的使用来。。。

ARouter、WMRouter、DDComponent被哪些商用APP使用。作为一个参考维度。

**Comment by macarthor** [comment]
三方库一般按star数和active status来选吧，好像是arouter占优。
不过也需要看你们有没有它不能做而其它库可以做的需求

**Comment by rhshen** [comment]
> 三方库一般按star数和active status来选吧，好像是arouter占优。
> 不过也需要看你们有没有它不能做而其它库可以做的需求
> 还有看看issues有没有没有解决的坑

你说的这个也是维度之一，但是领导要看商用的app，我们也没办法，反编译了很多热门应用，都没看到ARouter。大佬，你知道有哪些商用APP用了吗？T-T

**Comment by cheeryChenX** [comment]
- 斗牛
- 捉妖
- 虾米
- <学习强国>好像也有

**Comment by newbeginningxzm** [comment]
> * 斗牛
> * 捉妖
> * 虾米
> * <学习强国>好像也有

谢谢大佬！踏破铁鞋无觅处！

**Comment by macarthor** [comment]
> > 三方库一般按star数和active status来选吧，好像是arouter占优。
> > 不过也需要看你们有没有它不能做而其它库可以做的需求
> > 还有看看issues有没有没有解决的坑
> 
> 你说的这个也是维度之一，但是领导要看商用的app，我们也没办法，反编译了很多热门应用，都没看到ARouter。大佬，你知道有哪些商用APP用了吗？T-T

此时要说服领导，又不是UI库，看毛商用app，能看出个P来。。。

**Comment by rhshen** [comment]
> > > 三方库一般按star数和active status来选吧，好像是arouter占优。
> > > 不过也需要看你们有没有它不能做而其它库可以做的需求
> > > 还有看看issues有没有没有解决的坑
> > 
> > 
> > 你说的这个也是维度之一，但是领导要看商用的app，我们也没办法，反编译了很多热门应用，都没看到ARouter。大佬，你知道有哪些商用APP用了吗？T-T
> 
> 此时要说服领导，又不是UI库，看毛商用app，能看出个P来。。。

领导没看到有人用，不放心，觉得方案也许会有问题。哎。不过谢谢你了

**Comment by liangxiwei** [comment]
其实用不用也没啥大问题，每个module分一个export的module出来，比如A和A_export,后者依赖前者，前者不能被别人调用，仅仅A_export的东西可以被其他模块调用就行了。。。

**Comment by macarthor** [comment]
> 其实用不用也没啥大问题，每个module分一个export的module出来，比如A和A_export,后者依赖前者，前者不能被别人调用，仅仅A_export的东西可以被其他模块调用就行了。。。

是前者依赖后者吧

**Comment by liangxiwei** [comment]
> > 其实用不用也没啥大问题，每个module分一个export的module出来，比如A和A_export,后者依赖前者，前者不能被别人调用，仅仅A_export的东西可以被其他模块调用就行了。。。
> 
> 是前者依赖后者吧

我最开始也是直觉认为前者依赖后者，但实际确实是后者依赖前者
