### ISSUE TITLE
不支持多library同样组

### ISSUE THREAD

**Issue by liulongzhenhai** [alibaba/ARouter#624]
app下有两个library  lib1和lib2
lib1下有activity的router /lib/cancelActivity
lib2下有activity的router /lib/detailActivity
在这样的配置下，启动不了lib2下的activity,会报
ARouter::There is no route match the path [/lib/detailActivity], in group [lib][ ]   (有可能会是报lib1的启动不了)
如果把lib2下的改为/lib2/detailActivity则不会有问题

我看了源码似乎是会覆盖删除已注册的lib组

arouter-api:1.4.1
arouter-compiler:1.2.2

**Comment by zhi1ong** [comment]
符合预期
