### ISSUE TITLE
通用链接搭配ARouter怎么使用呢

### ISSUE THREAD

**Issue by caprice** [alibaba/ARouter#625]
项目想使用app link, 就需要在某个activity中这样配置：

<activity ...>

    <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="http" android:host="www.example.com" />
        <data android:scheme="https" />
    </intent-filter>

</activity>

如果使用Arouter,就产生两个问题：

这个配置在哪个activity下面。SchemaActivity?如果是SchemaActivity下面会有http schema和自定义的schema比如example://
我怎么区分http://www.example.com/redirect/searchPage?name=test(这个最终打开app 全局搜索activity)和http://www.example.com/web/asset/index.html#!/user/detail（打开app WebviewActivity然后打开这个html地址）呢？

**Comment by liangxiwei** [comment]
你路由用其他scheme就行，各自用各自的

**Comment by caprice** [comment]
如果你深入了解过app link,三端通过统一的地址打开相应的页面就会明白我在说什么了

**Comment by macarthor** [comment]
板凳瓜子。。。

**Comment by zhi1ong** [comment]
不耽误啊，就写在 SchemeActivity 呗，自己提取出 path 交给 ARouter 处理
