### ISSUE TITLE
小米mix3 腾讯加固以后 调用ARouter.init 报there's no route matched path=[/arouter/service/interceptor]

### ISSUE THREAD

**Issue by jianshengli** [alibaba/ARouter#626]
小米mix3 腾讯加固以后 调用ARouter.init 报there's no route matched path=[/arouter/service/interceptor]

**Comment by jianshengli** [comment]
@casparant @zhuzhaoyuan @JacksonTian @dannoy  https://wine-1258124931.cos.ap-chongqing.myqcloud.com/bug/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190314113002.jpg

**Comment by suncunx** [comment]
请问这个问题解决了么

**Comment by zhi1ong** [comment]
这是框架本身的路由找不到了，和加固有关系，应该让加固厂家去兼容一下
