### ISSUE TITLE
ARouter Helper 无法跳转问题

### ISSUE THREAD

**Issue by xchengDroid** [alibaba/ARouter#627]
如题 一直报	Road Sign: No destination found or unsupported type.
![image](https://user-images.githubusercontent.com/29690403/54330267-04996300-4650-11e9-99b2-0ebcdcb7269d.png)

**Comment by xchengDroid** [comment]
运行能跳转 ，点侧边栏的快捷按钮无法跳转

**Comment by AttITuder** [comment]
+1

**Comment by zhi1ong** [comment]
和变量有关系，直接 build("xxx") 试试

**Comment by louiewh** [comment]
+1

**Comment by QiaoYang0923** [comment]
插件关一下,在开一下就行了
