### ISSUE TITLE
多模块下，可以把每个模块的内容放到模块内而不下沉到base module吗

### ISSUE THREAD

**Issue by macarthor** [alibaba/ARouter#629]
用arouter实现多模块，跳转的path需要定义在base模块中，传递的参数类、参数字段名（withXxx方法的key）这些都需要定义在base模块中，也就是其实业务模块的内容放到了base模块中，使得业务模块其实不是那么的内聚

有没有方法使得每个模块的内容都定义在自己内部，而用arouter实现的base模块只负责实现dispatch逻辑？

我自己想了一下，好像是不可能，因为path、参数这些的内容对于arouter是属于非结构化的数据，没法统一处理

不过不知道我的想法是不是对？有没有方法实现我第二段提到的内容？

**Comment by macarthor** [comment]
即使是把类转为json传送，是解决了类定义的位置的问题，但是发起跳转的地方还是需要知道Json的结构，这样还是说两个模块在逻辑上有耦合，并没有根本解决问题

我想这还是因为传递参数是属于非结构化数据的问题，不知道对不对

**Comment by xchengDroid** [comment]
可以在被调用的组件自定义Service, 添加方法比如getData(String path)之类返回指定的bundle,肯定是需要某个参数是实现指定的！至少需要一个

**Comment by macarthor** [comment]
> 可以在被调用的组件自定义Service, 添加方法比如getData(String path)之类返回指定的bundle,肯定是需要某个参数是实现指定的！至少需要一个

@xchengDroid 能举个栗子么，没太明白你的意思，谢谢

**Comment by xchengDroid** [comment]
1、比如调到A模块的登录，在base模块中添加服务接口
`
public interface NavService extends IProvider {

    void toLoginView(String name, String password);

}`
2、然后在A模块中实现
`
public class NavServiceImpl implements NavService {

    @Override
    public void toLoginView(String loginName, String password) {
        ARouter.getInstance().build("/xx/xx")
                .withString("loginName", loginName)
                .withString("password", password)
                .navigation();

    }

    @Override
    public void init(Context context) {

    }
}`
3、在你需要调用的模块中
` NavService navService = ARouter.getInstance().navigation(NavService.class);
        navService.toLoginView("xiaoming", "123456");`

这样的话可读性就很高了，具体的toLoginView方法怎么写可以约定！怎么通用怎么来。

**Comment by macarthor** [comment]
@xchengDroid 这个也是我想的方式。不过这个方式还是把module A的内容下沉到了base module。有没有方式可以实现：base module完全不用知道module A/B/C/D的内容呢

**Comment by xchengDroid** [comment]
@macarthor 完全不知道怎么可能 ，怎么调用呢？你要调用某个方法某个功能，至少要知道类名和方法名吧。就像你Bundle里面传数据还要知道之前的key是什么！

**Comment by macarthor** [comment]
@xchengDroid 我的意思是，有没有可能使base module只作为一个逻辑控制者，而不参与具体的跳转，包括去哪个界面，传什么参数

如果你了解retrofit的call adapter的设计方式，就更容易明白我的意思了。在retrofit里，有一个CallAdapterFactory接口，其get()方法返回了一个CallAdapter类，它的adapt()方法具体去做一件事。而retrofit的core logic则是，遍历存储CallAdapterFactory的list，根据某些条件筛选出一个CallAdapterFactory，然后用其get()方法得到CallAdapter实例，再调用其adapt()方法。这样一来，retrofit core就是一个逻辑调度者，而不必关心每个call adapter怎么实现和干了什么

**Comment by xchengDroid** [comment]
@macarthor 适配器模式 首先适配需要有条件，根据什么条件筛选适配器。你的条件怎么传如呢 。retrofit的适配是根据api的返回值，你需要先知道这个返回值类型对吧！这个类型如果在你不依赖的moudle中，你怎么使用呢？
`@Override public @Nullable CallAdapter<?, ?> get(
      Type returnType, Annotation[] annotations, Retrofit retrofit) {
    if (getRawType(returnType) != Call.class) {
      return null;
    }
    final Type responseType = Utils.getCallResponseType(returnType);
    return new CallAdapter<Object, Call<?>>() {
      @Override public Type responseType() {
        return responseType;
      }

      @Override public Call<Object> adapt(Call<Object> call) {
        return new ExecutorCallbackCall<>(callbackExecutor, call);
      }
    };
  }`

**Comment by xchengDroid** [comment]
@macarthor Arouter 可以设置生成路由映射文档 ，你可以根据文档来 ，还是比较清晰的
![image](https://user-images.githubusercontent.com/29690403/54514594-857c9580-4995-11e9-9d26-18f00b62cc21.png)

**Comment by macarthor** [comment]
@xchengDroid 现在咱俩开始说到一起了 :-)

像retrofit call adapter factory的get()方法，它的参数对于每一个需要处理的method定义，都是固定的

```java
public abstract @Nullable CallAdapter<?, ?> get(Type returnType, Annotation[] annotations, Retrofit retrofit);
```

不过好像对于我要抽象的`navigation`这个概念来说，我理解是没法抽象出固定的参数表的，因为每个`navigation`所需的参数都不同，属于是非结构化数据。

所以我的问题（也是最初post里的问题）就是，有没有方法可以把`navigation`进行抽象，得到固定的参数表，从而使base module可以更加抽象而不会知道各个module的内容（path定义，参数类定义）？用string json貌似不通用，因为除了UI navigation，还有`IProvider`的实现类的实例获取，它的参数不要求像parcelable和serializable一样可以json化。

**Comment by xchengDroid** [comment]
@macarthor 你这么说我觉得你要自己写编译时注解处理器，生成对应的启动代码，就像 @Route @Autowired 生成的类一样！自动生成navigation方法，参数即为你要传的任意类型！

**Comment by xchengDroid** [comment]
我自己没写过不知道这样生成的代码当前模块是否能访问到，这是个问题

**Comment by macarthor** [comment]
@xchengDroid 我也想过自己写annotation processor，不过太麻烦了，没往这个方向深想，哈哈。不知道还有没有其它方法

**Comment by asmh1989** [comment]
@macarthor  可以看看[CC框架](https://github.com/luckybilly/CC),  做到模块间彻底解耦, 其实就是使用json字符串传递, 类似http 接口的样式, 模块间根据接口文档交流, 不需要额外主动import类

**Comment by macarthor** [comment]
@asmh1989 想过这个String json的方式，不过字段多的话会比较崩溃。。。

不过在公司项目里倒是一个方法，毕竟不会发布到github要适配很多情况，考虑公司业务就好了

**Comment by liangxiwei** [comment]
我们这边是每个模块提供一个export目录专门给给其他模块调用，里面包了路由表地址，所以调用方是无需只要路由地址之类的，提供的方法里面要不要带参数根据实际情况来定

**Comment by macarthor** [comment]
@liangxiwei 可以举个栗子么，谢谢

**Comment by titanseason** [comment]
@xchengDroid IProvider本身直接提供一个方法，`Object call(String methodName, String jsonParams)`, 这样的话，就不必先继承IProvider，然后再写实现。只要约定好 methodName 和 参数 即可

**Comment by liulinjie1990823** [comment]
> @xchengDroid 我的意思是，有没有可能使base module只作为一个逻辑控制者，而不参与具体的跳转，包括去哪个界面，传什么参数
> 
> 如果你了解retrofit的call adapter的设计方式，就更容易明白我的意思了。在retrofit里，有一个CallAdapterFactory接口，其get()方法返回了一个CallAdapter类，它的adapt()方法具体去做一件事。而retrofit的core logic则是，遍历存储CallAdapterFactory的list，根据某些条件筛选出一个CallAdapterFactory，然后用其get()方法得到CallAdapter实例，再调用其adapt()方法。这样一来，retrofit core就是一个逻辑调度者，而不必关心每个call adapter怎么实现和干了什么
> 
> 有没有可能这样实现基于arouter的base module：
> 
> * 每个模块注册其factory，表明自己提供什么跳转，参数是什么
> * 需要跳转时，发起者把跳转条件告知base module，而base则根据这个条件来筛选factory，从而选择合适的跳转地点返回给发起者，由其调用
> * 这样，base module就不用知道每个跳转的具体逻辑了，比如不用在base中定义path和参数类，而这些都可以定义在各个module中，使得它们更加内聚

path和参数本来就可以定义在自己的module中把，没说必须放在base中；至于一些对象就用json传输，框架中本来就支持参数的序列化和反序列化来传参。对于module中自定义方法调用，目前是只能用反射获取对应的对象，然后通过下沉的接口调用对应方法，这样避免了调用每个方法的时候使用反射；如果你不想下沉，直接用反射初始化对象，反射调用方法。或者你可以用apt把module中需要提供给外部使用的方法封装callback，用一个key来索引，组装到一个全局的静态map中（也可以分散到每个module的map中，节省内存），每次调用对应的方法都用key来获取对应的callback，这样不需要使用实现IProvider而下沉接口。但是获取其他module中某个类中的map对象，还是要用反射调用的。
![image](https://user-images.githubusercontent.com/8141393/60508670-adea8e80-9cfd-11e9-86c6-e2b39d3ec720.png)

**Comment by zgq105** [comment]
我认为可以业务组件分为API层和实现层，比如，模块A就分为moduleA  API+moduleA impl，模块B就分为moduleB  API+moduleB impl，这样如果模块B需要访问模块A的内容，只需要引用moduleA  API即可，就不需要下沉到base module中，做到模块内的高内聚。这里moduleA  API、moduleA impl，moduleB  API、moduleB impl层级上都是同一级别的。

**Comment by zhi1ong** [comment]
这块设计上和 @zgq105 说的比较接近了，每个业务模块应该提供一个  xxx-export 或者 xxx-service 的二方包，里面包含外部调用用到的方法和实体、接口等等。外部调用的时候，并不需要直接依赖你的实现。

**Comment by TheMelody** [comment]
可以在你的base_module里面新建一个ARouterUtils，代码如下：


```kotlin
object ARouterUtils {

    fun build(path:String): Postcard {
        return ARouter.getInstance().build(path)
    }

    fun build(uri: Uri): Postcard {
        return ARouter.getInstance().build(uri)
    }
}
```

这样的话可以了，**不用**每个module都要依赖了，别的module里面直接使用：
```kotlin
ARouterUtils.build("xxxxxx").navigation()
```
