### ISSUE TITLE
不产生注解类

### ISSUE THREAD

**Issue by HDHunter** [alibaba/ARouter#63]
## Look at here

集成到自己的项目中，修改了包路径，也在Const中修改。annotationProcessor等也引入了，apt:1.8也引入了。可以怎么编译运行，虽然不报错。但是也不在build中产生类文件。

**Comment by zhi1ong** [comment]
你是修改了源码使用的么？还是直接使用的sdk呢，建议直接使用sdk，按照接入方式排查。
