### ISSUE TITLE
对于ARouter一些改进的建议

### ISSUE THREAD

**Issue by LukeXeon** [alibaba/ARouter#630]
1.ARouter生成的.java文件中的类最好对开发者来说是不可见的，如果使用package private,就可以避免开发者在不小心的时候访问到这些类型，而且修改成package private之后也不会影响扫描Dex。

2.ARouter可以实用ContentProvider进行自动初始化，在lib的manifest中注册provider：

        <provider
            android:authorities="${applicationId}.arouter-initializer"
            android:multiprocess="true"
            android:name="com.alibaba.android.arouter.ARouterInitializer"
            android:exported="false"/>

可以在ContentProvider#onCreate方法中，来初始化ARouter。

onCreate()
{
       ARouter.init(getContext());
}

ContentProvider几乎不占用内存，并且会在Application#attachBaseContext之后，以及Application#onCreate之前得到执行，并且在设置了android:multiprocess之后在多进程情况下工作良好。这种方式非常可靠，在Google推出的Android Jetpack Lifecycle包中就使用了这种方式初始化框架的代码。

3.在使用ARouter.getInstance().inject(Object)的时候如果注入的IProvider在init时出错，ARouter不会让他抛出任何异常，也不会打印任何日志，我将会得到一个空指针异常。

4.模块预初始化功能，有些时候APP内的某些模块，需要Application启动时进行一些预初始化工作（比如SDK初始化，如果放到host中会增加代码耦合），可是在模块中无法通过自定义Application实现该功能，能否参考第三条的ContentProvider提供一个ModuleLoader的功能？

5.@Autowired注解的name属性实际引用的是@Route的path，容易造成概念混乱。

最后希望ARouter越来越好。

**Comment by xchengDroid** [comment]
@Route注解、 RouteMeta类  、@Autowired注解中的变量其实有点乱，
RouteMeta 中赋值extra =route.extras()，@Autowired 的name属性可以赋值Provider的path。生成的路由文档也没和 RouteMeta中的变量名对应，如 extras 变成了mark， name、className、字段也不统一
感觉这个是有点尴尬！

**Comment by zhaoyuehai** [comment]
> 1.ARouter生成的.java文件中的类最好对开发者来说是不可见的，如果使用package private,就可以避免开发者在不小心的时候访问到这些类型，而且修改成package private之后也不会影响扫描Dex。
> 
> 2.ARouter可以实用ContentProvider进行自动初始化，在lib的manifest中注册provider：
> 
> ```
>     <provider
>         android:authorities="${applicationId}.arouter-initializer"
>         android:multiprocess="true"
>         android:name="com.alibaba.android.arouter.ARouterInitializer"
>         android:exported="false"/>
> ```
> 
> 可以在ContentProvider#onCreate方法中，来初始化ARouter。
> 
> onCreate()
> {
> ARouter.init(getContext());
> }
> 
> ContentProvider几乎不占用内存，并且会在Application#attachBaseContext之后，以及Application#onCreate之前得到执行，并且在设置了android:multiprocess之后在多进程情况下工作良好。这种方式非常可靠，在Google推出的Android Jetpack Lifecycle包中就使用了这种方式初始化框架的代码。
> 
> 3.在使用ARouter.getInstance().inject(Object)的时候如果注入的IProvider在init时出错，ARouter不会让他抛出任何异常，也不会打印任何日志，我将会得到一个空指针异常。
> 
> 4.模块预初始化功能，有些时候APP内的某些模块，需要Application启动时进行一些预初始化工作（比如SDK初始化，如果放到host中会增加代码耦合），可是在模块中无法通过自定义Application实现该功能，能否参考第三条的ContentProvider提供一个ModuleLoader的功能？
> 
> 5.@Autowired注解的name属性实际引用的是@route的path，容易造成概念混乱。
> 
> 最后希望ARouter越来越好。

BaseApplication

**Comment by zhaoyuehai** [comment]
Application

**Comment by zhaoyuehai** [comment]
BaseApplication

**Comment by andych008** [comment]
如果市面上所有的第三方库都以这种方式自动初始化，那这件事情太可怕了。

另外，如果是debug
```
ARouter.openLog();
ARouter.openDebug();
```
这两句该写在`ARouter.init(getContext());`的前面吧？怎么办？就算能做到，是不是增加了ARouter集成的复杂性？

多数公司都有自己的框架，初始化也许是统一管理的，比如部分第三方框架是可以在子线程里初始化的。
