### ISSUE TITLE
withObject问题

### ISSUE THREAD

**Issue by loveAndroidAndroid** [alibaba/ARouter#631]
1.3.1版本：
withObject传递对象，在编译过程官方会通过serializationService对在底层传递的对象转成的Json进行反序列化parseObject，我可以通过Autowired注解得到实际想要的值。

为了使用文档功能，我们升级到了1.4.1版本。
同样的传对象代码，编译后的文件代码成了这样：
substitute.orderInfo = (....OrderInfo) substitute.getIntent().getSerializableExtra("orderinfo");
字符串强转对象肯定为空啊。导致项目报错了，你们注解器的逻辑我没找到，麻烦可以解释一下吗？

**Comment by liangxiwei** [comment]
他这块是自动生成代码，没法区分你用对是Serializable还是json存储，但代码会优先对Parcelable和Serializable作处理，最后才是普通的object，你这个对象去掉Serializable接口就好了

这块在withObject这个方法上应该做一下判断，如果是可序列化对象，就默认用原来的方式并且打个log告诉用户这个对象实现了Parcelable或者Serializable接口，咱们不支持json格式化好了。。。
