### ISSUE TITLE
关于自动注入，值并没有改变的疑问

### ISSUE THREAD

**Issue by RmondJone** [alibaba/ARouter#632]
如果Activity自动注入值A,第一次进入页面A是有值的，按Home键退出应用到后台。再次从外部点击路由链接，但是自动注入的值A已经变化。跳转页面，此时Activity走onResume方法，值A并没有变化，请问我要怎么处理才可以让这个自动注入的值变化？

**Comment by zhi1ong** [comment]
onResume 里面调 inject
