### ISSUE TITLE
navigation(Class<? extends T> service)接口是不是应该明确表示T是IProvider的子类？

### ISSUE THREAD

**Issue by macarthor** [alibaba/ARouter#636]
```java
public <T> T navigation(Class<? extends T> service);
```

是不是应该明确`T`是`IProvider`的子类？以让开发者明确知道该怎么定义他的实现。

实际上这个`T`也确实是`IProvider`的子类。

另外，项目中也应该明确这个泛型的定义。

#638

**Comment by zhi1ong** [comment]
设计上是希望更加普适一点，暂时只有 IProvider，这块修改的话，就要考虑兼容性了
