### ISSUE TITLE
布局加载错误Bug

### ISSUE THREAD

**Issue by TinycoderWang** [alibaba/ARouter#64]
在app的layout文件加下添加与module同名的布局文件，使用Arouter跳转到module相应布局的Activity后加载的布局为app的layout下的布局而不是module下的布局。

**Comment by zhi1ong** [comment]
ARouter只能决定跳转到哪个Activity，不能决定用哪个Layout，可以通过setContentView来自己设置。

**Comment by TinycoderWang** [comment]
你没理解我的意思，你可以在本项目的app的res/layout目录下新建一个activity_test_module.xml的布局文件，然后再点击 Demo的 **多模块测试** 下的 **跳转到模块1** 看看加载出来的页面布局是哪个

**Comment by zhi1ong** [comment]
那你用原生的startActivity跳转一下，看看是不是也打开了错误的Layout
