### ISSUE TITLE
void com.alibaba.android.arouter.facade.service.InterceptorService.doInterceptions(com.alibaba.android.arouter.facade.Postcard, com.alibaba.android.arouter.facade.callback.InterceptorCallback)' on a null object reference

### ISSUE THREAD

**Issue by huopochuan** [alibaba/ARouter#640]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by huopochuan** [comment]
类名缓存 要重新安装app

**Comment by lyqaiym** [comment]
我也偶现了一次。
