### ISSUE TITLE
why do ARouter and _ARouter need an instance?

### ISSUE THREAD

**Issue by macarthor** [alibaba/ARouter#641]
all members of `ARouter` and `_ARouter` are static, so i suppose they do not need an instance?

I inspected the non-static methods of the two classes, and their logics also seem not to require an instance to run.

and... the implementation of the singleton is double check locking... i wonder why???

**Comment by liangxiwei** [comment]
because maybe it will init with a global config in future.

**Comment by macarthor** [comment]
> because maybe it will init with a global config in future.

@liangxiwei so you mean it's not necessary in current version, right?

**Comment by zhi1ong** [comment]
ARouter 和 _ARouter 是门面模式，统一外部调用和屏蔽内部逻辑用的，instance 是双重锁单例模式，防止重复 init
