### ISSUE TITLE
是否应该把APT生成的类归到标记了@Route的类的包中？

### ISSUE THREAD

**Issue by macarthor** [alibaba/ARouter#643]
比如我有一个类需要暴露为服务：

``` java
@Route(path = xxx)
final class B implements IProvider { xxx }
```

编译时会报错：

> error: B is not public in xxx package; cannot be accessed from outside package

如果把它改成public的，编译后看了一下APT生成的类：

```java
package com.alibaba.android.arouter.routes;
import com.homecredit.business.b.BService;
public class ARouter$$Group$$B implements IRouteGroup { xxx }
```

这个类的包是`com.alibaba.android.arouter.routes`，所以我的B类就必须是public的。

有没有可能把APT生成的类变成和`@Route`相同的包名，那我的类就可以是package的了，做到了类对外部的隐藏。

Dagger 2的APT也是这么做的。

**Comment by zhi1ong** [comment]
可以是可以，一方面是兼容性问题，一方面是放在当前目录，便于排查问题
