### ISSUE TITLE
Fragment 混淆无法获取参数

### ISSUE THREAD

**Issue by zhongxiong00** [alibaba/ARouter#644]
混淆配置了
-keepclassmembers class * {
    @com.alibaba.android.arouter.facade.annotation.Autowired < fields >;
}
但是打的混淆包中，Fragment无法获取参数，代码如下
 @Autowired(name = PageRouteConstants.PageParam.STRING_PARAM1)
    public String shopId;

  LogUtils.e("方式1" + getArguments().getString(PageRouteConstants.PageParam.STRING_PARAM1)); //方式1
        ARouter.getInstance().inject(this);//方式2
        LogUtils.e("方式2" + shopId);

方式1能获取到值,方式2不能。

**Comment by liangxiwei** [comment]
反编译之后的代码是怎样的。

**Comment by zhongxiong00** [comment]
> 反编译之后的代码是怎样的。

我看了，字段确实没混淆，但是取不到值。

**Comment by zhongxiong00** [comment]
> 反编译之后的代码是怎样的。

你可以试试。

**Comment by liangxiwei** [comment]
说错了，应该是自动生成的代码，应该也有这段类似下面这段代码
getArguments().getString(PageRouteConstants.PageParam.STRING_PARAM1))
你把自动生成的代码贴出来看看

**Comment by zhongxiong00** [comment]
> 说错了，应该是自动生成的代码，应该也有这段类似下面这段代码
> getArguments().getString(PageRouteConstants.PageParam.STRING_PARAM1))
> 你把自动生成的代码贴出来看看

public class CollectBillFragment$$ARouter$$Autowired implements ISyringe {
  private SerializationService serializationService;

  @Override
  public void inject(Object target) {
    serializationService = ARouter.getInstance().navigation(SerializationService.class);
    CollectBillFragment substitute = (CollectBillFragment)target;
    substitute.shopId = substitute.getArguments().getString("param_string1");
  }
}
没有一点问题，哎。就是不知道为什么拿不到值。

**Comment by campusboy** [comment]
[release Fragment 参数](https://github.com/alibaba/ARouter/issues/617)
