### ISSUE TITLE
不同模块内实现了同一个服务接口，会导致调用端获取到不确定的某个实现

### ISSUE THREAD

**Issue by macarthor** [alibaba/ARouter#645]
base module定义了`interface IService extends IProvider`，然后module A和B都实现了这个接口。

此时app模块用by type可能获取到A的实现或者B的实现。

ARouter能不能防一下这个情况？

别告诉我改用by name调用哈。。。作为接口调用者，为什么需要知道要获取哪个实现呢？这样好像背离了interface的初衷。

**Comment by liangxiwei** [comment]
ARouter.getInstance().build()的时候不是要传一个path进去吗，你这边A和B应该是不同的path，调用哪个不是你决定的吗？

**Comment by JeckChou** [comment]
有一个priority

**Comment by macarthor** [comment]
> 如果by type传递了IProvider接口.....

@liangxiwei what do you imply... i don't get your point...

**Comment by macarthor** [comment]
> 有一个priority

@JeckChou 不同模块都定义自己的priority为1或者base里定义的HIGH，那相当于没有这个priority呗？

另外，ARouter的`Route.class`里边的`int priority() default -1;`方法，我没看到有什么有效的使用？只是在`LogisticsCenter`里调用过一次：`postcard.setPriority(routeMeta.getPriority());`，而这个`PostCard`类是`RouteMeta`的子类，它也没有使用其`priority`变量。所以我觉得ARouter根本没有使用`Route`的priority注解参数？

看了下`public synchronized static void init(Context context, ThreadPoolExecutor tpe);`方法和`public static Set<String> getFileNameByPackageName(Context context, final String packageName);`方法，从dex获取Arouter生成的类，然后就加入了一个HashSet，确实没有使用priority属性

**Comment by liangxiwei** [comment]
> > 如果by type传递了IProvider接口.....
> 
> @liangxiwei what do you imply... i don't get your point...

it means if you use Iprovider type, nobody know class return back.

**Comment by zhi1ong** [comment]
如过有多个实现，通过 byName 来解决，多态的场景，你自己不做选择，ARouter 也没办法选出你想要的结果呀。
