### ISSUE TITLE
kotlon 和java 混合开发，集成是没法跳转的。

### ISSUE THREAD

**Issue by zidanpiaoguo** [alibaba/ARouter#647]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by zidanpiaoguo** [comment]
在集成kotlin 之后，用router 是无法跳转的。java 的Activity中的。

**Comment by zhi1ong** [comment]
要注意是不是用了 kapt
