### ISSUE TITLE
关于 转场动画(API16+)的问题

### ISSUE THREAD

**Issue by MigoNoSalt** [alibaba/ARouter#65]
// 转场动画(API16+)
 ActivityOptionsCompat compat = ActivityOptionsCompat.makeScaleUpAnimation(v, v.getWidth() / 2, v.getHeight() / 2, 0, 0);
使用文档中提供的运行没问题。

String transitionName = getString(R.string.transition_shared_elements);
ActivityOptionsCompat options = ActivityOptionsCompat.makeSceneTransitionAnimation(this, view, transitionName);
但是使用共享元素进行跳转时发现页面无法正常显示（页面应该已经跳转了，但是页面元素都没显示出来）。

**Comment by zhi1ong** [comment]
使用共享元素动画的时候，navigation方法需要传入当前的Activity，和startActivityForResult一样，但是这个不太容易检查，所以没在api上做，需要用户自己注意

**Comment by kkseay** [comment]
navigation方法需要传入当前的Activity，这句话我理解了半天终于想明白了，是要navigation(this)...果然，我的理解能力有问题。
