### ISSUE TITLE
AROUTER_MODULE_NAME 直接赋值会导致其他框架的属性被覆盖

### ISSUE THREAD

**Issue by lcyluo** [alibaba/ARouter#651]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by lcyluo** [comment]
如题，如果其他注入框架用到annotationProcessorOptions ，则会导致其他框架的属性值为空，因为是直接赋值的；

**Comment by act262** [comment]
使用+=, 直接=会覆盖原有值
```
  arguments += [AROUTER_MODULE_NAME: project.getName(), AROUTER_GENERATE_DOC: "enable"]
```
