### ISSUE TITLE
Scheme协议跳转时，Activity使用了withFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)后跳转不到目标Activity

### ISSUE THREAD

**Issue by ZhangJian96** [alibaba/ARouter#654]
在使用scheme协议从连接跳转到应用的Activity时，当代码中有用ARouter.getInstance().build(XXX).withFlags.withFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK).navigation(context)去跳转的代码时（这句是给应用中调用去跳转的，不是scheme处用的），就无法跳转成功，具体表现为：
1.应用打开状态可以将应用调到前台但是无法跳转到目标Activity
2.应用关闭状态无法调起

调试结果getIntent().getData()拿到的uri正确，也正确回调了NavigationCallback的onFound，并且拿到的postcard参数中path也是没问题的。

只要去掉代码中的withFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)就可以正常，不知道为什么这句在scheme跳转时起到作用导致调不起来

**Comment by liangxiwei** [comment]
你直接用startActivity试试看，确定一下是flag的问题还是Arouter的问题
