### ISSUE TITLE
请问，支持view的组件化吗？

### ISSUE THREAD

**Issue by xushanning** [alibaba/ARouter#657]
如何通过路由的方式获取view？

**Comment by macarthor** [comment]
有具体的场景么，有很多地方需要获取view。。。

**Comment by xushanning** [comment]
> 有具体的场景么，有很多地方需要获取view。。。

我们这边需要在一个activity中可配置化的替换view，view非常多，想把放到一个module中去，但是又不直接依赖，ARouter能做到吗？

**Comment by macarthor** [comment]
如果你是要从一个module中获取一个View的instance，然后设置给你的activity的一个变量，是这样吧？
可以这样想：
按你说的需求的方向，arouter提供两种方式，我们看看是否满足你的需求。
- 用`@AutoWired`。但是，这个依赖注入的来源，是`Intent.getXxx()`方法，你怎么把View放到Intent里呢？即使你的自定义View实现了Parcelable或者Serializable接口，但View本身没有，你无法把View的一些属性带过去。
- 你的View实现`IProvider`并标记`@Route`，这样你的另一个module里的activity就可以获取到其实例了。***但是！！！***及其不建议这样做，因为`IProvider`的实例会以static的形式存在ARouter里，参考`WareHouse`的代码，就可以发现了。
所以，我感觉你的需求用ARouter实现不了，不过你可以考虑一下Dagger 2，应该可以做你的事情。

**Comment by macarthor** [comment]
github markdown不支持***语法哈？或者有其他形式？

**Comment by xushanning** [comment]
谢谢，实现IProvider的方式考虑过，的确是你说的那样，会static形式，还是非常感谢~！
