### ISSUE TITLE
DegradeService 作为服务级的东西，优先级比callBack低？

### ISSUE THREAD

**Issue by yueshaojun** [alibaba/ARouter#659]
if (null != callback) {
                callback.onLost(postcard);
            } else {    // No callback for this invoke, then we use the global degrade service.
                DegradeService degradeService = ARouter.getInstance().navigation(DegradeService.class);
                if (null != degradeService) {
                    degradeService.onLost(context, postcard);
                }
            }
我理解DegradeService 是个服务级别的，但是这里却被有米有callBack给阻断了？好像不是很合适

**Comment by macarthor** [comment]
DegradeService应该是被设计为一个fail over机制吧，并不是一个服务，虽然名字带service

**Comment by yueshaojun** [comment]
> DegradeService应该是被设计为一个fail over机制吧，并不是一个服务，虽然名字带service

但是它是IProvider的一种，其他IProvider的派生貌似都是服务？

**Comment by macarthor** [comment]
@yueshaojun 我个人理解，`IProvider`和“服务”完全没有关系。网上很多例子里用了“服务”的概念可能有些误导。ARouter本身一些类实现了这个接口也叫做XxxService，应该理解为内部的一个“功能”。

`IProvider`在ARouter里的真正含义，我认为是代表了一个：开发者（ARouter的使用者也就是我们）可以用interface方式暴露出来的API。实现方实现这个接口，调用者用这个接口并结合`@Route`来获取实现类的实例，从而达到双方`talk with interface`的解耦效果。而ARouter也用这套方式来实现自己的一些逻辑和暴露自己的API，仅此而已。

**Comment by zhi1ong** [comment]
DegradeService 是全局的，优先级比直接设置 callback 要低，这样能保证自己输入的 callback 不会被全局的覆盖掉，导致非预期的逻辑

**Comment by manondidi** [comment]
> @yueshaojun 我个人理解，`IProvider`和“服务”完全没有关系。网上很多例子里用了“服务”的概念可能有些误导。ARouter本身一些类实现了这个接口也叫做XxxService，应该理解为内部的一个“功能”。
> 
> `IProvider`在ARouter里的真正含义，我认为是代表了一个：开发者（ARouter的使用者也就是我们）可以用interface方式暴露出来的API。实现方实现这个接口，调用者用这个接口并结合`@Route`来获取实现类的实例，从而达到双方`talk with interface`的解耦效果。而ARouter也用这套方式来实现自己的一些逻辑和暴露自己的API，仅此而已。

是啊,我简书很多博客说这套东西支持service,回头翻翻源码 发现service要继承provider, 做法是 去调用service的构造函数 然后存在路由表里,我越看越懵逼,这样service不是永远无法释放吗,后来仔细一看, service只是叫做service,和android系统的service没有半毛钱关系
