### ISSUE TITLE
用ARouter这个框架来跳转Module2中的页面，发现第一次启动比较慢，第二次就好一些了

### ISSUE THREAD

**Issue by finddreams** [alibaba/ARouter#66]
ARouter来跳转Module2中的Activity第一次启动比较慢，之后就好多了，比原生的启动方式要慢，启动速度受到了影响。

**Comment by zhi1ong** [comment]
确实会略有延迟，不过不会有明显的卡顿，因为有路由分组，模块是按需加载的，某一个分组的路由信息，会在这个分组中的任意一个页面第一次使用的时候加载。你这个module2指的是demo中的module2么

**Comment by finddreams** [comment]
不是demo中的，是实际项目中，项目中如果页面比较多的话，加载的时间可能会更久一点。

**Comment by zhi1ong** [comment]
这个建议你分组的粒度尽量小一点，一个分组下面10个页面左右比较好，服务和页面路由是共用分组的：

/1/1      /1/2     /2/1     /2/2

前两个斜线之间的就是分组

**Comment by emptybird** [comment]
@finddreams 请问这个问题是否解决了呢？我按照建议减小分组粒度，情况并没有好转，延迟可以达到几秒钟之久

**Comment by wanghaibao123** [comment]
@emptybird @finddreams  跳转很慢有没有解决办法呢

**Comment by finddreams** [comment]
@emptybird 后面没发现这个问题了
