### ISSUE TITLE
自动注入参数  不能给对象类型付默认值  

### ISSUE THREAD

**Issue by lmh14790** [alibaba/ARouter#661]
public class AssetsTransferActivity$$ARouter$$Autowired implements ISyringe {
  private SerializationService serializationService;

  @Override
  public void inject(Object target) {
    serializationService = ARouter.getInstance().navigation(SerializationService.class);
    AssetsTransferActivity substitute = (AssetsTransferActivity)target;
    substitute.mTransferType = substitute.getIntent().getIntExtra("type", substitute.mTransferType);
    substitute.productId = substitute.getIntent().getIntExtra("product_id", substitute.productId);
    substitute.mCurrencyName = substitute.getIntent().getStringExtra("currency_name");
    substitute.mCurrencyId = substitute.getIntent().getIntExtra("currency_id", substitute.mCurrencyId);
  }
}

currency_name 的默认值 会被 substitute.mCurrencyName = substitute.getIntent().getStringExtra("currency_name"); 改变null

**Comment by zhi1ong** [comment]
字符串不支持默认值，这块fix掉了，compiler 新版本可用

**Comment by YuYongzhi** [comment]
@zhi1ong  

```
case STRING:
                statement += (isActivity ? ("getExtras() == null ? " + originalValue + " : substitute.getIntent().getExtras().getString($S, " + originalValue + ")") : ("getString($S)"));
                break;
```
看这段逻辑，对于Fragment，是不支持默认值的

**Comment by autofocus** [comment]
@zhi1ong  貌似还没发布支持默认值的新版本compiler，最新依然是1.2.2 ？
