### ISSUE TITLE
使用乐固加固后，Arouter不能用了

### ISSUE THREAD

**Issue by avenue2013** [alibaba/ARouter#667]
使用乐固加固后，Arouter不能用了 register插件我也用了，但还是不行，大家有没有什么好办法！

**Comment by zhi1ong** [comment]
@avenue2013 联系乐固厂家，让他们兼容一下，ARouter 用的都是标准的安卓技术，没有什么特殊的 hack

**Comment by JavaBasketball** [comment]
遇到同样的问题，这个问题解决了吗？
