### ISSUE TITLE
Autowired注解失败

### ISSUE THREAD

**Issue by lvshtwl** [alibaba/ARouter#671]
我在基类加了ARouter.getInstance().inject(this);

在每个module都加了    annotationProcessor rootProject.ext.dependencies["arouter-compile"]
但是Autowired一直拿到的是null

**Comment by lvshtwl** [comment]
通过arounter.withString(),Autowired拿不到，getintent就拿到了

**Comment by zhangqufa** [comment]
我也遇到这个问题，getIntent 是可以拿到

**Comment by shunlibest** [comment]
记一次找bug经理，注解的时候，把boolean写成了Boolean。希望大家注意啊。找到晚上1点了。
