### ISSUE TITLE
Multiple dex files define Lcom/alibaba/android/arouter/routes/ARouter$$Root$$app;

### ISSUE THREAD

**Issue by ningjiaqi** [alibaba/ARouter#676]
注意是ARouter$$Root$$app问题，不是Group分组问题
只有都依赖Core模块有这句：api 'com.alibaba:arouter-api:1.4.0'
其他每个模块都有annotationProcessor 'com.alibaba:arouter-compiler:1.2.1'
和javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName(), AROUTER_GENERATE_DOC: "enable"]
            }
        }
配置没问题，就是各种dex问题，指明就是ARouter导致的，求助大神！

**Comment by zhi1ong** [comment]
你每个module都叫app 么？如果这样的话，这个 AROUTER_MODULE_NAME 自己配置成不同的
