### ISSUE TITLE
解决"There is no route match the path [/xxx/xxx], in group [xxx][ ]"的一种方法

### ISSUE THREAD

**Issue by zjxuzhj** [alibaba/ARouter#678]
使用kotlin编程，添加了所有已知需要添加的配置。一直无法跳转。

打算打断点查看具体问题

在_ARouter类->navigation方法中断点后页面正常跳转，去除断点重新运行后依旧可以正常跳转。实在没法解决问题的同学可以看看。

**Comment by baolw** [comment]
出现了同样的问题。怎么解决？

**Comment by 1031900805** [comment]
请问解决了吗 刚刚遇到同样问题

**Comment by andyxm** [comment]
kotlin需要使用kapt去处理吧!在项目的build.gradle中并且和android{}同级,可以去试试
并添加依赖kapt 'com.alibaba:arouter-compiler:1.2.2'
kapt {
    arguments {
        arg("AROUTER_MODULE_NAME", project.getName())
    }
}

**Comment by zjxuzhj** [comment]
楼上这些都是可用的，我只是提供一个在配置了所有可以配置操作的情况下还不能解决问题的一种方法
