### ISSUE TITLE
kotlin Map<String,List<JavaBean> 反序列化失败

### ISSUE THREAD

**Issue by DreamerLeon** [alibaba/ARouter#679]
`    public static Class<?> getRawClass(Type type){
        if(type instanceof Class<?>){
            return (Class<?>) type;
        } else if(type instanceof ParameterizedType){
            return getRawClass(((ParameterizedType) type).getRawType());
        } else{
            throw new JSONException("TODO");
        }
    }
`
com.alibaba.fastjson.util.TypeUtils
应该是定位再这里抛出了异常 throw new JSONException("TODO");

**Comment by zhi1ong** [comment]
可以先自行序列化为字符串传递
