### ISSUE TITLE
IProvider 在fragment中的使用

### ISSUE THREAD

**Issue by xushanning** [alibaba/ARouter#680]
kotlin语言，在fragment中注入service
    @Autowired(name = ARouterPath.main)
    @JvmField
    var countService: ITodoCountService? = null

使用countService.xxx的时候，countService总是null，没有被注入，在fragment的init{}或者onCreate中已经inject了

**Comment by zhi1ong** [comment]
断点调试一下，看看 inject 的逻辑是不是执行了
