### ISSUE TITLE
有个bug，我删了一个module，但是arouter还保存着它的路径

### ISSUE THREAD

**Issue by 972223177** [alibaba/ARouter#681]
加群来不及。如题，arouter还在sp中保存着这个已删module的路径，导致在安装新包的时候报ARouter init logistics center exception!异常而crash。必须得卸载重装应用才能正常使用。请问这个如何解决。

**Comment by fanturbo** [comment]
@972223177 hello，问下这个最后怎么解决的呢

**Comment by fanturbo** [comment]
Arouter有版本的概念，同样的app版本如果路由不同，会造成加载路由失败导致crash
