### ISSUE TITLE
@Autowired后无法获取到值仍然是null

### ISSUE THREAD

**Issue by parcool** [alibaba/ARouter#686]
写了一个demo：https://github.com/parcool/DynamicApp

**Comment by parcool** [comment]
![image](https://user-images.githubusercontent.com/12092478/57919076-a8122880-78ca-11e9-82cf-c7aacecb72b5.png)
我看这个都生产了啊，怎么还是null？

**Comment by liuxujian** [comment]
注意属性类型的大小写，应该为小写的数据类型。比兔withBoolean(“isBoy”,true) 对应的属性应该boolean isBoy;
