### ISSUE TITLE
Kotlin 解决 There is no route match the path的

### ISSUE THREAD

**Issue by baolw** [alibaba/ARouter#688]
第一次将kotlin引入项目，自认为配置都是对的。其实还是漏了一点。主要是在项目中，原来使用annotationProcessor来导的arouter的注解处理器，必须退换为kapt，导入kapt的插件即可。其实详细的配置可以参考Arouter官方项目中的module-kotlin中的gradle配置。

**Comment by MONRRT** [comment]
还有些kotlin项目中使用过程中出现的综合问题可以去看看这里：https://blog.csdn.net/thirteenmonth/article/details/85620338
有个大佬做的总结。
顺便说一嘴，要实在构建不好，可以试试降版本。我的项目arouter-api:1.5.0 、arouter-compiler:1.2.2，构建总是出错，改为arouter-api:1.4.0'、arouter-compiler:1.2.1，就好了。不知道什么玄学。

**Comment by xiaozhi805157387** [comment]
增加一个
    implementation 'com.alibaba:arouter-annotation:{{last_version}}'就解决了

**Comment by wenfengtou** [comment]
我丢

**Comment by w441813542** [comment]
@xiaozhi805157387 我就是这个问题我丢，为什么啊

**Comment by xiaozhi805157387** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 330132662** [comment]
..插眼@！

**Comment by xiaozhi805157387** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
