### ISSUE TITLE
ARouter.getInstance().build(url)中的参数未注入mBundle

### ISSUE THREAD

**Issue by scsfwgy** [alibaba/ARouter#696]
通过Url跳转，比如外链中携带参数`?name=abc&age=12` 通过`    @Autowired(name = "name")
`可以取到。但是通过`intent.getString("name")`就取不到。希望可以处理一下。
code大概位置:

`
/**
     * Completion the postcard by route metas
     *
     * @param postcard Incomplete postcard, should complete by this method.
     */
    public synchronized static void completion(Postcard postcard) {
        if (null == postcard) {
            throw new NoRouteFoundException(TAG + "No postcard!");
        }

        RouteMeta routeMeta = Warehouse.routes.get(postcard.getPath());
        if (null == routeMeta) {    // Maybe its does't exist, or didn't load.
           ...
        } else {
            postcard.setDestination(routeMeta.getDestination());
            postcard.setType(routeMeta.getType());
            postcard.setPriority(routeMeta.getPriority());
            postcard.setExtra(routeMeta.getExtra());

            Uri rawUri = postcard.getUri();
            if (null != rawUri) {   // Try to set params into bundle.
                Map<String, String> resultMap = TextUtils.splitQueryParameters(rawUri);
                Map<String, Integer> paramsType = routeMeta.getParamsType();
                //问题在这里：	paramsType如果为null,参数就不会再注入==>ARouter$$Group$$home 中@Autowired注入routeMeta.getParamsType()，
                if (MapUtils.isNotEmpty(paramsType)) {
                    // Set value by its type, just for params which annotation by @Param
                    for (Map.Entry<String, Integer> params : paramsType.entrySet()) {
                        setValue(postcard,
                                params.getValue(),
                                params.getKey(),
                                resultMap.get(params.getKey()));
                    }

                    // Save params name which need auto inject.
                    postcard.getExtras().putStringArray(ARouter.AUTO_INJECT, paramsType.keySet().toArray(new String[]{}));
                }

                // Save raw uri
                postcard.withString(ARouter.RAW_URI, rawUri.toString());
            }

           ...
        }
    }
`

**Comment by scsfwgy** [comment]
不处理的原因：url中的参数获取到的都是String类型？比如?name=abc&age=12  获取到age是12,但是是String类型。

**Comment by zhi1ong** [comment]
不预先知道参数类型的话，从 url 里面解出来的参数就填不进去了
