### ISSUE TITLE
demo运行无法正常跳转

### ISSUE THREAD

**Issue by jasonfresher** [alibaba/ARouter#7]
Aroute example运行log如下：
01-13 15:25:06.490 30616-30616/com.alibaba.android.arouter.demo I/ARouter::: ARouter start attachBaseContext
01-13 15:25:06.497 30616-30616/com.alibaba.android.arouter.demo I/ARouter::: ARouter hook instrumentation success!
01-13 15:25:06.527 30616-30616/com.alibaba.android.arouter.demo I/galaxy: VM with name 'Android' has multidex support
01-13 15:25:06.529 30616-30616/com.alibaba.android.arouter.demo D/galaxy: Filter 0 classes by packageName <com.alibaba.android.arouter.routes>
01-13 15:25:06.532 30616-30616/com.alibaba.android.arouter.demo D/ActivityThread: BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{32762597 com.alibaba.android.arouter.demo}}
01-13 15:25:06.533 30616-30616/com.alibaba.android.arouter.demo V/ActivityThread: Handling launch of ActivityRecord{258c3384 token=android.os.BinderProxy@32e29fa2 {com.alibaba.android.arouter.demo/com.alibaba.android.arouter.demo.MainActivity}}

按照readme里的集成方法集成到我自己的app中也是无法跳转，There's no routematched!

**Comment by zhi1ong** [comment]
demo是否正常运行呢？

01-13 15:25:06.529 30616-30616/com.alibaba.android.arouter.demo D/galaxy: Filter 0 classes by packageName <com.alibaba.android.arouter.routes>

看上面日志，没有扫描到任何映射文件，可能映射文件没有生成，也可能是设置了混淆，但是没有添加keep规则，没有生成映射文件的话，要看一下 #4 里面提到的排查办法

**Comment by jasonfresher** [comment]
demo运行不正常，#5里有一个人跟我的情况一样，只有build apk文件，再安装，就可以跳转了，但是用as直接run的话会无法跳转

**Comment by zhi1ong** [comment]
直接run也是会打成apk的，但是要是Instant Run的话，会直接改变化的内容，生成文件不会进去，你可以确认一下是不是开了Instant Run，涉及到这种生成代码的情况，要完全build安装

**Comment by jasonfresher** [comment]
谢了，确实是开启了Install Run就会导致无法生成映射文件不能跳转，关闭一下就ok了
