### ISSUE TITLE
ARouter Helper插件，在Kotlin中无法使用

### ISSUE THREAD

**Issue by ruhaly** [alibaba/ARouter#700]
#596 这个问题可以解决？ARouter Helper插件，在Kotlin中无法使用

**Comment by xiaojinzi123** [comment]
> #596 这个问题可以解决？ARouter Helper插件，在Kotlin中无法使用

建议使用 [Component](https://github.com/xiaojinzi123/Component),配套的插件支持 kotlin, 库本身非常优秀

**Comment by zhi1ong** [comment]
同 #596 后续支持
