### ISSUE TITLE
建议通过IProvide接口添加回调支持,ModuleA:通过路由添加固定的callback参数指定要回调IProvide路径.ModuleB:通过callback参数获取IProvide实例进行回调。

### ISSUE THREAD

**Issue by tanlzhi** [alibaba/ARouter#701]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by Waylon-Firework** [comment]
这个close了是这个功能有了吗？没有找到。
