### ISSUE TITLE
最近这个没效果了都，为啥？之前都还可以跳转

### ISSUE THREAD

**Issue by huanyuan** [alibaba/ARouter#702]
ARouter.getInstance().build("/oss/WindowActivity").withString("path", filePath).navigation();
代码两边都没动， @Route(path = "/oss1/WindowActivity") 这边完全没反应了

**Comment by zhi1ong** [comment]
看起来一个是 oss，一个是 oss1

**Comment by huanyuan** [comment]
我的两边是对的，只是上边代码没写对，我这里是同一份apk在不同的固件中出现了这情况，一个可以另一个什么反应都没有
