### ISSUE TITLE
ARouter VS Component

### ISSUE THREAD

**Issue by xiaojinzi123** [alibaba/ARouter#703]
这里我整理了一下 `ARouter` 和 `Component` 的优缺点.我想让更多的人知道还有一个 `Component`.下面比较的项目有误的话,请回复我更改.
更多详情请查看 [Component](https://github.com/xiaojinzi123/Component),欢迎来讨论

| 比较项     | Arouter                                                      | Component                                                    |
| :--------- | :----------------------------------------------------------: | :----------------------------------------------------------: |
| 业务模块的生命周期 | <img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px /> | <img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px /> |
| 页面拦截器(只针对指定页面有效的拦截器) | <img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px /> | <img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px /> |
|路由可手动取消|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|路由自动取消<br/>(界面销毁,会自动取消关联的路由)|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|支持 `Androidx`|未知(貌似有 issue)|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|支持 0 配置获取 `ActivityResult`|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|自定义 `Intent`|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|支持第三方界面和系统界面|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|支持生成文档|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px /> 目前不支持|
|支持标准 `URI`|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|全局拦截器|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|支持接口路由方式(类似 `Retrofit`)|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|支持 `RxJava`|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|Idea Plugin|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|Idea Plugin 支持 kotlin|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/error.png" width=26px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|各方面兼容性|可以看 issue 有少数的兼容性问题<br/>虽然少,但是出现会让用户束手无措|几乎 100%|
|支持目标界面属性注入|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|支持获取 `Fragment`|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|支持降级|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px /> <br/>通过全局拦截器支持|
|发现服务|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|
|支持 `H5`|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px />|<img src="https://xiaojinzi.oss-cn-shanghai.aliyuncs.com/blogImages/ok.png" width=32px /><br/>因为有页面拦截器的支持, `H5` 不需要管目标界面是否需要登录、定位等预处理|

**Comment by YummyLau** [comment]
感觉两个框架是不同的范畴。

**Comment by xiaojinzi123** [comment]
> 感觉两个框架是不同的范畴。

不,都是基于 `URI` 设计的,是同一个类型的框架不同的实现
`ARouter` 是把 服务发现和路由一起设计了,`Component` 是分开设计的.

**Comment by zhi1ong** [comment]
1. 这里是提 issue 的地方
2. 替广大开发者感谢你对开源事业做出贡献
3. 不用非要和别人对比，才能证明自己的东西比较好，让大众来选择
4. 看起来差异对比都是一些比较特性化的功能，“路由可手动取消” 不知道有什么意义，功能的罗列不难，重要的是普适
5. 开源是希望能众人拾柴火焰高，而不是造一堆轮子

**Comment by achenglike** [comment]
我们需要的是一个简单、易用、稳定的路由器，这就够了

**Comment by xiaojinzi123** [comment]
> 我们需要的是一个简单、易用、稳定的路由器，这就够了

你应该充分了解双方的使用再说这句话.

**Comment by achenglike** [comment]
> > 我们需要的是一个简单、易用、稳定的路由器，这就够了
> 
> 你应该充分了解双方的使用再说这句话.

以下内容仅作为讨论，尝试回答下提主给出的对比，基本2个维度：A、是不是路由的范畴 B、使用ARouter如何做到。
首先声明下我个人对组件化与路由的理解：组件化是一直架构方式，路由只是处理这个架构中页面或功能导航的一直方式，所以路由不应该过多的去处理非路由的功能，即使它是在组件化的范畴中。

1. 业务模块声明周期 ：
A：我认为不是路由功能的范畴，首先我看了提主项目中的声明周期，用来做一个当前模块需要用到功能的初始化，卸载时也可以做内容的清理等扩展。我有3个疑问，1如何处理多模块共用内容的初始化，2如何处理模块初始化优先级，3一个组件化中做模块加载和卸载的功能是不是独立出来处理更好。B

**Comment by xiaojinzi123** [comment]
看您也没有写完整,那我就先回答您的第一点问题

`ARouter` 和 `Component` 都不止是路由而已,都是组件化这个架构下的一种一站式解决方案
所以您说的 业务模块声明周期 这个功能当然不是路由模块的功能,我的库也没有把这个功能归类于路由模块

第二个问题

共用内容的初始化问题
> 每一个项目基本上都会有一个基础业务模块,比如 `ModuleBase`,这个也是一个业务模块,但是没有具体的业务代码,每一个业务模块都会依赖它.所以共用内容的初始化可以放这.当然这是解决方式之一.

模块初始化优先级的问题
> 这个很简单, 初始化的优先级就是你业务模块被加载的顺序.所以这个不是问题

模块加载卸载是否独立出来做的问题
> 上面说过, 库都是组件化架构的一种一站式解决方案. 模块加载卸载就是这个库的一个功能模块而已.本身和路由也没关系.当然了这方面也有其他库专门做给业务组件提供生命周期,也可以用呀

再次说明,每一个完整的组件化方案的实现基本都有几个模块,几个模块共同作用才是组件化的一个完整的实现.
- 路由
- 服务发现
- 模块管理(加载和卸载啊)
- 一些监控
- 配套的辅助功能的 Idea Plugin
- 。。。。。。

**Comment by achenglike** [comment]
> @achenglike 看您也没有写完整,那我就先回答您的第一点问题
> 
> `ARouter` 和 `Component` 都不止是路由而已,都是组件化这个架构下的一种一站式解决方案
> 所以您说的 业务模块声明周期 这个功能当然不是路由模块的功能,我的库也没有把这个功能归类于路由模块
> 
> 第二个问题
> 
> 共用内容的初始化问题
> 
> > 每一个项目基本上都会有一个基础业务模块,比如 `ModuleBase`,这个也是一个业务模块,但是没有具体的业务代码,每一个业务模块都会依赖它.所以共用内容的初始化可以放这.当然这是解决方式之一.
> 
> 模块初始化优先级的问题
> 
> > 这个很简单, 初始化的优先级就是你业务模块被加载的顺序.所以这个不是问题
> 
> 模块加载卸载是否独立出来做的问题
> 
> > 上面说过, 库都是组件化架构的一种一站式解决方案. 模块加载卸载就是这个库的一个功能模块而已.本身和路由也没关系.当然了这方面也有其他库专门做给业务组件提供生命周期,也可以用呀
> 
> 再次说明,每一个完整的组件化方案的实现基本都有几个模块,几个模块共同作用才是组件化的一个完整的实现.
> 
> * 路由
> * 服务发现
> * 模块管理(加载和卸载啊)
> * 一些监控
> * 配套的辅助功能的 Idea Plugin
> * 。。。。。。

抱歉，本来是想写写具体的理解和ARouter使用是如何使用这些功能的，但是发现需要写的内容内容太多，又时间不够，就搁置了，之前写的也忘了删掉。总的来说，我不认为ARouter是一个一站式解决方案，应该是作者在介绍页第一句描述中的“💪 A framework for assisting in the renovation of Android componentization (帮助 Android App 进行组件化改造的路由框架)”，定位很明确是路由框架，所以ARouter应该并且也是边界清晰，只做自己该做的。
