### ISSUE TITLE
加拦截器导致主界面的启动速度变慢 加入拦截器进入主界面activity的方式从下往上进入，不加从左往右进入

### ISSUE THREAD

**Issue by SixGL** [alibaba/ARouter#704]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by zhi1ong** [comment]
拦截器的 init 方法会阻塞首次跳转，不要写太复杂的 init 逻辑

**Comment by SixGL** [comment]
> 拦截器的init方法会阻塞首次跳转，不要写太复杂的init逻辑

进入程序的以后，Activity跳转没问题的（init只做了一个token的判断）。
可能表述的不清楚，加入拦截器以后，从桌面启动App的时候，这个时候的进入方式由下往上了，然后由闪屏进入主界面MainActivity时，会空白一段时间（闪屏就是为了解决这个空白问题），不加拦截器没问题，加了出现这种现象

**Comment by SixGL** [comment]
> 拦截器的init方法会阻塞首次跳转，不要写太复杂的init逻辑

启动优化：不是为了避免app启动时，进入主界面之前出现短暂空白这个问题嘛。

优化后，就是无缝衔接的进入，但是加了拦截器，又会出现这个问题

**Comment by loshine** [comment]
Android10
MIUI12
arouter-api 1.5.0
arouter-compiler 1.2.2

出现相同问题，当应用完全退出重新进入时，从 SplashActivity 跳转到 MainActivity 一定概率会先回到桌面等待一段时间再打开 MainActivity

代码如下

```kotlin
@Interceptor(priority = 10, name = "tutorial")
class RidingTutorialInterceptor : IInterceptor {

    override fun process(postcard: Postcard, callback: InterceptorCallback) {
        val path = postcard.path
        if (path == ARouterManager.VIDEO_PLAY_ACTIVITY) {
            val tutorialShown = false
            if (tutorialShown) {
                callback.onContinue(postcard)
            } else {
                ARouter.getInstance()
                        .build(ARouterManager.TUTORIAL)
                        .with(postcard.extras)
                        .navigation()
                callback.onInterrupt(null)
            }
        } else {
            callback.onContinue(postcard)
        }
    }

    override fun init(context: Context) {

    }

}
```

**Comment by Break369** [comment]
> Android10
> MIUI12
> arouter-api 1.5.0
> arouter-compiler 1.2.2
> 
> 出现相同问题，当应用完全退出重新进入时，从 SplashActivity 跳转到 MainActivity 一定概率会先回到桌面等待一段时间再打开 MainActivity
> 
> 代码如下
> 
> ```kotlin
> @Interceptor(priority = 10, name = "tutorial")
> class RidingTutorialInterceptor : IInterceptor {
> 
>     override fun process(postcard: Postcard, callback: InterceptorCallback) {
>         val path = postcard.path
>         if (path == ARouterManager.VIDEO_PLAY_ACTIVITY) {
>             val tutorialShown = false
>             if (tutorialShown) {
>                 callback.onContinue(postcard)
>             } else {
>                 ARouter.getInstance()
>                         .build(ARouterManager.TUTORIAL)
>                         .with(postcard.extras)
>                         .navigation()
>                 callback.onInterrupt(null)
>             }
>         } else {
>             callback.onContinue(postcard)
>         }
>     }
> 
>     override fun init(context: Context) {
> 
>     }
> 
> }
> ```
同样出现去掉拦截器，还是大概率出现桌面退出再跳转的问题，单独miui12出现

**Comment by lx36301766** [comment]
这个问题有解了吗，太明显了，加了拦截器后从Splash->Main这一段多出一段空白出来

**Comment by zhi1ong** [comment]
没明白，你是还没跳转完就 finish 了吧，在 callback 里面再 finish

**Comment by iamdennisme** [comment]
同样MIUI 12 出现了这个问题，只要申明拦截器，拦截器空实现也会出现这个问题

**Comment by 751496032** [comment]
这个问题是必现的，我是通过反射解决的

**Comment by Pannarrow** [comment]
有人解决吗,不是初始化阻塞,是开始跳转时进入拦截器的代码导致阻塞

我擦,其实只要Splash->Main的时候.greenChannel().navigation(),过滤使用拦截器,就好了

**Comment by yuqirong** [comment]
```
        ARouter.getInstance().build(Router.Home.HOME_PAGE)
                .navigation(this, new NavCallback() {
                    @Override
                    public void onArrival(Postcard postcard) {
                        finish();
                    }
                });
```

换成这样写就可以了。
