### ISSUE TITLE
舊有版本更新後出現 arouter there is no route matched bug

### ISSUE THREAD

**Issue by lowfiend** [alibaba/ARouter#707]
哈囉，

測試流程同樣模組：

1. 建一個新的app (MainActivity)
2. 建一個test模組
3. test模組建一個/test/testActivity  
4. 編譯在A手機 正常跳轉
5. 在建一個/test/test2Activity
6. 編譯在A手機 出現arouter there is no route matched bug
7. 編譯在B手機 正常跳轉

遇到狀況：
如果在已存在的模組下有新的跳轉，只有在沒有安裝過的手機上會正常，
如果在已安裝的手機會出現arouter there is no route matched的bug

如果在已安裝的手機清除該app資料，剛剛出現的arouter there is no route matched bug就沒了，可以正常使用。

以上問題是有開著 ARouter.openDebug();的模式下  他不會自動更新
如果我有改 versionCode 或 name 會更新

![image](https://user-images.githubusercontent.com/9345164/61025728-1f080100-a3e4-11e9-9552-7f2a5a349cef.png)

 api 'com.alibaba:arouter-api:1.5.0'
 annotationProcessor 'com.alibaba:arouter-compiler:1.2.2'

**Comment by zhi1ong** [comment]
看起来是因为 instant run，如过确定开启了 openDebug 是可以加载 instant run 的 dex 的
