### ISSUE TITLE
同一个module使用同一个group，导致找不到RouteMeta ARouter::There is no route match the path [/app/login], in group [app][ ] 

### ISSUE THREAD

**Issue by MapleSunFLY** [alibaba/ARouter#709]
ARouter::There is no route match the path [/app/login], in group [app][ ] 
用一个module，用Url跳转或者普通跳转的时候，第一级目录基本相同，会出现这个问题，是用一个module group 也能相同么，但是有时候又不会报错，是什么原因了

**Comment by MapleSunFLY** [comment]
以解决

**Comment by Ymars1990** [comment]
怎么解决的？ 不同module 会出现这个问题，一级目录不一样
