### ISSUE TITLE
建议:支持andoird app bundle

### ISSUE THREAD

**Issue by roths** [alibaba/ARouter#714]
andoird app bundle是官方插件化机制，将来是否会考虑支持该机制？
目前因为插件安装的目录不在splitSource目录中，因此Arouter没能在初始化的时候获取到动态下载的dex文件并扫描里面包含的路由注册组件类，另一方面Arouter也不支持动态注册路由信息，所以插件下载完成后无法立马生效，目前我是利用反射清空并注册插件的路由信息才能实现预期结果

**Comment by xiaojinzi123** [comment]
[Component](https://github.com/xiaojinzi123/Component) 支持

**Comment by zhi1ong** [comment]
这块可以排到计划中支持一下

**Comment by JsonYuu** [comment]
> andoird app bundle是官方插件化机制，将来是否会考虑支持该机制？
> 目前因为插件安装的目录不在splitSource目录中，因此Arouter没能在初始化的时候获取到动态下载的dex文件并扫描里面包含的路由注册组件类，另一方面Arouter也不支持动态注册路由信息，所以插件下载完成后无法立马生效，目前我是利用反射清空并注册插件的路由信息才能实现预期结果

你好，能请问下 你这边是如何实现的吗？我这边有个项目使用ARouter 的组件化的模式，现在想转成插件化，但是又不想抛弃ARouter。能说下你的思路吗？谢谢

**Comment by zhi1ong** [comment]
1.5.2 提供接口支持动态注册路由信息

**Comment by hulalaty123** [comment]
提供動態註冊信息有使用說明文檔嗎？
