### ISSUE TITLE
请问：Fetch fragment instance error,     at java.lang.reflect.Constructor.newInstance(Native Method) 这种是什么时候情况造成的？

### ISSUE THREAD

**Issue by leguang** [alibaba/ARouter#715]
请问：Fetch fragment instance error,     at java.lang.reflect.Constructor.newInstance(Native Method) 这种是什么时候情况造成的？
有两个Fragment，一个可以获取并跳转，一个获取为空。
这个为空的fragment在获取报的异常错误如上所示，这两个fragment的写法几乎一样，只是处在不同的module中，请问这里有需要注意的什么吗？

**Comment by JonTree** [comment]
这个问题解决了吗  为啥关闭了

**Comment by nanguaSky** [comment]
我同样也遇到了这个问题，如果在同一个模块中一个fragment可以获取到一个获取不到，其实跟arouter框架无关，是获取不到的那个fragment代码有问题，断点arouter里面的源码查看到的异常，其实跟Constructor.newInstance 反射异常无关的，进入到catch里面断点就可以看到真正的异常原因了，我后来是发现我的初始化代码块里面的代码有异常才导致反射的时候创建fragment失败了
