### ISSUE TITLE
一样的代码，一样的配置，androidx提示找不到路由，希望早日解决适配

### ISSUE THREAD

**Issue by 1170762202** [alibaba/ARouter#718]
一样的代码，一样的配置，androidx提示找不到路由，希望早日解决适配

**Comment by yushilong** [comment]
。。。。。。找找自己的原因吧，我的androidx是可以的

**Comment by lu-xu** [comment]
[``](https://github.com/alibaba/ARouter/issues/713)
应该是自己代码报错，试一下
