### ISSUE TITLE
Program type already present: com.alibaba.android.arouter.routes.ARouter$$Group$$cardriver 分组没有重复运行没有问题打包编译就不行

### ISSUE THREAD

**Issue by 358803280** [alibaba/ARouter#723]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by titanseason** [comment]
我之前遇到过同样的问题，是因为你在不同的module里面，用了同样的group。
比如你在模块1中，有个注解 @Route("/login/xx01")

**Comment by 358803280** [comment]
嗯嗯谢谢我找到问题了  是我自己初始化路劲放错了module




------------------ 原始邮件 ------------------
发件人: "K.T. Wang"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 中午11:20
收件人: "alibaba/ARouter"<ARouter@noreply.github.com>; 
抄送: "σ伱祗荟晎藕"<358803280@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/ARouter] Program type already present: com.alibaba.android.arouter.routes.ARouter$$Group$$cardriver 分组没有重复运行没有问题打包编译就不行 (#723)




我之前遇到过同样的问题，是因为你在不同的module里面，用了同样的group。
 比如你在模块1中，有个注解 @route("/login/xx01")
