### ISSUE TITLE
Kotlin中使用ARouter.getInstance().build(path).navigation()返回值一直为null

### ISSUE THREAD

**Issue by panyiyiyi** [alibaba/ARouter#724]
通过这个步骤去获取Provider的时候，使用kotlin时候ARouter.getInstance().build(path).navigation()返回的一直是空，这是少了那个配置吗？
![image](https://user-images.githubusercontent.com/17979173/63147306-40d25480-c030-11e9-9708-b8556b1bc250.png)

**Comment by faithHyperion** [comment]
兄弟，你找到原因了吗？

**Comment by android-taoge** [comment]
我也遇到这个问题，请问你是怎么解决的？
