### ISSUE TITLE
使用Arouter启动的Activity页面,该Activity页面启动模式未生效

### ISSUE THREAD

**Issue by tangkunttkk** [alibaba/ARouter#725]
重现场景:
A页面启动B页面,B页面在AndroidManefest.xml中设置启动模式为SingleTop,此时在A页面中通过Arouter重复启动B页面,此时会启动多个B页面,而不是只启动一次B页面;
如果不使用Arouter,而使用startActivity这种方式则只会启动一次B页面,而不会启动多个.

因为现在在组件化开发中使用到了阿里路由用于页面跳转,从而导致无法使用startActivity这种方式做跨组件跳转页面,所以采用了Arouter,请问使用Arouter如何做到保留跳转页面配置的启动模式呢?

**Comment by inPeige** [comment]
ARouter.getInstance().build(path)
                .withString(EXTRA_RURL, rurl)
                .withFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK)
                .navigation();

**Comment by titanseason** [comment]
去掉 Intent.FLAG_ACTIVITY_NEW_TASK
