### ISSUE TITLE
ARouter初始化时间特别长。 华为Mate20Pro

### ISSUE THREAD

**Issue by lyqaiym** [alibaba/ARouter#726]
需要1400毫秒。ARouter.init(ContextManager.getApplication());

**Comment by lyqaiym** [comment]
我们工程大，getFileNameByPackageName方法特别耗时。com.alibaba.android.arouter.routes.ARouter$$Root$$iwriter  这些class是动态生成的。那能不能动态生成个类，里面是这些类的集合

**Comment by lyqaiym** [comment]
我看新版本有PackageUtils.isNewVersion，应该能解决问题了

**Comment by laomengzhu** [comment]
Duplicate of #200
