### ISSUE TITLE
支持AS 3.5增量编译（Support AndroidStudio 3.5 Incremental annotation processing）

### ISSUE THREAD

**Issue by chenfei0928** [alibaba/ARouter#728]
AS 3.5 添加了注释处理增量编译特性，但由于aRouter编译插件不支持增量编译，所以会在Log中出现以下警告：

> w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: com.alibaba.android.arouter.compiler.processor.AutowiredProcessor (NON_INCREMENTAL), com.alibaba.android.arouter.compiler.processor.InterceptorProcessor (NON_INCREMENTAL), com.alibaba.android.arouter.compiler.processor.RouteProcessor (NON_INCREMENTAL).

增量编译特性可以加速编译过程，是否考虑在下一个 arouter-compiler 中添加增量编译支持？

**Comment by nEdAy** [comment]
希望尽快支持

**Comment by openproject** [comment]
+1

**Comment by sw926** [comment]
+1

**Comment by zhi1ong** [comment]
1.5.1 已支持
