### ISSUE TITLE
@Autowired注解会覆盖默认值

### ISSUE THREAD

**Issue by zhpanvip** [alibaba/ARouter#729]
@Autowired()
 String name="Andy";
通过Scheme跳转当Uri中没有没有name参数时，name的默认值会被覆盖掉变成null.

版本：
arouter-compiler:1.2.2
arouter-api:1.5.0

**Comment by OblivioU** [comment]
同问！

**Comment by yeaper** [comment]
+1

**Comment by zhi1ong** [comment]
Activity 不会，Fragment 会，dev 中 fix 了
