### ISSUE TITLE
不支持gradle5

### ISSUE THREAD

**Issue by tangxiangpi** [alibaba/ARouter#731]
gradle4编译是ok了，但是修改为gradle-5.4.1-all.zip以后编译失败
e: 错误: ARouter::Compiler An exception is encountered, [null]
      at com.alibaba.android.arouter.compiler.processor.RouteProcessor.parseRoutes(RouteProcessor.java:189)

**Comment by Payaml** [comment]
最新版本是支持 Gradle5x 的

**Comment by tangxiangpi** [comment]
是么，那奇怪，我用gradle4没有任何问题，gradle5就有上面的日志输出

**Comment by tangxiangpi** [comment]
![image](https://user-images.githubusercontent.com/18000558/71541206-56696a80-2990-11ea-8715-515e4d9cf8d9.png)
![image](https://user-images.githubusercontent.com/18000558/71541212-6719e080-2990-11ea-8bfd-a8bed63da4c9.png)
![image](https://user-images.githubusercontent.com/18000558/71541220-80229180-2990-11ea-8734-058a35e9968e.png)
gradle构建时没问题，编译的时候报这个错误

**Comment by tangxiangpi** [comment]
能回复大概什么原因么？ 也没有啥非常规的用法

**Comment by liruixing** [comment]
我真的是奇了怪了~~一个项目的5.4.1可以正常，然后写了个demo不可以~~继承步骤一模一样
