### ISSUE TITLE
Interceptor拦截器不知道自己将运行于子线程还是主线程

### ISSUE THREAD

**Issue by liaodq** [alibaba/ARouter#732]
&emsp;&emsp;从DEMO测试和arouter-api模块的InterceptorServiceImpl实现来看，拦截器所在的线程都是由**上一个拦截器**回调InterceptorCallback\#onContinue方法所在的线程决定的。
&emsp;&emsp;从第二个到第N个拦截器，每个拦截器都**不知道自己将要运行于哪个线程**。虽然统一给耗时操作new Thread和把UI操作runOnUiThread是可以的。
&emsp;&emsp;所以，我这个算一个问题吗？

**Comment by zhi1ong** [comment]
不在拦截器里面继续切换线程，就一直是同一个线程
