### ISSUE TITLE
ARoute与AAC的Navigation的区别和联系

### ISSUE THREAD

**Issue by chenwuwen** [alibaba/ARouter#736]
ARoute可以跳转Activity/Fragment 
Navigation只能在Fragment间跳转
由于项目是分模块的，所以接触到了ARoute，之前一直做的单模块项目(单Activity使用Navigation)，
情况是首页有四个tab，每个tab页是一个模块,这个时候，首页的四个tab对应四个模块中的对应Fragment
由于是分模块的,所以首页这一块肯定是使用的ARoute，但是我在特定的Tab页，点击其中的内容(跳转页面)，这个时候我希望是使用AAC的Navigation组件，毕竟使用ARoute需要维护大量路径，而Navigation有可视化的编辑功能，然后当我尝试在单个Tab页点击使用Navigation跳转时，不出意外的报错了，我不知道ARoute在这一块是否有相应设置？(注：如果使用ARoute跳转到Activity，然后再在Activity中使用Navigation跳转到Fragment是没有问题的,但这样就没有了tab的效果)

**Comment by zhi1ong** [comment]
多 tab 主要是用参数自行区分
