### ISSUE TITLE
针对 ARouter 部分特性的探讨

### ISSUE THREAD

**Issue by robotAndroidCode** [alibaba/ARouter#737]
- 比如一个跳转需要 3 秒, ARouter 执行路由跳转, 但是用户点击返回键, 退出界面, 但是跳转还在继续, 如何取消本次跳转？或者说这个问题如何解决
- ARouter 所谓的跳转 `Fragment` 本质上是获取到了一个 `Fragment`, 和说的 `跳转 Fragment` 好像不太符合把？跳转 `Fragment` 其实看上去就是一个跨组件调用为获取 Fragment 提供的一个方便吧？这点在文档上我觉得是否应该解释下, 我见过很多人对这个理解都有问题
- 我看很多其他的框架都有所谓的 `页面拦截器` 的概念, 就是那种和目标界面绑定的拦截器, 这种方式貌似比用全局拦截器去处理好像更好吧？这点我看 [WMRouter](https://github.com/meituan/WMRouter) 和 [Component](https://github.com/xiaojinzi123/Component) 都有类似的概念.比如进入某些页面我需要定位或者某个权限或者登陆后才能进入, 这个东东就很好用. 不知后续 Arouter 的是怎么看这个功能的
- 这点是关于某些框架中有跳转之后拿 `ActivityResult` 的, 这点我看 `ARouter` 也是没有的, 这点其实也可以看成是路由功能的一部分吧, 就好像一个请求拿到对应的 `Response`, 关键是这功能可以让我们不写 onActivityResult, 让整段代码都是连续的. 不知道后续 Arouter 能否支持下.
- 还有一个问题是, 现在界面多了, 有些跳转是多个地方跳转到同一个界面的, 而且参数可能很多, 这时候其实代码就会 copy 来 copy 去, 可能这边少几个参数, 那边多几个, 我看有些框架有设计类似于 `Retrofit` 的形式去描述一个跳转, 然后就可以都调用这个接口去跳转, 不知道后续 Arouter 有无这样的打算?

**Comment by zhi1ong** [comment]
我觉得算不上核心问题，对你来说的核心问题，对大部分人可能算不上，框架是一个通用的解决方案，不可能面面俱到，按照你的提问，我从我的理解上试着回答吧

1. 跳转为什么会耗时这么久？就让用户等着么，我对这种场景么有预期，你可以做个 loading 动画之类的阻塞用户操作

2. 关于 Fragment 这个是问题由来已久，Fragment 需要提供容器，框架不可能解决各种容器的样式等问题，只是提供给你获取实例，不过不建议用 Fragment

3. 页面拦截器并么有全局拦截器有效，功能过于单一，针对某一特定场景，全局拦截器可以保证拦截器和目标页完全解耦，ARouter 拦截器的最佳实践是在页面的注解上使用 extra 来定义开关，拦截器里面判断开关来决定是否拦截，页面可以定义多种特性(开关)

4. 跳转完成之后，流程就结束了，没必要拿 Result

5. 目前没有这个打算，页面需要哪些参数，哪些必填哪些非必填要自己文档中声明好
