### ISSUE TITLE
安卓6.0中爆出Init provider failed! Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by admasterlu** [alibaba/ARouter#739]
最近在bugly中发现好多这种错误，机型全部为安卓6.0，详细如下：

1 java.lang.RuntimeException:Unable to start activity ComponentInfo{com.myapplication/com.myapplication.view.LoginActivity}: b.b.a.a.c.a: Init provider failed! Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2638)
3 ......
4 com.alibaba.android.arouter.exception.HandlerException:Init provider failed! Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
5 a.a.a.b.g.f.a(PlaybackStateCompatApi21.java:572)
6 com.alibaba.android.arouter.launcher._ARouter.java.lang.Object navigation(android.content.Context,com.alibaba.android.arouter.facade.Postcard,int,com.alibaba.android.arouter.facade.callback.NavigationCallback)(_ARouter.java:11)
7 com.alibaba.android.arouter.launcher.ARouter.java.lang.Object navigation(android.content.Context,com.alibaba.android.arouter.facade.Postcard,int,com.alibaba.android.arouter.facade.callback.NavigationCallback)(ARouter.java:19)
8 com.alibaba.android.arouter.facade.Postcard.java.lang.Object navigation(android.content.Context,com.alibaba.android.arouter.facade.callback.NavigationCallback)(Postcard.java:3)
9 com.alibaba.android.arouter.facade.Postcard.java.lang.Object navigation(android.content.Context)(Postcard.java:2)
10 com.alibaba.android.arouter.facade.Postcard.java.lang.Object navigation()(Postcard.java:1)
11 com.alibaba.android.arouter.launcher._ARouter.void inject(java.lang.Object)(_ARouter.java:10)
12 com.alibaba.android.arouter.launcher.ARouter.void inject(java.lang.Object)(ARouter.java:16)
13 com.myapplication.view.LoginActivity.void initViews(android.os.Bundle)(LoginActivity.java:11)
14 com.myapplication.base.BaseLifeCycleActivity.void onCreate(android.os.Bundle)(BaseLifeCycleActivity.java:8)
15 android.app.Activity.performCreate(Activity.java:6444)
16 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
17 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
18 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2720)
19 android.app.ActivityThread.access$900(ActivityThread.java:196)
20 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
21 android.os.Handler.dispatchMessage(Handler.java:111)
22 android.os.Looper.loop(Looper.java:210)
23 android.app.ActivityThread.main(ActivityThread.java:5982)
24 java.lang.reflect.Method.invoke(Native Method)
25 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
26 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

请问是哪里的问题，之前版本也都没有发现过，最近爆出来好多，没有头绪。

**Comment by admasterlu** [comment]
都是activity，没有provider，怎么会失败呢

**Comment by zhi1ong** [comment]
Init provider failed :
是执行你自己的 provider 里面的 init 方法报错了
