### ISSUE TITLE
android:launchMode="singleTop"  Autowired 如何赋值

### ISSUE THREAD

**Issue by INTKILOW** [alibaba/ARouter#746]
android:launchMode="singleTop"  Autowired 如何赋值

**Comment by hunter524** [comment]
是指重复启动一个launchModel为singleTop的Activity吗？如果是可以在onNewIntent中调用，Inject方法。

**Comment by INTKILOW** [comment]
@Override
    protected void onNewIntent(Intent intent) {
        ARouter.getInstance().inject(this);
    }
是这个样子吗，还是null

**Comment by hunter524** [comment]
请展示你的完整代码。

**Comment by xiaojinzi123** [comment]
> ```
> @Override
> protected void onNewIntent(Intent intent) {
>     ARouter.getInstance().inject(this);
> }
> ```
> 
> 是这个样子吗，还是null

你这个问题是因为注入时候一直取的是 getIntent 的 Intent 中的 bundle, 其实这时候应该是拿 
onNewIntent 方法回传的 Intent 去注入的. 换句话说就是少了一个重载方法支持传 Intent 进去
ARouter.getInstance().inject(intent);

**Comment by hunter524** [comment]
> > ```
> > @Override
> > protected void onNewIntent(Intent intent) {
> >     ARouter.getInstance().inject(this);
> > }
> > ```
> > 
> > 
> > 是这个样子吗，还是null
> 
> 你这个问题是因为注入时候一直取的是 getIntent 的 Intent 中的 bundle, 其实这时候应该是拿
> onNewIntent 方法回传的 Intent 去注入的. 换句话说就是少了一个重载方法支持传 Intent 进去
> ARouter.getInstance().inject(intent);

刚刚看了一下自己的项目，我们是这么写的。才开始没看代码一直以为系统帮我们设置了Intent，然后翻阅了一下系统代码并没有。我们需要自己设置setIntent,然后再执行注入即可。
    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
        ARouter.getInstance().inject(this);
}

ActivityThread:

`void performNewIntents(IBinder token, List<ReferrerIntent> intents, boolean andPause) {
        final ActivityClientRecord r = mActivities.get(token);
        if (r == null) {
            return;
        }

        final boolean resumed = !r.paused;
        if (resumed) {
            r.activity.mTemporaryPause = true;
            mInstrumentation.callActivityOnPause(r.activity);
        }
        deliverNewIntents(r, intents);
        if (resumed) {
            r.activity.performResume();
            r.activity.mTemporaryPause = false;
        }

        if (r.paused && andPause) {
            // In this case the activity was in the paused state when we delivered the intent,
            // to guarantee onResume gets called after onNewIntent we temporarily resume the
            // activity and pause again as the caller wanted.
            performResumeActivity(token, false, "performNewIntents");
            performPauseActivityIfNeeded(r, "performNewIntents");
        }
    }`

`private void deliverNewIntents(ActivityClientRecord r, List<ReferrerIntent> intents) {
        final int N = intents.size();
        for (int i=0; i<N; i++) {
            ReferrerIntent intent = intents.get(i);
            intent.setExtrasClassLoader(r.activity.getClassLoader());
            intent.prepareToEnterProcess();
            r.activity.mFragments.noteStateNotSaved();
            mInstrumentation.callActivityOnNewIntent(r.activity, intent);
        }
    }`

Instrumentation:

`    /**
     * @hide
     */
    public void callActivityOnNewIntent(Activity activity, ReferrerIntent intent) {
        final String oldReferrer = activity.mReferrer;
        try {
            if (intent != null) {
                activity.mReferrer = intent.mReferrer;
            }
            callActivityOnNewIntent(activity, intent != null ? new Intent(intent) : null);
        } finally {
            activity.mReferrer = oldReferrer;
        }
    }`

`public void callActivityOnNewIntent(Activity activity, Intent intent) {
        activity.onNewIntent(intent);
    }`

**Comment by xiaojinzi123** [comment]
> > > ```
> > > @Override
> > > protected void onNewIntent(Intent intent) {
> > >     ARouter.getInstance().inject(this);
> > > }
> > > ```
> > > 
> > > 
> > > 是这个样子吗，还是null
> > 
> > 
> > 你这个问题是因为注入时候一直取的是 getIntent 的 Intent 中的 bundle, 其实这时候应该是拿
> > onNewIntent 方法回传的 Intent 去注入的. 换句话说就是少了一个重载方法支持传 Intent 进去
> > ARouter.getInstance().inject(intent);
> 
> 刚刚看了一下自己的项目，我们是这么写的。才开始没看代码一直以为系统帮我们设置了Intent，然后翻阅了一下系统代码并没有。我们需要自己设置setIntent,然后再执行注入即可。
> @override
> protected void onNewIntent(Intent intent) {
> super.onNewIntent(intent);
> setIntent(intent);
> ARouter.getInstance().inject(this);
> }
> 
> ActivityThread:
> 
> `void performNewIntents(IBinder token, List intents, boolean andPause) {
> final ActivityClientRecord r = mActivities.get(token);
> if (r == null) {
> return;
> }
> 
> ```
>     final boolean resumed = !r.paused;
>     if (resumed) {
>         r.activity.mTemporaryPause = true;
>         mInstrumentation.callActivityOnPause(r.activity);
>     }
>     deliverNewIntents(r, intents);
>     if (resumed) {
>         r.activity.performResume();
>         r.activity.mTemporaryPause = false;
>     }
> 
>     if (r.paused && andPause) {
>         // In this case the activity was in the paused state when we delivered the intent,
>         // to guarantee onResume gets called after onNewIntent we temporarily resume the
>         // activity and pause again as the caller wanted.
>         performResumeActivity(token, false, "performNewIntents");
>         performPauseActivityIfNeeded(r, "performNewIntents");
>     }
> }`
> ```
> 
> `private void deliverNewIntents(ActivityClientRecord r, List<ReferrerIntent> intents) { final int N = intents.size(); for (int i=0; i<N; i++) { ReferrerIntent intent = intents.get(i); intent.setExtrasClassLoader(r.activity.getClassLoader()); intent.prepareToEnterProcess(); r.activity.mFragments.noteStateNotSaved(); mInstrumentation.callActivityOnNewIntent(r.activity, intent); } }`
> 
> Instrumentation:
> 
> ` /** * @hide */ public void callActivityOnNewIntent(Activity activity, ReferrerIntent intent) { final String oldReferrer = activity.mReferrer; try { if (intent != null) { activity.mReferrer = intent.mReferrer; } callActivityOnNewIntent(activity, intent != null ? new Intent(intent) : null); } finally { activity.mReferrer = oldReferrer; } }`
> 
> `public void callActivityOnNewIntent(Activity activity, Intent intent) { activity.onNewIntent(intent); }`

你那么做是有问题的, 系统的 Intent 是原先上个界面传过来的数据, 而你 onNewIntent 是新的界面传给你的, 你怎么能够吧新的覆盖老的呢？万一你有的地方要用到 getIntent 去获取数据呢？
所以还是上面所说, 注入的方式少了一个方法, 参数是 Intent

**Comment by zhi1ong** [comment]
可以自己合并一下 Intent
