### ISSUE TITLE
Autowired 继承取不到值

### ISSUE THREAD

**Issue by Break369** [alibaba/ARouter#747]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**
编写一个父类activity A，A里面使用Autowired进行获取值，采用路由跳转A，Autowired里面的值能够正常获取，但是，编写B activity 继承自A，然后跳转到B activity，日志显示Autowired里面的值都是null，为啥

**Comment by qrc0403** [comment]
我也遇到了，使用url跳转时查看源码发现，LogisticsCenter.completion(Postcard)中，routeMeta.getParamsType()取的需要赋值的并没有父类的参数，xxx$$ARouter$$Autowired.inject(Object)方法中也没有赋值父类的参数，望作者修复下！

**Comment by owant** [comment]
是的。因为这个inject传递的是this。而这个this是子类

**Comment by zhi1ong** [comment]
dev 中已经修复，需要同时升级 compiler 和 api，不日merge到master
