### ISSUE TITLE
Fragment 中 开启Activity,在Fragment中不回调onActivityResult

### ISSUE THREAD

**Issue by nevermore1314** [alibaba/ARouter#75]
1.Fragment 中 开启Activity带requestCode ,开启的Activity关闭后,不会回调Fragment中的onActivityResult.
只会调用Fragment 所在Activity的onActivityResult.

2.用系统自带的开启Activity方式是Activity和Fragment中的onActivityResult都会执行.

3.现在需求在Fragment 中开启Activity然后在Activity关闭后回调fragment中的方法执行相应功能就没法做了.

4.是否会在近期版本修复这个问题?或者有什么其他的解决方法?

**Comment by zhi1ong** [comment]
有两种情况：
 1. Fragment中调用，Activity中接收结果：需要调用 getActivity().startActivityForResult()
 2. Fragment中调用，Fragment中接收结果：需要调用 this.startActivityForResult()，且在Activity的onActivityResult()中调用super.onActivityResult()

ARouter目前没有拿Fragment的实例，Fragment不是Context,兼容的话，写起来比较难看，所以ARouter是第一种情况，解决这个问题，推荐你可以 

1. 通过广播
2. 在Activity中转发这个事件，比方说让Fragment统一依赖一个接口，然后在Activity中转发。

**Comment by 4332weizi** [comment]
很需要这个方法:worried:
