### ISSUE TITLE
使用adb 命令打开 SchameFilterActivity url 参数解析问题

### ISSUE THREAD

**Issue by NiLuogege** [alibaba/ARouter#750]
### 问题
我使用adb命令去打开 SchameFilterActivity（监听Scheme事件的Activity）。 虽然activity可以正常打开，但是 data携带的参数就只解析出来了个一个剩下的会在控制台报 “XXX参数”不是内部或外部命令，我知道这和ARouter框架本身没有关系，就是想看看各路大神有没有知道原因能够解决问题的。

### 完整adb命令
```
adb shell am start -a android.intent.action.VIEW -d airent2://www.xxxxxx.com/app/productxxxxNew?productId=284&rentId=1772&schedule_id=16
```

### 截图
![微信截图_20191018094432](https://user-images.githubusercontent.com/17189584/67059828-1a927780-f18d-11e9-9181-ae2c9d77110c.png)

**Comment by FreeLoopC** [comment]
看样子是&字符的原因, 把后面的参数名当成命令程序了

**Comment by NiLuogege** [comment]
@FreeLoopC 现象是这个现象但是就不知道怎么解决 0.0

**Comment by zhi1ong** [comment]
希望你已经解决了这个问题，可以通过 //n 换行就好了
