### ISSUE TITLE
ARouter::ARouter init logistics center exception!

### ISSUE THREAD

**Issue by LRdeath** [alibaba/ARouter#752]
## Look at here

Caused by:
--
com.alibaba.android.arouter.exception.HandlerException:ARouter::ARouter init logistics center exception! [**Package manager has died**]
com.alibaba.android.arouter.core.LogisticsCenter.init(SourceFile:208)
com.alibaba.android.arouter.launcher._ARouter.init(SourceFile:59)
com.alibaba.android.arouter.launcher.ARouter.init(SourceFile:41)

类似的**android.os.DeadObjectException**的崩溃也出现在init()好多次；
能否在ARouter框架中兼容一下这个错误；
或者有什么好的解决方式吗?

**Comment by zhi1ong** [comment]
及其少见的情况
