### ISSUE TITLE
拦截问题

### ISSUE THREAD

**Issue by NerdAnonymous** [alibaba/ARouter#753]
类似于#436 这样的问题，多次拦截会造成  LogisticsCenter.executor.execute 等待执行，停在一个界面不动，然后延迟一段时间后，会连续执行这个方法，打开多次界面

**Comment by adonis-lsh** [comment]
这个问题解决了吗?

**Comment by adonis-lsh** [comment]
我明白了,她里面有一个线程池,超过数量就会在那里面等着,如果你一直拦截,而不去释放的话,就会有超时的时间

**Comment by NerdAnonymous** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"笨呆呆"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 晚上10:08
收件人:&nbsp;"alibaba/ARouter"<ARouter@noreply.github.com&gt;;
抄送:&nbsp;""<1415157631@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/ARouter] 拦截问题 (#753)




我明白了,她里面有一个线程池,超过数量就会在那里面等着,如果你一直拦截,而不去释放的话,就会有超时的时间
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.




是的

**Comment by szn0212** [comment]
“超过数量就会在那里面等着,如果你一直拦截,而不去释放的话,就会有超时的时间”，请问一下要怎么释放呢?

**Comment by adonis-lsh** [comment]
> “超过数量就会在那里面等着,如果你一直拦截,而不去释放的话,就会有超时的时间”，请问一下要怎么释放呢?

callback.onContinue(null)
