### ISSUE TITLE
【建议】对外暴露的服务如果可以声明Scope(单例/每次创建)就更完美了

### ISSUE THREAD

**Issue by zengfantian** [alibaba/ARouter#756]
如题，在大型App中拆解的模块细粒度比较细，对外暴露的服务以及其他组件会比较多，如果每次访问其他模块的服务都创建一个实例的话会比较耗时，部分服务可以设置成单例，维护全局的实例缓存，只初始化一次即可，下次访问直接从缓存中拿，开发者在合适的时机自行release释放清理缓存，类似Spring的bean管理效果

**Comment by zhi1ong** [comment]
说的好，实际上就是这样的。
