### ISSUE TITLE
不支持 Fragment 使用 requestCode 可获取返回值的方式去启动另一个 Activity 么

### ISSUE THREAD

**Issue by lasttimes** [alibaba/ARouter#76]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhi1ong** [comment]
fragment中跳转的时候，没有拿到Fragment的实例，所以调用的是Activity中的startActivity，可以在Activity容器中转发一下forResult事件
