### ISSUE TITLE
调用navigation不传activity参数时setFlags无效

### ISSUE THREAD

**Issue by zhpanvip** [alibaba/ARouter#760]
// _ARouter
if (-1 != flags) {
                    intent.setFlags(flags);
                } else if (!(currentContext instanceof Activity)) {    // Non activity, need less one flag.
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
   }
这段代码在flags!=-1的情况下intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)不会被添加，造成非Activity无法启动目的页面。

**Comment by xing634325131** [comment]
这个问题不处理？

**Comment by zhpanvip** [comment]
哈哈，估计作者最近都没来维护这个库了吧。

**Comment by littlecurl** [comment]
瞎说，昨天下午，作者集中回复了一波问题。你watch一下仓库就能收到消息了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhpanvip"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 中午1:35
收件人:&nbsp;"alibaba/ARouter"<ARouter@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/ARouter] 调用navigation不传activity参数时setFlags无效 (#760)




哈哈，估计作者最近都没来维护这个库了吧。

**Comment by ZhangJian96** [comment]
这个不能算是bug，ARouter内部也是使用Intent跳转的，当你直接用navigation()跳转时，传入的Context是null，这个时候会使用初始化ARouter的传入的Context作为Intent的上下文，而初始化的这个方法传入的Context是Application。使用Application作为上下文跳转的时候肯定要添加Intent.FLAG_ACTIVITY_NEW_TASK的flag,所以就只有抛弃你设置的Flag而给予Intent.FLAG_ACTIVITY_NEW_TASK。所以使用navigation()只适用于跳转一个新的Activity栈的场景。
关键代码：
```
//_ARouter.java

final Context currentContext = null == context ? mContext : context;  //context是navigation()方法传入的上下文，mContext是初始化传入的Application
......
 final Intent intent = new Intent(currentContext, postcard.getDestination());
 int flags = postcard.getFlags();
                if (-1 != flags) {
                    intent.setFlags(flags);
                } else if (!(currentContext instanceof Activity)) {    // Non activity, need less one flag.
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                }
```
其实即使不看源码，从Intent本身也能分析出来。

**Comment by ZhangJian96** [comment]
这个不能算是bug。
ARouter本质上也是用Intent跳转的，当使用navigation()跳转时，未传入Context参数，这个时候ARouter的设计是拿了初始化传入的Context，而初始化传入的Context是Application，我们知道：
**当通过Application跳转时必须带上Intent.FLAG_ACTIVITY_NEW_TASK这个FLAG**。
这里如果直接使用Application启动Activity而不加NEW_TASK是会报错的，因为新启动的Activity不是属于任何一个Activity栈的(通过Activity A启动的Activity B默认情况下是属于A所在的栈的，除非加了其他的flag，launchModel也是通过转为flag处理的)。
关键代码：
```
//_ARouter.java
final Context currentContext = null == context ? mContext : context; //这里context是navigation传入的Context,mContext是初始化传入的Aplication
......
  final Intent intent = new Intent(currentContext, postcard.getDestination());
                // Set flags.
                int flags = postcard.getFlags();
                if (-1 != flags) {
                    intent.setFlags(flags);
                } else if (!(currentContext instanceof Activity)) {    // Non activity, need less one flag.
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                }
```
当然，这里没有将传入的flag和Intent.FLAG_ACTIVITY_NEW_TASK做与运算得到新的newFlag应该是考虑到了newFlag并不是开发者期望的FLAG，而且navigation()应该也只是提供给需要在新栈启动Activity的场景的一种简易写法，而不是任何场景都适用。
其实不看源码，从Intent本身也是可以推测出的。

**Comment by ZhangJian96** [comment]
> 这个问题不处理？

https://github.com/alibaba/ARouter/issues/760#issuecomment-573624712

**Comment by zhi1ong** [comment]
不能算 bug，倒是可以优化一下
