### ISSUE TITLE
连续拦截多次后路由无效

### ISSUE THREAD

**Issue by CK875430315** [alibaba/ARouter#763]
连续拦截多次后路由无效

**Comment by CK875430315** [comment]
注释调拦截器里的业务逻辑代码后，业务逻辑居然还是生效的，卸载了app重装都不行，只能删除工程的build文件夹后重新构建才可以，难道是把配置都缓存到了里面么？

**Comment by szn0212** [comment]
我也遇到了这个问题，请问是怎么解决的啊？@CK875430315
