### ISSUE TITLE
建议:移除json解析库依赖

### ISSUE THREAD

**Issue by CLD1994** [alibaba/ARouter#77]
可以不依赖json库吗？项目里已经有其他json库了，方法数即将超限。强迫症很难受。。。

**Comment by zhi1ong** [comment]
方法数超过65535的话，用Google的multidex-support可以很容易解决的，FastJson 是目前java-base中差不多最好的json解析库了，推荐你也用起来

**Comment by zhi1ong** [comment]
arouter_compiler_version=1.1.1.1
arouter_api_version=1.2.0.3

预发版，去掉了fastjson的依赖，传递自定义对象的时候，需要实现SerializationService

**Comment by CLD1994** [comment]
好极了！十分给力！
