### ISSUE TITLE
可以通过Activity.class获取当前页面的path值吗

### ISSUE THREAD

**Issue by BigBigDeBoy** [alibaba/ARouter#772]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by zhi1ong** [comment]
不能，Route 是编译期注解

**Comment by BigBigDeBoy** [comment]
@zhi1ong 有这个需求该怎么办 给点建议

**Comment by superchow** [comment]
同这个需求
