### ISSUE TITLE
@Autowired 失效没有获取的到参数的解决办法

### ISSUE THREAD

**Issue by MySai** [alibaba/ARouter#774]
看了很多评论说什么名字错了什么。 我的情况应该有人遇到过 
   A类  withString("name", "android")

B类   @Autowired(name = "name")
           public String name = "";
或者
@Autowired  
public String name = "";

都获取不到参数但是  getIntent().getStringExtra("name")。 可以获取参数。弄得头疼，后面发现是因为初始化的问题 。模块化除了主  MyApplication 里
 //Arouter 初始化
 ARouter.init(application);
后面每个模块我都是父类写了
ARouter.getInstance().inject(this);  
这样获取就没问题了

**Comment by zhi1ong** [comment]
inject 的原理就是在 .inject(this) 里面执行的赋值，自然要任何的 Activity 的 onCreate 都要调用这个 inject，最佳实践就是在 BaseActivity加
