### ISSUE TITLE
有种情况无法注入，注入的方法都不走，但是手动可以获取

### ISSUE THREAD

**Issue by wanghaibao123** [alibaba/ARouter#776]
![image](https://user-images.githubusercontent.com/14246724/71350762-0021b380-25ad-11ea-8d64-cd4fbb961e06.png)

**Comment by sceneren** [comment]
我也遇到了一样的问题

**Comment by Aurora-zls** [comment]
整理了一下
/**
     * Arouter Autowired注入的时候在存在kotlin-java兼容性问题
     * 针对基本数据类型的传递
     * var showBadge: Boolean? = null  注入失败
     * var showBadge: Boolean? = false 注入成功
     * 原因：
     * 在arouter生成代码中 获取注入变量通过
     * substitute.showBadge = substitute.getIntent().getBooleanExtra("showBadge", substitute.showBadge)
     * 对于基本数据类型的获取接口都带有默认参数 如 getBooleanExtra(String name, boolean defaultValue)
     * 问题出在默认参数 对应java boolean类型 没有null的概念
     * 报错 can't unbox a null value
     */

**Comment by zhi1ong** [comment]
是一个 bug，kotlin 注入不能设置默认 null，会有拆箱异常，1.5.2 修复
