### ISSUE TITLE
使用ARouter在华为P20手机上内联报错

### ISSUE THREAD

**Issue by yuqirong** [alibaba/ARouter#779]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Tombstone maker: 'xCrash 2.4.8'
Crash type: 'native'
Start time: '2019-12-25T08:46:59.283+0800'
Crash time: '2019-12-25T08:47:01.343+0800'
App ID: 'com.orange.note'
App version: '5.54'
Rooted: 'No'
API level: '29'
OS version: '10'
Kernel version: 'Linux version 4.14.116 #1 SMP PREEMPT Thu Nov 28 20:52:01 CST 2019 (armv8l)'
ABI list: 'arm64-v8a,armeabi-v7a,armeabi'
Manufacturer: 'HUAWEI'
Brand: 'HUAWEI'
Model: 'EML-AL00'
Build fingerprint: 'HUAWEI/EML-AL00/HWEML:10/HUAWEIEML-AL00/10.0.0.143C00:user/release-keys'
ABI: 'arm'
pid: 26406, tid: 26412, name: Jit thread pool  >>> com.orange.note <<<
signal 6 (SIGABRT), code 0 (SI_USER), fault addr --------
Abort message: 'Inlined method resolution crossed dex file boundary: from void com.alibaba.android.arouter.routes.ARouter$$Group$$mine.loadInto(java.util.Map) in /data/app/com.orange.note-kBpyhNTWLE5kaJQM7fyXSg==/base.apk/0xe1946690 to void com.alibaba.android.arouter.rou'
    r0  f553e868  r1  00000080  r2  0000000e  r3  00000000
    r4  00000000  r5  00000000  r6  00000002  r7  000000f0
    r8  00000043  r9  e18054f0  r10 f1eee17c  r11 00000001
    ip  e18054a0  sp  e1805490  lr  f0837695  pc  f1e91ef0

backtrace:
    #00 pc 0004eef0  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
    #01 pc 000ee691  /apex/com.android.runtime/lib/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+88)
    #02 pc 00125b7b  /apex/com.android.runtime/lib/libart-compiler.so (_ZNK3art10HLoadClass21InstructionDataEqualsEPKNS_12HInstructionE+594)
    #03 pc 0009391b  /apex/com.android.runtime/lib/libart-compiler.so (_ZN3art19GlobalValueNumberer15VisitBasicBlockEPNS_11HBasicBlockE+1030)
    #04 pc 000934af  /apex/com.android.runtime/lib/libart-compiler.so (_ZN3art15GVNOptimization3RunEv+270)
    #05 pc 000ab195  /apex/com.android.runtime/lib/libart-compiler.so (_ZNK3art18OptimizingCompiler16RunOptimizationsEPNS_6HGraphEPNS_13CodeGeneratorERKNS_18DexCompilationUnitEPNS_12PassObserverEPNS_24VariableSizedHandleScopeEPKNS_15OptimizationDefEj+128)
    #06 pc 000aadc7  /apex/com.android.runtime/lib/libart-compiler.so (_ZNK3art18OptimizingCompiler16RunOptimizationsEPNS_6HGraphEPNS_13CodeGeneratorERKNS_18DexCompilationUnitEPNS_12PassObserverEPNS_24VariableSizedHandleScopeE+666)
    #07 pc 000aa3fb  /apex/com.android.runtime/lib/libart-compiler.so (_ZNK3art18OptimizingCompiler10TryCompileEPNS_14ArenaAllocatorEPNS_10ArenaStackEPNS_19CodeVectorAllocatorERKNS_18DexCompilationUnitEPNS_9ArtMethodEbbPNS_24VariableSizedHandleScopeE+3886)
    #08 pc 001dd0f9  /apex/com.android.runtime/lib/libart-compiler.so (_ZN3art18OptimizingCompiler10JitCompileEPNS_6ThreadEPNS_3jit12JitCodeCacheEPNS_9ArtMethodEbbPNS3_9JitLoggerE+1272)
    #09 pc 001b292d  /apex/com.android.runtime/lib/libart-compiler.so (_ZN3art3jit11JitCompiler13CompileMethodEPNS_6ThreadEPNS_9ArtMethodEbb+140)
    #10 pc 001b2897  /apex/com.android.runtime/lib/libart-compiler.so (jit_compile_method+14)
    #11 pc 00262877  /apex/com.android.runtime/lib/libart.so (_ZN3art3jit3Jit13CompileMethodEPNS_9ArtMethodEPNS_6ThreadEbb+438)
    #12 pc 00264eff  /apex/com.android.runtime/lib/libart.so (_ZN3art3jit14JitCompileTask3RunEPNS_6ThreadE+438)
    #13 pc 003d6387  /apex/com.android.runtime/lib/libart.so (_ZN3art16ThreadPoolWorker3RunEv+54)
    #14 pc 003d5fff  /apex/com.android.runtime/lib/libart.so (_ZN3art16ThreadPoolWorker8CallbackEPv+90)
    #15 pc 0009c1a7  /apex/com.android.runtime/lib/bionic/libc.so (_ZL15__pthread_startPv+20)
    #16 pc 00055657  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)

build id:
    /apex/com.android.runtime/lib/bionic/libc.so (BuildId: f2470da1a22265f8104ce6bb9bcaf63e. FileSize: 921952. LastModified: 1970-01-01T08:00:00.000+0800. MD5: b469c0d7633deabfb0a537c1503ecaf6)
    /apex/com.android.runtime/lib/libart.so (BuildId: 2414152b7788a9b8520d543b931388a5. FileSize: 6210072. LastModified: 1970-01-01T08:00:00.000+0800. MD5: b981131029d54e53f8a5c82f54ff0659)
    /apex/com.android.runtime/lib/libart-compiler.so (BuildId: 96879bd11c4b065c7bc8730da3ed8d3f. FileSize: 2478244. LastModified: 1970-01-01T08:00:00.000+0800. MD5: 5632ca5dff20dc5bf90203887642ba38)

应用没有接入热修复、插件化，有使用腾讯乐固加固了，用户反馈多次卸载重装都不行。

**Comment by yuqirong** [comment]
com.alibaba.android.arouter.routes.ARouter$$Group$$mine 类

``` java
/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER. */
public class ARouter$$Group$$mine implements IRouteGroup {
  @Override
  public void loadInto(Map<String, RouteMeta> atlas) {
    atlas.put("/mine/about", RouteMeta.build(RouteType.ACTIVITY, AboutChengguoActivity.class, "/mine/about", "mine", null, -1, -2147483648));
    atlas.put("/mine/auth_code", RouteMeta.build(RouteType.ACTIVITY, AuthCodeActivity.class, "/mine/auth_code", "mine", null, -1, -2147483648));
    atlas.put("/mine/bind_phone", RouteMeta.build(RouteType.ACTIVITY, BindPhoneActivity.class, "/mine/bind_phone", "mine", null, -1, -2147483648));
    atlas.put("/mine/bind_teacher", RouteMeta.build(RouteType.ACTIVITY, BindTeacherActivity.class, "/mine/bind_teacher", "mine", null, -1, -2147483648));
    atlas.put("/mine/choose_grade", RouteMeta.build(RouteType.ACTIVITY, GradeActivity.class, "/mine/choose_grade", "mine", new java.util.HashMap<String, Integer>(){{put("fromBatchTag", 0); put("new_reg", 0); put("selectedId", 8); }}, -1, -2147483648));
    atlas.put("/mine/contact_us", RouteMeta.build(RouteType.ACTIVITY, ContactUsActivity.class, "/mine/contact_us", "mine", null, -1, -2147483648));
    atlas.put("/mine/feedback", RouteMeta.build(RouteType.ACTIVITY, FeedbackActivity.class, "/mine/feedback", "mine", null, -1, -2147483648));
    atlas.put("/mine/function_settings", RouteMeta.build(RouteType.ACTIVITY, FunctionSettingActivity.class, "/mine/function_settings", "mine", null, -1, -2147483648));
    atlas.put("/mine/info_modify", RouteMeta.build(RouteType.ACTIVITY, InfoModifyActivity.class, "/mine/info_modify", "mine", null, -1, -2147483648));
    atlas.put("/mine/mine", RouteMeta.build(RouteType.ACTIVITY, MineActivity.class, "/mine/mine", "mine", null, -1, -2147483648));
    atlas.put("/mine/mine_service", RouteMeta.build(RouteType.PROVIDER, MineRemoteImpl.class, "/mine/mine_service", "mine", null, -1, -2147483648));
    atlas.put("/mine/modify_name", RouteMeta.build(RouteType.ACTIVITY, ModifyNameActivity.class, "/mine/modify_name", "mine", null, -1, -2147483648));
    atlas.put("/mine/province", RouteMeta.build(RouteType.ACTIVITY, ProvActivity.class, "/mine/province", "mine", null, -1, -2147483648));
    atlas.put("/mine/upload_log", RouteMeta.build(RouteType.ACTIVITY, LogUploadActivity.class, "/mine/upload_log", "mine", null, -1, -2147483648));
    atlas.put("/mine/user_agreement", RouteMeta.build(RouteType.ACTIVITY, UserAgreementActivity.class, "/mine/user_agreement", "mine", null, -1, -2147483648));
    atlas.put("/mine/user_privacy", RouteMeta.build(RouteType.ACTIVITY, UserPrivacyActivity.class, "/mine/user_privacy", "mine", null, -1, -2147483648));
  }
}
```

**Comment by fantasybei** [comment]
我在华为Mate20上也遇到了同样的问题。

**Comment by MelonWXD** [comment]
@yuqirong @fantasybei  遇到同样的问题了  请问两位解决了吗？

**Comment by zhangchuanchuan** [comment]
我联系了提问者，可能跟加固有关。

**Comment by MelonWXD** [comment]
> 我联系了提问者，可能跟加固有关。

@zhangchuanchuan  是的 之前咨询过  好像用的都是乐固，才导致的问题 
前置条件可能还跟项目迁移到androidx有关
