### ISSUE TITLE
Arouter一直无法跳转，出现There is no route.....

### ISSUE THREAD

**Issue by razerdp** [alibaba/ARouter#78]
开发大大你好，最近开始使用Arouter

出现问题的项目可以直接看源码的，因为这是一个开源项目：

他们分别是：

目标activity:[PhotoMultiBrowserActiviry](https://github.com/razerdp/FriendCircle/blob/main-dev/photoselect/src/main/java/razerdp/github/com/photoselect/PhotoMultiBrowserActivity.java)

调用的adapter:[PhotoSelectAdapter](https://github.com/razerdp/FriendCircle/blob/main-dev/photoselect/src/main/java/razerdp/github/com/adapter/PhotoSelectAdapter.java) line:203

根据文档，我已经写好了注解，没有主动分组，相关dependence也有了，GroupIndex =1，但还是没法跳转

相关截图如下(国内图床，因为怕无法显示出图片，所以把连接也一同附上)：

gradle:
![gradle](http://i1.piimg.com/4851/fc27b4db186e5bf9.png)

[gradle图片链接](http://i1.piimg.com/4851/fc27b4db186e5bf9.png)

init:
![init](http://i1.piimg.com/4851/7645b364545b90fc.png)

[initLogcat图片链接](http://i1.piimg.com/4851/7645b364545b90fc.png)

跳转:
![跳转](http://i1.piimg.com/4851/bbdbb279de65ca42.png)

[跳转Logcat图片链接](http://i1.piimg.com/4851/bbdbb279de65ca42.png)

**Comment by razerdp** [comment]
噢，对了，还有这个控制台的：

![](http://i1.piimg.com/4851/dd065c9eea228efc.png)

[图片连接](http://i1.piimg.com/4851/dd065c9eea228efc.png)

**Comment by zhi1ong** [comment]
这些基础问题可以去加讨论群提问，应该是配置问题，会有人回答你的，群号在文档最下面
