### ISSUE TITLE
关于每个module在编译期间生成的RouterMap整合问题

### ISSUE THREAD

**Issue by dndxxiangyu** [alibaba/ARouter#780]
ARouter在整合各个module编译期间生成的RouterMap的时候，是在ARouter.init()的时候去dex文件中查找具体的class，虽然这块有通过sp存储来做优化，但对于第一次使用，还是会存在通过dex中查找RouterrMap class的过程。
所以：是否可以通过Transfrom，在编译期间就查找到所有的RouterMap，然后注入到Arouter.init()方法中，免去自爱运行时从dex查找class的过程呢？
这是我实现的一个小demo：https://github.com/dndxxiangyu/accumulate/blob/master/Android%E5%9F%BA%E4%BA%8EGradle%E6%8F%92%E4%BB%B6%E7%9A%84%E6%A8%A1%E5%9D%97%E5%8C%96map%E6%95%B4%E5%90%88.md
好处：可以避免查找dex

**Comment by FioneraGH** [comment]
ARouter gradle plugin

**Comment by Paul-Guo** [comment]
classpath "com.alibaba:arouter-register:" 这个好像就是用来解决您提的问题的吧？
