### ISSUE TITLE
跪求支持增量变异

### ISSUE THREAD

**Issue by smallSohoSolo** [alibaba/ARouter#786]
w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: com.alibaba.android.arouter.compiler.processor.AutowiredProcessor (NON_INCREMENTAL), com.alibaba.android.arouter.compiler.processor.InterceptorProcessor (NON_INCREMENTAL), com.alibaba.android.arouter.compiler.processor.RouteProcessor (NON_INCREMENTAL), com.airbnb.epoxy.EpoxyProcessor (NON_INCREMENTAL), com.smile.gifshow.annotation.invoker.processing.InvokerProcessor (NON_INCREMENTAL), com.google.auto.service.processor.AutoServiceProcessor (NON_INCREMENTAL).

**Comment by zhi1ong** [comment]
支持了
