### ISSUE TITLE
使用ARouter.getInstance().build("/***/***").navigation()时概率出现部分无法跳转情况

### ISSUE THREAD

**Issue by RainliFu** [alibaba/ARouter#787]
使用ARouter.getInstance().build("/***/***").navigation()时概率出现部分无法跳转情况，
测试过程中发现如果navigation不传递context参数的时候经常会出现各种奇怪的点击无响应状况，调试后发现是ARouter跳转导致的，我把项目中用到的地方都添加了context参数，不知道其他的人有没有遇到过这个现象

**Comment by stonehiy** [comment]
没有传context  我是release包下出现这个问题，必须杀掉应用重新打开才可以

**Comment by zhi1ong** [comment]
ARouter 最终还是调用了 startActivity, 还是要检查一下你的页面的启动模式
