### ISSUE TITLE
神奇的重复跳转的bug

### ISSUE THREAD

**Issue by luanshinicko** [alibaba/ARouter#788]
我的业务是这样的 在A页面点击继续跳转A页面，当前页面是带参数的，并且启动模式是默认的，神奇的一幕出现了，无法跳转，我debug到源码发现一路下去已经执行到了最后的跳转逻辑，没有头绪，于是我听从同事建议加了NavigationCallback,发现又可以跳转了。。去掉callback又无法跳转。。很神奇，我看了下源码 并未发现callback有额外的处理。请教一下是什么原因~~

**Comment by luanshinicko** [comment]
我继续看了下源码，问题应该和callback无关，当传入callback的时候 同时要传入一个activity实例，这个实例最后是作为了ActivityCompat.startActivity(currentContext, intent, postcard.getOptionsBundle());这行代码的currentContext，如果不传入activity会把application作为currentContext，貌似是这个区别导致的，但是我从首页跳转到A页面同样没传入activity，也能跳转呀，为什么当前页面就不行呢，很疑惑

**Comment by lmDai** [comment]
应该是跟启动模式有关
