### ISSUE TITLE
我使用ARouter ，但有些需求想使用aop，就引入了aspectjx，导致组件化失效。

### ISSUE THREAD

**Issue by sunbest110** [alibaba/ARouter#789]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by che5277** [comment]
刚好我做了这一块。测试是可以的。我使用的是aspectjrt:1.9.2，和arouter-api:1.4.1，gradle5.6.4。如果你也使用相同的环境。
asp在基础model的配置是：

android.libraryVariants.all { variant ->
    LibraryPlugin plugin = project.plugins.getPlugin(LibraryPlugin)
    JavaCompile javaCompile = variant.javaCompile
    javaCompile.doLast {
        String[] args = ["-showWeaveInfo",
                         "-1.5",
                         "-inpath", javaCompile.destinationDir.toString(),
                         "-aspectpath", javaCompile.classpath.asPath,
                         "-d", javaCompile.destinationDir.toString(),
                         "-classpath", javaCompile.classpath.asPath,
                         "-bootclasspath", plugin.project.android.bootClasspath.join(
                File.pathSeparator)]

        MessageHandler handler = new MessageHandler(true);
        new Main().run(args, handler)

        def log = project.logger
        for (IMessage message : handler.getMessages(null, true)) {
            switch (message.getKind()) {
                case IMessage.ABORT:
                case IMessage.ERROR:
                case IMessage.FAIL:
                    log.error message.message, message.thrown
                    break;
                case IMessage.WARNING:
                case IMessage.INFO:
                    log.info message.message, message.thrown
                    break;
                case IMessage.DEBUG:
                    log.debug message.message, message.thrown
                    break;
            }
        }
    }
}

在app.gradle

//aspectJ
//在构建工程时，执行编织
android.applicationVariants.all { variant ->
    if (!variant.buildType.isDebuggable()) {
        logger.debug("Skipping non-debuggable build type '${variant.buildType.name}'.")
        return;
    }

    JavaCompile javaCompile = variant.javaCompile
    javaCompile.doLast {
        String[] args = ["-showWeaveInfo",
                         "-1.8",
                         "-inpath", javaCompile.destinationDir.toString(),
                         "-aspectpath", javaCompile.classpath.asPath,
                         "-d", javaCompile.destinationDir.toString(),
                         "-classpath", javaCompile.classpath.asPath,
                         "-bootclasspath", project.android.bootClasspath.join(File.pathSeparator)]
        logger.debug "ajc args: " + Arrays.toString(args)

        MessageHandler handler = new MessageHandler(true);
        new Main().run(args, handler);
        for (IMessage message : handler.getMessages(null, true)) {
            switch (message.getKind()) {
                case IMessage.ABORT:
                case IMessage.ERROR:
                case IMessage.FAIL:
                    logger.error message.message, message.thrown
                    break;
                case IMessage.WARNING:
                    logger.warn message.message, message.thrown
                    break;
                case IMessage.INFO:
                    logger.info message.message, message.thrown
                    break;
                case IMessage.DEBUG:
                    logger.debug message.message, message.thrown
                    break;
            }
        }
    }
}

**Comment by xiachengcheng** [comment]
十分遗憾的是，这个库和hujiang的[AspectJX](https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx)库存在冲突，在一个新建的demo工程上，先引入本库；
再引入AspectJX，并在app.gradle中使用插件apply plugin: 'android-aspectjx'；
重新同步工程并进行debug build后，会在运行app时crash：
 Process: com.example.cheng.test, PID: 28274
    java.lang.RuntimeException: Unable to instantiate application com.example.cheng.test.App: java.lang.ClassNotFoundException: Didn't find class "com.example.cheng.test.App" on path: DexPathList[[zip file "/data/app/com.example.cheng.test-LmmzUFPtQYZLOdVKbTHOHg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.cheng.test-LmmzUFPtQYZLOdVKbTHOHg==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
发现App.class没有被打包进apk。

我猜测可能是两者都是用了transform api，而彼此在一些处理上出现了些许冲突。
这个不能算是ARouter的问题，不过如果能提供一些解决思路就十分棒了。

**Comment by melancholyboy** [comment]
我们公司的项目同时使用了ARouter和hujiang的AspectJx库没有存在冲突


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 上午10:46
收件人:&nbsp;"alibaba/ARouter"<ARouter@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/ARouter] 我使用ARouter ，但有些需求想使用aop，就引入了aspectjx，导致组件化失效。 (#789)





 
十分遗憾的是，这个库和hujiang的AspectJX库存在冲突，在一个新建的demo工程上，先引入本库；
 再引入AspectJX，并在app.gradle中使用插件apply plugin: 'android-aspectjx'；
 重新同步工程并进行debug build后，会在运行app时crash：
 Process: com.example.cheng.test, PID: 28274
 java.lang.RuntimeException: Unable to instantiate application com.example.cheng.test.App: java.lang.ClassNotFoundException: Didn't find class "com.example.cheng.test.App" on path: DexPathList[[zip file "/data/app/com.example.cheng.test-LmmzUFPtQYZLOdVKbTHOHg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.cheng.test-LmmzUFPtQYZLOdVKbTHOHg==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
 发现App.class没有被打包进apk。
 
我猜测可能是两者都是用了transform api，而彼此在一些处理上出现了些许冲突。
 这个不能算是ARouter的问题，不过如果能提供一些解决思路就十分棒了。

**Comment by xiachengcheng** [comment]
@melancholyboy 您好，这个是我demo实验的配置，能否帮我看下我的使用是否存在问题吗，谢谢。
project/build.gradle:
 ```
dependencies {
        classpath "com.android.tools.build:gradle:$build_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.10'
    }
```
app/build.gradle 
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'android-aspectjx'

android {
    compileSdkVersion 28

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.example.cheng.test"
        minSdkVersion min_sdk
        targetSdkVersion target_sdk
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

androidExtensions {
    experimental = true
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'

    implementation project(':api')
    implementation project(':common')
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'com.alibaba:arouter-api:1.4.0'
    kapt 'com.alibaba:arouter-compiler:1.2.1'
}


kapt {
    arguments {
        arg("moduleName", project.getName())
    }
}
```
MainActivity.kt: 
```
package com.example.cheng.test
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.alibaba.android.arouter.facade.annotation.Route
import com.alibaba.android.arouter.launcher.ARouter
import kotlinx.android.synthetic.main.activity_main.*

@Route(path = "/text/activity/main")
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        foo()
    }
    fun foo() {
        id_text.text = "mainActivity"
        id_text.setOnClickListener {
            ARouter.getInstance().build("/text/activity/second")
                .withLong("KEY1", 100)
                .navigation()
        }
    }
}
```
AspectJx.java:
```
package com.example.cheng.test;
import android.util.Log;
import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.After;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
@Aspect
public class AspectJx {
    @Pointcut("call(* *.MainActivity.foo(..))")
    public void point1() {
    }

    @After("point1()")
    public void hook(JoinPoint joinPoint) throws Throwable {
        Log.e("TEST123", joinPoint.getSignature().toLongString());
    }
}
```
现在的现象是：
如果相同build.gradle配置，没有AspectJx.java时，在build的时候会出现app.java没有打包进apk，造成app运行时crash
如果加入了aspectJx.java，能够正常build过，app正常运行，检查ajx输出文件有正常生成对应的文件，但是实际上并没有织入aspectj的功能，例如上面的Log并没有生效。

**Comment by melancholyboy** [comment]
org.aspectj.aspectjrt:1.9.5这个依赖库，有依赖吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 中午11:12
收件人:&nbsp;"alibaba/ARouter"<ARouter@noreply.github.com&gt;;
抄送:&nbsp;"全球变冷@宇宙之大@不语"<397432103@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/ARouter] 我使用ARouter ，但有些需求想使用aop，就引入了aspectjx，导致组件化失效。 (#789)





 
@melancholyboy 您好，这个是我demo实验的配置，能否帮我看下我的使用是否存在问题吗，谢谢。
 project/build.gradle:
 dependencies {        classpath "com.android.tools.build:gradle:$build_version"        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"        // NOTE: Do not place your application dependencies here; they belong        // in the individual module build.gradle files        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.10'    }  
app/build.gradle
 apply plugin: 'com.android.application' apply plugin: 'kotlin-android' apply plugin: 'kotlin-android-extensions' apply plugin: 'kotlin-kapt' apply plugin: 'android-aspectjx' android {     compileSdkVersion 28     compileOptions {         sourceCompatibility JavaVersion.VERSION_1_8         targetCompatibility JavaVersion.VERSION_1_8     }     defaultConfig {         applicationId "com.example.cheng.test"         minSdkVersion min_sdk         targetSdkVersion target_sdk         versionCode 1         versionName "1.0"         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"         javaCompileOptions {             annotationProcessorOptions {                 arguments = [AROUTER_MODULE_NAME: project.getName()]             }         }     }     buildTypes {         release {             minifyEnabled false             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'         }     } } androidExtensions {     experimental = true } dependencies {     implementation fileTree(dir: 'libs', include: ['*.jar'])     testImplementation 'junit:junit:4.12'     androidTestImplementation 'androidx.test.ext:junit:1.1.1'     androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'     implementation 'androidx.constraintlayout:constraintlayout:1.1.3'     implementation 'androidx.recyclerview:recyclerview:1.1.0'     implementation project(':api')     implementation project(':common')     implementation 'com.google.android.material:material:1.1.0'     implementation 'com.alibaba:arouter-api:1.4.0'     kapt 'com.alibaba:arouter-compiler:1.2.1' } kapt {     arguments {         arg("moduleName", project.getName())     } }  
MainActivity.kt:
 package com.example.cheng.test import android.os.Bundle import androidx.appcompat.app.AppCompatActivity import com.alibaba.android.arouter.facade.annotation.Route import com.alibaba.android.arouter.launcher.ARouter import kotlinx.android.synthetic.main.activity_main.* @Route(path = "/text/activity/main") class MainActivity : AppCompatActivity() {     override fun onCreate(savedInstanceState: Bundle?) {         super.onCreate(savedInstanceState)         setContentView(R.layout.activity_main)         foo()     }     fun foo() {         id_text.text = "mainActivity"         id_text.setOnClickListener {             ARouter.getInstance().build("/text/activity/second")                 .withLong("KEY1", 100)                 .navigation()         }     } }  
AspectJx.java:
 package com.example.cheng.test; import android.util.Log; import org.aspectj.lang.JoinPoint; import org.aspectj.lang.annotation.After; import org.aspectj.lang.annotation.Aspect; import org.aspectj.lang.annotation.Pointcut; @Aspect public class AspectJx {     @Pointcut("call(* *.MainActivity.foo(..))")     public void point1() {     }     @After("point1()")     public void hook(JoinPoint joinPoint) throws Throwable {         Log.e("TEST123", joinPoint.getSignature().toLongString());     } }  
现在的现象是：
 如果相同build.gradle配置，没有AspectJx.java时，在build的时候会出现app.java没有打包进apk，造成app运行时crash
 如果加入了aspectJx.java，能够正常build过，app正常运行，检查ajx输出文件有正常生成对应的文件，但是实际上并没有织入aspectj的功能，例如上面的Log并没有生效。

**Comment by xiachengcheng** [comment]
> org.aspectj.aspectjrt:1.9.5这个依赖库，有依赖吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Cheng"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月24日(星期三) 中午11:12 收件人:&nbsp;"alibaba/ARouter"<ARouter@noreply.github.com&gt;; 抄送:&nbsp;"全球变冷@宇宙之大@不语"<397432103@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [alibaba/ARouter] 我使用ARouter ，但有些需求想使用aop，就引入了aspectjx，导致组件化失效。 (#789) @melancholyboy 您好，这个是我demo实验的配置，能否帮我看下我的使用是否存在问题吗，谢谢。 project/build.gradle: dependencies { classpath "com.android.tools.build:gradle:$build_version" classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version" // NOTE: Do not place your application dependencies here; they belong // in the individual module build.gradle files classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.10' } app/build.gradle apply plugin: 'com.android.application' apply plugin: 'kotlin-android' apply plugin: 'kotlin-android-extensions' apply plugin: 'kotlin-kapt' apply plugin: 'android-aspectjx' android { compileSdkVersion 28 compileOptions { sourceCompatibility JavaVersion.VERSION_1_8 targetCompatibility JavaVersion.VERSION_1_8 } defaultConfig { applicationId "com.example.cheng.test" minSdkVersion min_sdk targetSdkVersion target_sdk versionCode 1 versionName "1.0" testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner" javaCompileOptions { annotationProcessorOptions { arguments = [AROUTER_MODULE_NAME: project.getName()] } } } buildTypes { release { minifyEnabled false proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' } } } androidExtensions { experimental = true } dependencies { implementation fileTree(dir: 'libs', include: ['*.jar']) testImplementation 'junit:junit:4.12' androidTestImplementation 'androidx.test.ext:junit:1.1.1' androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0' implementation 'androidx.constraintlayout:constraintlayout:1.1.3' implementation 'androidx.recyclerview:recyclerview:1.1.0' implementation project(':api') implementation project(':common') implementation 'com.google.android.material:material:1.1.0' implementation 'com.alibaba:arouter-api:1.4.0' kapt 'com.alibaba:arouter-compiler:1.2.1' } kapt { arguments { arg("moduleName", project.getName()) } } MainActivity.kt: package com.example.cheng.test import android.os.Bundle import androidx.appcompat.app.AppCompatActivity import com.alibaba.android.arouter.facade.annotation.Route import com.alibaba.android.arouter.launcher.ARouter import kotlinx.android.synthetic.main.activity_main.* @route(path = "/text/activity/main") class MainActivity : AppCompatActivity() { override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState) setContentView(R.layout.activity_main) foo() } fun foo() { id_text.text = "mainActivity" id_text.setOnClickListener { ARouter.getInstance().build("/text/activity/second") .withLong("KEY1", 100) .navigation() } } } AspectJx.java: package com.example.cheng.test; import android.util.Log; import org.aspectj.lang.JoinPoint; import org.aspectj.lang.annotation.After; import org.aspectj.lang.annotation.Aspect; import org.aspectj.lang.annotation.Pointcut; @aspect public class AspectJx { @pointcut("call(* *.MainActivity.foo(..))") public void point1() { } @after("point1()") public void hook(JoinPoint joinPoint) throws Throwable { Log.e("TEST123", joinPoint.getSignature().toLongString()); } } 现在的现象是： 如果相同build.gradle配置，没有AspectJx.java时，在build的时候会出现app.java没有打包进apk，造成app运行时crash 如果加入了aspectJx.java，能够正常build过，app正常运行，检查ajx输出文件有正常生成对应的文件，但是实际上并没有织入aspectj的功能，例如上面的Log并没有生效。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢回复，apply plugin: 'android-aspectjx' 会加入这个依赖；事实上再次添加这个依赖后，aspect依然没有起效。

**Comment by Limy1992** [comment]
@xiachengcheng 请问最后是怎么处理的，有办法兼容2个库的存在并且不影响功能吗
