### ISSUE TITLE
建议:能不能支持gson解析,不依赖于fastjson

### ISSUE THREAD

**Issue by weinierfei** [alibaba/ARouter#79]
哈喽,作者辛苦了!感谢开源贡献;项目中使用gson解析json;ARouter引入了fastjson解析,一个项目引入多个json解析库感觉不太合适;能不能支持gson解析,让开发者自己选择使用gson还是fastjson?

**Comment by zhi1ong** [comment]
这块我的想法是，有必要的话，可以把序列化功能用ARouter service的形式解耦出来，交给开发者自己实现

不过Fastjson应该还是比gson序列化效率要高的(常见的小对象情况)

**Comment by weinierfei** [comment]
恩恩,期待支持自定义;fastjson的大名鼎鼎,不过公司所有项目中都是gson,所以一时半会也不能换过来的

**Comment by zhi1ong** [comment]
arouter_compiler_version=1.1.1.1
arouter_api_version=1.2.0.3

预发版，去掉了fastjson的依赖，传递自定义对象的时候，需要实现SerializationService
