### ISSUE TITLE
【建议】withTransition方法和原生设计有点不统一

### ISSUE THREAD

**Issue by ZhangJian96** [alibaba/ARouter#790]
原生安卓提供的api中，overridePendingTransition方法传（0，0）时是无动画，直接显示下一个Activity，但是发现用Arouter发现传0却是默认效果，于是看了下ARouter中的原码，如下：
```
   if ((0 != postcard.getEnterAnim() || 0 != postcard.getExitAnim()) && currentContext instanceof Activity) {    // Old version.
                            ((Activity) currentContext).overridePendingTransition(postcard.getEnterAnim(), postcard.getExitAnim());
                        }
```
Postcard中的exitAnim、enterAnim默认是0，当是0时直接在上面代码中过滤了，于是乎变成了默认动画。这个在使用上和原生sdk还是有点出入的，不看下源码就不知道ARouter不支持传（0，0）,还需要再写个空的动画文件。建议与原生api统一。

**Comment by zhi1ong** [comment]
很早就 fix 了

**Comment by ZhangJian96** [comment]
> 很早就 fix 了

项目中使用的版本确实很久没升级过了，没有看最新的版本，抱歉
