### ISSUE TITLE
我最近遇到一个问题，就是拦截器的问题

### ISSUE THREAD

**Issue by sunbest110** [alibaba/ARouter#791]
偶现的，就是写了一个登陆拦截，跳转到登陆界面，米九不会出现，小米6x，安卓9重装必现，我也加了监听，都显示找到界面。加了断点也走了
![image](https://user-images.githubusercontent.com/12553543/72697434-f1fa8f00-3b7a-11ea-87a9-09e96f2a0c5b.png)
然后就发现非activity的context，会出现这个问题。但是重启几次又好了。不会再出现不显示界面的问题。

**Comment by sunbest110** [comment]
![image](https://user-images.githubusercontent.com/12553543/72705469-7d354e00-3b96-11ea-8dd5-bfaf60b4a1b6.png)

**Comment by ananas-xxj** [comment]
你说你问了啥？本来跟我没关系，看你这表达真是来火，就你这提问 ，你还做程序员，求你转行送外卖吧。
