### ISSUE TITLE
一切配置正常 抛There is no route match the path

### ISSUE THREAD

**Issue by Mangosir** [alibaba/ARouter#792]
现有几个module使用path注解，在app上能正常跳转，现在新增了一个module，添加完配置，进行跳转时抛ARouter::There is no route match the path [/web/DefaultWebViewAct], in group [web][ ] 错误，但是build目录下的代码是有生成的
`public class ARouter$$Group$$web implements IRouteGroup {
  
@Override
  public void loadInto(Map<String, RouteMeta> atlas) {
    
atlas.put("/web/DefaultWebViewAct", RouteMeta.build(RouteType.ACTIVITY, DefaultWebViewAct.class, "/web/defaultwebviewact", "web", null, -1, -2147483648));
  
}
}`

但是把apk卸载，重新安装就可以跳转了。。。
这是不是有点坑，那以后线上版本更新碰到这种情况难道要让用户卸载完再去下载安装？

**Comment by Paul-Guo** [comment]
我的理解是这样子，Arouter的release版本默认是在versionCode有更新的时候，才会重新进行包扫描，才会把新增的配置添加进来。debug版本每次都会进行包扫描。

如果增加了auto-register配置，那么在编译器就会进行扫描，也就不会有类似问题。
debug版本每次都会包扫描。
执行了ARouter.openDebug()后，也会每次都包扫描，但是release版本可能有安全问题。

您的问题会不会是这个原因导致的呢？

**Comment by Mangosir** [comment]
> 我的理解是这样子，Arouter的release版本默认是在versionCode有更新的时候，才会重新进行包扫描，才会把新增的配置添加进来。debug版本每次都会进行包扫描。
> 
> 如果增加了auto-register配置，那么在编译器就会进行扫描，也就不会有类似问题。
> debug版本每次都会包扫描。
> 执行了ARouter.openDebug()后，也会每次都包扫描，但是release版本可能有安全问题。
> 
> 您的问题会不会是这个原因导致的呢？

感谢回复
有点迷糊了，既然说debug模式，每次都会包扫描，那为啥我新加一个module，添加配置，重新运行还是找不到指定的path呢

**Comment by Mangosir** [comment]
> 我的理解是这样子，Arouter的release版本默认是在versionCode有更新的时候，才会重新进行包扫描，才会把新增的配置添加进来。debug版本每次都会进行包扫描。
> 
> 如果增加了auto-register配置，那么在编译器就会进行扫描，也就不会有类似问题。
> debug版本每次都会包扫描。
> 执行了ARouter.openDebug()后，也会每次都包扫描，但是release版本可能有安全问题。
> 
> 您的问题会不会是这个原因导致的呢？

我也添加了arouter-register插件，按道理应该是在编译期就进行了路由表的扫描，可就是这样运行在手机上还是找不到path

**Comment by Paul-Guo** [comment]
> > 我的理解是这样子，Arouter的release版本默认是在versionCode有更新的时候，才会重新进行包扫描，才会把新增的配置添加进来。debug版本每次都会进行包扫描。
> > 如果增加了auto-register配置，那么在编译器就会进行扫描，也就不会有类似问题。
> > debug版本每次都会包扫描。
> > 执行了ARouter.openDebug()后，也会每次都包扫描，但是release版本可能有安全问题。
> > 您的问题会不会是这个原因导致的呢？
> 
> 我也添加了arouter-register插件，按道理应该是在编译期就进行了路由表的扫描，可就是这样运行在手机上还是找不到path

如果添加了arouter-register插件，建议通过apktool反编译apk后，检查com.alibaba.android.arouter.core.LogisticsCenter.loadRouterMap()函数内容，看看是不是映射表以及生成了。
也可以同时看看sp里面的内容（可以通过logcat输出）是不是已经更新了。

**Comment by wolongalick** [comment]
至今也没解决,太坑了

**Comment by zhi1ong** [comment]
这是最基本的情况了，都不能叫问题。耐心排查，按照 Readme 走一遍

**Comment by wolongalick** [comment]
我解决了，原因是A module的路由前缀与B module的路由前缀有一样的。
修改方案：将各个module的路由前缀区分开，别出现一致的情况即可

**Comment by Mangosir** [comment]
> 我解决了，原因是A module的路由前缀与B module的路由前缀有一样的。
> 修改方案：将各个module的路由前缀区分开，别出现一致的情况即可

我两个module得路由前缀肯定是不同的，不然卸载掉重新安装怎么会跳转成功呢

**Comment by chenshenglong126** [comment]
遇到了一样的情况，检查了一上午没发现问题。然后卸载重装就可以正常跳转了...

**Comment by tanzhihao1qaz** [comment]
妈的我也遇到这个问题，发了一个下午才无意中发现卸载重装解决
