### ISSUE TITLE
使用arouter1.5.0版本时，会自动远程依赖fastjson1.2.48版本是什么原因

### ISSUE THREAD

**Issue by windfallsheng** [alibaba/ARouter#796]
使用arouter1.5.0版本时，会自动远程依赖fastjson1.2.48版本是什么原因，使用低一些的版本就不会有这个问题？有时候依赖下载不成功时就无法编译通过。

**Comment by zhi1ong** [comment]
没有依赖 fastjson，早起版本有，后面通过服务的方式把序列化开放给用户了

**Comment by zhi1ong** [comment]
不过编译期需要，生成路由文档部分会使用 fastjson 序列化。

**Comment by windfallsheng** [comment]
> 不过编译期需要，生成路由文档部分会使用 fastjson 序列化。

明白了，THANK very much.

**Comment by windfallsheng** [comment]
> 不过编译期需要，生成路由文档部分会使用 fastjson 序列化。

明白了，Thank you very much.
