### ISSUE TITLE
Instant Run 都用不了啊。 好像也没有什么特色啊

### ISSUE THREAD

**Issue by Jomes** [alibaba/ARouter#8]

**Comment by ManchesterLee** [comment]
难道支持了就有特色了？ @Jomes

**Comment by zhi1ong** [comment]
准确的说不是用不了Instant Run，而是开了Instant Run编译期生成的类文件，不会下载到机器中，如果开启了Instant Run，**新增注解之后rebuild即可**，考虑到不会经常性添加注解，rebuild成本较低，短期内不会对这部分做优化。

ARouter提供了免注册的拦截器机制、Service管理以及多种访问方式、支持降级策略、URL重写、参数自动注入等功能，相对于同类产品功能略多了一点而已，当然您有好的建议也可以提交MR，一起优化ARouter

**Comment by zhi1ong** [comment]
最新 1.0.6 版本支持了 Instant Run.
