### ISSUE TITLE
com.alibaba.android.arouter.exception.HandlerException

### ISSUE THREAD

**Issue by tulongchao** [alibaba/ARouter#800]
com.alibaba.android.arouter.exception.HandlerException
Init provider failed! Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

com.alibaba.android.arouter.exception.HandlerException: Init provider failed! Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

设备机型

华为 DUB AL00A
系统版本

Android 8.1.0,level 27

ROM

HuaWei/EMOTION

CPU架构

arm64-v8a

**Comment by zhi1ong** [comment]
这是回调 init 方法的时候报错了，检查一下自己的代码
