### ISSUE TITLE
android:launchMode="singleTask"的activity参数传递不过去

### ISSUE THREAD

**Issue by xiaopengs** [alibaba/ARouter#802]
场景：singleTask  Activity A启动----启动B(standard)----启动C(standard)-----再arouter到A,参数无法获取到

**Comment by xiaopengs** [comment]
@Override
    protected void onNewIntent(Intent intent) {
        GLog.i(TAG, "baseActivity onNewIntent");
        super.onNewIntent(intent);
        setIntent(intent);
        ARouter.getInstance().inject(this);
    }

**Comment by BBNO** [comment]
这个问题解决了吗？怎么解决的？
