### ISSUE TITLE
fastjson 1.2.48有远程命令执行漏洞，能否升级到官方最新版本

### ISSUE THREAD

**Issue by battleAgain** [alibaba/ARouter#804]
由于fastjson在早期版本有远程命令执行漏洞，公司已经将fastjson 2.6.7（包含）之前的版本加入了黑名单，能否升级到官方最新版本

**Comment by zhi1ong** [comment]
fastjson 只是在编译期依赖的，线上不会有影响。会在后续版本中升级的。
