### ISSUE TITLE
兄弟 看来阿里技术很多也不咋样啊 技术有待提升 看看目录结构乱七八糟的

### ISSUE THREAD

**Issue by kobe-bean** [alibaba/ARouter#810]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by kobe-bean** [comment]
还有说明文档 废话一大堆

**Comment by kobe-bean** [comment]
越解释 人家越看不懂

**Comment by kobe-bean** [comment]
没听说过 一个成语吗
简单明了

**Comment by renyuan1991** [comment]
嘴里一边嚼着人家幸苦做好的饭，一边骂人家手艺垃圾，饭做得难吃。这种人我觉得就是不要脸！

**Comment by kobe-bean** [comment]
> 嘴里一边嚼着人家幸苦做好的饭，一边骂人家手艺垃圾，饭做得难吃。这种人我觉得就是不要脸！

这个社会 只有垃圾的老师 从来没有垃圾的学生

**Comment by kobe-bean** [comment]
> 嘴里一边嚼着人家幸苦做好的饭，一边骂人家手艺垃圾，饭做得难吃。这种人我觉得就是不要脸！
目录结构混乱 这是不争的事实

**Comment by kobe-bean** [comment]
文章写得垃圾 像无字天书 你就算再牛逼也学不会 就是这个道理
证明老师垃圾 文章没写好

**Comment by kobe-bean** [comment]
> 嘴里一边嚼着人家幸苦做好的饭，一边骂人家手艺垃圾，饭做得难吃。这种人我觉得就是不要脸！

证明你还没开窍

**Comment by kobe-bean** [comment]
> 嘴里一边嚼着人家幸苦做好的饭，一边骂人家手艺垃圾，饭做得难吃。这种人我觉得就是不要脸！
我一看你 估计技术也不咋样 因为你不懂用户体验 代码也是一种体验 
好的代码要吸收垃圾代码也能一并吃了？
你咋不把屎也给吃了？
好的东西能吃 
狗屎也能吃  ？
不批评下咋能进步？

**Comment by evansherry** [comment]
> > 嘴里一边嚼着人家幸苦做好的饭，一边骂人家手艺垃圾，饭做得难吃。这种人我觉得就是不要脸！
> > 我一看你 估计技术也不咋样 因为你不懂用户体验 代码也是一种体验
> > 好的代码要吸收垃圾代码也能一并吃了？
> > 你咋不把屎也给吃了？
> > 好的东西能吃
> > 狗屎也能吃  ？
> > 不批评下咋能进步？

杠

**Comment by limuyang2** [comment]
我觉得文档非常简单易懂啊

**Comment by kobe-bean** [comment]
我说的是 他目录结构 混乱
没说他不好用

**Comment by KElli0t** [comment]
> 我说的是 他目录结构 混乱 没说他不好用

目录结构 = 技术。扫地僧 = 无敌。 啊哈哈哈，兄弟你怕是活着小说里。

**Comment by lmDai** [comment]
一看评论都是大佬级别的，出口成章的

**Comment by zhi1ong** [comment]
首先我个人觉得目录结构并不混乱。其次，在 issues 区发这种毫无意义的 spam 只能浪费大家的时间。
