### ISSUE TITLE
初始化后还是会出抛出ARouter::Init::Invoke init(context) first!"异常

### ISSUE THREAD

**Issue by s7655120** [alibaba/ARouter#811]
目前发现存在部分初始化后还会抛出ARouter::Init::Invoke init(context) first!"异常的情况，经分析应该是在后台运行导致应用状态被清引起，这种情况该如何解决，并且是否可以提供监听是否初始化的方法

**Comment by zhi1ong** [comment]
要检查一下你调用 ARouter 初始化的地方是不是在某些 case 下启动的时候不会执行

**Comment by BananaHuo** [comment]
同样，在 mate 30 5G版 TAS-AN00 这个型号的线上机型也出现了这个问题，

**Comment by BananaHuo** [comment]
> 同样，在 mate 30 5G版 TAS-AN00 这个型号的线上机型也出现了这个问题，

有解决方案的麻烦告诉下，谢谢了

**Comment by yuqirong** [comment]
我也遇到了，发现重新调用了 ARouter.init(context) 方法还是没用

**Comment by Bigoy** [comment]
查看源码分析后发现我是因为调用了destroy代码：
`ARouter.getInstance().destroy()`
在这里会把初始化标识重置为false
