### ISSUE TITLE
注: ARouter::Compiler >>> AutowiredProcessor init. <<< 

### ISSUE THREAD

**Issue by CoderDuMeng** [alibaba/ARouter#812]
> Task :app:compileDebugJavaWithJavac FAILED
Gradle may disable incremental compilation as the following annotation processors are not incremental: jetified-arouter-compiler-1.2.2.jar (com.alibaba:arouter-compiler:1.2.2), jetified-auto-service-1.0-rc2.jar (com.google.auto.service:auto-service:1.0-rc2).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
注: ARouter::Compiler >>> AutowiredProcessor init. <<<
警告: 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> InterceptorProcessor init. <<<
警告: 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> RouteProcessor init. <<<
警告: 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler >>> Found routes, start... <<<
注: ARouter::Compiler >>> Found routes, size is 1 <<<
注: ARouter::Compiler >>> Found activity route: com.apt.shop.WebViewActivity <<<
错误: ARouter::Compiler An exception is encountered, [Failed to extract default group! String index out of range: -2]
警告: ARouter::Compiler >>> Route meta verify error, group is  <<<
注: ARouter::Compiler >>> Generated provider map, name is ARouter$$Providers$$app <<<
注: ARouter::Compiler >>> Generated root, name is ARouter$$Root$$app <<<
1 个错误
4 个警告

FAILURE: Build failed with an exception.

**Comment by zeuscode** [comment]
我也遇到这个，怎么关掉了

**Comment by jiulu313** [comment]
我也遇到这个了,一直报错没改掉,还要不要用这个了,在考虑
