### ISSUE TITLE
java kotlin混合项目导入问题

### ISSUE THREAD

**Issue by tianwailaike61** [alibaba/ARouter#815]
java kotlin混合项目怎么导入？
单纯的Java项目直接使用annotationProcessor导入compiler；
单纯的Java项目直接使用kapt导入compiler；
但是混合项目里面同时使用这两条，Activity跳转就不正确了

**Comment by DaoBillTang** [comment]
只用kapt

**Comment by tianwailaike61** [comment]
测试过  kotlin编写的Activity能够正常跳转，但是java的不行
