### ISSUE TITLE
rebuild的问题 

### ISSUE THREAD

**Issue by Founder005** [alibaba/ARouter#819]
每次改完代码，install安装就不行，打开就报错，看之前的issues说是混乱，rebuild一下，但是有时候rebuild也不行；比如我这次安装debug，改完代码debug不行了，换成install release就可以，release不行了，install debug‘版又可以了，有时候两个都不行，rebuild好几次才可以

**Comment by zhi1ong** [comment]
debug 环境要记得 openDebug()
