### ISSUE TITLE
关于转场动画的共享元素在Arouter里配置后不起作用

### ISSUE THREAD

**Issue by xu2012** [alibaba/ARouter#821]
val aoc= ActivityOptionsCompat.makeSceneTransitionAnimation(
                this@SplashActivity,
                Pair(imageView, "test")
            )
            ARouter.getInstance().build("/app/test")
                .withOptionsCompat(
                    aoc
                ).navigation()

**Comment by xu2012** [comment]
我使用startActivity的方式是可以正常跳转的，但是使用Arouter不行

**Comment by qinhehu** [comment]
navigation要带上context

**Comment by zhi1ong** [comment]
设置动画要传入 context

**Comment by 791180116** [comment]
makeSceneTransitionAnimation 使用共享元素的时候，需要在navigation方法中传入当前Activity
