### ISSUE TITLE
再次打开启动模式为 singleInstance 的Activity 接受不到传递的参数 injection()在onCreate()和onNewIntent()时都有注入

### ISSUE THREAD

**Issue by vqinlin** [alibaba/ARouter#824]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by biaji** [comment]
同样的问题。感觉是autowire取缓存的时候用的老的intent extra

**Comment by godisnoone** [comment]
onNewIntent中调用inject前先setIntent(intent)
