### ISSUE TITLE
@Autowired 在内部类的字段上会导至生成的代码中包重名

### ISSUE THREAD

**Issue by zhouao** [alibaba/ARouter#830]
@Autowired 在内部类的字段上会导至生成的代码中包重名

package com.jiwei.apps.redpacket.ui;

public class Test{
public static class ExampleActivity{

@Autowired
public String url;

}
}

会生成类：ExampleActivity$$ARouter$$Autowired，包名为：com.jiwei.apps.redpacket.ui.Test，
此包名就会与Test类冲突。

原因是AutowiredProcessor计算要生成的包名时，没有去判断上一级封装是类还是包。

**Comment by zhi1ong** [comment]
这么用就有点复杂了，参数注入主要还是为了解决页面跳转的时候的参数传递的。

**Comment by zhi1ong** [comment]
如果要作为一个全功能的  IoC 框架还是要做很多额外的开发的。
