### ISSUE TITLE
arouter-compiler依赖fastjson，可增加序列化接口，去除依赖关系

### ISSUE THREAD

**Issue by mingabc** [alibaba/ARouter#833]
在arouter-api module中SerializationService通过接口将序列化实现由外部自定义；但是在arouter-compiler.enity.RootDoc却依赖了fastjson，这里是否应该统一一下，如果序列化可由外部自定义，compiler和api都应该包含配置接口;

**Comment by zhi1ong** [comment]
arouter-compiler 是编译期用的，依赖不影响的
