### ISSUE TITLE
新增module时，跳转时提示ARouter::There is no route match the path

### ISSUE THREAD

**Issue by Mangosir** [alibaba/ARouter#834]
新增了一个module，然后从其它module跳转到该module的activity，报错ARouter::There is no route match the path；真的一切配置都是对的，卸载app，重新运行就没问题了，这是什么情况，每次新增module都会碰到这个问题

**Comment by yanchengdeng** [comment]
> 
> 
> > 遇到这个问题的同学请仔细检查是否在每个`build.gradle`文件中都正确设置了以下代码（kotlin项目，java项目参考修改）
> > ```groovy
> > kapt {
> >     arguments {
> >         arg("moduleName", project.getName())
> >     }
> > }
> > 
> > 
> > dependencies {
> > //...
> >     kapt 'com.alibaba:arouter-compiler:1.1.4'
> > }
> > ```
> > 
> > 
> > ⚠️注意！`arouter-compiler` 这个依赖必须在`build.gradle`中声明，只在`base_module`中声明然后引用`base_module`中引用是无效的！
> 
> 最后这句话解决了我的问题：
> ⚠️注意！`arouter-compiler` 这个依赖必须在`build.gradle`中声明，只在`base_module`中声明然后引用`base_module`中引用是无效的！
> 调试半天不知道问题出现在，谢谢！
