### ISSUE TITLE
There is no route match the path

### ISSUE THREAD

**Issue by xHonghui** [alibaba/ARouter#837]
简单应用内部跳转，一直报 “There is no route match the path”，看了好几遍，路由决定没有错，具体代码如下：
@Route(path = "/home/main")
class TestActivity : Activity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_test)
    }
}

class MainActivity : Activity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        btn_goto_login.setOnClickListener {
            ARouter.getInstance().build("/home/main").navigation();
        }
    }
}

ARouter使用版本：
compile "com.alibaba:arouter-api:1.5.0"
annotationProcessor "com.alibaba:arouter-compiler:1.2.2"

日志如下：
I/ARouter::: ARouter openLog[ ] 
I/ARouter::: ARouter openDebug[ ] 
I/ARouter::: ARouter init start.[ ] 
I/ARouter::: Run with debug mode or new install, rebuild router map.[ ] 
I/ARouter::: VM with name 'Android' has multidex support
E/ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths
I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.1][ ] 
D/ARouter::: Filter 3 classes by packageName <com.alibaba.android.arouter.routes>
I/ARouter::: Find router map finished, map size = 3, cost 65 ms.[ ] 
I/ARouter::: Load root element finished, cost 3 ms.[ ] 
D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[1], InterceptorIndex[0], ProviderIndex[2][ ] 
I/ARouter::: ARouter init success![ ] 
W/ARouter::: ARouter::No postcard![ ] 
W/ARouter::: ARouter::No postcard![ ] 
D/ARouter::: The group [arouter] starts loading, trigger by [/arouter/service/interceptor][ ] 
D/ARouter::: The group [arouter] has already been loaded, trigger by [/arouter/service/interceptor][ ] 
I/ARouter::: Thread production, name is [ARouter task pool No.1, thread No.2][ ] 
I/ARouter::: ARouter init over.[ ] 

W/ARouter::: ARouter::No postcard![ ] 
W/ARouter::: ARouter::No postcard![ ] 
W/ARouter::: ARouter::There is no route match the path [/home/main], in group [home][ ] 
W/ARouter::: ARouter::No postcard![ ]

**Comment by wenfengtou** [comment]
我也报这个错，kotlin

**Comment by githuvn** [comment]
为啥close了？
