### ISSUE TITLE
app刚开启的时候跳转会闪2次白屏

### ISSUE THREAD

**Issue by nevermore1314** [alibaba/ARouter#84]
我在app的Splashctivity通过Arouter跳转到主页面,会闪一到两下白屏.
这个问题出现在我把版本替换为1.2.1之后出现.
之前用的1.0.7没有这个问题.
我没看见别人提到过这种情况,不知道是不是我哪里使用方式不对?

**Comment by tqlmorepassion** [comment]
66666
