### ISSUE TITLE
Gradle may disable incremental compilation as the following annotation processors are not incremental

### ISSUE THREAD

**Issue by zeuscode** [alibaba/ARouter#842]
Gradle may disable incremental compilation as the following annotation processors are not incremental: jetified-arouter-compiler-1.2.2.jar (com.alibaba:arouter-compiler:1.2.2), jetified-auto-service-1.0-rc2.jar (com.google.auto.service:auto-service:1.0-rc2).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
注: ARouter::Compiler >>> AutowiredProcessor init. <<<
警告: 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: ARouter::Compiler The user has configuration the module name, it was [app]

FAILURE: Build failed with an **exception.**

**Comment by haegyeong** [comment]
你好，请问你解决这个问题了吗

**Comment by zhi1ong** [comment]
1.5.0 支持了
