### ISSUE TITLE
activity跳转异常

### ISSUE THREAD

**Issue by bruceliu199** [alibaba/ARouter#845]
使用方式：
                int flag = Intent.FLAG_ACTIVITY_CLEAR_TASK | Intent.FLAG_ACTIVITY_NEW_TASK;
                ARouter.getInstance().build(UserPageConstants.IDLoginActivity).greenChannel()
                        .withFlags(flag)
                        .navigation();
部分机型跳转异常
android.util.AndroidRuntimeException
Activity could not be started for Intent { flg=0x10008000 cmp=xxx/xxx.IDLoginActivity (has extras) }
查看源码发现在Instrumentation会抛出此异常
![image](https://user-images.githubusercontent.com/20267176/89013714-f03e2f00-d346-11ea-9852-51ffa2193a50.png)

**Comment by MaHuanglei** [comment]
Excuse me, has this problem been solved?

**Comment by Hal-yang** [comment]
Excuse me, has this problem been solved?

**Comment by qihuan92** [comment]
Excuse me, has this problem been solved?
