### ISSUE TITLE
按官方文档接入报错

### ISSUE THREAD

**Issue by zhanghq666** [alibaba/ARouter#849]
官方文档描述： 
defaultConfig {
        ...
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }
    }
使用版本为：
    api 'com.alibaba:arouter-api:1.5.0'
    annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'

编译报错：
ARouter::Compiler >>> No module name, for more information, look at gradle log.

续把上述配置中的AROUTER_MODULE_NAME改为moduleName才能解决。如果是新版本有了变动，请及时更新官方文档。

**Comment by zhi1ong** [comment]
moduleName 是老版本的 compiler 配置，AROUTER_MODULE_NAME 反而是新的
