### ISSUE TITLE
系统应用升级后初始化出现Crash

### ISSUE THREAD

**Issue by superlelele** [alibaba/ARouter#850]
## 前置条件
- 系统应用，只有作为系统应用才会出现
- 多进程，应用中存在3个子进程
- MultiDex，采用谷歌官方分包方案
- Kotlin，采用Kotlin混合开发，出问题模块启用混合开发，其他模块之前就已启用
- 覆盖安装，只在覆盖安装时出现，且出问题的路由是历史模块，路由很早就配置一直未启用，新版该模块才启用路由

## Crash 堆栈

1  **java.lang.RuntimeException:Unable to create application com.xx.xx.xx.SmartApp: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Providers$$XXXXmodulepromotion]**

2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:5428)
3 ......
4 com.alibaba.android.arouter.exception.HandlerException:ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Providers$$XXXXmodulepromotion]
5 com.alibaba.android.arouter.core.LogisticsCenter.void init(android.content.Context,java.util.concurrent.ThreadPoolExecutor)(LogisticsCenter.java:30)
6 com.alibaba.android.arouter.launcher._ARouter.boolean init(android.app.Application)(_ARouter.java:2)
7 com.alibaba.android.arouter.launcher.ARouter.void init(android.app.Application)(ARouter.java:4)
8 com.xx.xx.xx.SmartApp.void a()(SmartApp.java:4)
9 com.xx.xx.xx.SmartApp.void onCreate()(SmartApp.java:6)
10 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
11 android.app.ActivityThread.handleBindApplication(ActivityThread.java:5425)
12 android.app.ActivityThread.-wrap2(ActivityThread.java)
13 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551)
14 android.os.Handler.dispatchMessage(Handler.java:102)
15 android.os.Looper.loop(Looper.java:154)
16 android.app.ActivityThread.main(ActivityThread.java:6141)
17 java.lang.reflect.Method.invoke(Native Method)
18 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
19 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

麻烦问下哪位大神知道该问题如何解？

**Comment by zhi1ong** [comment]
应该是 crash 在 [com.alibaba.android.arouter.routes.ARouter$$Providers$$XXXXmodulepromotion] 这个类里面了，看看自己的逻辑
