### ISSUE TITLE
A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution

### ISSUE THREAD

**Issue by JerrNeon** [alibaba/ARouter#855]
gradle4.0.1中引用kapt“com.alibaba:arouter-compiler:1.2.2”出现
“A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution”

![微信截图_20200911113600](https://user-images.githubusercontent.com/21085391/92854016-16192200-f423-11ea-8fbe-85d530264914.png)
![微信截图_20200911113619](https://user-images.githubusercontent.com/21085391/92854023-17e2e580-f423-11ea-9cb0-f2ffc593dfc2.png)
![微信截图_20200911113639](https://user-images.githubusercontent.com/21085391/92854025-17e2e580-f423-11ea-88d4-9038ad61ef39.png)

**Comment by wangdroid** [comment]
我这里也出现了，请问如何解决的呢？
