### ISSUE TITLE
可以提供根据当前Activity查找对应的路由路径的API 吗

### ISSUE THREAD

**Issue by wangfeigit** [alibaba/ARouter#858]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by zhi1ong** [comment]
是什么样的业务场景？

**Comment by wangfeigit** [comment]
跳转某一个Activity，要显示到悬浮窗对应的路由何传参，便于产品运营配置数据

**Comment by zhi1ong** [comment]
这种非用户态的需求，直接读取路由表json解析出来就好了
