### ISSUE TITLE
使用拦截器onActivityResult回调问题

### ISSUE THREAD

**Issue by lujun525** [alibaba/ARouter#859]
你好，请问下，我现在A(有requestCode)跳转C(需要登录)，写了拦截器跳到B(登录)，登录后跳转到C了，点返回回到A，这个流程是没问题，可是A中的requestCode收不到了啊，因为拦截器里拿不到A的context 了啊，拦截器里这样写的，ARouter.getInstance("/path/login").greenChannel().navigation()

**Comment by zhi1ong** [comment]
正常的流程是B处理完之后，在拦截器中放行，而不是在拦截器中跳转到C
