### ISSUE TITLE
_ARouter在Activity跳转时引发短暂黑屏问题

### ISSUE THREAD

**Issue by qdliujun588** [alibaba/ARouter#86]
_ARouter的实现中第349行开始new Handler(Looper.getMainLooper()).post方法如果在页面跳转后面执行finish()方法的话会导致finish方法比启动Activity方法要早，会出现短暂的黑屏，此处应该判断一下如果当前线程为主线程的话直接执行run方法中的内容，如果当前线程不是主线程再走new Handler(Looper.getMainLooper()).post。

**Comment by weixinfree** [comment]
我们在使用的过程中也遇到了这个问题，机制上应该类似 Activity#runOnUiThread，如果是在主线程的话，直接执行，否则post到主线。这样执行顺序才是可预期的

**Comment by weixinfree** [comment]
麻烦阿里的同学尽快修复下吧

**Comment by ManchesterLee** [comment]
_ARouter._navigation()就是在子线程中执行的，应该不要判断。

**Comment by zhi1ong** [comment]
@qdliujun588  @weixinfree  这个问题其实是因为过拦截器的在子线程操作的，因为可能耗时，像登录拦截之类的，最后startActivity是在主线程，但是你刚执行跳转就手动 finish() ，还没有startActivity，所以黑屏了，问题不是有没有切换到主线程的问题，要在 回调的 onArrival()中执行 finish()，不过一般页面跳转之后不需要finish，需要保留页面栈
