### ISSUE TITLE
通过Uri 跳转时 没有添加 Autowired的参数都不会被解析到Bundle里面了

### ISSUE THREAD

**Issue by MapleSunFLY** [alibaba/ARouter#864]
通过Uri 跳转时 没有添加 Autowired的参数都不会被解析到Bundle里面了，添加拦截之后发现uri传递的参数都没有被解析到Postcard里的mBundle中了，activity，fragment都是了

**Comment by zhi1ong** [comment]
一直也是这样，不添加 Autowired，无法判断入参类型
