### ISSUE TITLE
addRouteGroup

### ISSUE THREAD

**Issue by lu769257351** [alibaba/ARouter#866]
请问addRouteGroup怎么用？我这边使用的是 1.5.1版本，但是未找到对应的方法

**Comment by zhi1ong** [comment]
IV. Advanced usage - 9

**Comment by lu769257351** [comment]
> IV. Advanced usage - 9

ARouter中未提供addRouteGroup函数

**Comment by zhi1ong** [comment]
> > IV. Advanced usage - 9
> 
> ARouter中未提供addRouteGroup函数

记错了，是 1.5.2 还没发，代码在 dev 分支，急需的话，可以源码依赖，自己打包一下。

**Comment by lu769257351** [comment]
> > > IV. Advanced usage - 9
> > 
> > 
> > ARouter中未提供addRouteGroup函数
> 
> 记错了，是 1.5.2 还没发，代码在 dev 分支，急需的话，可以源码依赖，自己打包一下。

好的，谢谢，已经解决了
