### ISSUE TITLE
升级android studio4.1问题 

### ISSUE THREAD

**Issue by fenghuajueli** [alibaba/ARouter#868]
Plugin "ARouter Helper" is incompatible (supported only in IntelliJ IDEA).

**Comment by puming** [comment]
Plugin "ARouter Helper" is incompatible (supported only in IntelliJ IDEA).

**Comment by TanZiDong** [comment]
> Plugin "ARouter Helper" is incompatible (supported only in IntelliJ IDEA).
> 
> 临时解决方案：
> 将用户插件拷贝到系统插件目录，并且删除用户目录的插件。等插件开发者适配android studio4.1。
> 
> form:
> C:\Users\UserName\AppData\Roaming\Google\AndroidStudio4.1\plugins
> 
> to:
> C:\Program Files\Android\Android Studio\plugins

谢谢大佬的临时解决方案！

**Comment by huage2580** [comment]
https://github.com/huage2580/arouter-idea-plugin-x  
支持了Kotlin和AS4.1以上

**Comment by GitGuy2015** [comment]
ARouter Helper 插件文件叫什么名字？在mac上找不到对应的名字

**Comment by TanZiDong** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月1日(星期五) 上午10:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/ARouter] 升级android studio4.1问题  (#868)





 
ARouter Helper 插件文件叫什么名字？在mac上找不到对应的名字
