### ISSUE TITLE
启动页使用ARouter打开页面失败

### ISSUE THREAD

**Issue by lijunhuayc** [alibaba/ARouter#875]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

有收到 onArrival 回调，但是页面却没有打开，并非必现，出现频率较小。
无法下手排查原因。用法整个项目都一样，使用的kotlin封装的扩展函数来统一调用navigate方法。

CptActivityRouterTable.CPT_LOGIN_ACTIVITY_PHONE_LOGIN_PATH.navigation(mContext)

/**
 * 开启页面
 * @param options 配置参数
 */
inline fun String.navigation(context: Context, callbackCustom: CustomNavigateCallback? = null, options: (Postcard) -> Unit) {
    val postcard = ARouter.getInstance().build(this)
    options.invoke(postcard)
    postcard.navigation(context, callbackCustom ?: CustomNavigateCallback())
}

/**
 * 开启页面
 */
inline fun String.navigation(context: Context, callbackCustom: CustomNavigateCallback? = null) {
    val postcard = ARouter.getInstance().build(this)
    postcard.navigation(context, callbackCustom ?: CustomNavigateCallback())
}

**Comment by bird7310** [comment]
为什么close了？
