### ISSUE TITLE
强烈建议将初始化IProvider的异常打印出来，而不是只抛出 e.getMessage()

### ISSUE THREAD

**Issue by ooftf** [alibaba/ARouter#878]
ARouter中类似的代码
HandlerException("Init provider failed! " + e.getMessage())
都应该用e.printStackTrace()打印出来，而不只是  拼接一个 e.getMessage() 
对于查找错误太费事了，经常获取到的错误信息就是 Init provider failed! null

**Comment by jackeyliu** [comment]
这个是在子线程调用抛出来的异常吗

**Comment by zhi1ong** [comment]
有道理

**Comment by zhi1ong** [comment]
fix in 1.5.2
