### ISSUE TITLE
Kotlin使用Autowired问题

### ISSUE THREAD

**Issue by lamandys** [alibaba/ARouter#879]
` @Autowired(name = Constants.INTENT_DATA)
    @JvmField
    var type: Int = 0

    @Autowired(name = Constants.INTENT_DATA1)
    @JvmField
    var goodId: String? = ""

    @Autowired(name = Constants.INTENT_DATA2)
    @JvmField
    var showTitle: Boolean = true`

目标页面接受参数如上，autowired生成的代码如下：

`/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER. */
public class IVoicePricesFragment$$ARouter$$Autowired implements ISyringe {
  private SerializationService serializationService;

  @Override
  public void inject(Object target) {
    serializationService = ARouter.getInstance().navigation(SerializationService.class);
    IVoicePricesFragment substitute = (IVoicePricesFragment)target;
    substitute.type = substitute.getArguments().getInt("data");
    substitute.goodId = substitute.getArguments().getString("data1");
    substitute.showTitle = substitute.getArguments().getBoolean("data2");
  }
}`

为什么getBoolean方法中没有用目标页面的默认值作为参数呢？不应该是getBoolean("data2",substitute.showTitle);吗？？？

**Comment by zhi1ong** [comment]
默认值问题已经fix过了
