### ISSUE TITLE
使用Hilt后添加ARouter编译会报错

### ISSUE THREAD

**Issue by TungHongChao** [alibaba/ARouter#884]
我先集成了Hilt框架，然后准备再集成ARouter，项目sync没有问题，但是run的时候会报错
主要是添加了这个就会报错
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }

D:\WorkSpace\Android\TdTools\app\build\tmp\kapt3\stubs\debug\com\tdtech\tdlog\module\main\MainActivity.java:7: ����: [Hilt]
public final class MainActivity extends com.tdtech.base.ui.BaseActivity<com.tdtech.tdlog.module.main.MainFragment> {
             ^
  Expected @AndroidEntryPoint to have a value. Did you forget to apply the Gradle Plugin? (dagger.hilt.android.plugin)
  See https://dagger.dev/hilt/gradle-setup.html
  [Hilt] Processing did not complete. See error above for details.D:\WorkSpace\Android\TdTools\app\build\tmp\kapt3\stubs\debug\com\tdtech\tdlog\module\main\MainFragment.java:7: ����: [Hilt]

**Comment by l7356507** [comment]
我也遇到了同样的问题  请问有解决办法吗？

**Comment by l7356507** [comment]
问题解决了， arguments 后面使用 +=

**Comment by TungHongChao** [comment]
好的，回头我也试一试

**Comment by yangjiannan2018** [comment]
> 问题解决了， arguments 后面使用 +=

为啥我的加了也没用

**Comment by yangjiannan2018** [comment]
> > 问题解决了， arguments 后面使用 +=
> 
> 为啥我 += 没用

解决了，是因为 kotlin 混编导致的，按照 ARouter 的 kotlin项目的配置即可

**Comment by zhaoxiuyu** [comment]
按照kotlin项目的配置还是不行
