### ISSUE TITLE
ARouter.getInstance().navigation(MainActivity.class); 这个意味着不能传递bound了？

### ISSUE THREAD

**Issue by XinYiWorld** [alibaba/ARouter#887]
对于本组件内的activity跳转，ARouter.getInstance().navigation(MainActivity.class)这个方法，不能传递bundle。我还得定义一个Route注解然后，通过ARouter.getInstance().build("/test/activity1").withString("name", "老王").navigation();再去跳转？这个为啥不封装起来？

**Comment by zhi1ong** [comment]
不知道你在说什么，如果已经拿到目标 activity class 了，还用 arouter 干啥

**Comment by XinYiWorld** [comment]
免得我再写Intent传参，何不直接ARouter封装一下呢？既能跨组件传递参数，也能在本组件里传递参数。

**Comment by zhi1ong** [comment]
组件内跳转没有这个必要

**Comment by showwiki** [comment]
组件内就不该用Arouter再传来传去

**Comment by XinYiWorld** [comment]
这个不符合一般适用性规则吧*^_^*，组件外能用，组件内按道理也要支持。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月9日(星期五) 下午2:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/ARouter] ARouter.getInstance().navigation(MainActivity.class); 这个意味着不能传递bound了？ (#887)

**Comment by showwiki** [comment]
一般适用性规则?  没听说过啊， arouter 本来就是组件之间的桥梁，你在组件内部架一堆桥，那不是又将组件耦合arouter了，对外暴露的就应该尽可能少。如果两个组件联系非常紧密，原则上他们就应该是一个组件，你应该抽取一个中介者来解耦。

**Comment by XinYiWorld** [comment]
打个比方，Binder可以用来跨进程通讯 ，它也可以用来进程内通讯啊。为啥ARouter能进行module间的通讯，就不能进行module内的通讯呢？这不应该是个设计的问题吗？
