### ISSUE TITLE
Kotlin项目集成Arouter，报错Task :app:kaptDebugKotlin

### ISSUE THREAD

**Issue by tiebenxin** [alibaba/ARouter#889]
Kotlin 项目集成后，编译过程中报错，点击跳转时，提示There is no route match! Path=[XX/XX]

> Task :app:kaptDebugKotlin
警告: 以下选项未被任何处理程序识别: '[AROUTER_GENERATE_DOC, kapt.kotlin.generated, AROUTER_MODULE_NAME]'[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: android.databinding.annotationprocessor.ProcessDataBinding (DYNAMIC).

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.alibaba.arouter'
apply plugin: 'kotlin-kapt'

kapt {
    arguments {
        arg("AROUTER_MODULE_NAME", project.getName())
        arg("AROUTER_GENERATE_DOC", "enable")
    }
}

dependencies
    implementation "com.alibaba:arouter-api:1.5.0" 
    kapt "com.alibaba:arouter-api: 1.2.2"

**Comment by fengxiaocan** [comment]
如果还没开始使用，建议不要用；如果已固定架构就没法了。每次更新Gradle或者更新依赖或者更新Studio就会提示一堆编译不通过的错误。你这问题是没按照文档来做的。不过就算按照文档做好了，更新版本依赖的时候你就知道了

**Comment by zhi1ong** [comment]
@fengxiaocan 首先 gradle 不是经常要更新的，gradle 大版本之间都会有不兼容升级，其次编译不通过要看一下为啥编译不通过，不知道跟 arouter 有啥关系。
