### ISSUE TITLE
能不能升级一下android studio插件呢？

### ISSUE THREAD

**Issue by fenghuajueli** [alibaba/ARouter#892]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by louiewh** [comment]
+1

**Comment by huage2580** [comment]
https://github.com/huage2580/arouter-idea-plugin-x
支持了Kotlin和AS4.1以上
