### ISSUE TITLE
Interceptor拦截，处理之后，该如何跳转到拦截之前想跳转的位置

### ISSUE THREAD

**Issue by ManchesterLee** [alibaba/ARouter#9]
您好，我有个问题想请教下。

比如：从Activity A想要跳转到Activity B，但是B需要登录，于是我在Interceptor中拦截这个跳转事件，修改Postcard的目的地为LoginActivity，登录结束之后会回到Activity A，如何才能让登录结束后，直接跳转到该事件原先想要跳转的位置呢？

非常感谢。

**Comment by zhi1ong** [comment]
不是这样用的，不要修改目的地，在拦截器里面自己拉起登录页，登录成功之后，调用回调的onContinue就会继续往下走了，失败的话，调用终止即可。

参考Demo中的用法。

**Comment by ManchesterLee** [comment]
@zhi1ong 
非常感谢您的耐心回答。

我还有一点不明白的，在拦截器中去自己启动登录页的话，登录结果如何通知到Interceptor，回调onContinue呢？

**Comment by zhi1ong** [comment]
广播、消息、回调，反正能通知回来就行，然后再回调Interceptor的回调

**Comment by ManchesterLee** [comment]
@zhi1ong 
非常感谢您的耐心回答。

我也想过要这样做，但是这样写出来感觉有点别扭。如果能有一种方法让Router直接处理这些事件就好了。目前可能只能这样解决了。再次感谢您的耐心回答。

**Comment by zhi1ong** [comment]
拦截器只是提供了这种机制，不太适合关心内部的业务逻辑，如果搞成LoginInterceptor这种目的性很强的设计，用起来可能简单一些，但是不具通用性，可能用户就需要去记住N个不同功能的拦截器了，成本反而更高了。

大家会就纠结这些特型的拦截器和标准的拦截器的区别和时序了

**Comment by chris-jason** [comment]
登录结果具体怎么回调到拦截器中能说细点吗？

**Comment by zhi1ong** [comment]
最简单的可以通过广播，不过一般的实践是把登录封装起来，做成一个异步接口，外部需要登录的时候，不关心内部的页面，只需要在接口的回调中调用拦截器的onContinue即可

**Comment by chris-jason** [comment]
@zhi1ong 谢谢，用广播来通知会不会太重量级了，能不能加一下 QQ 细说？851183849还有一些别的问题想请教您。

**Comment by zhi1ong** [comment]
可以，本地广播传递点事件还是很常用的

**Comment by AvatarQing** [comment]
如果能把这个案例写在demo里最好了

**Comment by loandroid** [comment]
可以在LoginInterceptor里面把控制拦截或者释放两个对象（PostCard和InterceptorCallback）传到一个自定义的单例中，然后在登录页面对这个单例（即是对PostCard和InterceptorCallback）进行操作，来实现目的。

**Comment by iceyang1989** [comment]
调起登录页面，但是无法知道前一个activity引用。不知道各位咋实现的？

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/50372840-bbb5ad80-0610-11e9-923b-766f6381b558.png)

登录的activity里
![image](https://user-images.githubusercontent.com/17565737/50372843-d12ad780-0610-11e9-9076-5c4d66c8800e.png)

这样搞行不行。两个静态变量会不会有空指针的危险啊
