### ISSUE TITLE
组件化后，编译引用的问题

### ISSUE THREAD

**Issue by zhangxiliang** [alibaba/ARouter#90]
我现在有App，MoudleA、MoudleB ，采用ARouter 的方式暴露服务，但IAService、IBService 接口、以及实现类分别在MoudleA、MoudleB中，MoudleA 需要拿到IBService，ModuleB需要拿到IAService，但ModuleA和MoudleB是不能相互依赖的，所以相互调用的时候，如何才能编译通过，独立打包呢？

**Comment by zhi1ong** [comment]
提问的话，建议你去交流群，里面有人答复

这里建议你每一个业务模块单独提供一个接口包，这个包中包含接口和传递数据的对象，这样互相依赖接口包就行了
