### ISSUE TITLE
引入后应用启动时间拖慢了1秒多点，有没有谁遇到类似的问题 。 已经使用了 classpath "com.alibaba:arouter-register:1.0.2"  。冷启动需要2秒左右的时间，不引入框架大概7百毫秒左右。 adb shell am start -W  com.example.main/com.example.main.MainActivity

### ISSUE THREAD

**Issue by duxiyao** [alibaba/ARouter#900]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by DYP1016** [comment]
apply plugin: 'com.alibaba.arouter'

这一行是不是直接写在project的build.gradle里面了?

这个要在每一个module和app的build.gradle里面写才能生效
