### ISSUE TITLE
kotlin下添加生成路由文档配置时编译不通过

### ISSUE THREAD

**Issue by chouxingxing** [alibaba/ARouter#909]
kapt {
        arguments {
            arg("AROUTER_MODULE_NAME", project.getName())
            //arg("AROUTER_GENERATE_DOC", "enable") 报错

        }
    }

**Comment by fengguangbo** [comment]
那是因为arouter-compiler这个项目没有支持kotlin的kapt

**Comment by fengguangbo** [comment]
![微信截图_20210520192719](https://user-images.githubusercontent.com/12950349/118970989-76dcff00-b9a1-11eb-883c-a6e5df26e93c.png)

**Comment by fengguangbo** [comment]
我下载源码，给注解器加上kotlin-kapt支持后，给kotlin工程配置arg("AROUTER_GENERATE_DOC", "enable")就没问题了

**Comment by zhi1ong** [comment]
chuanc
