### ISSUE TITLE
加了finish()后，原有的转场动画会被强制改变，且无法再配置。

### ISSUE THREAD

**Issue by MirkoWu** [alibaba/ARouter#92]
通过Router启动Activity，如果 ARouter.getInstance().build(url).navigation();后跟了finish()时，原有的转场动画会被改变成从底部弹出和消失，并且withTransition()无效。但是通过原生的Intent跳转后面跟了finish()也不会有这种情况。

**Comment by zhi1ong** [comment]
如果一定要在跳转之后finish掉之前的页面，那么推荐你在navigation中传入 Callback，在onArrival中finish(), 你立刻finish，可能还没跳转到目标，尝试一下，看看问题是否已经解决了

**Comment by nifengxiao** [comment]
当设置windowDrawsSystemBarBackgrounds为false的时候，再用arouter进行跳转到另外一个界面，会出现上个界面会上抬一部分然后再完成跳转的情况。
