### ISSUE TITLE
最新版gradle-6.7.1  报错 全部按照kotlin 文档接入 感觉arouter不支持高版本的gradle 

### ISSUE THREAD

**Issue by GuoFeilong** [alibaba/ARouter#920]
`        classpath "com.alibaba:arouter-register:1.0.2"
`

`api("com.alibaba:arouter-api:1.5.1"){
        exclude group: 'com.android.support'
        exclude group: 'com.android.core'
        exclude group: 'com.android.versionedparcelable'
    }

    kapt("com.alibaba:arouter-compiler:1.2.2"){
        exclude group: 'com.android.support'
        exclude group: 'com.android.core'
        exclude group: 'com.android.versionedparcelable'
    }`

`plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
    id 'com.alibaba.arouter'
}`

`kapt {
    arguments {
        arg("AROUTER_MODULE_NAME", project.getName())
    }
}`

添加路由编译的时候 发生错误

注: ARouter::Compiler >>> AutowiredProcessor init. <<<警告: 来自注释处理程序 'org.jetbrains.kotlin.kapt3.base.ProcessorWrapper' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'注: ARouter::Compiler The user has configuration the module name, it was [app]注: ARouter::Compiler >>> InterceptorProcessor init. <<<警告: 来自注释处理程序 'org.jetbrains.kotlin.kapt3.base.ProcessorWrapper' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'注: ARouter::Compiler The user has configuration the module name, it was [app]注: ARouter::Compiler >>> RouteProcessor init. <<<警告: 来自注释处理程序 'org.jetbrains.kotlin.kapt3.base.ProcessorWrapper' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'注: ARouter::Compiler >>> Found routes, start... <<<注: ARouter::Compiler >>> Found routes, size is 1 <<<错误: ARouter::Compiler An exception is encountered, [null]

**Comment by GuoFeilong** [comment]
ARouter::Compiler An exception is encountered, [null] 

发生错误,低版本的gradle 5.x就可以

**Comment by panmin** [comment]
为啥不支持升级新版本的gradle

**Comment by zhouxin1233** [comment]
遇到了同样的问题

**Comment by AlbertZyc** [comment]
各位 遇到高版本出现Configuration cache state could not be cached: input property '$3' of ':app:transformClassesWithCom.alibaba.arouterForDebug': error writing value of type 'org.gradle.api.internal.file.FilteredFileTree'
> Querying the mapped value of provider(interface java.util.Set) before task ':app:compileDebugKotlin' has completed is not supported
问题的都是高版本不兼容的问题，不用去找解决方法了，最好的方法就是降版本
