### ISSUE TITLE
升级到android gradle 插件4.2.1版本后编译时出现好多警告信息

### ISSUE THREAD

**Issue by qq549631030** [alibaba/ARouter#927]
警告如下：
AGPBI: {"kind":"warning","text":"Expected stack map table for method with non-linear control flow.","sources":[{"file":"D:\\source\\Demo\\app\\build\\intermediates\\transforms\\com.alibaba.arouter\\debug\\184.jar"}],"tool":"D8"}

**Comment by wuhj2015** [comment]
ｍａｒｋ，是添加了其他的ａｐｉ或者ｐｌｕｇｉｎ吗？我这边添加了ｄｉｄｉ的ｂｏｏｓｔｅｒ出现一样的问题，ｇｒａｄｌｅｗ　ｂｕｉｌｄ编译不通过，如果楼主解决了这个问题，望告知，３ｑ

**Comment by Joehzd** [comment]
4.2.2，kotlin 1.5.10 也出现这个问题了

**Comment by chenmingyin** [comment]
我也是啊，大佬们解决了没有？

**Comment by qq549631030** [comment]
通过排除法发现不是ARouter插件的问题，是神策埋点插件造成的，其它类似的埋点插件也有可能出这个问题
