### ISSUE TITLE
一直提示找不到mapping file

### ISSUE THREAD

**Issue by stoneLee81** [alibaba/ARouter#93]
使用AS2.3,gradle 3.3,jdk1.8
配置如下：
config.gradle
"arouter-api"              : "com.alibaba:arouter-api:1.2.1",
"arouter-compiler"         : "com.alibaba:arouter-compiler:1.1.2",
"arouter-annotation"       : "com.alibaba:arouter-annotation:1.0.3",

build.gradle

defaultConfig {
        minSdkVersion rootProject.ext.android["minSdkVersion"]
        targetSdkVersion rootProject.ext.android["targetSdkVersion"]
        versionCode rootProject.ext.android["versionCode"]
        versionName rootProject.ext.android["versionName"]

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ moduleName : project.getName() ]
            }
        }
    }

compile rootProject.ext.dependencies["arouter-annotation"]
annotationProcessor rootProject.ext.dependencies["arouter-compiler"]

activity文件引用
@Route(path = "/test/profile")
public class ProfileActivity extends BaseSupportActivity<ActivityMultipleImgUseBinding> {

然后启动调试，一直提示找不到mapping

**Comment by stoneLee81** [comment]
04-26 12:17:50.383 29750-29750/trip.com.haowma I/ARouter::: ARouter openLog[ ] 
04-26 12:17:50.384 29750-29750/trip.com.haowma I/ARouter::: ARouter openDebug[ ] 
04-26 12:17:50.385 29750-29750/trip.com.haowma I/ARouter::: ARouter init start.[ ] 
04-26 12:17:50.392 29750-29750/trip.com.haowma E/ARouter: InstantRun support error, com.android.tools.fd.runtime.Paths
04-26 12:17:50.426 29750-29750/trip.com.haowma D/ARouter: Filter 0 classes by packageName <com.alibaba.android.arouter.routes>
04-26 12:17:50.429 29750-29750/trip.com.haowma E/ARouter::: No mapping files were found, check your configuration please![ ] 
04-26 12:17:50.429 29750-29750/trip.com.haowma D/ARouter::: LogisticsCenter has already been loaded, GroupIndex[0], InterceptorIndex[0], ProviderIndex[0][ ] 
04-26 12:17:50.429 29750-29750/trip.com.haowma I/ARouter::: ARouter init success![ ] 
04-26 12:17:50.433 29750-29750/trip.com.haowma W/ARouter::: ARouter::No postcard![ ] 
04-26 12:17:50.433 29750-29750/trip.com.haowma W/ARouter::: ARouter::No postcard![ ] 
04-26 12:17:50.439 29750-29750/trip.com.haowma W/ARouter::: ARouter::There is no route match the path [/arouter/service/interceptor], in group [arouter][ ] 
04-26 12:17:50.457 29750-29750/trip.com.haowma W/ARouter::: ARouter::No postcard![ ] 
04-26 12:17:50.458 29750-29750/trip.com.haowma I/ARouter::: ARouter init over.[ ] 
04-26 12:17:50.863 29750-29750/trip.com.haowma W/ARouter::: ARouter::No postcard![ ] 
04-26 12:17:50.863 29750-29750/trip.com.haowma W/ARouter::: ARouter::No postcard![ ] 
04-26 12:17:50.864 29750-29750/trip.com.haowma W/ARouter::: ARouter::There is no route match the path [/arouter/service/autowired], in group [arouter][ ] 
04-26 12:17:50.869 29750-29750/trip.com.haowma W/ARouter::: ARouter::No postcard![ ]

**Comment by stoneLee81** [comment]
问题是我用的jrebel android启动，就会提示找不到mapping file,如果用google as自带的RUN，就没问题

**Comment by chenpwb** [comment]
解决了吗

**Comment by chenpwb** [comment]
我通过修改混淆配置解决了，如下
#集成 ARouter 的混淆 start
-keep public class com.alibaba.android.arouter.routes.**{*;}
-keep class * implements com.alibaba.android.arouter.facade.template.ISyringe{*;}
# 如果使用了 byType 的方式获取 Service，需添加下面规则，保护接口
#-keep interface * implements com.alibaba.android.arouter.facade.template.IProvider
# 如果使用了 单类注入，即不定义接口实现 IProvider，需添加下面规则，保护实现
-keep class * implements com.alibaba.android.arouter.facade.template.IProvider
#集成 ARouter 的混淆 end

注释了byType那行
