### ISSUE TITLE
Extract the default group failed, the path must be start with '/' and contain more than 2 '/'! 

### ISSUE THREAD

**Issue by xuhang1993** [alibaba/ARouter#933]
Extract the default group failed, the path must be start with '/' and contain more than 2 '/'! 

我一开始没有加"\", 后来加上但是路径一直没变, 我调试时看到传的路径是对的,但是到包里
 public Postcard build(String path) {
        return _ARouter.getInstance().build(path);
    }
这个路径还是之前的, 也加过版本号了 但是还是不行

**Comment by gudulangzi07** [comment]
看报错，说的应该是需要两级目录，你试试   /app/login，这样的两级目录试试
