### ISSUE TITLE
低端机新安装首次扫描dex文件性能耗时大，建议去掉扫描dex文件操作

### ISSUE THREAD

**Issue by suyxin** [alibaba/ARouter#936]
## Look at here
能否优化改进这块去掉扫描dex文件的消耗，借助ASM技术，将生成类直接搜集插入到一个固定名称的类中，启动时直接反射加载这个固定名称类，省去扫描dex逻辑

**Comment by zhi1ong** [comment]
有这个能力，需要使用 register 插件。
