### ISSUE TITLE
Arouter AndroidX版本发布

### ISSUE THREAD

**Issue by weikaiyun** [alibaba/ARouter#947]
Arouter AndroidX 版本 https://github.com/weikaiyun/Arouter 用法与Arouter一致。

**Comment by zhouxin1233** [comment]
问个问题哈，我没有用你的版本，为什么使用androidX没有报错？

**Comment by weikaiyun** [comment]
gradle中配置android.useAndroidX与android.enableJetifier使应用对support库的依赖自动转换为androidx的依赖

**Comment by weikaiyun** [comment]
android.enableJetifier=true 表示Android插件会通过重写其二进制文件来自动迁移现有的第三方库，以使用AndroidX依赖项

**Comment by zhouxin1233** [comment]
> android.enableJetifier=true 表示Android插件会通过重写其二进制文件来自动迁移现有的第三方库，以使用AndroidX依赖项
怎么确定是迁移了 看字节码么 怎么看？

**Comment by JeckChou** [comment]
> > android.enableJetifier=true 表示Android插件会通过重写其二进制文件来自动迁移现有的第三方库，以使用AndroidX依赖项
> > 怎么确定是迁移了 看字节码么 怎么看？

你混用没有编译错误就说明迁移成功了，这个是你在编译的时候给你动态修改的，同时会降低你编译的速度，如果可以，最好是将其他库都换成androidx的
