### ISSUE TITLE
Google Play新上架需要提交aab文件，但是项目架构不支持 App Bundle

### ISSUE THREAD

**Issue by silentpride** [alibaba/ARouter#948]
我们的项目使用了ARouter，并且版本依赖已升级至1.5.2，编译生成出来的aab文件，安装到手机上，无法正常跳转，报路由缺失的问题。
【ARouter::: ARouter::There is no route match the path】

能否尽快给个答复，何时能支持谷歌的app bundle。
如果近期没有安排的话，我们会考虑更换其他的路由框架。
这样的话对项目的开发来讲，代码改动太大了。。。

**Comment by pangli** [comment]
你确定不支持App Bundle？我现在的新项目(开发阶段)也需要上架GooglePlay，如果是这样的话就不能用ARouter了，我还找到另一个库你可以看看[Component](https://github.com/xiaojinzi123/Component)，如有结果请告知一下，谢谢

**Comment by pangli** [comment]
> 我们的项目使用了ARouter，并且版本依赖已升级至1.5.2编译生成的aab文件，安装到上，无法正常跳转，报告接入手机的问题。
> 【ARouter::ARouter::There is没有路由匹配路径】
> 
> 能否尽快给个答复，何时能支持谷歌的应用程序包。
> 如果近期没有安排的话，我们会考虑更换其他的路由框架。
> 这样的话对项目的开发来讲，代码改动太大了......

你确定不支持App Bundle？我现在的新项目（开发阶段）也需要上架GooglePlay，如果这样的话就不能用ARouter了，我还找到另一个库你可以看看组件，如果有请告知一下，谢谢

**Comment by silentpride** [comment]
> > 我们的项目使用了ARouter，并且版本依赖已升级至1.5.2编译生成的aab文件，安装到上，无法正常跳转，报告接入手机的问题。
> > 【ARouter::ARouter::There is没有路由匹配路径】
> > 能否尽快给个答复，何时能支持谷歌的应用程序包。
> > 如果近期没有安排的话，我们会考虑更换其他的路由框架。
> > 这样的话对项目的开发来讲，代码改动太大了......
> 
> 你确定不支持App Bundle？我现在的新项目（开发阶段）也需要上架GooglePlay，如果这样的话就不能用ARouter了，我还找到另一个库你可以看看组件，如果有请告知一下，谢谢

单纯模块化是可以的，如果使用了另外的组件化框架做解耦，可能导致不兼容。
我的项目用了Arouter和逻辑思维的组件化框架，导致其他模块的代码打不进去，无法跳转。正在考虑移除组件化的框架。
你可以自己打一个aab的文件，然后安装试一下能否正常跳转。

**Comment by pangli** [comment]
> > > 我们的项目使用了ARouter，并且版本依赖已升级至1.5.2编译生成的aab文件，安装到上，无法正常跳转，报告接入手机的问题。
> > > 【ARouter::ARouter::There is没有路由匹配路径】
> > > 能否尽快给个答复，何时能支持谷歌的应用程序包。
> > > 如果近期没有安排的话，我们会考虑更换其他的路由框架。
> > > 这样的话对项目的开发来讲，代码改动太大了......
> > 
> > 
> > 你确定不支持App Bundle？我现在的新项目（开发阶段）也需要上架GooglePlay，如果这样的话就不能用ARouter了，我还找到另一个库你可以看看组件，如果有请告知一下，谢谢
> 
> 单纯模块化是可以的，如果使用了另外的组件化框架做解耦，可能导致不兼容。
> 我的项目用了Arouter和逻辑思维的组件化框架，导致其他模块的代码打不进去，无法跳转。正在考虑移除组件化的框架。
> 你可以自己打一个aab的文件，然后安装试一下能否正常跳转。

我也打算用组件化开发的，你目前有什么替代方案吗？

**Comment by silentpride** [comment]
> > > > 我们的项目使用了ARouter，并且版本依赖已升级至1.5.2编译生成的aab文件，安装到上，无法正常跳转，报告接入手机的问题。
> > > > 【ARouter::ARouter::There is没有路由匹配路径】
> > > > 能否尽快给个答复，何时能支持谷歌的应用程序包。
> > > > 如果近期没有安排的话，我们会考虑更换其他的路由框架。
> > > > 这样的话对项目的开发来讲，代码改动太大了......
> > > 
> > > 
> > > 你确定不支持App Bundle？我现在的新项目（开发阶段）也需要上架GooglePlay，如果这样的话就不能用ARouter了，我还找到另一个库你可以看看组件，如果有请告知一下，谢谢
> > 
> > 
> > 单纯模块化是可以的，如果使用了另外的组件化框架做解耦，可能导致不兼容。
> > 我的项目用了Arouter和逻辑思维的组件化框架，导致其他模块的代码打不进去，无法跳转。正在考虑移除组件化的框架。
> > 你可以自己打一个aab的文件，然后安装试一下能否正常跳转。
> 
> 我也打算用组件化开发的，你目前有什么替代方案吗？

目前没有哦，因为GP的规定8.1才生效，我们昨天才发现生成的aab有问题，现在在改项目架构。逻辑思维的框架好久也没更新了，如果要找替代的框架可能会花其他精力。
如果你有发现好用的组件化框架，可以留言给我哦

**Comment by pangli** [comment]
> > > > > 我们的项目使用了ARouter，并且版本依赖已升级至1.5.2编译生成的aab文件，安装到上，无法正常跳转，报告接入手机的问题。
> > > > > 【ARouter::ARouter::There is没有路由匹配路径】
> > > > > 能否尽快给个答复，何时能支持谷歌的应用程序包。
> > > > > 如果近期没有安排的话，我们会考虑更换其他的路由框架。
> > > > > 这样的话对项目的开发来讲，代码改动太大了......
> > > > 
> > > > 
> > > > 你确定不支持App Bundle？我现在的新项目（开发阶段）也需要上架GooglePlay，如果这样的话就不能用ARouter了，我还找到另一个库你可以看看组件，如果有请告知一下，谢谢
> > > 
> > > 
> > > 单纯模块化是可以的，如果使用了另外的组件化框架做解耦，可能导致不兼容。
> > > 我的项目用了Arouter和逻辑思维的组件化框架，导致其他模块的代码打不进去，无法跳转。正在考虑移除组件化的框架。
> > > 你可以自己打一个aab的文件，然后安装试一下能否正常跳转。
> > 
> > 
> > 我也打算用组件化开发的，你目前有什么替代方案吗？
> 
> 目前没有哦，因为GP的规定8.1才生效，我们昨天才发现生成的aab有问题，现在在改项目架构。逻辑思维的框架好久也没更新了，如果要找替代的框架可能会花其他精力。
> 如果你有发现好用的组件化框架，可以留言给我哦

我使用一个组件化项目其中页面跳转使用了ARouter进行了测试没有发现此问题
可能我使用的项目比较小未超过150M的限制
测试方法参考[google文档](https://developer.android.com/studio/run/rundebugconfig#general-tab)使用AndroidStudio直接运行安装
![image](https://user-images.githubusercontent.com/7498978/128978920-ea8ef268-884d-4c4c-9149-1dc1c4c705ac.png)
是否和生成abb和安装方法有关才导致的问题

**Comment by silentpride** [comment]
> > > > > > 我们的项目使用了ARouter，并且版本依赖已升级至1.5.2编译生成的aab文件，安装到上，无法正常跳转，报告接入手机的问题。
> > > > > > 【ARouter::ARouter::There is没有路由匹配路径】
> > > > > > 能否尽快给个答复，何时能支持谷歌的应用程序包。
> > > > > > 如果近期没有安排的话，我们会考虑更换其他的路由框架。
> > > > > > 这样的话对项目的开发来讲，代码改动太大了......
> > > > > 
> > > > > 
> > > > > 你确定不支持App Bundle？我现在的新项目（开发阶段）也需要上架GooglePlay，如果这样的话就不能用ARouter了，我还找到另一个库你可以看看组件，如果有请告知一下，谢谢
> > > > 
> > > > 
> > > > 单纯模块化是可以的，如果使用了另外的组件化框架做解耦，可能导致不兼容。
> > > > 我的项目用了Arouter和逻辑思维的组件化框架，导致其他模块的代码打不进去，无法跳转。正在考虑移除组件化的框架。
> > > > 你可以自己打一个aab的文件，然后安装试一下能否正常跳转。
> > > 
> > > 
> > > 我也打算用组件化开发的，你目前有什么替代方案吗？
> > 
> > 
> > 目前没有哦，因为GP的规定8.1才生效，我们昨天才发现生成的aab有问题，现在在改项目架构。逻辑思维的框架好久也没更新了，如果要找替代的框架可能会花其他精力。
> > 如果你有发现好用的组件化框架，可以留言给我哦
> 
> 我使用一个组件化项目其中页面跳转使用了ARouter进行了测试没有发现此问题
> 可能我使用的项目比较小未超过150M的限制
> 测试方法参考[google文档](https://developer.android.com/studio/run/rundebugconfig#general-tab)使用AndroidStudio直接运行安装
> ![image](https://user-images.githubusercontent.com/7498978/128978920-ea8ef268-884d-4c4c-9149-1dc1c4c705ac.png)
> 是否和生成abb和安装方法有关才导致的问题

应该是另一个框架导致的问题。
我们项目保留了Arouter，去除了另一个组件化的框架，能正常跳转了。

**Comment by ender115** [comment]
两位大佬，在项目中使用Arouter对上架google没影响吧，政策方面

**Comment by silentpride** [comment]
> 两位大佬，在项目中使用Arouter对上架google没影响吧，政策方面

可以，Arouter能正常上架。
