### ISSUE TITLE
suggest: 建议降低 SUPPORT_LIB_VERSION 版本至 25.0.1 或更低(23.1.1)

### ISSUE THREAD

**Issue by kingtami** [alibaba/ARouter#96]
由于本想限定 support-v4 版本为 25.0.1, 高于此版本会导致指纹识别失效, 但是发现 External Libraries 中有两个版本, 其中之一是 25.2.0, 最终使用的也是高版本, 于是通过 ./gradlew -q dependencies app:dependencies --configuration compile 检查依赖发现是 ARouter 使用了 25.2.0, 虽然可以 exclude, 但是考虑部分用户不一定找得到办法解决,还是希望可以考虑降低版本.
ps: ARouter 也是截止目前我所使用的(20~30个) libraries 中唯一一个使用 25.2.0 的 library.

**Comment by weinierfei** [comment]
每个人使用的版本都不一样,每个人都会有某种理由使用某些版本;比较好的做法是v4包参与编译,不参与打包;让使用者自己选择相应版本

**Comment by zhi1ong** [comment]
理论上用最新的support包和最新的build-tool是没问题的，毕竟是兼容的，可以自行排除掉。

指纹问题那个恰好我也关注过，是因为25之后的support包中，google强制验证厂商是否配置了指纹支持的描述文件，国内厂商很多都没有声明指纹支持，那个是有解法的，就不细说了

这块可以考虑改成 @weinierfei  的方案，改成provide依赖
