### ISSUE TITLE
想问下 init扫描文件的时候 为什么要扫描zip结尾的文件 原生的不就是apk文件么 还希望解答下

### ISSUE THREAD

**Issue by LcxAndroidwawa** [alibaba/ARouter#98]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

**Comment by zhi1ong** [comment]
这个要区分不同版本的，建议你了解一下 

1. MultiDex 原理
2. InstantRun 原理
3. SplitApk 原理
