### ISSUE TITLE
Fastjson<=1.2.68纰漏严重漏洞，请问Arouter1.5.1是否受影响

### ISSUE THREAD

**Issue by wangsc0355** [alibaba/ARouter#982]
漏洞软件：fastjson；

漏洞版本：<=1.2.68;

漏洞描述：近日，外部安全厂商监测到有消息称Fastjson<=1.2.68版本中存在一个高危漏洞。攻击者可以绕过autotype限制，但必须利用不在黑名单中的gadgets，实际造成的危害与利用的gadgets有关。
fastjson是阿里巴巴的开源JSON解析库，它可以解析JSON格式的字符串，支持将Java Bean序列化为JSON字符串，也可以从JSON字符串反序列化到JavaBean，由于具有执行效率高的特点，应用范围广泛。请相关用户尽快采取防护措施。

利用条件：漏洞利用必要条件：
a)       存在不在黑名单中的反序列化利用链(gadgets)
b)      (Fastjson<=1.2.68 / Fastjson sec版本 <= sec9)且未开启safeMode

影响与风险：
攻击者可以绕过autotype限制，导致远程代码执行。

**Comment by zhi1ong** [comment]
不影响，只是在编译阶段使用
