### ISSUE TITLE
关于ARouter初始化入参是application的问题

### ISSUE THREAD

**Issue by ChawLoo** [alibaba/ARouter#983]
今天用StartUp把在Application中初始化的迁移时，发现StartUp只传入了context，已知这个context是Application 的context，但是还是来搜了一下issues，我看到有个人反馈过无法用于StartUp，因为startUp传入的是application 的context，但是翻了一下ARouter的初始化，虽然传入的是Application，但是最终赋值给了context，难道是为了限定用户传入Application的context吗？为何不直接传入context？

**Comment by ChawLoo** [comment]
纯粹有这个疑问，并非有Bug，问题我已解决，强转，由于不太喜欢强转，所以来问问

**Comment by zhi1ong** [comment]
Application 也是 Context 中的一种呀，也不是强制要用 Application
