### ISSUE TITLE
避免遍历dexfile获取生成类名，缩短启动时间的建议

### ISSUE THREAD

**Issue by xns1001** [alibaba/ARouter#99]
我发现ClassUtils.getFileNameByPackageName这个方法耗时很高，主要是遍历dexfile获取arouter生成class类名这个操作造成的。

我做了实验，在有4个dex，3个生成类的情况下。如果是外部传入生成类名，省去遍历dexfile获取类名这步操作，app的启动时间能缩短100ms左右。虽然这样做会使接入麻烦点。但确实能缩短不少启动时间。

**Comment by zhi1ong** [comment]
这块确实会有耗时，不过这个问题在于要通过包名拿具体的映射文件，拿之前并不知道有多少个映射文件，因为这个包下有多少映射文件完全由用户打包了多少个模块动态决定的。

**Comment by jason0539** [comment]
这个问题导致了ANR，尤其4.4.x机型，有解决方案么 @zhi1ong

**Comment by zhi1ong** [comment]
anr的包发给我，还有手机型号，我这边的Android 4.4.x 没问题  mail:to=zhilong.liu@aliyun.com

**Comment by linsea** [comment]
![arouter](https://user-images.githubusercontent.com/5970853/61458557-66226300-a99d-11e9-837c-7169d7d96c96.png)

ClassUtils.getFileNameByPackageName这个方法的耗时占用了 Application.onCreate() 总耗时的一半, 有优化方法吗?

**Comment by linsea** [comment]
![arouter](https://user-images.githubusercontent.com/5970853/61459104-8f8fbe80-a99e-11e9-9349-2754c97a5c1f.png)

ClassUtils.getFileNameByPackageName这个方法的耗时占用了 Application.onCreate() 方法耗时的一半, 有优化方法吗?

**Comment by zhi1ong** [comment]
@linsea 用 arouter-register 插件
