### ISSUE TITLE
关于Arouter新增Provider报空 卸载后重装正常运行的问题

### ISSUE THREAD

**Issue by weizhihan** [alibaba/ARouter#996]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by weizhihan** [comment]
目前我们的项目在新增Provider之后 通过autowired编译生成了对应的文件 可以跳转 但是在调用provider会出现IXXXprovider为空的错误  重新卸载之后安装就正常了 请问这个问题是由于编译后文件没有完成打包造成的吗？

**Comment by phoenixsky** [comment]
@weizhihan 
我这也会有provider为空的问题。kotlin，同事那是必现，我这没事，但不知道是什么原因，急着上线fix，就通过直接依赖的方式，规避了使用provider。
现在有时间调查，代码回滚回来，发现又不为空了。

这块太危险了，我现在不敢使用provider了已经。

**Comment by zhi1ong** [comment]
clean rebuild 解决所有问题

**Comment by phoenixsky** [comment]
clean rebuild 当时clean rebuild  invalid cache 都试了 还是崩溃

**Comment by zhi1ong** [comment]
> clean rebuild 当时clean rebuild invalid cache 都试了 还是崩溃

ARouter 逻辑其实是非常简单的，都有源码 debug 一下就好，不会出现一会好使一会不行的情况，研究研究总能发现问题所在
