### ISSUE TITLE
请问Arouter是否存在Spring框架曝出0day漏洞的情况

### ISSUE THREAD

**Issue by wangsc0355** [alibaba/ARouter#998]
Spring 框架以及衍生的框架可能会存在0day漏洞，详细情况 如下：
https://www.obatis.com/article/1648606963311

请问：Arouter是否受以上漏洞影响？如果存在影响，请问修复计划如何？
感谢各位大佬的解答！

**Comment by zhi1ong** [comment]
和 spring 可以说是毫无关系了
